#ifndef _CHROBJDATA_H_
#define _CHROBJDATA_H_
#include "ultra64.h"

struct prop_pos_data {
    u16 x;
    u16 y;
    u16 z;
};

struct item_related {
    short num_entries_in_block;
    short field_2;
    struct prop_pos_data * ptr_block;
    short total_cmd_indexval;
    short field_A;
};

struct Gitemheader {
    int offset_objtable;
    void * guntype_modeldata;
    int offset_objblock;
    u16 num05soffset_entries;
    u16 num_objgroups;
    float drawdistance;
    u16 num_entries;
    u16 num_images;
    int offset_imgdecl;
    u32 isloaded;
};


struct PitemZ_header {
    s32 microcode_entry_num;
    struct item_related * anonymous_1;
    short anonymous_2;
    short field_E;
    s32 drawdistance;
    float anonymous_4;
    s32 anonymous_5;
    s32 anonymous_6;
    s32 anonymous_7;
};

struct p_itementry {
    struct PitemZ_header * header;
    char * filename;
    float scale;
};

struct object_header {
    int offset_obj_table;
    void * ptr_archetype;
    int offset_obj_offset_block;
    short num_offset_entries;
    short num_object_grps;
    float anonymous_4;
    short num_table_entries;
    short num_image_entries;
    int offset_img_declaration;
    int is_loaded_in_mem;
};

struct c_itementry {
    struct object_header * header;
    char * filename;
    float anonymous_1;
    float anonymous_2;
    int anonymous_3;
};

struct model_data {
    u32  anonymous_0;
    u32 *propposdata;
    u32  anonymous_2;
};

struct player_gait_header {
    u8 field_0x0;
    u8 type;
    u16 field_0x2;
    struct player_gait_object_entry * field_0x4;
    struct player_gait_pos_header * previous;
    void * field_0xc;
    void * field_0x10;
    struct player_gait_pos_header * next;
};

struct player_gait_pos_header {
    u8 field_0x0;
    u8 type;
    u16 field_0x2;
    struct player_gait_position_entry * field_0x4;
    struct player_gait_pos_header * previous;
    void * field_0xc;
    void * field_0x10;
    struct player_gait_pos_header * next;
};

struct player_gait_object_entry {
    u32 field_0x0;
    struct player_gait_pos_header * ptr_header;
    u32 field_0x8;
    u32 field_0xc;
};

struct player_gait_position_entry {
    float z_scale;
    float y_offset;
    float xy_scale;
    u16 field_0xc;
    u16 field_0xe;
    u16 field_0x10;
    u16 field_0x12;
    struct player_gait_pos_header * ptr_header;
    u32 field_0x18;
};

struct struct_13 {
    void * ailist;
    int ailistid;
};

struct headHat
{
    float xoffset;
    float yoffset;
    float zoffset;
    float xsize;
    float ysize;
    float zsize;
};

extern struct p_itementry PitemZ_entries[];

extern struct item_related prop_cctv_related;
extern struct item_related prop_console_one_screen_related;
extern struct item_related prop_console_four_screen_related;
extern struct item_related prop_tv_holder_related;
extern struct item_related prop_rotating_stuff_related;
extern struct item_related prop_eyelid_door_related;
extern struct item_related prop_iris_door_related;
extern struct item_related prop_walletbond_related;
extern struct item_related prop_car_related;
extern struct item_related prop_flying_related;
extern struct item_related prop_door_related;
extern struct item_related item_tank_related;
extern struct item_related item_hat_related;
extern struct item_related model_object_standard_object;
extern struct item_related prop_weapon_related;
extern struct model_data model_guard_character;
extern struct player_gait_header player_gait_hdr;
extern struct player_gait_pos_header player_gait_pos_hdr_1;
extern struct player_gait_pos_header player_gait_pos_hdr_2;
extern struct player_gait_pos_header player_gait_pos_hdr_3;
extern struct player_gait_object_entry player_gait_obj;
extern struct player_gait_position_entry player_gait_pos_1;
extern struct player_gait_position_entry player_gait_pos_2;
extern struct player_gait_position_entry player_gait_pos_3;

extern struct object_header player_gait_object;

extern struct Gitemheader GwppkZ_struct;
extern struct Gitemheader GwppksilZ_struct;
extern struct Gitemheader Gtt33Z_struct;
extern struct Gitemheader GskorpianZ_struct;
extern struct Gitemheader Gak47Z_struct;
extern struct Gitemheader GuziZ_struct;
extern struct Gitemheader Gmp5kZ_struct;
extern struct Gitemheader Gmp5ksilZ_struct;
extern struct Gitemheader Gm16Z_struct;
extern struct Gitemheader Gfnp90Z_struct;
extern struct Gitemheader G8003C900_struct;
extern struct Gitemheader GrugerZ_struct;
extern struct Gitemheader GgoldengunZ_struct;
extern struct Gitemheader GshotgunZ_struct;
extern struct Gitemheader GautoshotZ_struct;
extern struct Gitemheader GgrenadelaunchZ_struct;
extern struct Gitemheader GspectreZ_struct;
extern struct Gitemheader GlaserZ_struct;
extern struct Gitemheader GrocketlaunchZ_struct;
extern struct Gitemheader GknifeZ_header;
extern struct Gitemheader GthrowknifeZ_struct;
extern struct Gitemheader GtaserZ_struct;
extern struct Gitemheader GremotemineZ_struct;
extern struct Gitemheader GproximitymineZ_struct;
extern struct Gitemheader GtimedmineZ_struct;
extern struct Gitemheader GtriggerZ_struct;
extern struct Gitemheader GgrenadeZ_struct;
extern struct Gitemheader GfistZ_header;
extern struct Gitemheader GsniperrifleZ_struct;
extern struct Gitemheader GcartridgeZ_struct;
extern struct Gitemheader GcartrifleZ_struct;
extern struct Gitemheader GcartblueZ_struct;
extern struct Gitemheader GcartshellZ_struct;
extern struct Gitemheader GjoypadZ_struct;
extern struct Gitemheader G8003CC00_struct;
extern struct Gitemheader G8003CC20_struct;
extern struct Gitemheader GbombcaseZ_struct;
extern struct Gitemheader GflarepistolZ_struct;
extern struct Gitemheader GpitongunZ_struct;
extern struct Gitemheader G8003CCA0_struct;
extern struct Gitemheader GsilverwppkZ_struct;
extern struct Gitemheader GgoldwppkZ_struct;
extern struct Gitemheader G8003CD00_struct;
extern struct Gitemheader GbungeeZ_struct;
extern struct Gitemheader GdoordecoderZ_struct;
extern struct Gitemheader GbombdefuserZ_struct;
extern struct Gitemheader GbugdetectorZ_struct;
extern struct Gitemheader GsafecrackercaseZ_struct;
extern struct Gitemheader GcameraZ_struct;
extern struct Gitemheader GlockexploderZ_struct;
extern struct Gitemheader GdoorexploderZ_struct;
extern struct Gitemheader GkeyanalysercaseZ_struct;
extern struct Gitemheader GweaponcaseZ_struct;
extern struct Gitemheader GkeycardZ_struct;
extern struct Gitemheader GkeyyaleZ_struct;
extern struct Gitemheader GkeyboltZ_struct;
extern struct Gitemheader GbugZ_struct;
extern struct Gitemheader GmicrocameraZ_struct;
extern struct Gitemheader GexplosivefloppyZ_struct;
extern struct Gitemheader GgoldeneyekeyZ_struct;
extern struct Gitemheader GpolarizedglassesZ_struct;
extern struct Gitemheader GcreditcardZ_struct;
extern struct Gitemheader GdarkglassesZ_struct;
extern struct Gitemheader GwatchidentifierZ_struct;
extern struct Gitemheader GwatchcommunicatorZ_struct;
extern struct Gitemheader GwatchlaserZ_struct;
extern struct Gitemheader GwatchgeigercounterZ_struct;
extern struct Gitemheader GwatchmagnetrepelZ_struct;
extern struct Gitemheader GwatchmagnetattractZ_struct;
extern struct Gitemheader GgaskeyringZ_struct;
extern struct Gitemheader GdatathiefZ_struct;
extern struct Gitemheader GbriefcaseZ_struct;
extern struct Gitemheader GblackboxZ_struct;
extern struct Gitemheader GplastiqueZ_struct;
extern struct Gitemheader GvideotapeZ_struct;
extern struct Gitemheader GclipboardZ_struct;
extern struct Gitemheader GstafflistZ_struct;
extern struct Gitemheader GdossierredZ_struct;
extern struct Gitemheader GaudiotapeZ_struct;
extern struct Gitemheader GdattapeZ_struct;
extern struct Gitemheader GplansZ_struct;
extern struct Gitemheader GspyfileZ_struct;
extern struct Gitemheader GblueprintsZ_struct;
extern struct Gitemheader GcircuitboardZ_struct;
extern struct Gitemheader GmapZ_struct;
extern struct Gitemheader GspooltapeZ_struct;
extern struct Gitemheader GmicrofilmZ_struct;
extern struct Gitemheader GmicrocodeZ_struct;
extern struct Gitemheader GlectreZ_struct;
extern struct Gitemheader GmoneyZ_struct;
extern struct Gitemheader GgoldbarZ_struct;
extern struct Gitemheader GheroinZ_struct;
extern struct model_data weapon_gun_controller;

extern struct object_header CcamguardZ_struct;
extern struct object_header CgreyguardZ_struct;
extern struct object_header ColiveguardZ_struct;
extern struct object_header CrusguardZ_struct;
extern struct object_header CtrevguardZ_struct;
extern struct object_header CborisZ_struct;
extern struct object_header CorumovZ_struct;
extern struct object_header CtrevelyanZ_struct;
extern struct object_header CboilertrevZ_struct;
extern struct object_header CvalentinZ_struct;
extern struct object_header CxeniaZ_struct;
extern struct object_header CbaronsamediZ_struct;
extern struct object_header CjawsZ_struct;
extern struct object_header CmaydayZ_struct;
extern struct object_header CoddjobZ_struct;
extern struct object_header CnatalyaZ_struct;
extern struct object_header CarmourguardZ_struct;
extern struct object_header CcommguardZ_struct;
extern struct object_header CgreatguardZ_struct;
extern struct object_header CnavyguardZ_struct;
extern struct object_header CsnowguardZ_struct;
extern struct object_header CbluewomanZ_struct;
extern struct object_header CfattechwomanZ_struct;
extern struct object_header CtechwomanZ_struct;
extern struct object_header CjeanwomanZ_struct;
extern struct object_header CgreymanZ_struct;
extern struct object_header CbluemanZ_struct;
extern struct object_header CredmanZ_struct;
extern struct object_header CcardimanZ_struct;
extern struct object_header CcheckmanZ_struct;
extern struct object_header CtechmanZ_struct;
extern struct object_header CpilotZ_struct;
extern struct object_header Cgreatguard2Z_struct;
extern struct object_header CbluecamguardZ_struct;
extern struct object_header CmoonguardZ_struct;
extern struct object_header CmoonfemaleZ_struct;
extern struct object_header CboilerbondZ_struct;
extern struct object_header CsuitbondZ_struct;
extern struct object_header CtimberbondZ_struct;
extern struct object_header CsnowbondZ_struct;
extern struct object_header CdjbondZ_struct;
extern struct object_header Csuit_lf_handz_struct;
extern struct object_header CheadkarlZ_struct;
extern struct object_header CheadalanZ_struct;
extern struct object_header CheadpeteZ_struct;
extern struct object_header CheadmartinZ_struct;
extern struct object_header stru_D_8003D9D0;
extern struct object_header stru_D_8003D9F0;
extern struct object_header stru_D_8003DA10;
extern struct object_header stru_D_8003DA30;
extern struct object_header stru_D_8003DA50;
extern struct object_header stru_D_8003DA70;
extern struct object_header stru_D_8003DA90;
extern struct object_header stru_D_8003DAB0;
extern struct object_header stru_D_8003DAD0;
extern struct object_header stru_D_8003DAF0;
extern struct object_header stru_D_8003DB10;
extern struct object_header stru_D_8003DB30;
extern struct object_header stru_D_8003DB50;
extern struct object_header stru_D_8003DB70;
extern struct object_header stru_D_8003DB90;
extern struct object_header stru_D_8003DBB0;
extern struct object_header stru_D_8003DBD0;
extern struct object_header stru_D_8003DBF0;
extern struct object_header stru_D_8003DC10;
extern struct object_header stru_D_8003DC30;
extern struct object_header stru_D_8003DC50;
extern struct object_header stru_D_8003DC70;
extern struct object_header stru_D_8003DC90;
extern struct object_header stru_D_8003DCB0;
extern struct object_header stru_D_8003DCD0;
extern struct object_header stru_D_8003DCF0;
extern struct object_header stru_D_8003DD10;
extern struct object_header stru_D_8003DD30;
extern struct object_header stru_D_8003DD50;
extern struct object_header CheadbrosnansuitZ_struct;
extern struct object_header CheadbrosnantimberZ_struct;
extern struct object_header CheadbrosnansnowZ_struct;
extern struct object_header CheadbrosnanZ_struct;
extern struct object_header CspicebondZ_struct;

extern struct PitemZ_header Palarm1z_header;
extern struct PitemZ_header Palarm2Z_header;
extern struct PitemZ_header PexplosionbitZ_header;
extern struct PitemZ_header Pammo_crate1Z_header;
extern struct PitemZ_header Pammo_crate2Z_header;
extern struct PitemZ_header Pammo_crate3Z_header;
extern struct PitemZ_header Pammo_crate4Z_header;
extern struct PitemZ_header Pammo_crate5Z_header;
extern struct PitemZ_header Pbin1Z_header;
extern struct PitemZ_header Pblotter1Z_header;
extern struct PitemZ_header Pbook1Z_header;
extern struct PitemZ_header Pbookshelf1Z_header;
extern struct PitemZ_header Pbridge_console1aZ_header;
extern struct PitemZ_header Pbridge_console1bZ_header;
extern struct PitemZ_header Pbridge_console2aZ_header;
extern struct PitemZ_header Pbridge_console2bZ_header;
extern struct PitemZ_header Pbridge_console3aZ_header;
extern struct PitemZ_header Pbridge_console3bZ_header;
extern struct PitemZ_header Pcard_box1Z_header;
extern struct PitemZ_header Pcard_box2Z_header;
extern struct PitemZ_header Pcard_box3Z_header;
extern struct PitemZ_header Pcard_box4_lgZ_header;
extern struct PitemZ_header Pcard_box5_lgZ_header;
extern struct PitemZ_header Pcard_box6_lgZ_header;
extern struct PitemZ_header PcctvZ_header;
extern struct PitemZ_header Pconsole1Z_header;
extern struct PitemZ_header Pconsole2Z_header;
extern struct PitemZ_header Pconsole3Z_header;
extern struct PitemZ_header Pconsole_sevaZ_header;
extern struct PitemZ_header Pconsole_sevbZ_header;
extern struct PitemZ_header Pconsole_sevcZ_header;
extern struct PitemZ_header Pconsole_sevdZ_header;
extern struct PitemZ_header Pconsole_sev2aZ_header;
extern struct PitemZ_header Pconsole_sev2bZ_header;
extern struct PitemZ_header Pconsole_sev2cZ_header;
extern struct PitemZ_header Pconsole_sev2dZ_header;
extern struct PitemZ_header Pconsole_sev_GEaZ_header;
extern struct PitemZ_header Pconsole_sev_GEbZ_header;
extern struct PitemZ_header Pdesk1Z_header;
extern struct PitemZ_header Pdesk2Z_header;
extern struct PitemZ_header Pdesk_lamp2Z_header;
extern struct PitemZ_header Pdisc_readerZ_header;
extern struct PitemZ_header Pdisk_drive1Z_header;
extern struct PitemZ_header Pfiling_cabinet1Z_header;
extern struct PitemZ_header Pjerry_can1Z_header;
extern struct PitemZ_header Pkeyboard1Z_header;
extern struct PitemZ_header Pkit_units1Z_header;
extern struct PitemZ_header Pletter_tray1Z_header;
extern struct PitemZ_header Pmainframe1Z_header;
extern struct PitemZ_header Pmainframe2Z_header;
extern struct PitemZ_header Pmetal_chair1Z_header;
extern struct PitemZ_header Pmetal_crate1Z_header;
extern struct PitemZ_header Pmetal_crate2Z_header;
extern struct PitemZ_header Pmetal_crate3Z_header;
extern struct PitemZ_header Pmetal_crate4Z_header;
extern struct PitemZ_header Pmissile_rackZ_header;
extern struct PitemZ_header Pmissile_rack2Z_header;
extern struct PitemZ_header Poil_drum1Z_header;
extern struct PitemZ_header Poil_drum2Z_header;
extern struct PitemZ_header Poil_drum3Z_header;
extern struct PitemZ_header Poil_drum5Z_header;
extern struct PitemZ_header Poil_drum6Z_header;
extern struct PitemZ_header Poil_drum7Z_header;
extern struct PitemZ_header PpadlockZ_header;
extern struct PitemZ_header Pphone1Z_header;
extern struct PitemZ_header Pradio_unit1Z_header;
extern struct PitemZ_header Pradio_unit2Z_header;
extern struct PitemZ_header Pradio_unit3Z_header;
extern struct PitemZ_header Pradio_unit4Z_header;
extern struct PitemZ_header Psat1_reflectZ_header;
extern struct PitemZ_header PsatdishZ_header;
extern struct PitemZ_header PsatboxZ_header;
extern struct PitemZ_header Pstool1Z_header;
extern struct PitemZ_header Pswivel_chair1Z_header;
extern struct PitemZ_header Ptorpedo_rackZ_header;
extern struct PitemZ_header Ptv1Z_header;
extern struct PitemZ_header Ptv_holderZ_header;
extern struct PitemZ_header PtvscreenZ_header;
extern struct PitemZ_header Ptv4screenZ_header;
extern struct PitemZ_header Pwood_lg_crate1Z_header;
extern struct PitemZ_header Pwood_lg_crate2Z_header;
extern struct PitemZ_header Pwood_md_crate3Z_header;
extern struct PitemZ_header Pwood_sm_crate4Z_header;
extern struct PitemZ_header Pwood_sm_crate5Z_header;
extern struct PitemZ_header Pwood_sm_crate6Z_header;
extern struct PitemZ_header Pwooden_table1Z_header;
extern struct PitemZ_header Pswipe_card2Z_header;
extern struct PitemZ_header Pborg_crateZ_header;
extern struct PitemZ_header Pboxes4x4Z_header;
extern struct PitemZ_header Pboxes3x4Z_header;
extern struct PitemZ_header Pboxes2x4Z_header;
extern struct PitemZ_header Psec_panelZ_header;
extern struct PitemZ_header PICBM_noseZ_header;
extern struct PitemZ_header PICBMZ_header;
extern struct PitemZ_header Ptuning_console1Z_header;
extern struct PitemZ_header Pdesk_arecibo1Z_header;
extern struct PitemZ_header Plocker3Z_header;
extern struct PitemZ_header Plocker4Z_header;
extern struct PitemZ_header ProofgunZ_header;
extern struct PitemZ_header Pdest_engineZ_header;
extern struct PitemZ_header Pdest_exocetZ_header;
extern struct PitemZ_header Pdest_gunZ_header;
extern struct PitemZ_header Pdest_harpoonZ_header;
extern struct PitemZ_header Pdest_seawolfZ_header;
extern struct PitemZ_header PwindowZ_header;
extern struct PitemZ_header Pwindow_lib_lg1Z_header;
extern struct PitemZ_header Pwindow_lib_sm1Z_header;
extern struct PitemZ_header Pwindow_cor11Z_header;
extern struct PitemZ_header Pjungle3_treeZ_header;
extern struct PitemZ_header PpalmZ_header;
extern struct PitemZ_header PpalmtreeZ_header;
extern struct PitemZ_header Pplant2bZ_header;
extern struct PitemZ_header PlabbenchZ_header;
extern struct PitemZ_header PgasbarrelZ_header;
extern struct PitemZ_header PgasbarrelsZ_header;
extern struct PitemZ_header PbodyarmourZ_header;
extern struct PitemZ_header PbodyarmourvestZ_header;
extern struct PitemZ_header PgastankZ_header;
extern struct PitemZ_header Pglassware1Z_header;
extern struct PitemZ_header PhatchboltZ_header;
extern struct PitemZ_header PbrakeunitZ_header;
extern struct PitemZ_header Pak47magZ_header;
extern struct PitemZ_header Pm16magZ_header;
extern struct PitemZ_header Pmp5kmagZ_header;
extern struct PitemZ_header PskorpionmagZ_header;
extern struct PitemZ_header PspectremagZ_header;
extern struct PitemZ_header PuzimagZ_header;
extern struct PitemZ_header PsilencerZ_header;
extern struct PitemZ_header PchrextinguisherZ_header;
extern struct PitemZ_header PboxcartridgesZ_header;
extern struct PitemZ_header Pfnp90magZ_header;
extern struct PitemZ_header PgoldenshellsZ_header;
extern struct PitemZ_header PmagnumshellsZ_header;
extern struct PitemZ_header PwppkmagZ_header;
extern struct PitemZ_header Ptt33magZ_header;
extern struct PitemZ_header Psev_doorZ_header;
extern struct PitemZ_header Psev_door3Z_header;
extern struct PitemZ_header Psev_door3_windZ_header;
extern struct PitemZ_header Psev_door4_windZ_header;
extern struct PitemZ_header Psev_trislideZ_header;
extern struct PitemZ_header Psev_door_v1Z_header;
extern struct PitemZ_header Psteel_door1Z_header;
extern struct PitemZ_header Psteel_door2Z_header;
extern struct PitemZ_header Psteel_door3Z_header;
extern struct PitemZ_header Psilo_lift_doorZ_header;
extern struct PitemZ_header Psteel_door2bZ_header;
extern struct PitemZ_header Pdoor_roller1Z_header;
extern struct PitemZ_header Pdoor_roller2Z_header;
extern struct PitemZ_header Pdoor_roller3Z_header;
extern struct PitemZ_header Pdoor_roller4Z_header;
extern struct PitemZ_header Pdoor_st_arec1Z_header;
extern struct PitemZ_header Pdoor_st_arec2Z_header;
extern struct PitemZ_header Pdoor_dest1Z_header;
extern struct PitemZ_header Pdoor_dest2Z_header;
extern struct PitemZ_header Pgas_plant_sw_do1Z_header;
extern struct PitemZ_header Pgas_plant_sw2_do1Z_header;
extern struct PitemZ_header Pgas_plant_sw3_do1Z_header;
extern struct PitemZ_header Pgas_plant_sw4_do1Z_header;
extern struct PitemZ_header Pgas_plant_met1_do1Z_header;
extern struct PitemZ_header Pgas_plant_wc_cub1Z_header;
extern struct PitemZ_header Pgasplant_clear_doorZ_header;
extern struct PitemZ_header Ptrain_doorZ_header;
extern struct PitemZ_header Ptrain_door2Z_header;
extern struct PitemZ_header Ptrain_door3Z_header;
extern struct PitemZ_header Pdoor_eyelidZ_header;
extern struct PitemZ_header Pdoor_irisZ_header;
extern struct PitemZ_header PsevdoorwoodZ_header;
extern struct PitemZ_header PsevdoorwindZ_header;
extern struct PitemZ_header PsevdoornowindZ_header;
extern struct PitemZ_header PsevdoormetslideZ_header;
extern struct PitemZ_header Pcryptdoor1aZ_header;
extern struct PitemZ_header Pcryptdoor1bZ_header;
extern struct PitemZ_header Pcryptdoor2aZ_header;
extern struct PitemZ_header Pcryptdoor2bZ_header;
extern struct PitemZ_header Pcryptdoor3Z_header;
extern struct PitemZ_header Pcryptdoor4Z_header;
extern struct PitemZ_header PvertdoorZ_header;
extern struct PitemZ_header PhatchdoorZ_header;
extern struct PitemZ_header PdamgatedoorZ_header;
extern struct PitemZ_header PdamtundoorZ_header;
extern struct PitemZ_header PdamchaindoorZ_header;
extern struct PitemZ_header PsilotopdoorZ_header;
extern struct PitemZ_header Pdoorprison1Z_header;
extern struct PitemZ_header PdoorstatgateZ_header;
extern struct PitemZ_header PchrkalashZ_header;
extern struct PitemZ_header PchrgrenadelaunchZ_header;
extern struct PitemZ_header PchrknifeZ_header;
extern struct PitemZ_header PchrlaserZ_header;
extern struct PitemZ_header Pchrm16Z_header;
extern struct PitemZ_header Pchrmp5kZ_header;
extern struct PitemZ_header PchrrugerZ_header;
extern struct PitemZ_header PchrwppkZ_header;
extern struct PitemZ_header PchrshotgunZ_header;
extern struct PitemZ_header PchrskorpionZ_header;
extern struct PitemZ_header PchrspectreZ_header;
extern struct PitemZ_header PchruziZ_header;
extern struct PitemZ_header PchrgrenadeZ_header;
extern struct PitemZ_header Pchrfnp90Z_header;
extern struct PitemZ_header PchrbriefcaseZ_header;
extern struct PitemZ_header PchrremotemineZ_header;
extern struct PitemZ_header PchrproximitymineZ_header;
extern struct PitemZ_header PchrtimedmineZ_header;
extern struct PitemZ_header PchrrocketZ_header;
extern struct PitemZ_header PchrgrenaderoundZ_header;
extern struct PitemZ_header PchrwppksilZ_header;
extern struct PitemZ_header Pchrtt33Z_header;
extern struct PitemZ_header Pchrmp5ksilZ_header;
extern struct PitemZ_header PchrautoshotZ_header;
extern struct PitemZ_header PchrgoldenZ_header;
extern struct PitemZ_header PchrthrowknifeZ_header;
extern struct PitemZ_header PchrsniperrifleZ_header;
extern struct PitemZ_header PchrrocketlaunchZ_header;
extern struct PitemZ_header PhatfurryZ_header;
extern struct PitemZ_header PhatfurrybrownZ_header;
extern struct PitemZ_header PhatfurryblackZ_header;
extern struct PitemZ_header PhattbirdZ_header;
extern struct PitemZ_header PhattbirdbrownZ_header;
extern struct PitemZ_header PhathelmetZ_header;
extern struct PitemZ_header PhathelmetgreyZ_header;
extern struct PitemZ_header PhatmoonZ_header;
extern struct PitemZ_header PhatberetZ_header;
extern struct PitemZ_header PhatberetblueZ_header;
extern struct PitemZ_header PhatberetredZ_header;
extern struct PitemZ_header PhatpeakedZ_header;
extern struct PitemZ_header PchrwristdartZ_header;
extern struct PitemZ_header PchrexplosivepenZ_header;
extern struct PitemZ_header PchrbombcaseZ_header;
extern struct PitemZ_header PchrflarepistolZ_header;
extern struct PitemZ_header PchrpitongunZ_header;
extern struct PitemZ_header PchrfingergunZ_header;
extern struct PitemZ_header PchrsilverwppkZ_header;
extern struct PitemZ_header PchrgoldwppkZ_header;
extern struct PitemZ_header PchrdynamiteZ_header;
extern struct PitemZ_header PchrbungeeZ_header;
extern struct PitemZ_header PchrdoordecoderZ_header;
extern struct PitemZ_header PchrbombdefuserZ_header;
extern struct PitemZ_header PchrbugdetectorZ_header;
extern struct PitemZ_header PchrsafecrackercaseZ_header;
extern struct PitemZ_header PchrcameraZ_header;
extern struct PitemZ_header PchrlockexploderZ_header;
extern struct PitemZ_header PchrdoorexploderZ_header;
extern struct PitemZ_header PchrkeyanalysercaseZ_header;
extern struct PitemZ_header PchrweaponcaseZ_header;
extern struct PitemZ_header PchrkeyyaleZ_header;
extern struct PitemZ_header PchrkeyboltZ_header;
extern struct PitemZ_header PchrbugZ_header;
extern struct PitemZ_header PchrmicrocameraZ_header;
extern struct PitemZ_header PfloppyZ_header;
extern struct PitemZ_header PchrgoldeneyekeyZ_header;
extern struct PitemZ_header PchrpolarizedglassesZ_header;
extern struct PitemZ_header PchrcreditcardZ_header;
extern struct PitemZ_header PchrdarkglassesZ_header;
extern struct PitemZ_header PchrgaskeyringZ_header;
extern struct PitemZ_header PchrdatathiefZ_header;
extern struct PitemZ_header PsafeZ_header;
extern struct PitemZ_header PbombZ_header;
extern struct PitemZ_header PchrplansZ_header;
extern struct PitemZ_header PchrspyfileZ_header;
extern struct PitemZ_header PchrblueprintsZ_header;
extern struct PitemZ_header PchrcircuitboardZ_header;
extern struct PitemZ_header PchrmapZ_header;
extern struct PitemZ_header PchrspooltapeZ_header;
extern struct PitemZ_header PchraudiotapeZ_header;
extern struct PitemZ_header PchrmicrofilmZ_header;
extern struct PitemZ_header PchrmicrocodeZ_header;
extern struct PitemZ_header PchrlectreZ_header;
extern struct PitemZ_header PchrmoneyZ_header;
extern struct PitemZ_header PchrgoldbarZ_header;
extern struct PitemZ_header PchrheroinZ_header;
extern struct PitemZ_header PchrclipboardZ_header;
extern struct PitemZ_header PchrdossierredZ_header;
extern struct PitemZ_header PchrstafflistZ_header;
extern struct PitemZ_header PchrdattapeZ_header;
extern struct PitemZ_header PchrplastiqueZ_header;
extern struct PitemZ_header PchrblackboxZ_header;
extern struct PitemZ_header PchrvideotapeZ_header;
extern struct PitemZ_header PnintendologoZ_header;
extern struct PitemZ_header PgoldeneyelogoZ_header;
extern struct PitemZ_header PwalletbondZ_header;
extern struct PitemZ_header PmiltruckZ_header;
extern struct PitemZ_header PjeepZ_header;
extern struct PitemZ_header ParticZ_header;
extern struct PitemZ_header PhelicopterZ_header;
extern struct PitemZ_header PtigerZ_header;
extern struct PitemZ_header PmilcopterZ_header;
extern struct PitemZ_header PhindZ_header;
extern struct PitemZ_header PartictrailerZ_header;
extern struct PitemZ_header PmotorbikeZ_header;
extern struct PitemZ_header PtankZ_header;
extern struct PitemZ_header PapcZ_header;
extern struct PitemZ_header PspeedboatZ_header;
extern struct PitemZ_header PplaneZ_header;
extern struct PitemZ_header Pgun_runway1Z_header;
extern struct PitemZ_header PsafedoorZ_header;
extern struct PitemZ_header Pkey_holderZ_header;
extern struct PitemZ_header PhatchsevxZ_header;
extern struct PitemZ_header PsevdishZ_header;
extern struct PitemZ_header Parchsecdoor1Z_header;
extern struct PitemZ_header Parchsecdoor2Z_header;
extern struct PitemZ_header PgroundgunZ_header;
extern struct PitemZ_header PtrainextdoorZ_header;
extern struct PitemZ_header PcarbmwZ_header;
extern struct PitemZ_header PcarescortZ_header;
extern struct PitemZ_header PcargolfZ_header;
extern struct PitemZ_header PcarweirdZ_header;
extern struct PitemZ_header PcarzilZ_header;
extern struct PitemZ_header Pshuttle_door_lZ_header;
extern struct PitemZ_header Pshuttle_door_rZ_header;
extern struct PitemZ_header Pdepot_gate_entryZ_header;
extern struct PitemZ_header Pdepot_door_steelZ_header;
extern struct PitemZ_header Pglassware2Z_header;
extern struct PitemZ_header Pglassware3Z_header;
extern struct PitemZ_header Pglassware4Z_header;
extern struct PitemZ_header PlandmineZ_header;
extern struct PitemZ_header Pplant1Z_header;
extern struct PitemZ_header Pplant11Z_header;
extern struct PitemZ_header Pplant2Z_header;
extern struct PitemZ_header Pplant3Z_header;
extern struct PitemZ_header Pjungle5_treeZ_header;
extern struct PitemZ_header PlegalpageZ_header;
extern struct PitemZ_header Pst_pete_room_1iZ_header;
extern struct PitemZ_header Pst_pete_room_2iZ_header;
extern struct PitemZ_header Pst_pete_room_3tZ_header;
extern struct PitemZ_header Pst_pete_room_5cZ_header;
extern struct PitemZ_header Pst_pete_room_6cZ_header;
extern struct PitemZ_header Pdoor_rollertrainZ_header;
extern struct PitemZ_header Pdoor_winZ_header;
extern struct PitemZ_header Pdoor_aztecZ_header;
extern struct PitemZ_header PshuttleZ_header;
extern struct PitemZ_header Pdoor_azt_deskZ_header;
extern struct PitemZ_header Pdoor_azt_desk_topZ_header;
extern struct PitemZ_header Pdoor_azt_chairZ_header;
extern struct PitemZ_header Pdoor_mfZ_header;
extern struct PitemZ_header PflagZ_header;
extern struct PitemZ_header PbarricadeZ_header;
extern struct PitemZ_header PmodemboxZ_header;
extern struct PitemZ_header PdoorpanelZ_header;
extern struct PitemZ_header PdoorconsoleZ_header;
extern struct PitemZ_header PchrtesttubeZ_header;
extern struct PitemZ_header Pbollardz_header;

extern struct c_itementry c_item_entries[];

#endif
