             /*NAME, NOMODEL,         STATS,      UPPERTEXTID,      LOWERTEXTID,   POSX,   POSY,   POSZ,   XROT,  YROT,           WOCTEXT,        EQUIPTEXT,   EQUIPX, EQUIPY, EQUIPZ*/
GUNFILERECORD( fist,      0, GUNSTATS(fist), TEXT(LGUN, GUN_STR_83), TEXT(LGUN, GUN_STR_76),    0.0,    0.0, 1000.0,    0.0,   0.0,  TEXT(LGUN, GUN_STR_76), TEXT(LGUN, GUN_STR_CD),   10.0,     10.0, 1000.0)
