# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches

.include "globals.inc"
.include "macros.inc"

.include "src/header.s"
.section .c_data, "a"
.global Compressedrodata
Compressedrodata:
 # make a hole for when we compress .data segment
 .space 0x11C00
.global Compressedrodata_end
Compressedrodata_end:
.include "bin/romfiles.s"
.include "ramrom/ramrom.s"
.include "font/font.s"
.include "music/music.s"
.include "obseg/ob_seg.s"
.include "images/images.s"

# PADDING region BE6D10-C00000 [192F0]
.space 0x192F0, 0xFF


.include "src/buffers.s"



