             /*NAME, NOMODEL,         STATS,      UPPERTEXTID,      LOWERTEXTID,   POSX,   POSY,   POSZ,   XROT,  YROT,           WOCTEXT,        EQUIPTEXT,   EQUIPX, EQUIPY, EQUIPZ*/
GUNFILERECORD(knife,       0, GUNSTATS(knife), TEXT(LGUN, GUN_STR_83), TEXT(LGUN, GUN_STR_46), 200.0,  39.0, 1327.0,   0.0,    0.0,  TEXT(LGUN, GUN_STR_40),  TEXT(LGUN, GUN_STR_A8), 38.0, 118.0, 800.0)
