
base $80300000
seg_sp_start:
decompression_buffer:

base $803AB400
sp_boot:

base $803AB3D0
sp_init:;scope sp_init {
define sp_init_s0($1C)
define sp_init_s1($20)
define sp_init_ra($24)
define rarezip_pos($28)
define rodata_pos($34)
}

base $803AB410
sp_rmon:

base $803AB710
sp_idle:

base $803AB750
sp_shed:

base $803AB950
sp_main:

base $803B3950
sp_audi:

base $803B4950
sp_unknown:
seg_sp_end:
