# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# asm file.

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel sqrtf
/* 0203E0 7001F7E0 03E00008 */  jr    $ra
/* 0203E4 7001F7E4 46006004 */   sqrt.s $f0, $f12

