# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osAiDeviceBusy
/* 019CF0 700190F0 3C0EA450 */  lui   $t6, %hi(AI_STATUS_REG) # $t6, 0xa450
/* 019CF4 700190F4 8DC4000C */  lw    $a0, %lo(AI_STATUS_REG)($t6)
/* 019CF8 700190F8 3C018000 */  lui   $at, 0x8000
/* 019CFC 700190FC 27BDFFF8 */  addiu $sp, $sp, -8
/* 019D00 70019100 00817824 */  and   $t7, $a0, $at
/* 019D04 70019104 11E00003 */  beqz  $t7, .L70019114
/* 019D08 70019108 00000000 */   nop   
/* 019D0C 7001910C 10000002 */  b     .L70019118
/* 019D10 70019110 24020001 */   li    $v0, 1
.L70019114:
/* 019D14 70019114 00001025 */  move  $v0, $zero
.L70019118:
/* 019D18 70019118 03E00008 */  jr    $ra
/* 019D1C 7001911C 27BD0008 */   addiu $sp, $sp, 8
