# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alAuxBusParam
/* 01C0E0 7001B4E0 24010002 */  li    $at, 2
/* 01C0E4 7001B4E4 14A10008 */  bne   $a1, $at, .L7001B508
/* 01C0E8 7001B4E8 8C82001C */   lw    $v0, 0x1c($a0)
/* 01C0EC 7001B4EC 8C8E0014 */  lw    $t6, 0x14($a0)
/* 01C0F0 7001B4F0 000E7880 */  sll   $t7, $t6, 2
/* 01C0F4 7001B4F4 004FC021 */  addu  $t8, $v0, $t7
/* 01C0F8 7001B4F8 AF060000 */  sw    $a2, ($t8)
/* 01C0FC 7001B4FC 8C990014 */  lw    $t9, 0x14($a0)
/* 01C100 7001B500 27280001 */  addiu $t0, $t9, 1
/* 01C104 7001B504 AC880014 */  sw    $t0, 0x14($a0)
.L7001B508:
/* 01C108 7001B508 03E00008 */  jr    $ra
/* 01C10C 7001B50C 00001025 */   move  $v0, $zero

glabel alAuxBusPull
/* 01C110 7001B510 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 01C114 7001B514 8FA80050 */  lw    $t0, 0x50($sp)
/* 01C118 7001B518 AFBF003C */  sw    $ra, 0x3c($sp)
/* 01C11C 7001B51C AFB60038 */  sw    $s6, 0x38($sp)
/* 01C120 7001B520 AFB50034 */  sw    $s5, 0x34($sp)
/* 01C124 7001B524 AFB40030 */  sw    $s4, 0x30($sp)
/* 01C128 7001B528 AFB3002C */  sw    $s3, 0x2c($sp)
/* 01C12C 7001B52C AFB20028 */  sw    $s2, 0x28($sp)
/* 01C130 7001B530 AFB10024 */  sw    $s1, 0x24($sp)
/* 01C134 7001B534 AFB00020 */  sw    $s0, 0x20($sp)
/* 01C138 7001B538 8C83001C */  lw    $v1, 0x1c($a0)
/* 01C13C 7001B53C 3C0E0200 */  lui   $t6, (0x020006C0 >> 16) # lui $t6, 0x200
/* 01C140 7001B540 00061040 */  sll   $v0, $a2, 1
/* 01C144 7001B544 3C0F0200 */  lui   $t7, (0x02000800 >> 16) # lui $t7, 0x200
/* 01C148 7001B548 35CE06C0 */  ori   $t6, (0x020006C0 & 0xFFFF) # ori $t6, $t6, 0x6c0
/* 01C14C 7001B54C 35EF0800 */  ori   $t7, (0x02000800 & 0xFFFF) # ori $t7, $t7, 0x800
/* 01C150 7001B550 AD0E0000 */  sw    $t6, ($t0)
/* 01C154 7001B554 AD020004 */  sw    $v0, 4($t0)
/* 01C158 7001B558 AD0F0008 */  sw    $t7, 8($t0)
/* 01C15C 7001B55C AD02000C */  sw    $v0, 0xc($t0)
/* 01C160 7001B560 8C980014 */  lw    $t8, 0x14($a0)
/* 01C164 7001B564 00C0A025 */  move  $s4, $a2
/* 01C168 7001B568 00A0A825 */  move  $s5, $a1
/* 01C16C 7001B56C 00E0B025 */  move  $s6, $a3
/* 01C170 7001B570 00809825 */  move  $s3, $a0
/* 01C174 7001B574 00008025 */  move  $s0, $zero
/* 01C178 7001B578 1B000010 */  blez  $t8, .L7001B5BC
/* 01C17C 7001B57C 25120010 */   addiu $s2, $t0, 0x10
/* 01C180 7001B580 00608825 */  move  $s1, $v1
.L7001B584:
/* 01C184 7001B584 8E240000 */  lw    $a0, ($s1)
/* 01C188 7001B588 AFB20010 */  sw    $s2, 0x10($sp)
/* 01C18C 7001B58C 02A02825 */  move  $a1, $s5
/* 01C190 7001B590 8C990004 */  lw    $t9, 4($a0)
/* 01C194 7001B594 02803025 */  move  $a2, $s4
/* 01C198 7001B598 02C03825 */  move  $a3, $s6
/* 01C19C 7001B59C 0320F809 */  jalr  $t9
/* 01C1A0 7001B5A0 00000000 */  nop   
/* 01C1A4 7001B5A4 8E690014 */  lw    $t1, 0x14($s3)
/* 01C1A8 7001B5A8 26100001 */  addiu $s0, $s0, 1
/* 01C1AC 7001B5AC 26310004 */  addiu $s1, $s1, 4
/* 01C1B0 7001B5B0 0209082A */  slt   $at, $s0, $t1
/* 01C1B4 7001B5B4 1420FFF3 */  bnez  $at, .L7001B584
/* 01C1B8 7001B5B8 00409025 */   move  $s2, $v0
.L7001B5BC:
/* 01C1BC 7001B5BC 8FBF003C */  lw    $ra, 0x3c($sp)
/* 01C1C0 7001B5C0 02401025 */  move  $v0, $s2
/* 01C1C4 7001B5C4 8FB20028 */  lw    $s2, 0x28($sp)
/* 01C1C8 7001B5C8 8FB00020 */  lw    $s0, 0x20($sp)
/* 01C1CC 7001B5CC 8FB10024 */  lw    $s1, 0x24($sp)
/* 01C1D0 7001B5D0 8FB3002C */  lw    $s3, 0x2c($sp)
/* 01C1D4 7001B5D4 8FB40030 */  lw    $s4, 0x30($sp)
/* 01C1D8 7001B5D8 8FB50034 */  lw    $s5, 0x34($sp)
/* 01C1DC 7001B5DC 8FB60038 */  lw    $s6, 0x38($sp)
/* 01C1E0 7001B5E0 03E00008 */  jr    $ra
/* 01C1E4 7001B5E4 27BD0040 */   addiu $sp, $sp, 0x40

