# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osEepromLongWrite
/* 016560 70015960 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 016564 70015964 AFA50044 */  sw    $a1, 0x44($sp)
/* 016568 70015968 93AE0047 */  lbu   $t6, 0x47($sp)
/* 01656C 7001596C AFBF0024 */  sw    $ra, 0x24($sp)
/* 016570 70015970 AFA40040 */  sw    $a0, 0x40($sp)
/* 016574 70015974 29C10041 */  slti  $at, $t6, 0x41
/* 016578 70015978 AFA60048 */  sw    $a2, 0x48($sp)
/* 01657C 7001597C AFA7004C */  sw    $a3, 0x4c($sp)
/* 016580 70015980 14200003 */  bnez  $at, .L70015990
/* 016584 70015984 AFA0003C */   sw    $zero, 0x3c($sp)
/* 016588 70015988 10000040 */  b     .L70015A8C
/* 01658C 7001598C 2402FFFF */   li    $v0, -1
.L70015990:
/* 016590 70015990 8FAF004C */  lw    $t7, 0x4c($sp)
/* 016594 70015994 19E0003C */  blez  $t7, .L70015A88
/* 016598 70015998 00000000 */   nop   
.L7001599C:
/* 01659C 7001599C 8FA40040 */  lw    $a0, 0x40($sp)
/* 0165A0 700159A0 93A50047 */  lbu   $a1, 0x47($sp)
/* 0165A4 700159A4 0C0054D0 */  jal   osEepromWrite
/* 0165A8 700159A8 8FA60048 */   lw    $a2, 0x48($sp)
/* 0165AC 700159AC AFA2003C */  sw    $v0, 0x3c($sp)
/* 0165B0 700159B0 8FB8003C */  lw    $t8, 0x3c($sp)
/* 0165B4 700159B4 13000003 */  beqz  $t8, .L700159C4
/* 0165B8 700159B8 00000000 */   nop   
/* 0165BC 700159BC 10000033 */  b     .L70015A8C
/* 0165C0 700159C0 03001025 */   move  $v0, $t8
.L700159C4:
/* 0165C4 700159C4 8FB9004C */  lw    $t9, 0x4c($sp)
/* 0165C8 700159C8 93A90047 */  lbu   $t1, 0x47($sp)
/* 0165CC 700159CC 8FAB0048 */  lw    $t3, 0x48($sp)
/* 0165D0 700159D0 3C068002 */  lui   $a2, %hi(osClockRate)
/* 0165D4 700159D4 3C078002 */  lui   $a3, %hi(osClockRate+4)
/* 0165D8 700159D8 2728FFF8 */  addiu $t0, $t9, -8
/* 0165DC 700159DC 252A0001 */  addiu $t2, $t1, 1
/* 0165E0 700159E0 256C0008 */  addiu $t4, $t3, 8
/* 0165E4 700159E4 AFA8004C */  sw    $t0, 0x4c($sp)
/* 0165E8 700159E8 A3AA0047 */  sb    $t2, 0x47($sp)
/* 0165EC 700159EC AFAC0048 */  sw    $t4, 0x48($sp)
/* 0165F0 700159F0 8CE76984 */  lw    $a3, %lo(osClockRate+4)($a3)
/* 0165F4 700159F4 8CC66980 */  lw    $a2, %lo(osClockRate)($a2)
/* 0165F8 700159F8 24040000 */  li    $a0, 0
/* 0165FC 700159FC 0C003B6A */  jal   __ll_mul
/* 016600 70015A00 24052EE0 */   li    $a1, 12000
/* 016604 70015A04 AFA20028 */  sw    $v0, 0x28($sp)
/* 016608 70015A08 AFA3002C */  sw    $v1, 0x2c($sp)
/* 01660C 70015A0C 3C07000F */  lui   $a3, (0x000F4240 >> 16) # lui $a3, 0xf
/* 016610 70015A10 34E74240 */  ori   $a3, (0x000F4240 & 0xFFFF) # ori $a3, $a3, 0x4240
/* 016614 70015A14 8FA5002C */  lw    $a1, 0x2c($sp)
/* 016618 70015A18 8FA40028 */  lw    $a0, 0x28($sp)
/* 01661C 70015A1C 0C003B2A */  jal   __ull_div
/* 016620 70015A20 24060000 */   li    $a2, 0
/* 016624 70015A24 3C0D8006 */  lui   $t5, %hi(__osEepromTimerQ) 
/* 016628 70015A28 3C188006 */  lui   $t8, %hi(__osEepromTimerMsg) 
/* 01662C 70015A2C 27187D20 */  addiu $t8, %lo(__osEepromTimerMsg) # addiu $t8, $t8, 0x7d20
/* 016630 70015A30 25AD7D08 */  addiu $t5, %lo(__osEepromTimerQ) # addiu $t5, $t5, 0x7d08
/* 016634 70015A34 AFA20030 */  sw    $v0, 0x30($sp)
/* 016638 70015A38 AFA30034 */  sw    $v1, 0x34($sp)
/* 01663C 70015A3C 3C048006 */  lui   $a0, %hi(__osEepromTimer)
/* 016640 70015A40 240E0000 */  li    $t6, 0
/* 016644 70015A44 240F0000 */  li    $t7, 0
/* 016648 70015A48 AFAF0014 */  sw    $t7, 0x14($sp)
/* 01664C 70015A4C AFAE0010 */  sw    $t6, 0x10($sp)
/* 016650 70015A50 24847CE8 */  addiu $a0, %lo(__osEepromTimer) # addiu $a0, $a0, 0x7ce8
/* 016654 70015A54 8FA70034 */  lw    $a3, 0x34($sp)
/* 016658 70015A58 8FA60030 */  lw    $a2, 0x30($sp)
/* 01665C 70015A5C AFAD0018 */  sw    $t5, 0x18($sp)
/* 016660 70015A60 0C004314 */  jal   osSetTimer
/* 016664 70015A64 AFB8001C */   sw    $t8, 0x1c($sp)
/* 016668 70015A68 3C048006 */  lui   $a0, %hi(__osEepromTimerQ)
/* 01666C 70015A6C 24847D08 */  addiu $a0, %lo(__osEepromTimerQ) # addiu $a0, $a0, 0x7d08
/* 016670 70015A70 00002825 */  move  $a1, $zero
/* 016674 70015A74 0C003774 */  jal   osRecvMesg
/* 016678 70015A78 24060001 */   li    $a2, 1
/* 01667C 70015A7C 8FB9004C */  lw    $t9, 0x4c($sp)
/* 016680 70015A80 1F20FFC6 */  bgtz  $t9, .L7001599C
/* 016684 70015A84 00000000 */   nop   
.L70015A88:
/* 016688 70015A88 8FA2003C */  lw    $v0, 0x3c($sp)
.L70015A8C:
/* 01668C 70015A8C 8FBF0024 */  lw    $ra, 0x24($sp)
/* 016690 70015A90 27BD0040 */  addiu $sp, $sp, 0x40
/* 016694 70015A94 03E00008 */  jr    $ra
/* 016698 70015A98 00000000 */   nop   

/* 01669C 70015A9C 00000000 */  nop   
