# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osEepromProbe
/* 015BD0 70014FD0 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 015BD4 70014FD4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 015BD8 70014FD8 AFA40020 */  sw    $a0, 0x20($sp)
/* 015BDC 70014FDC 0C005798 */  jal   __osSiGetAccess
/* 015BE0 70014FE0 AFA0001C */   sw    $zero, 0x1c($sp)
/* 015BE4 70014FE4 8FA40020 */  lw    $a0, 0x20($sp)
/* 015BE8 70014FE8 0C00557F */  jal   __osEepStatus
/* 015BEC 70014FEC 27A50018 */   addiu $a1, $sp, 0x18
/* 015BF0 70014FF0 AFA2001C */  sw    $v0, 0x1c($sp)
/* 015BF4 70014FF4 8FAE001C */  lw    $t6, 0x1c($sp)
/* 015BF8 70014FF8 15C00008 */  bnez  $t6, .L7001501C
/* 015BFC 70014FFC 00000000 */   nop   
/* 015C00 70015000 97AF0018 */  lhu   $t7, 0x18($sp)
/* 015C04 70015004 31F88000 */  andi  $t8, $t7, 0x8000
/* 015C08 70015008 13000004 */  beqz  $t8, .L7001501C
/* 015C0C 7001500C 00000000 */   nop   
/* 015C10 70015010 24190001 */  li    $t9, 1
/* 015C14 70015014 10000002 */  b     .L70015020
/* 015C18 70015018 AFB9001C */   sw    $t9, 0x1c($sp)
.L7001501C:
/* 015C1C 7001501C AFA0001C */  sw    $zero, 0x1c($sp)
.L70015020:
/* 015C20 70015020 0C0057A9 */  jal   __osSiRelAccess
/* 015C24 70015024 00000000 */   nop   
/* 015C28 70015028 8FBF0014 */  lw    $ra, 0x14($sp)
/* 015C2C 7001502C 8FA2001C */  lw    $v0, 0x1c($sp)
/* 015C30 70015030 27BD0020 */  addiu $sp, $sp, 0x20
/* 015C34 70015034 03E00008 */  jr    $ra
/* 015C38 70015038 00000000 */   nop   

/* 015C3C 7001503C 00000000 */  nop   
