# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text  
glabel osContStartQuery
/* 0158C0 70014CC0 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 0158C4 70014CC4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0158C8 70014CC8 AFA40020 */  sw    $a0, 0x20($sp)
/* 0158CC 70014CCC 0C005798 */  jal   __osSiGetAccess
/* 0158D0 70014CD0 AFA0001C */   sw    $zero, 0x1c($sp)
/* 0158D4 70014CD4 3C0E8006 */  lui   $t6, %hi(__osContLastCmd) 
/* 0158D8 70014CD8 91CE7CE0 */  lbu   $t6, %lo(__osContLastCmd)($t6)
/* 0158DC 70014CDC 11C0000C */  beqz  $t6, .L70014D10
/* 0158E0 70014CE0 00000000 */   nop   
/* 0158E4 70014CE4 0C0052F2 */  jal   __osPackRequestData
/* 0158E8 70014CE8 00002025 */   move  $a0, $zero
/* 0158EC 70014CEC 3C058006 */  lui   $a1, %hi(__osContPifRam)
/* 0158F0 70014CF0 24A57CA0 */  addiu $a1, %lo(__osContPifRam) # addiu $a1, $a1, 0x7ca0
/* 0158F4 70014CF4 0C0057B4 */  jal   __osSiRawStartDma
/* 0158F8 70014CF8 24040001 */   li    $a0, 1
/* 0158FC 70014CFC AFA2001C */  sw    $v0, 0x1c($sp)
/* 015900 70014D00 8FA40020 */  lw    $a0, 0x20($sp)
/* 015904 70014D04 00002825 */  move  $a1, $zero
/* 015908 70014D08 0C003774 */  jal   osRecvMesg
/* 01590C 70014D0C 24060001 */   li    $a2, 1
.L70014D10:
/* 015910 70014D10 3C058006 */  lui   $a1, %hi(__osContPifRam)
/* 015914 70014D14 24A57CA0 */  addiu $a1, %lo(__osContPifRam) # addiu $a1, $a1, 0x7ca0
/* 015918 70014D18 0C0057B4 */  jal   __osSiRawStartDma
/* 01591C 70014D1C 00002025 */   move  $a0, $zero
/* 015920 70014D20 3C018006 */  lui   $at, %hi(__osContLastCmd)
/* 015924 70014D24 AFA2001C */  sw    $v0, 0x1c($sp)
/* 015928 70014D28 0C0057A9 */  jal   __osSiRelAccess
/* 01592C 70014D2C A0207CE0 */   sb    $zero, %lo(__osContLastCmd)($at)
/* 015930 70014D30 8FBF0014 */  lw    $ra, 0x14($sp)
/* 015934 70014D34 8FA2001C */  lw    $v0, 0x1c($sp)
/* 015938 70014D38 27BD0020 */  addiu $sp, $sp, 0x20
/* 01593C 70014D3C 03E00008 */  jr    $ra
/* 015940 70014D40 00000000 */   nop   

glabel osContGetQuery
/* 015944 70014D44 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 015948 70014D48 AFBF0014 */  sw    $ra, 0x14($sp)
/* 01594C 70014D4C AFA40020 */  sw    $a0, 0x20($sp)
/* 015950 70014D50 8FA50020 */  lw    $a1, 0x20($sp)
/* 015954 70014D54 0C0052BE */  jal   __osContGetInitData
/* 015958 70014D58 27A4001F */   addiu $a0, $sp, 0x1f
/* 01595C 70014D5C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 015960 70014D60 27BD0020 */  addiu $sp, $sp, 0x20
/* 015964 70014D64 03E00008 */  jr    $ra
/* 015968 70014D68 00000000 */   nop   



