# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osContRamWrite
/* 016D00 70016100 27BDFFA0 */  addiu $sp, $sp, -0x60
/* 016D04 70016104 8FB80070 */  lw    $t8, 0x70($sp)
/* 016D08 70016108 3C0E8006 */  lui   $t6, %hi(__osPfsPifRam) 
/* 016D0C 7001610C 25CE7D70 */  addiu $t6, %lo(__osPfsPifRam) # addiu $t6, $t6, 0x7d70
/* 016D10 70016110 240F0002 */  li    $t7, 2
/* 016D14 70016114 24010001 */  li    $at, 1
/* 016D18 70016118 AFBF001C */  sw    $ra, 0x1c($sp)
/* 016D1C 7001611C AFA40060 */  sw    $a0, 0x60($sp)
/* 016D20 70016120 AFA50064 */  sw    $a1, 0x64($sp)
/* 016D24 70016124 AFA60068 */  sw    $a2, 0x68($sp)
/* 016D28 70016128 AFA7006C */  sw    $a3, 0x6c($sp)
/* 016D2C 7001612C AFB00018 */  sw    $s0, 0x18($sp)
/* 016D30 70016130 AFA0005C */  sw    $zero, 0x5c($sp)
/* 016D34 70016134 AFAE0054 */  sw    $t6, 0x54($sp)
/* 016D38 70016138 13010009 */  beq   $t8, $at, .L70016160
/* 016D3C 7001613C AFAF0028 */   sw    $t7, 0x28($sp)
/* 016D40 70016140 97B9006A */  lhu   $t9, 0x6a($sp)
/* 016D44 70016144 2B210007 */  slti  $at, $t9, 7
/* 016D48 70016148 10200005 */  beqz  $at, .L70016160
/* 016D4C 7001614C 00000000 */   nop   
/* 016D50 70016150 13200003 */  beqz  $t9, .L70016160
/* 016D54 70016154 00000000 */   nop   
/* 016D58 70016158 10000070 */  b     .L7001631C
/* 016D5C 7001615C 00001025 */   move  $v0, $zero
.L70016160:
/* 016D60 70016160 0C005798 */  jal   __osSiGetAccess
/* 016D64 70016164 00000000 */   nop   
/* 016D68 70016168 24080003 */  li    $t0, 3
/* 016D6C 7001616C 3C018006 */  lui   $at, %hi(__osContLastCmd)
/* 016D70 70016170 A0287CE0 */  sb    $t0, %lo(__osContLastCmd)($at)
/* 016D74 70016174 8FA40064 */  lw    $a0, 0x64($sp)
/* 016D78 70016178 97A5006A */  lhu   $a1, 0x6a($sp)
/* 016D7C 7001617C 0C0058CC */  jal   __osContRamWrite_sub
/* 016D80 70016180 8FA6006C */   lw    $a2, 0x6c($sp)
/* 016D84 70016184 3C058006 */  lui   $a1, %hi(__osPfsPifRam)
/* 016D88 70016188 24A57D70 */  addiu $a1, %lo(__osPfsPifRam) # addiu $a1, $a1, 0x7d70
/* 016D8C 7001618C 0C0057B4 */  jal   __osSiRawStartDma
/* 016D90 70016190 24040001 */   li    $a0, 1
/* 016D94 70016194 AFA2005C */  sw    $v0, 0x5c($sp)
/* 016D98 70016198 8FA40060 */  lw    $a0, 0x60($sp)
/* 016D9C 7001619C 00002825 */  move  $a1, $zero
/* 016DA0 700161A0 0C003774 */  jal   osRecvMesg
/* 016DA4 700161A4 24060001 */   li    $a2, 1
.L700161A8:
/* 016DA8 700161A8 AFA00058 */  sw    $zero, 0x58($sp)
.L700161AC:
/* 016DAC 700161AC 8FAA0058 */  lw    $t2, 0x58($sp)
/* 016DB0 700161B0 8FAC0058 */  lw    $t4, 0x58($sp)
/* 016DB4 700161B4 3C018006 */  lui   $at, %hi(__osPfsPifRam)
/* 016DB8 700161B8 000A5880 */  sll   $t3, $t2, 2
/* 016DBC 700161BC 002B0821 */  addu  $at, $at, $t3
/* 016DC0 700161C0 240900FF */  li    $t1, 255
/* 016DC4 700161C4 AC297D70 */  sw    $t1, %lo(__osPfsPifRam)($at)
/* 016DC8 700161C8 258D0001 */  addiu $t5, $t4, 1
/* 016DCC 700161CC 29A10010 */  slti  $at, $t5, 0x10
/* 016DD0 700161D0 1420FFF6 */  bnez  $at, .L700161AC
/* 016DD4 700161D4 AFAD0058 */   sw    $t5, 0x58($sp)
/* 016DD8 700161D8 3C018006 */  lui   $at, %hi(__osPfsPifRam+0x3c)
/* 016DDC 700161DC 3C058006 */  lui   $a1, %hi(__osPfsPifRam)
/* 016DE0 700161E0 AC207DAC */  sw    $zero, %lo(__osPfsPifRam+0x3c)($at)
/* 016DE4 700161E4 24A57D70 */  addiu $a1, %lo(__osPfsPifRam) # addiu $a1, $a1, 0x7d70
/* 016DE8 700161E8 0C0057B4 */  jal   __osSiRawStartDma
/* 016DEC 700161EC 00002025 */   move  $a0, $zero
/* 016DF0 700161F0 AFA2005C */  sw    $v0, 0x5c($sp)
/* 016DF4 700161F4 8FA40060 */  lw    $a0, 0x60($sp)
/* 016DF8 700161F8 00002825 */  move  $a1, $zero
/* 016DFC 700161FC 0C003774 */  jal   osRecvMesg
/* 016E00 70016200 24060001 */   li    $a2, 1
/* 016E04 70016204 8FAF0064 */  lw    $t7, 0x64($sp)
/* 016E08 70016208 3C0E8006 */  lui   $t6, %hi(__osPfsPifRam) 
/* 016E0C 7001620C 25CE7D70 */  addiu $t6, %lo(__osPfsPifRam) # addiu $t6, $t6, 0x7d70
/* 016E10 70016210 11E0000C */  beqz  $t7, .L70016244
/* 016E14 70016214 AFAE0054 */   sw    $t6, 0x54($sp)
/* 016E18 70016218 19E0000A */  blez  $t7, .L70016244
/* 016E1C 7001621C AFA00058 */   sw    $zero, 0x58($sp)
.L70016220:
/* 016E20 70016220 8FA80058 */  lw    $t0, 0x58($sp)
/* 016E24 70016224 8FA90064 */  lw    $t1, 0x64($sp)
/* 016E28 70016228 8FB80054 */  lw    $t8, 0x54($sp)
/* 016E2C 7001622C 250A0001 */  addiu $t2, $t0, 1
/* 016E30 70016230 0149082A */  slt   $at, $t2, $t1
/* 016E34 70016234 27190001 */  addiu $t9, $t8, 1
/* 016E38 70016238 AFAA0058 */  sw    $t2, 0x58($sp)
/* 016E3C 7001623C 1420FFF8 */  bnez  $at, .L70016220
/* 016E40 70016240 AFB90054 */   sw    $t9, 0x54($sp)
.L70016244:
/* 016E44 70016244 8FAC0054 */  lw    $t4, 0x54($sp)
/* 016E48 70016248 27AB002C */  addiu $t3, $sp, 0x2c
/* 016E4C 7001624C 258E0024 */  addiu $t6, $t4, 0x24
.L70016250:
/* 016E50 70016250 89810000 */  lwl   $at, ($t4)
/* 016E54 70016254 99810003 */  lwr   $at, 3($t4)
/* 016E58 70016258 258C000C */  addiu $t4, $t4, 0xc
/* 016E5C 7001625C 256B000C */  addiu $t3, $t3, 0xc
/* 016E60 70016260 AD61FFF4 */  sw    $at, -0xc($t3)
/* 016E64 70016264 8981FFF8 */  lwl   $at, -8($t4)
/* 016E68 70016268 9981FFFB */  lwr   $at, -5($t4)
/* 016E6C 7001626C AD61FFF8 */  sw    $at, -8($t3)
/* 016E70 70016270 8981FFFC */  lwl   $at, -4($t4)
/* 016E74 70016274 9981FFFF */  lwr   $at, -1($t4)
/* 016E78 70016278 158EFFF5 */  bne   $t4, $t6, .L70016250
/* 016E7C 7001627C AD61FFFC */   sw    $at, -4($t3)
/* 016E80 70016280 89810000 */  lwl   $at, ($t4)
/* 016E84 70016284 99810003 */  lwr   $at, 3($t4)
/* 016E88 70016288 AD610000 */  sw    $at, ($t3)
/* 016E8C 7001628C 93AF002E */  lbu   $t7, 0x2e($sp)
/* 016E90 70016290 31F800C0 */  andi  $t8, $t7, 0xc0
/* 016E94 70016294 0018C903 */  sra   $t9, $t8, 4
/* 016E98 70016298 17200013 */  bnez  $t9, .L700162E8
/* 016E9C 7001629C AFB9005C */   sw    $t9, 0x5c($sp)
/* 016EA0 700162A0 0C00580C */  jal   __osContDataCrc
/* 016EA4 700162A4 8FA4006C */   lw    $a0, 0x6c($sp)
/* 016EA8 700162A8 93A80052 */  lbu   $t0, 0x52($sp)
/* 016EAC 700162AC 1048000E */  beq   $v0, $t0, .L700162E8
/* 016EB0 700162B0 00000000 */   nop   
/* 016EB4 700162B4 8FA40060 */  lw    $a0, 0x60($sp)
/* 016EB8 700162B8 0C0051FD */  jal   __osPfsGetStatus
/* 016EBC 700162BC 8FA50064 */   lw    $a1, 0x64($sp)
/* 016EC0 700162C0 AFA2005C */  sw    $v0, 0x5c($sp)
/* 016EC4 700162C4 8FAA005C */  lw    $t2, 0x5c($sp)
/* 016EC8 700162C8 11400005 */  beqz  $t2, .L700162E0
/* 016ECC 700162CC 00000000 */   nop   
/* 016ED0 700162D0 0C0057A9 */  jal   __osSiRelAccess
/* 016ED4 700162D4 00000000 */   nop   
/* 016ED8 700162D8 10000010 */  b     .L7001631C
/* 016EDC 700162DC 8FA2005C */   lw    $v0, 0x5c($sp)
.L700162E0:
/* 016EE0 700162E0 24090004 */  li    $t1, 4
/* 016EE4 700162E4 AFA9005C */  sw    $t1, 0x5c($sp)
.L700162E8:
/* 016EE8 700162E8 8FAD005C */  lw    $t5, 0x5c($sp)
/* 016EEC 700162EC 24010004 */  li    $at, 4
/* 016EF0 700162F0 15A10007 */  bne   $t5, $at, .L70016310
/* 016EF4 700162F4 00000000 */   nop   
/* 016EF8 700162F8 8FAE0028 */  lw    $t6, 0x28($sp)
/* 016EFC 700162FC 29D00000 */  slti  $s0, $t6, 0
/* 016F00 70016300 3A100001 */  xori  $s0, $s0, 1
/* 016F04 70016304 25CCFFFF */  addiu $t4, $t6, -1
/* 016F08 70016308 1600FFA7 */  bnez  $s0, .L700161A8
/* 016F0C 7001630C AFAC0028 */   sw    $t4, 0x28($sp)
.L70016310:
/* 016F10 70016310 0C0057A9 */  jal   __osSiRelAccess
/* 016F14 70016314 00000000 */   nop   
/* 016F18 70016318 8FA2005C */  lw    $v0, 0x5c($sp)
.L7001631C:
/* 016F1C 7001631C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 016F20 70016320 8FB00018 */  lw    $s0, 0x18($sp)
/* 016F24 70016324 27BD0060 */  addiu $sp, $sp, 0x60
/* 016F28 70016328 03E00008 */  jr    $ra
/* 016F2C 7001632C 00000000 */   nop   

glabel __osContRamWrite_sub
/* 016F30 70016330 27BDFFB8 */  addiu $sp, $sp, -0x48
/* 016F34 70016334 3C0E8006 */  lui   $t6, %hi(__osPfsPifRam) 
/* 016F38 70016338 25CE7D70 */  addiu $t6, %lo(__osPfsPifRam) # addiu $t6, $t6, 0x7d70
/* 016F3C 7001633C AFBF0014 */  sw    $ra, 0x14($sp)
/* 016F40 70016340 AFA40048 */  sw    $a0, 0x48($sp)
/* 016F44 70016344 AFA5004C */  sw    $a1, 0x4c($sp)
/* 016F48 70016348 AFA60050 */  sw    $a2, 0x50($sp)
/* 016F4C 7001634C AFAE0044 */  sw    $t6, 0x44($sp)
/* 016F50 70016350 AFA00018 */  sw    $zero, 0x18($sp)
.L70016354:
/* 016F54 70016354 8FAF0018 */  lw    $t7, 0x18($sp)
/* 016F58 70016358 8FB90018 */  lw    $t9, 0x18($sp)
/* 016F5C 7001635C 3C018006 */  lui   $at, %hi(__osPfsPifRam)
/* 016F60 70016360 000FC080 */  sll   $t8, $t7, 2
/* 016F64 70016364 00380821 */  addu  $at, $at, $t8
/* 016F68 70016368 AC207D70 */  sw    $zero, %lo(__osPfsPifRam)($at)
/* 016F6C 7001636C 27280001 */  addiu $t0, $t9, 1
/* 016F70 70016370 29010010 */  slti  $at, $t0, 0x10
/* 016F74 70016374 1420FFF7 */  bnez  $at, .L70016354
/* 016F78 70016378 AFA80018 */   sw    $t0, 0x18($sp)
/* 016F7C 7001637C 24090001 */  li    $t1, 1
/* 016F80 70016380 3C018006 */  lui   $at, %hi(__osPfsPifRam+0x3c)
/* 016F84 70016384 240A00FF */  li    $t2, 255
/* 016F88 70016388 240B0023 */  li    $t3, 35
/* 016F8C 7001638C 240C0001 */  li    $t4, 1
/* 016F90 70016390 240D0003 */  li    $t5, 3
/* 016F94 70016394 AC297DAC */  sw    $t1, %lo(__osPfsPifRam+0x3c)($at)
/* 016F98 70016398 A3AA001C */  sb    $t2, 0x1c($sp)
/* 016F9C 7001639C A3AB001D */  sb    $t3, 0x1d($sp)
/* 016FA0 700163A0 A3AC001E */  sb    $t4, 0x1e($sp)
/* 016FA4 700163A4 A3AD001F */  sb    $t5, 0x1f($sp)
/* 016FA8 700163A8 0C0057E0 */  jal   __osContAddressCrc
/* 016FAC 700163AC 97A4004E */   lhu   $a0, 0x4e($sp)
/* 016FB0 700163B0 97AE004E */  lhu   $t6, 0x4e($sp)
/* 016FB4 700163B4 241900FF */  li    $t9, 255
/* 016FB8 700163B8 A3B90042 */  sb    $t9, 0x42($sp)
/* 016FBC 700163BC 000E7940 */  sll   $t7, $t6, 5
/* 016FC0 700163C0 004FC025 */  or    $t8, $v0, $t7
/* 016FC4 700163C4 A7B80020 */  sh    $t8, 0x20($sp)
/* 016FC8 700163C8 AFA00018 */  sw    $zero, 0x18($sp)
.L700163CC:
/* 016FCC 700163CC 8FA80050 */  lw    $t0, 0x50($sp)
/* 016FD0 700163D0 8FAA0018 */  lw    $t2, 0x18($sp)
/* 016FD4 700163D4 91090000 */  lbu   $t1, ($t0)
/* 016FD8 700163D8 03AA5821 */  addu  $t3, $sp, $t2
/* 016FDC 700163DC A1690022 */  sb    $t1, 0x22($t3)
/* 016FE0 700163E0 8FAE0018 */  lw    $t6, 0x18($sp)
/* 016FE4 700163E4 8FAC0050 */  lw    $t4, 0x50($sp)
/* 016FE8 700163E8 25CF0001 */  addiu $t7, $t6, 1
/* 016FEC 700163EC 29E10020 */  slti  $at, $t7, 0x20
/* 016FF0 700163F0 258D0001 */  addiu $t5, $t4, 1
/* 016FF4 700163F4 AFAF0018 */  sw    $t7, 0x18($sp)
/* 016FF8 700163F8 1420FFF4 */  bnez  $at, .L700163CC
/* 016FFC 700163FC AFAD0050 */   sw    $t5, 0x50($sp)
/* 017000 70016400 8FB80048 */  lw    $t8, 0x48($sp)
/* 017004 70016404 1300000E */  beqz  $t8, .L70016440
/* 017008 70016408 00000000 */   nop   
/* 01700C 7001640C 1B00000C */  blez  $t8, .L70016440
/* 017010 70016410 AFA00018 */   sw    $zero, 0x18($sp)
.L70016414:
/* 017014 70016414 8FB90044 */  lw    $t9, 0x44($sp)
/* 017018 70016418 A3200000 */  sb    $zero, ($t9)
/* 01701C 7001641C 8FAA0018 */  lw    $t2, 0x18($sp)
/* 017020 70016420 8FAC0048 */  lw    $t4, 0x48($sp)
/* 017024 70016424 8FA80044 */  lw    $t0, 0x44($sp)
/* 017028 70016428 254B0001 */  addiu $t3, $t2, 1
/* 01702C 7001642C 016C082A */  slt   $at, $t3, $t4
/* 017030 70016430 25090001 */  addiu $t1, $t0, 1
/* 017034 70016434 AFAB0018 */  sw    $t3, 0x18($sp)
/* 017038 70016438 1420FFF6 */  bnez  $at, .L70016414
/* 01703C 7001643C AFA90044 */   sw    $t1, 0x44($sp)
.L70016440:
/* 017040 70016440 27AE001C */  addiu $t6, $sp, 0x1c
/* 017044 70016444 25D80024 */  addiu $t8, $t6, 0x24
/* 017048 70016448 8FAD0044 */  lw    $t5, 0x44($sp)
.L7001644C:
/* 01704C 7001644C 8DC10000 */  lw    $at, ($t6)
/* 017050 70016450 25CE000C */  addiu $t6, $t6, 0xc
/* 017054 70016454 25AD000C */  addiu $t5, $t5, 0xc
/* 017058 70016458 A9A1FFF4 */  swl   $at, -0xc($t5)
/* 01705C 7001645C B9A1FFF7 */  swr   $at, -9($t5)
/* 017060 70016460 8DC1FFF8 */  lw    $at, -8($t6)
/* 017064 70016464 A9A1FFF8 */  swl   $at, -8($t5)
/* 017068 70016468 B9A1FFFB */  swr   $at, -5($t5)
/* 01706C 7001646C 8DC1FFFC */  lw    $at, -4($t6)
/* 017070 70016470 A9A1FFFC */  swl   $at, -4($t5)
/* 017074 70016474 15D8FFF5 */  bne   $t6, $t8, .L7001644C
/* 017078 70016478 B9A1FFFF */   swr   $at, -1($t5)
/* 01707C 7001647C 8DC10000 */  lw    $at, ($t6)
/* 017080 70016480 240900FE */  li    $t1, 254
/* 017084 70016484 A9A10000 */  swl   $at, ($t5)
/* 017088 70016488 B9A10003 */  swr   $at, 3($t5)
/* 01708C 7001648C 8FB90044 */  lw    $t9, 0x44($sp)
/* 017090 70016490 27280028 */  addiu $t0, $t9, 0x28
/* 017094 70016494 AFA80044 */  sw    $t0, 0x44($sp)
/* 017098 70016498 A1090000 */  sb    $t1, ($t0)
/* 01709C 7001649C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0170A0 700164A0 27BD0048 */  addiu $sp, $sp, 0x48
/* 0170A4 700164A4 03E00008 */  jr    $ra
/* 0170A8 700164A8 00000000 */   nop   

