# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osEepromRead
/* 015C40 70015040 27BDFFC8 */  addiu $sp, $sp, -0x38
/* 015C44 70015044 AFA5003C */  sw    $a1, 0x3c($sp)
/* 015C48 70015048 93AF003F */  lbu   $t7, 0x3f($sp)
/* 015C4C 7001504C 3C0E8006 */  lui   $t6, %hi(__osEepPifRam) 
/* 015C50 70015050 25CE7D30 */  addiu $t6, %lo(__osEepPifRam) # addiu $t6, $t6, 0x7d30
/* 015C54 70015054 29E10041 */  slti  $at, $t7, 0x41
/* 015C58 70015058 AFBF0014 */  sw    $ra, 0x14($sp)
/* 015C5C 7001505C AFA40038 */  sw    $a0, 0x38($sp)
/* 015C60 70015060 AFA60040 */  sw    $a2, 0x40($sp)
/* 015C64 70015064 AFA00034 */  sw    $zero, 0x34($sp)
/* 015C68 70015068 AFA00030 */  sw    $zero, 0x30($sp)
/* 015C6C 7001506C 14200003 */  bnez  $at, .L7001507C
/* 015C70 70015070 AFAE002C */   sw    $t6, 0x2c($sp)
/* 015C74 70015074 1000006A */  b     .L70015220
/* 015C78 70015078 2402FFFF */   li    $v0, -1
.L7001507C:
/* 015C7C 7001507C 0C005798 */  jal   __osSiGetAccess
/* 015C80 70015080 00000000 */   nop   
/* 015C84 70015084 8FA40038 */  lw    $a0, 0x38($sp)
/* 015C88 70015088 0C00557F */  jal   __osEepStatus
/* 015C8C 7001508C 27A50028 */   addiu $a1, $sp, 0x28
/* 015C90 70015090 AFA20034 */  sw    $v0, 0x34($sp)
/* 015C94 70015094 8FB80034 */  lw    $t8, 0x34($sp)
/* 015C98 70015098 17000005 */  bnez  $t8, .L700150B0
/* 015C9C 7001509C 00000000 */   nop   
/* 015CA0 700150A0 97B90028 */  lhu   $t9, 0x28($sp)
/* 015CA4 700150A4 34018000 */  li    $at, 32768
/* 015CA8 700150A8 13210003 */  beq   $t9, $at, .L700150B8
/* 015CAC 700150AC 00000000 */   nop   
.L700150B0:
/* 015CB0 700150B0 1000005B */  b     .L70015220
/* 015CB4 700150B4 24020008 */   li    $v0, 8
.L700150B8:
/* 015CB8 700150B8 93A8002A */  lbu   $t0, 0x2a($sp)
/* 015CBC 700150BC 31090080 */  andi  $t1, $t0, 0x80
/* 015CC0 700150C0 11200008 */  beqz  $t1, .L700150E4
/* 015CC4 700150C4 00000000 */   nop   
.L700150C8:
/* 015CC8 700150C8 8FA40038 */  lw    $a0, 0x38($sp)
/* 015CCC 700150CC 0C00557F */  jal   __osEepStatus
/* 015CD0 700150D0 27A50028 */   addiu $a1, $sp, 0x28
/* 015CD4 700150D4 93AA002A */  lbu   $t2, 0x2a($sp)
/* 015CD8 700150D8 314B0080 */  andi  $t3, $t2, 0x80
/* 015CDC 700150DC 1560FFFA */  bnez  $t3, .L700150C8
/* 015CE0 700150E0 00000000 */   nop   
.L700150E4:
/* 015CE4 700150E4 0C00548C */  jal   osEepromRead_sub
/* 015CE8 700150E8 93A4003F */   lbu   $a0, 0x3f($sp)
/* 015CEC 700150EC 3C058006 */  lui   $a1, %hi(__osEepPifRam)
/* 015CF0 700150F0 24A57D30 */  addiu $a1, %lo(__osEepPifRam) # addiu $a1, $a1, 0x7d30
/* 015CF4 700150F4 0C0057B4 */  jal   __osSiRawStartDma
/* 015CF8 700150F8 24040001 */   li    $a0, 1
/* 015CFC 700150FC AFA20034 */  sw    $v0, 0x34($sp)
/* 015D00 70015100 8FA40038 */  lw    $a0, 0x38($sp)
/* 015D04 70015104 00002825 */  move  $a1, $zero
/* 015D08 70015108 0C003774 */  jal   osRecvMesg
/* 015D0C 7001510C 24060001 */   li    $a2, 1
/* 015D10 70015110 AFA00030 */  sw    $zero, 0x30($sp)
.L70015114:
/* 015D14 70015114 8FAD0030 */  lw    $t5, 0x30($sp)
/* 015D18 70015118 8FAF0030 */  lw    $t7, 0x30($sp)
/* 015D1C 7001511C 3C018006 */  lui   $at, %hi(__osEepPifRam)
/* 015D20 70015120 000D7080 */  sll   $t6, $t5, 2
/* 015D24 70015124 002E0821 */  addu  $at, $at, $t6
/* 015D28 70015128 240C00FF */  li    $t4, 255
/* 015D2C 7001512C AC2C7D30 */  sw    $t4, %lo(__osEepPifRam)($at)
/* 015D30 70015130 25F80001 */  addiu $t8, $t7, 1
/* 015D34 70015134 2B010010 */  slti  $at, $t8, 0x10
/* 015D38 70015138 1420FFF6 */  bnez  $at, .L70015114
/* 015D3C 7001513C AFB80030 */   sw    $t8, 0x30($sp)
/* 015D40 70015140 3C018006 */  lui   $at, %hi(__osEepPifRam+0x3C)
/* 015D44 70015144 3C058006 */  lui   $a1, %hi(__osEepPifRam)
/* 015D48 70015148 AC207D6C */  sw    $zero, %lo(__osEepPifRam+0x3C)($at)
/* 015D4C 7001514C 24A57D30 */  addiu $a1, %lo(__osEepPifRam) # addiu $a1, $a1, 0x7d30
/* 015D50 70015150 0C0057B4 */  jal   __osSiRawStartDma
/* 015D54 70015154 00002025 */   move  $a0, $zero
/* 015D58 70015158 24190004 */  li    $t9, 4
/* 015D5C 7001515C 3C018006 */  lui   $at, %hi(__osContLastCmd)
/* 015D60 70015160 AFA20034 */  sw    $v0, 0x34($sp)
/* 015D64 70015164 A0397CE0 */  sb    $t9, %lo(__osContLastCmd)($at)
/* 015D68 70015168 8FA40038 */  lw    $a0, 0x38($sp)
/* 015D6C 7001516C 00002825 */  move  $a1, $zero
/* 015D70 70015170 0C003774 */  jal   osRecvMesg
/* 015D74 70015174 24060001 */   li    $a2, 1
/* 015D78 70015178 AFA00030 */  sw    $zero, 0x30($sp)
.L7001517C:
/* 015D7C 7001517C 8FAA0030 */  lw    $t2, 0x30($sp)
/* 015D80 70015180 8FA8002C */  lw    $t0, 0x2c($sp)
/* 015D84 70015184 254B0001 */  addiu $t3, $t2, 1
/* 015D88 70015188 29610004 */  slti  $at, $t3, 4
/* 015D8C 7001518C 25090001 */  addiu $t1, $t0, 1
/* 015D90 70015190 AFAB0030 */  sw    $t3, 0x30($sp)
/* 015D94 70015194 1420FFF9 */  bnez  $at, .L7001517C
/* 015D98 70015198 AFA9002C */   sw    $t1, 0x2c($sp)
/* 015D9C 7001519C 8FAC002C */  lw    $t4, 0x2c($sp)
/* 015DA0 700151A0 27AD001C */  addiu $t5, $sp, 0x1c
/* 015DA4 700151A4 89810000 */  lwl   $at, ($t4)
/* 015DA8 700151A8 99810003 */  lwr   $at, 3($t4)
/* 015DAC 700151AC ADA10000 */  sw    $at, ($t5)
/* 015DB0 700151B0 898F0004 */  lwl   $t7, 4($t4)
/* 015DB4 700151B4 998F0007 */  lwr   $t7, 7($t4)
/* 015DB8 700151B8 ADAF0004 */  sw    $t7, 4($t5)
/* 015DBC 700151BC 89810008 */  lwl   $at, 8($t4)
/* 015DC0 700151C0 9981000B */  lwr   $at, 0xb($t4)
/* 015DC4 700151C4 ADA10008 */  sw    $at, 8($t5)
/* 015DC8 700151C8 93B8001D */  lbu   $t8, 0x1d($sp)
/* 015DCC 700151CC 331900C0 */  andi  $t9, $t8, 0xc0
/* 015DD0 700151D0 00194103 */  sra   $t0, $t9, 4
/* 015DD4 700151D4 1500000F */  bnez  $t0, .L70015214
/* 015DD8 700151D8 AFA80034 */   sw    $t0, 0x34($sp)
/* 015DDC 700151DC AFA00030 */  sw    $zero, 0x30($sp)
.L700151E0:
/* 015DE0 700151E0 8FA90030 */  lw    $t1, 0x30($sp)
/* 015DE4 700151E4 8FAB0040 */  lw    $t3, 0x40($sp)
/* 015DE8 700151E8 03A95021 */  addu  $t2, $sp, $t1
/* 015DEC 700151EC 914A0020 */  lbu   $t2, 0x20($t2)
/* 015DF0 700151F0 A16A0000 */  sb    $t2, ($t3)
/* 015DF4 700151F4 8FAC0030 */  lw    $t4, 0x30($sp)
/* 015DF8 700151F8 8FAE0040 */  lw    $t6, 0x40($sp)
/* 015DFC 700151FC 258F0001 */  addiu $t7, $t4, 1
/* 015E00 70015200 29E10008 */  slti  $at, $t7, 8
/* 015E04 70015204 25CD0001 */  addiu $t5, $t6, 1
/* 015E08 70015208 AFAF0030 */  sw    $t7, 0x30($sp)
/* 015E0C 7001520C 1420FFF4 */  bnez  $at, .L700151E0
/* 015E10 70015210 AFAD0040 */   sw    $t5, 0x40($sp)
.L70015214:
/* 015E14 70015214 0C0057A9 */  jal   __osSiRelAccess
/* 015E18 70015218 00000000 */   nop   
/* 015E1C 7001521C 8FA20034 */  lw    $v0, 0x34($sp)
.L70015220:
/* 015E20 70015220 8FBF0014 */  lw    $ra, 0x14($sp)
/* 015E24 70015224 27BD0038 */  addiu $sp, $sp, 0x38
/* 015E28 70015228 03E00008 */  jr    $ra
/* 015E2C 7001522C 00000000 */   nop   

glabel osEepromRead_sub
/* 015E30 70015230 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 015E34 70015234 3C0E8006 */  lui   $t6, %hi(__osEepPifRam) 
/* 015E38 70015238 25CE7D30 */  addiu $t6, %lo(__osEepPifRam) # addiu $t6, $t6, 0x7d30
/* 015E3C 7001523C 308400FF */  andi  $a0, $a0, 0xff
/* 015E40 70015240 AFAE0014 */  sw    $t6, 0x14($sp)
/* 015E44 70015244 AFA00004 */  sw    $zero, 4($sp)
.L70015248:
/* 015E48 70015248 8FB80004 */  lw    $t8, 4($sp)
/* 015E4C 7001524C 8FA80004 */  lw    $t0, 4($sp)
/* 015E50 70015250 3C018006 */  lui   $at, %hi(__osEepPifRam)
/* 015E54 70015254 0018C880 */  sll   $t9, $t8, 2
/* 015E58 70015258 00390821 */  addu  $at, $at, $t9
/* 015E5C 7001525C 240F00FF */  li    $t7, 255
/* 015E60 70015260 AC2F7D30 */  sw    $t7, %lo(__osEepPifRam)($at)
/* 015E64 70015264 25090001 */  addiu $t1, $t0, 1
/* 015E68 70015268 29210010 */  slti  $at, $t1, 0x10
/* 015E6C 7001526C 1420FFF6 */  bnez  $at, .L70015248
/* 015E70 70015270 AFA90004 */   sw    $t1, 4($sp)
/* 015E74 70015274 240A0001 */  li    $t2, 1
/* 015E78 70015278 3C018006 */  lui   $at, %hi(__osEepPifRam+0x3C)
/* 015E7C 7001527C 240B0002 */  li    $t3, 2
/* 015E80 70015280 240C0008 */  li    $t4, 8
/* 015E84 70015284 240D0004 */  li    $t5, 4
/* 015E88 70015288 AC2A7D6C */  sw    $t2, %lo(__osEepPifRam+0x3C)($at)
/* 015E8C 7001528C A3AB0008 */  sb    $t3, 8($sp)
/* 015E90 70015290 A3AC0009 */  sb    $t4, 9($sp)
/* 015E94 70015294 A3AD000A */  sb    $t5, 0xa($sp)
/* 015E98 70015298 A3A4000B */  sb    $a0, 0xb($sp)
/* 015E9C 7001529C AFA00004 */  sw    $zero, 4($sp)
.L700152A0:
/* 015EA0 700152A0 8FAE0004 */  lw    $t6, 4($sp)
/* 015EA4 700152A4 03AEC021 */  addu  $t8, $sp, $t6
/* 015EA8 700152A8 A300000C */  sb    $zero, 0xc($t8)
/* 015EAC 700152AC 8FAF0004 */  lw    $t7, 4($sp)
/* 015EB0 700152B0 25F90001 */  addiu $t9, $t7, 1
/* 015EB4 700152B4 2B210008 */  slti  $at, $t9, 8
/* 015EB8 700152B8 1420FFF9 */  bnez  $at, .L700152A0
/* 015EBC 700152BC AFB90004 */   sw    $t9, 4($sp)
/* 015EC0 700152C0 AFA00004 */  sw    $zero, 4($sp)
.L700152C4:
/* 015EC4 700152C4 8FA80014 */  lw    $t0, 0x14($sp)
/* 015EC8 700152C8 A1000000 */  sb    $zero, ($t0)
/* 015ECC 700152CC 8FAB0004 */  lw    $t3, 4($sp)
/* 015ED0 700152D0 8FA90014 */  lw    $t1, 0x14($sp)
/* 015ED4 700152D4 256C0001 */  addiu $t4, $t3, 1
/* 015ED8 700152D8 29810004 */  slti  $at, $t4, 4
/* 015EDC 700152DC 252A0001 */  addiu $t2, $t1, 1
/* 015EE0 700152E0 AFAC0004 */  sw    $t4, 4($sp)
/* 015EE4 700152E4 1420FFF7 */  bnez  $at, .L700152C4
/* 015EE8 700152E8 AFAA0014 */   sw    $t2, 0x14($sp)
/* 015EEC 700152EC 27AE0008 */  addiu $t6, $sp, 8
/* 015EF0 700152F0 8DC10000 */  lw    $at, ($t6)
/* 015EF4 700152F4 8FAD0014 */  lw    $t5, 0x14($sp)
/* 015EF8 700152F8 240900FE */  li    $t1, 254
/* 015EFC 700152FC A9A10000 */  swl   $at, ($t5)
/* 015F00 70015300 B9A10003 */  swr   $at, 3($t5)
/* 015F04 70015304 8DCF0004 */  lw    $t7, 4($t6)
/* 015F08 70015308 A9AF0004 */  swl   $t7, 4($t5)
/* 015F0C 7001530C B9AF0007 */  swr   $t7, 7($t5)
/* 015F10 70015310 8DC10008 */  lw    $at, 8($t6)
/* 015F14 70015314 A9A10008 */  swl   $at, 8($t5)
/* 015F18 70015318 B9A1000B */  swr   $at, 0xb($t5)
/* 015F1C 7001531C 8FB90014 */  lw    $t9, 0x14($sp)
/* 015F20 70015320 2728000C */  addiu $t0, $t9, 0xc
/* 015F24 70015324 AFA80014 */  sw    $t0, 0x14($sp)
/* 015F28 70015328 A1090000 */  sb    $t1, ($t0)
/* 015F2C 7001532C 03E00008 */  jr    $ra
/* 015F30 70015330 27BD0018 */   addiu $sp, $sp, 0x18

/* 015F34 70015334 00000000 */  nop   
/* 015F38 70015338 00000000 */  nop   
/* 015F3C 7001533C 00000000 */  nop   

.section .bss
glabel __osEepPifRam
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
