# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alCopy
/* 01E290 7001D690 00801025 */  move  $v0, $a0
/* 01E294 7001D694 00A01825 */  move  $v1, $a1
/* 01E298 7001D698 18C00018 */  blez  $a2, .L7001D6FC
/* 01E29C 7001D69C 00003825 */   move  $a3, $zero
/* 01E2A0 7001D6A0 30C50003 */  andi  $a1, $a2, 3
/* 01E2A4 7001D6A4 10A00009 */  beqz  $a1, .L7001D6CC
/* 01E2A8 7001D6A8 00A02025 */   move  $a0, $a1
.L7001D6AC:
/* 01E2AC 7001D6AC 904E0000 */  lbu   $t6, ($v0)
/* 01E2B0 7001D6B0 24E70001 */  addiu $a3, $a3, 1
/* 01E2B4 7001D6B4 24630001 */  addiu $v1, $v1, 1
/* 01E2B8 7001D6B8 24420001 */  addiu $v0, $v0, 1
/* 01E2BC 7001D6BC 1487FFFB */  bne   $a0, $a3, .L7001D6AC
/* 01E2C0 7001D6C0 A06EFFFF */   sb    $t6, -1($v1)
/* 01E2C4 7001D6C4 10E6000D */  beq   $a3, $a2, .L7001D6FC
/* 01E2C8 7001D6C8 00000000 */   nop   
.L7001D6CC:
/* 01E2CC 7001D6CC 904F0000 */  lbu   $t7, ($v0)
/* 01E2D0 7001D6D0 24E70004 */  addiu $a3, $a3, 4
/* 01E2D4 7001D6D4 24630004 */  addiu $v1, $v1, 4
/* 01E2D8 7001D6D8 A06FFFFC */  sb    $t7, -4($v1)
/* 01E2DC 7001D6DC 90580001 */  lbu   $t8, 1($v0)
/* 01E2E0 7001D6E0 24420004 */  addiu $v0, $v0, 4
/* 01E2E4 7001D6E4 A078FFFD */  sb    $t8, -3($v1)
/* 01E2E8 7001D6E8 9059FFFE */  lbu   $t9, -2($v0)
/* 01E2EC 7001D6EC A079FFFE */  sb    $t9, -2($v1)
/* 01E2F0 7001D6F0 9048FFFF */  lbu   $t0, -1($v0)
/* 01E2F4 7001D6F4 14E6FFF5 */  bne   $a3, $a2, .L7001D6CC
/* 01E2F8 7001D6F8 A068FFFF */   sb    $t0, -1($v1)
.L7001D6FC:
/* 01E2FC 7001D6FC 03E00008 */  jr    $ra
/* 01E300 7001D700 00000000 */   nop   
