# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel coss
/* 017830 70016C30 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 017834 70016C34 AFA40018 */  sw    $a0, 0x18($sp)
/* 017838 70016C38 00802825 */  move  $a1, $a0
/* 01783C 70016C3C 24A44000 */  addiu $a0, $a1, 0x4000
/* 017840 70016C40 AFBF0014 */  sw    $ra, 0x14($sp)
/* 017844 70016C44 308EFFFF */  andi  $t6, $a0, 0xffff
/* 017848 70016C48 0C005B18 */  jal   sins
/* 01784C 70016C4C 01C02025 */   move  $a0, $t6
/* 017850 70016C50 8FBF0014 */  lw    $ra, 0x14($sp)
/* 017854 70016C54 27BD0018 */  addiu $sp, $sp, 0x18
/* 017858 70016C58 03E00008 */  jr    $ra
/* 01785C 70016C5C 00000000 */   nop   
