# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osDevMgrMain
/* 01F210 7001E610 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 01F214 7001E614 AFA40040 */  sw    $a0, 0x40($sp)
/* 01F218 7001E618 8FAE0040 */  lw    $t6, 0x40($sp)
/* 01F21C 7001E61C AFBF001C */  sw    $ra, 0x1c($sp)
/* 01F220 7001E620 AFA00028 */  sw    $zero, 0x28($sp)
/* 01F224 7001E624 AFA0003C */  sw    $zero, 0x3c($sp)
/* 01F228 7001E628 AFA00030 */  sw    $zero, 0x30($sp)
/* 01F22C 7001E62C AFAE002C */  sw    $t6, 0x2c($sp)
.L7001E630:
/* 01F230 7001E630 8FAF002C */  lw    $t7, 0x2c($sp)
/* 01F234 7001E634 27A5003C */  addiu $a1, $sp, 0x3c
/* 01F238 7001E638 24060001 */  li    $a2, 1
/* 01F23C 7001E63C 0C003774 */  jal   osRecvMesg
/* 01F240 7001E640 8DE40008 */   lw    $a0, 8($t7)
/* 01F244 7001E644 8FB8003C */  lw    $t8, 0x3c($sp)
/* 01F248 7001E648 8F190014 */  lw    $t9, 0x14($t8)
/* 01F24C 7001E64C 13200065 */  beqz  $t9, .L7001E7E4
/* 01F250 7001E650 00000000 */   nop   
/* 01F254 7001E654 93280004 */  lbu   $t0, 4($t9)
/* 01F258 7001E658 24010002 */  li    $at, 2
/* 01F25C 7001E65C 15010061 */  bne   $t0, $at, .L7001E7E4
/* 01F260 7001E660 00000000 */   nop   
/* 01F264 7001E664 8F290014 */  lw    $t1, 0x14($t9)
/* 01F268 7001E668 11200003 */  beqz  $t1, .L7001E678
/* 01F26C 7001E66C 24010001 */   li    $at, 1
/* 01F270 7001E670 1521005C */  bne   $t1, $at, .L7001E7E4
/* 01F274 7001E674 00000000 */   nop   
.L7001E678:
/* 01F278 7001E678 8FAA003C */  lw    $t2, 0x3c($sp)
/* 01F27C 7001E67C 2408FFFF */  li    $t0, -1
/* 01F280 7001E680 24010003 */  li    $at, 3
/* 01F284 7001E684 8D4B0014 */  lw    $t3, 0x14($t2)
/* 01F288 7001E688 256C0014 */  addiu $t4, $t3, 0x14
/* 01F28C 7001E68C AFAC0020 */  sw    $t4, 0x20($sp)
/* 01F290 7001E690 958D0006 */  lhu   $t5, 6($t4)
/* 01F294 7001E694 000D70C0 */  sll   $t6, $t5, 3
/* 01F298 7001E698 01CD7021 */  addu  $t6, $t6, $t5
/* 01F29C 7001E69C 000E7080 */  sll   $t6, $t6, 2
/* 01F2A0 7001E6A0 018E7821 */  addu  $t7, $t4, $t6
/* 01F2A4 7001E6A4 25F80018 */  addiu $t8, $t7, 0x18
/* 01F2A8 7001E6A8 AFB80024 */  sw    $t8, 0x24($sp)
/* 01F2AC 7001E6AC AD880008 */  sw    $t0, 8($t4)
/* 01F2B0 7001E6B0 8FB90020 */  lw    $t9, 0x20($sp)
/* 01F2B4 7001E6B4 97290004 */  lhu   $t1, 4($t9)
/* 01F2B8 7001E6B8 11210006 */  beq   $t1, $at, .L7001E6D4
/* 01F2BC 7001E6BC 00000000 */   nop   
/* 01F2C0 7001E6C0 8FAA0024 */  lw    $t2, 0x24($sp)
/* 01F2C4 7001E6C4 8D4B0004 */  lw    $t3, 4($t2)
/* 01F2C8 7001E6C8 8D4D000C */  lw    $t5, 0xc($t2)
/* 01F2CC 7001E6CC 016D7023 */  subu  $t6, $t3, $t5
/* 01F2D0 7001E6D0 AD4E0004 */  sw    $t6, 4($t2)
.L7001E6D4:
/* 01F2D4 7001E6D4 8FAF0020 */  lw    $t7, 0x20($sp)
/* 01F2D8 7001E6D8 24010002 */  li    $at, 2
/* 01F2DC 7001E6DC 95F80004 */  lhu   $t8, 4($t7)
/* 01F2E0 7001E6E0 17010009 */  bne   $t8, $at, .L7001E708
/* 01F2E4 7001E6E4 00000000 */   nop   
/* 01F2E8 7001E6E8 8FA8003C */  lw    $t0, 0x3c($sp)
/* 01F2EC 7001E6EC 8D0C0014 */  lw    $t4, 0x14($t0)
/* 01F2F0 7001E6F0 8D990014 */  lw    $t9, 0x14($t4)
/* 01F2F4 7001E6F4 17200004 */  bnez  $t9, .L7001E708
/* 01F2F8 7001E6F8 00000000 */   nop   
/* 01F2FC 7001E6FC 24090001 */  li    $t1, 1
/* 01F300 7001E700 10000002 */  b     .L7001E70C
/* 01F304 7001E704 AFA90028 */   sw    $t1, 0x28($sp)
.L7001E708:
/* 01F308 7001E708 AFA00028 */  sw    $zero, 0x28($sp)
.L7001E70C:
/* 01F30C 7001E70C 8FAB002C */  lw    $t3, 0x2c($sp)
/* 01F310 7001E710 27A50034 */  addiu $a1, $sp, 0x34
/* 01F314 7001E714 24060001 */  li    $a2, 1
/* 01F318 7001E718 0C003774 */  jal   osRecvMesg
/* 01F31C 7001E71C 8D640010 */   lw    $a0, 0x10($t3)
/* 01F320 7001E720 3C040010 */  lui   $a0, (0x00100401 >> 16) # lui $a0, 0x10
/* 01F324 7001E724 0C008338 */  jal   __osResetGlobalIntMask
/* 01F328 7001E728 34840401 */   ori   $a0, (0x00100401 & 0xFFFF) # ori $a0, $a0, 0x401
/* 01F32C 7001E72C 8FAE0020 */  lw    $t6, 0x20($sp)
/* 01F330 7001E730 8FAD003C */  lw    $t5, 0x3c($sp)
/* 01F334 7001E734 3C018000 */  lui   $at, 0x8000
/* 01F338 7001E738 8DC60010 */  lw    $a2, 0x10($t6)
/* 01F33C 7001E73C 3C050500 */  lui   $a1, (0x05000510 >> 16) # lui $a1, 0x500
/* 01F340 7001E740 34A50510 */  ori   $a1, (0x05000510 & 0xFFFF) # ori $a1, $a1, 0x510
/* 01F344 7001E744 00C15025 */  or    $t2, $a2, $at
/* 01F348 7001E748 01403025 */  move  $a2, $t2
/* 01F34C 7001E74C 0C008350 */  jal   osEPiRawWriteIo
/* 01F350 7001E750 8DA40014 */   lw    $a0, 0x14($t5)
.L7001E754:
/* 01F354 7001E754 8FAF002C */  lw    $t7, 0x2c($sp)
/* 01F358 7001E758 27A50038 */  addiu $a1, $sp, 0x38
/* 01F35C 7001E75C 24060001 */  li    $a2, 1
/* 01F360 7001E760 0C003774 */  jal   osRecvMesg
/* 01F364 7001E764 8DE4000C */   lw    $a0, 0xc($t7)
/* 01F368 7001E768 8FB8003C */  lw    $t8, 0x3c($sp)
/* 01F36C 7001E76C 00003025 */  move  $a2, $zero
/* 01F370 7001E770 8F040004 */  lw    $a0, 4($t8)
/* 01F374 7001E774 0C0037C4 */  jal   osSendMesg
/* 01F378 7001E778 03002825 */   move  $a1, $t8
/* 01F37C 7001E77C 8FA80028 */  lw    $t0, 0x28($sp)
/* 01F380 7001E780 24010001 */  li    $at, 1
/* 01F384 7001E784 15010008 */  bne   $t0, $at, .L7001E7A8
/* 01F388 7001E788 00000000 */   nop   
/* 01F38C 7001E78C 8FAC003C */  lw    $t4, 0x3c($sp)
/* 01F390 7001E790 8D990014 */  lw    $t9, 0x14($t4)
/* 01F394 7001E794 8F29002C */  lw    $t1, 0x2c($t9)
/* 01F398 7001E798 15200003 */  bnez  $t1, .L7001E7A8
/* 01F39C 7001E79C 00000000 */   nop   
/* 01F3A0 7001E7A0 1000FFEC */  b     .L7001E754
/* 01F3A4 7001E7A4 AFA00028 */   sw    $zero, 0x28($sp)
.L7001E7A8:
/* 01F3A8 7001E7A8 8FAB002C */  lw    $t3, 0x2c($sp)
/* 01F3AC 7001E7AC 00002825 */  move  $a1, $zero
/* 01F3B0 7001E7B0 00003025 */  move  $a2, $zero
/* 01F3B4 7001E7B4 0C0037C4 */  jal   osSendMesg
/* 01F3B8 7001E7B8 8D640010 */   lw    $a0, 0x10($t3)
/* 01F3BC 7001E7BC 8FAD003C */  lw    $t5, 0x3c($sp)
/* 01F3C0 7001E7C0 24010001 */  li    $at, 1
/* 01F3C4 7001E7C4 8DAE0014 */  lw    $t6, 0x14($t5)
/* 01F3C8 7001E7C8 95CA001A */  lhu   $t2, 0x1a($t6)
/* 01F3CC 7001E7CC 1541FF98 */  bne   $t2, $at, .L7001E630
/* 01F3D0 7001E7D0 00000000 */   nop   
/* 01F3D4 7001E7D4 0C0042B4 */  jal   osYieldThread
/* 01F3D8 7001E7D8 00000000 */   nop   
/* 01F3DC 7001E7DC 1000FF94 */  b     .L7001E630
/* 01F3E0 7001E7E0 00000000 */   nop   
.L7001E7E4:
/* 01F3E4 7001E7E4 8FAF003C */  lw    $t7, 0x3c($sp)
/* 01F3E8 7001E7E8 95F80000 */  lhu   $t8, ($t7)
/* 01F3EC 7001E7EC 2708FFF6 */  addiu $t0, $t8, -0xa
/* 01F3F0 7001E7F0 2D010007 */  sltiu $at, $t0, 7
/* 01F3F4 7001E7F4 10200052 */  beqz  $at, .L7001E940
/* 01F3F8 7001E7F8 00000000 */   nop   
/* 01F3FC 7001E7FC 00084080 */  sll   $t0, $t0, 2
/* 01F400 7001E800 3C018003 */  lui   $at, %hi(jpt_80029CF0)
/* 01F404 7001E804 00280821 */  addu  $at, $at, $t0
/* 01F408 7001E808 8C289CF0 */  lw    $t0, %lo(jpt_80029CF0)($at)
/* 01F40C 7001E80C 01000008 */  jr    $t0
/* 01F410 7001E810 00000000 */   nop   
.L7001E814:
/* 01F414 7001E814 8FAC002C */  lw    $t4, 0x2c($sp)
/* 01F418 7001E818 27A50034 */  addiu $a1, $sp, 0x34
/* 01F41C 7001E81C 24060001 */  li    $a2, 1
/* 01F420 7001E820 0C003774 */  jal   osRecvMesg
/* 01F424 7001E824 8D840010 */   lw    $a0, 0x10($t4)
/* 01F428 7001E828 8FB9003C */  lw    $t9, 0x3c($sp)
/* 01F42C 7001E82C 8FA9002C */  lw    $t1, 0x2c($sp)
/* 01F430 7001E830 00002025 */  move  $a0, $zero
/* 01F434 7001E834 8F25000C */  lw    $a1, 0xc($t9)
/* 01F438 7001E838 8F260008 */  lw    $a2, 8($t9)
/* 01F43C 7001E83C 8F270010 */  lw    $a3, 0x10($t9)
/* 01F440 7001E840 8D390014 */  lw    $t9, 0x14($t1)
/* 01F444 7001E844 0320F809 */  jalr  $t9
/* 01F448 7001E848 00000000 */  nop   
/* 01F44C 7001E84C 1000003E */  b     .L7001E948
/* 01F450 7001E850 AFA20030 */   sw    $v0, 0x30($sp)
.L7001E854:
/* 01F454 7001E854 8FAB002C */  lw    $t3, 0x2c($sp)
/* 01F458 7001E858 27A50034 */  addiu $a1, $sp, 0x34
/* 01F45C 7001E85C 24060001 */  li    $a2, 1
/* 01F460 7001E860 0C003774 */  jal   osRecvMesg
/* 01F464 7001E864 8D640010 */   lw    $a0, 0x10($t3)
/* 01F468 7001E868 8FAE002C */  lw    $t6, 0x2c($sp)
/* 01F46C 7001E86C 8FAD003C */  lw    $t5, 0x3c($sp)
/* 01F470 7001E870 24040001 */  li    $a0, 1
/* 01F474 7001E874 8DD90014 */  lw    $t9, 0x14($t6)
/* 01F478 7001E878 8DA5000C */  lw    $a1, 0xc($t5)
/* 01F47C 7001E87C 8DA60008 */  lw    $a2, 8($t5)
/* 01F480 7001E880 0320F809 */  jalr  $t9
/* 01F484 7001E884 8DA70010 */  lw    $a3, 0x10($t5)
/* 01F488 7001E888 1000002F */  b     .L7001E948
/* 01F48C 7001E88C AFA20030 */   sw    $v0, 0x30($sp)
.L7001E890:
/* 01F490 7001E890 8FAA002C */  lw    $t2, 0x2c($sp)
/* 01F494 7001E894 27A50034 */  addiu $a1, $sp, 0x34
/* 01F498 7001E898 24060001 */  li    $a2, 1
/* 01F49C 7001E89C 0C003774 */  jal   osRecvMesg
/* 01F4A0 7001E8A0 8D440010 */   lw    $a0, 0x10($t2)
/* 01F4A4 7001E8A4 8FAF003C */  lw    $t7, 0x3c($sp)
/* 01F4A8 7001E8A8 8FA8002C */  lw    $t0, 0x2c($sp)
/* 01F4AC 7001E8AC 00002825 */  move  $a1, $zero
/* 01F4B0 7001E8B0 8DF80010 */  lw    $t8, 0x10($t7)
/* 01F4B4 7001E8B4 8DE40014 */  lw    $a0, 0x14($t7)
/* 01F4B8 7001E8B8 8DE6000C */  lw    $a2, 0xc($t7)
/* 01F4BC 7001E8BC 8DE70008 */  lw    $a3, 8($t7)
/* 01F4C0 7001E8C0 AFB80010 */  sw    $t8, 0x10($sp)
/* 01F4C4 7001E8C4 8D190018 */  lw    $t9, 0x18($t0)
/* 01F4C8 7001E8C8 0320F809 */  jalr  $t9
/* 01F4CC 7001E8CC 00000000 */  nop   
/* 01F4D0 7001E8D0 1000001D */  b     .L7001E948
/* 01F4D4 7001E8D4 AFA20030 */   sw    $v0, 0x30($sp)
.L7001E8D8:
/* 01F4D8 7001E8D8 8FAC002C */  lw    $t4, 0x2c($sp)
/* 01F4DC 7001E8DC 27A50034 */  addiu $a1, $sp, 0x34
/* 01F4E0 7001E8E0 24060001 */  li    $a2, 1
/* 01F4E4 7001E8E4 0C003774 */  jal   osRecvMesg
/* 01F4E8 7001E8E8 8D840010 */   lw    $a0, 0x10($t4)
/* 01F4EC 7001E8EC 8FA9003C */  lw    $t1, 0x3c($sp)
/* 01F4F0 7001E8F0 8FAD002C */  lw    $t5, 0x2c($sp)
/* 01F4F4 7001E8F4 24050001 */  li    $a1, 1
/* 01F4F8 7001E8F8 8D2B0010 */  lw    $t3, 0x10($t1)
/* 01F4FC 7001E8FC 8D240014 */  lw    $a0, 0x14($t1)
/* 01F500 7001E900 8D26000C */  lw    $a2, 0xc($t1)
/* 01F504 7001E904 8D270008 */  lw    $a3, 8($t1)
/* 01F508 7001E908 AFAB0010 */  sw    $t3, 0x10($sp)
/* 01F50C 7001E90C 8DB90018 */  lw    $t9, 0x18($t5)
/* 01F510 7001E910 0320F809 */  jalr  $t9
/* 01F514 7001E914 00000000 */  nop   
/* 01F518 7001E918 1000000B */  b     .L7001E948
/* 01F51C 7001E91C AFA20030 */   sw    $v0, 0x30($sp)
.L7001E920:
/* 01F520 7001E920 8FAE003C */  lw    $t6, 0x3c($sp)
/* 01F524 7001E924 00003025 */  move  $a2, $zero
/* 01F528 7001E928 8DC40004 */  lw    $a0, 4($t6)
/* 01F52C 7001E92C 0C0037C4 */  jal   osSendMesg
/* 01F530 7001E930 01C02825 */   move  $a1, $t6
/* 01F534 7001E934 240AFFFF */  li    $t2, -1
/* 01F538 7001E938 10000003 */  b     .L7001E948
/* 01F53C 7001E93C AFAA0030 */   sw    $t2, 0x30($sp)
.L7001E940:
/* 01F540 7001E940 240FFFFF */  li    $t7, -1
/* 01F544 7001E944 AFAF0030 */  sw    $t7, 0x30($sp)
.L7001E948:
/* 01F548 7001E948 8FB80030 */  lw    $t8, 0x30($sp)
/* 01F54C 7001E94C 1700FF38 */  bnez  $t8, .L7001E630
/* 01F550 7001E950 00000000 */   nop   
/* 01F554 7001E954 8FA8002C */  lw    $t0, 0x2c($sp)
/* 01F558 7001E958 27A50038 */  addiu $a1, $sp, 0x38
/* 01F55C 7001E95C 24060001 */  li    $a2, 1
/* 01F560 7001E960 0C003774 */  jal   osRecvMesg
/* 01F564 7001E964 8D04000C */   lw    $a0, 0xc($t0)
/* 01F568 7001E968 8FAC003C */  lw    $t4, 0x3c($sp)
/* 01F56C 7001E96C 00003025 */  move  $a2, $zero
/* 01F570 7001E970 8D840004 */  lw    $a0, 4($t4)
/* 01F574 7001E974 0C0037C4 */  jal   osSendMesg
/* 01F578 7001E978 01802825 */   move  $a1, $t4
/* 01F57C 7001E97C 8FA9002C */  lw    $t1, 0x2c($sp)
/* 01F580 7001E980 00002825 */  move  $a1, $zero
/* 01F584 7001E984 00003025 */  move  $a2, $zero
/* 01F588 7001E988 0C0037C4 */  jal   osSendMesg
/* 01F58C 7001E98C 8D240010 */   lw    $a0, 0x10($t1)
/* 01F590 7001E990 1000FF27 */  b     .L7001E630
/* 01F594 7001E994 00000000 */   nop   
/* 01F598 7001E998 00000000 */  nop   
/* 01F59C 7001E99C 00000000 */  nop   
/* 01F5A0 7001E9A0 00000000 */  nop   
/* 01F5A4 7001E9A4 00000000 */  nop   
/* 01F5A8 7001E9A8 00000000 */  nop   
/* 01F5AC 7001E9AC 00000000 */  nop   
/* 01F5B0 7001E9B0 8FBF001C */  lw    $ra, 0x1c($sp)
/* 01F5B4 7001E9B4 27BD0040 */  addiu $sp, $sp, 0x40
/* 01F5B8 7001E9B8 03E00008 */  jr    $ra
/* 01F5BC 7001E9BC 00000000 */   nop   
.section .rodata
glabel jpt_80029CF0
 .word .L7001E920
 .word .L7001E814
 .word .L7001E854
 .word .L7001E940
 .word .L7001E940
 .word .L7001E890
 .word .L7001E8D8
.align 4
