# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osEPiRawWriteIo
/* 021940 70020D40 3C0EA460 */  lui   $t6, %hi(PI_STATUS_REG) # $t6, 0xa460
/* 021944 70020D44 8DC70010 */  lw    $a3, %lo(PI_STATUS_REG)($t6)
/* 021948 70020D48 27BDFFF8 */  addiu $sp, $sp, -8
/* 02194C 70020D4C 30EF0003 */  andi  $t7, $a3, 3
/* 021950 70020D50 11E00006 */  beqz  $t7, .L70020D6C
/* 021954 70020D54 00000000 */   nop   
.L70020D58:
/* 021958 70020D58 3C18A460 */  lui   $t8, %hi(PI_STATUS_REG) # $t8, 0xa460
/* 02195C 70020D5C 8F070010 */  lw    $a3, %lo(PI_STATUS_REG)($t8)
/* 021960 70020D60 30F90003 */  andi  $t9, $a3, 3
/* 021964 70020D64 1720FFFC */  bnez  $t9, .L70020D58
/* 021968 70020D68 00000000 */   nop   
.L70020D6C:
/* 02196C 70020D6C 8C88000C */  lw    $t0, 0xc($a0)
/* 021970 70020D70 3C01A000 */  lui   $at, 0xa000
/* 021974 70020D74 27BD0008 */  addiu $sp, $sp, 8
/* 021978 70020D78 01054825 */  or    $t1, $t0, $a1
/* 02197C 70020D7C 01215025 */  or    $t2, $t1, $at
/* 021980 70020D80 AD460000 */  sw    $a2, ($t2)
/* 021984 70020D84 03E00008 */  jr    $ra
/* 021988 70020D88 00001025 */   move  $v0, $zero

