# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alFilterNew
/* 0204F0 7001F8F0 AC800000 */  sw    $zero, ($a0)
/* 0204F4 7001F8F4 AC850004 */  sw    $a1, 4($a0)
/* 0204F8 7001F8F8 AC860008 */  sw    $a2, 8($a0)
/* 0204FC 7001F8FC A480000C */  sh    $zero, 0xc($a0)
/* 020500 7001F900 A480000E */  sh    $zero, 0xe($a0)
/* 020504 7001F904 03E00008 */  jr    $ra
/* 020508 7001F908 AC870010 */   sw    $a3, 0x10($a0)


