# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osGetThreadPri
/* 019630 70018A30 14800003 */  bnez  $a0, .L70018A40
/* 019634 70018A34 00000000 */   nop   
/* 019638 70018A38 3C048002 */  lui   $a0, %hi(__osRunningThread)
/* 01963C 70018A3C 8C847730 */  lw    $a0, %lo(__osRunningThread)($a0)
.L70018A40:
/* 019640 70018A40 03E00008 */  jr    $ra
/* 019644 70018A44 8C820004 */   lw    $v0, 4($a0)

/* 019648 70018A48 00000000 */  nop   
/* 01964C 70018A4C 00000000 */  nop  
