# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osDisableInt
/* 0191F0 700185F0 40086000 */  mfc0  $t0, $12
/* 0191F4 700185F4 2401FFFE */  li    $at, -2
/* 0191F8 700185F8 01014824 */  and   $t1, $t0, $at
/* 0191FC 700185FC 40896000 */  mtc0  $t1, $12
/* 019200 70018600 31020001 */  andi  $v0, $t0, 1
/* 019204 70018604 00000000 */  nop   
/* 019208 70018608 03E00008 */  jr    $ra
/* 01920C 7001860C 00000000 */   nop   

glabel __osRestoreInt
/* 019210 70018610 40086000 */  mfc0  $t0, $12
/* 019214 70018614 01044025 */  or    $t0, $t0, $a0
/* 019218 70018618 40886000 */  mtc0  $t0, $12
/* 01921C 7001861C 00000000 */  nop   
/* 019220 70018620 00000000 */  nop   
/* 019224 70018624 03E00008 */  jr    $ra
/* 019228 70018628 00000000 */   nop   

