# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osJamMesg
/* 01C2B0 7001B6B0 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 01C2B4 7001B6B4 AFBF001C */  sw    $ra, 0x1c($sp)
/* 01C2B8 7001B6B8 AFA40028 */  sw    $a0, 0x28($sp)
/* 01C2BC 7001B6BC AFA5002C */  sw    $a1, 0x2c($sp)
/* 01C2C0 7001B6C0 AFA60030 */  sw    $a2, 0x30($sp)
/* 01C2C4 7001B6C4 AFB10018 */  sw    $s1, 0x18($sp)
/* 01C2C8 7001B6C8 0C00617C */  jal   __osDisableInt
/* 01C2CC 7001B6CC AFB00014 */   sw    $s0, 0x14($sp)
/* 01C2D0 7001B6D0 8FAE0028 */  lw    $t6, 0x28($sp)
/* 01C2D4 7001B6D4 00408025 */  move  $s0, $v0
/* 01C2D8 7001B6D8 8DCF0008 */  lw    $t7, 8($t6)
/* 01C2DC 7001B6DC 8DD80010 */  lw    $t8, 0x10($t6)
/* 01C2E0 7001B6E0 01F8082A */  slt   $at, $t7, $t8
/* 01C2E4 7001B6E4 14200018 */  bnez  $at, .L7001B748
/* 01C2E8 7001B6E8 00000000 */   nop   
.L7001B6EC:
/* 01C2EC 7001B6EC 8FB90030 */  lw    $t9, 0x30($sp)
/* 01C2F0 7001B6F0 24010001 */  li    $at, 1
/* 01C2F4 7001B6F4 1721000A */  bne   $t9, $at, .L7001B720
/* 01C2F8 7001B6F8 00000000 */   nop   
/* 01C2FC 7001B6FC 3C098002 */  lui   $t1, %hi(__osRunningThread) 
/* 01C300 7001B700 8D297730 */  lw    $t1, %lo(__osRunningThread)($t1)
/* 01C304 7001B704 24080008 */  li    $t0, 8
/* 01C308 7001B708 A5280010 */  sh    $t0, 0x10($t1)
/* 01C30C 7001B70C 8FA40028 */  lw    $a0, 0x28($sp)
/* 01C310 7001B710 0C0041EB */  jal   __osEnqueueAndYield
/* 01C314 7001B714 24840004 */   addiu $a0, $a0, 4
/* 01C318 7001B718 10000005 */  b     .L7001B730
/* 01C31C 7001B71C 00000000 */   nop   
.L7001B720:
/* 01C320 7001B720 0C006184 */  jal   __osRestoreInt
/* 01C324 7001B724 02002025 */   move  $a0, $s0
/* 01C328 7001B728 10000030 */  b     .L7001B7EC
/* 01C32C 7001B72C 2402FFFF */   li    $v0, -1
.L7001B730:
/* 01C330 7001B730 8FAA0028 */  lw    $t2, 0x28($sp)
/* 01C334 7001B734 8D4B0008 */  lw    $t3, 8($t2)
/* 01C338 7001B738 8D4C0010 */  lw    $t4, 0x10($t2)
/* 01C33C 7001B73C 016C082A */  slt   $at, $t3, $t4
/* 01C340 7001B740 1020FFEA */  beqz  $at, .L7001B6EC
/* 01C344 7001B744 00000000 */   nop   
.L7001B748:
/* 01C348 7001B748 8FAD0028 */  lw    $t5, 0x28($sp)
/* 01C34C 7001B74C 8DAE000C */  lw    $t6, 0xc($t5)
/* 01C350 7001B750 8DAF0010 */  lw    $t7, 0x10($t5)
/* 01C354 7001B754 01CFC021 */  addu  $t8, $t6, $t7
/* 01C358 7001B758 2719FFFF */  addiu $t9, $t8, -1
/* 01C35C 7001B75C 032F001A */  div   $zero, $t9, $t7
/* 01C360 7001B760 00004010 */  mfhi  $t0
/* 01C364 7001B764 ADA8000C */  sw    $t0, 0xc($t5)
/* 01C368 7001B768 8FAA0028 */  lw    $t2, 0x28($sp)
/* 01C36C 7001B76C 8FA9002C */  lw    $t1, 0x2c($sp)
/* 01C370 7001B770 15E00002 */  bnez  $t7, .L7001B77C
/* 01C374 7001B774 00000000 */   nop   
/* 01C378 7001B778 0007000D */  break 7
.L7001B77C:
/* 01C37C 7001B77C 2401FFFF */  li    $at, -1
/* 01C380 7001B780 15E10004 */  bne   $t7, $at, .L7001B794
/* 01C384 7001B784 3C018000 */   lui   $at, 0x8000
/* 01C388 7001B788 17210002 */  bne   $t9, $at, .L7001B794
/* 01C38C 7001B78C 00000000 */   nop   
/* 01C390 7001B790 0006000D */  break 6
.L7001B794:
/* 01C394 7001B794 8D4C000C */  lw    $t4, 0xc($t2)
/* 01C398 7001B798 8D4B0014 */  lw    $t3, 0x14($t2)
/* 01C39C 7001B79C 000C7080 */  sll   $t6, $t4, 2
/* 01C3A0 7001B7A0 016EC021 */  addu  $t8, $t3, $t6
/* 01C3A4 7001B7A4 AF090000 */  sw    $t1, ($t8)
/* 01C3A8 7001B7A8 8FB90028 */  lw    $t9, 0x28($sp)
/* 01C3AC 7001B7AC 8F2F0008 */  lw    $t7, 8($t9)
/* 01C3B0 7001B7B0 25E80001 */  addiu $t0, $t7, 1
/* 01C3B4 7001B7B4 AF280008 */  sw    $t0, 8($t9)
/* 01C3B8 7001B7B8 8FAD0028 */  lw    $t5, 0x28($sp)
/* 01C3BC 7001B7BC 8DAA0000 */  lw    $t2, ($t5)
/* 01C3C0 7001B7C0 8D4C0000 */  lw    $t4, ($t2)
/* 01C3C4 7001B7C4 11800006 */  beqz  $t4, .L7001B7E0
/* 01C3C8 7001B7C8 00000000 */   nop   
/* 01C3CC 7001B7CC 0C00423D */  jal   __osPopThread
/* 01C3D0 7001B7D0 01A02025 */   move  $a0, $t5
/* 01C3D4 7001B7D4 00408825 */  move  $s1, $v0
/* 01C3D8 7001B7D8 0C003560 */  jal   osStartThread
/* 01C3DC 7001B7DC 02202025 */   move  $a0, $s1
.L7001B7E0:
/* 01C3E0 7001B7E0 0C006184 */  jal   __osRestoreInt
/* 01C3E4 7001B7E4 02002025 */   move  $a0, $s0
/* 01C3E8 7001B7E8 00001025 */  move  $v0, $zero
.L7001B7EC:
/* 01C3EC 7001B7EC 8FBF001C */  lw    $ra, 0x1c($sp)
/* 01C3F0 7001B7F0 8FB00014 */  lw    $s0, 0x14($sp)
/* 01C3F4 7001B7F4 8FB10018 */  lw    $s1, 0x18($sp)
/* 01C3F8 7001B7F8 03E00008 */  jr    $ra
/* 01C3FC 7001B7FC 27BD0028 */   addiu $sp, $sp, 0x28
