# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .bss
glabel leoDiskStack
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0


.section .text
glabel __osLeoInterrupt
/* 018930 70017D30 3C0E8002 */  lui   $t6, %hi(osDiskExist) 
/* 018934 70017D34 8DCE6990 */  lw    $t6, %lo(osDiskExist)($t6)
/* 018938 70017D38 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 01893C 70017D3C AFBF001C */  sw    $ra, 0x1c($sp)
/* 018940 70017D40 15C00003 */  bnez  $t6, .L70017D50
/* 018944 70017D44 00000000 */   nop   
/* 018948 70017D48 100001AE */  b     .L70018404
/* 01894C 70017D4C 00001025 */   move  $v0, $zero
.L70017D50:
/* 018950 70017D50 3C0F8007 */  lui   $t7, %hi(__osDiskHandle) 
/* 018954 70017D54 8DEF9074 */  lw    $t7, %lo(__osDiskHandle)($t7)
/* 018958 70017D58 3C0BA460 */  lui   $t3, %hi(PI_STATUS_REG) # $t3, 0xa460
/* 01895C 70017D5C 25F80014 */  addiu $t8, $t7, 0x14
/* 018960 70017D60 AFB80030 */  sw    $t8, 0x30($sp)
/* 018964 70017D64 95F9001A */  lhu   $t9, 0x1a($t7)
/* 018968 70017D68 001940C0 */  sll   $t0, $t9, 3
/* 01896C 70017D6C 01194021 */  addu  $t0, $t0, $t9
/* 018970 70017D70 00084080 */  sll   $t0, $t0, 2
/* 018974 70017D74 03084821 */  addu  $t1, $t8, $t0
/* 018978 70017D78 252A0018 */  addiu $t2, $t1, 0x18
/* 01897C 70017D7C AFAA002C */  sw    $t2, 0x2c($sp)
/* 018980 70017D80 8D6C0010 */  lw    $t4, %lo(PI_STATUS_REG)($t3)
/* 018984 70017D84 AFAC0038 */  sw    $t4, 0x38($sp)
/* 018988 70017D88 8FAD0038 */  lw    $t5, 0x38($sp)
/* 01898C 70017D8C 31AE0001 */  andi  $t6, $t5, 1
/* 018990 70017D90 11C00034 */  beqz  $t6, .L70017E64
/* 018994 70017D94 00000000 */   nop   
/* 018998 70017D98 240F0003 */  li    $t7, 3
/* 01899C 70017D9C 3C19A460 */  lui   $t9, %hi(PI_STATUS_REG) # $t9, 0xa460
/* 0189A0 70017DA0 AF2F0010 */  sw    $t7, %lo(PI_STATUS_REG)($t9)
/* 0189A4 70017DA4 3C18A460 */  lui   $t8, %hi(PI_STATUS_REG) # $t8, 0xa460
/* 0189A8 70017DA8 8F080010 */  lw    $t0, %lo(PI_STATUS_REG)($t8)
/* 0189AC 70017DAC AFA80038 */  sw    $t0, 0x38($sp)
/* 0189B0 70017DB0 8FA90038 */  lw    $t1, 0x38($sp)
/* 0189B4 70017DB4 312A0002 */  andi  $t2, $t1, 2
/* 0189B8 70017DB8 11400008 */  beqz  $t2, .L70017DDC
/* 0189BC 70017DBC 00000000 */   nop   
.L70017DC0:
/* 0189C0 70017DC0 3C0BA460 */  lui   $t3, %hi(PI_STATUS_REG) # $t3, 0xa460
/* 0189C4 70017DC4 8D6C0010 */  lw    $t4, %lo(PI_STATUS_REG)($t3)
/* 0189C8 70017DC8 AFAC0038 */  sw    $t4, 0x38($sp)
/* 0189CC 70017DCC 8FAD0038 */  lw    $t5, 0x38($sp)
/* 0189D0 70017DD0 31AE0002 */  andi  $t6, $t5, 2
/* 0189D4 70017DD4 15C0FFFA */  bnez  $t6, .L70017DC0
/* 0189D8 70017DD8 00000000 */   nop   
.L70017DDC:
/* 0189DC 70017DDC 3C0FA500 */  lui   $t7, %hi(ASIC_STATUS) # $t7, 0xa500
/* 0189E0 70017DE0 8DF90508 */  lw    $t9, %lo(ASIC_STATUS)($t7)
/* 0189E4 70017DE4 3C010200 */  lui   $at, 0x200
/* 0189E8 70017DE8 AFB9003C */  sw    $t9, 0x3c($sp)
/* 0189EC 70017DEC 8FB8003C */  lw    $t8, 0x3c($sp)
/* 0189F0 70017DF0 03014024 */  and   $t0, $t8, $at
/* 0189F4 70017DF4 11000015 */  beqz  $t0, .L70017E4C
/* 0189F8 70017DF8 00000000 */   nop   
/* 0189FC 70017DFC 3C09A460 */  lui   $t1, %hi(PI_STATUS_REG) # $t1, 0xa460
/* 018A00 70017E00 8D2A0010 */  lw    $t2, %lo(PI_STATUS_REG)($t1)
/* 018A04 70017E04 AFAA0038 */  sw    $t2, 0x38($sp)
/* 018A08 70017E08 8FAB0038 */  lw    $t3, 0x38($sp)
/* 018A0C 70017E0C 316C0002 */  andi  $t4, $t3, 2
/* 018A10 70017E10 11800008 */  beqz  $t4, .L70017E34
/* 018A14 70017E14 00000000 */   nop   
.L70017E18:
/* 018A18 70017E18 3C0DA460 */  lui   $t5, %hi(PI_STATUS_REG) # $t5, 0xa460
/* 018A1C 70017E1C 8DAE0010 */  lw    $t6, %lo(PI_STATUS_REG)($t5)
/* 018A20 70017E20 AFAE0038 */  sw    $t6, 0x38($sp)
/* 018A24 70017E24 8FAF0038 */  lw    $t7, 0x38($sp)
/* 018A28 70017E28 31F90002 */  andi  $t9, $t7, 2
/* 018A2C 70017E2C 1720FFFA */  bnez  $t9, .L70017E18
/* 018A30 70017E30 00000000 */   nop   
.L70017E34:
/* 018A34 70017E34 8FB80030 */  lw    $t8, 0x30($sp)
/* 018A38 70017E38 3C010100 */  lui   $at, 0x100
/* 018A3C 70017E3C 3C0AA500 */  lui   $t2, %hi(ASIC_BM_STATUS) # $t2, 0xa500
/* 018A40 70017E40 8F080010 */  lw    $t0, 0x10($t8)
/* 018A44 70017E44 01014825 */  or    $t1, $t0, $at
/* 018A48 70017E48 AD490510 */  sw    $t1, %lo(ASIC_BM_STATUS)($t2)
.L70017E4C:
/* 018A4C 70017E4C 8FAC002C */  lw    $t4, 0x2c($sp)
/* 018A50 70017E50 240B004B */  li    $t3, 75
/* 018A54 70017E54 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018A58 70017E58 AD8B0000 */   sw    $t3, ($t4)
/* 018A5C 70017E5C 10000169 */  b     .L70018404
/* 018A60 70017E60 24020001 */   li    $v0, 1
.L70017E64:
/* 018A64 70017E64 3C0DA460 */  lui   $t5, %hi(PI_STATUS_REG) # $t5, 0xa460
/* 018A68 70017E68 8DAE0010 */  lw    $t6, %lo(PI_STATUS_REG)($t5)
/* 018A6C 70017E6C AFAE0038 */  sw    $t6, 0x38($sp)
/* 018A70 70017E70 8FAF0038 */  lw    $t7, 0x38($sp)
/* 018A74 70017E74 31F90002 */  andi  $t9, $t7, 2
/* 018A78 70017E78 13200008 */  beqz  $t9, .L70017E9C
/* 018A7C 70017E7C 00000000 */   nop   
.L70017E80:
/* 018A80 70017E80 3C18A460 */  lui   $t8, %hi(PI_STATUS_REG) # $t8, 0xa460
/* 018A84 70017E84 8F080010 */  lw    $t0, %lo(PI_STATUS_REG)($t8)
/* 018A88 70017E88 AFA80038 */  sw    $t0, 0x38($sp)
/* 018A8C 70017E8C 8FA90038 */  lw    $t1, 0x38($sp)
/* 018A90 70017E90 312A0002 */  andi  $t2, $t1, 2
/* 018A94 70017E94 1540FFFA */  bnez  $t2, .L70017E80
/* 018A98 70017E98 00000000 */   nop   
.L70017E9C:
/* 018A9C 70017E9C 3C0BA500 */  lui   $t3, %hi(ASIC_STATUS) # $t3, 0xa500
/* 018AA0 70017EA0 8D6C0508 */  lw    $t4, %lo(ASIC_STATUS)($t3)
/* 018AA4 70017EA4 3C010200 */  lui   $at, 0x200
/* 018AA8 70017EA8 AFAC003C */  sw    $t4, 0x3c($sp)
/* 018AAC 70017EAC 8FAD003C */  lw    $t5, 0x3c($sp)
/* 018AB0 70017EB0 01A17024 */  and   $t6, $t5, $at
/* 018AB4 70017EB4 11C00019 */  beqz  $t6, .L70017F1C
/* 018AB8 70017EB8 00000000 */   nop   
/* 018ABC 70017EBC 3C0FA460 */  lui   $t7, %hi(PI_STATUS_REG) # $t7, 0xa460
/* 018AC0 70017EC0 8DF90010 */  lw    $t9, %lo(PI_STATUS_REG)($t7)
/* 018AC4 70017EC4 AFB90038 */  sw    $t9, 0x38($sp)
/* 018AC8 70017EC8 8FB80038 */  lw    $t8, 0x38($sp)
/* 018ACC 70017ECC 33080002 */  andi  $t0, $t8, 2
/* 018AD0 70017ED0 11000008 */  beqz  $t0, .L70017EF4
/* 018AD4 70017ED4 00000000 */   nop   
.L70017ED8:
/* 018AD8 70017ED8 3C09A460 */  lui   $t1, %hi(PI_STATUS_REG) # $t1, 0xa460
/* 018ADC 70017EDC 8D2A0010 */  lw    $t2, %lo(PI_STATUS_REG)($t1)
/* 018AE0 70017EE0 AFAA0038 */  sw    $t2, 0x38($sp)
/* 018AE4 70017EE4 8FAB0038 */  lw    $t3, 0x38($sp)
/* 018AE8 70017EE8 316C0002 */  andi  $t4, $t3, 2
/* 018AEC 70017EEC 1580FFFA */  bnez  $t4, .L70017ED8
/* 018AF0 70017EF0 00000000 */   nop   
.L70017EF4:
/* 018AF4 70017EF4 8FAD0030 */  lw    $t5, 0x30($sp)
/* 018AF8 70017EF8 3C010100 */  lui   $at, 0x100
/* 018AFC 70017EFC 3C19A500 */  lui   $t9, %hi(ASIC_BM_STATUS) # $t9, 0xa500
/* 018B00 70017F00 8DAE0010 */  lw    $t6, 0x10($t5)
/* 018B04 70017F04 00001025 */  move  $v0, $zero
/* 018B08 70017F08 01C17825 */  or    $t7, $t6, $at
/* 018B0C 70017F0C AF2F0510 */  sw    $t7, %lo(ASIC_BM_STATUS)($t9)
/* 018B10 70017F10 8FB8002C */  lw    $t8, 0x2c($sp)
/* 018B14 70017F14 1000013B */  b     .L70018404
/* 018B18 70017F18 AF000000 */   sw    $zero, ($t8)
.L70017F1C:
/* 018B1C 70017F1C 8FA8003C */  lw    $t0, 0x3c($sp)
/* 018B20 70017F20 3C010800 */  lui   $at, 0x800
/* 018B24 70017F24 01014824 */  and   $t1, $t0, $at
/* 018B28 70017F28 11200011 */  beqz  $t1, .L70017F70
/* 018B2C 70017F2C 00000000 */   nop   
/* 018B30 70017F30 8FAB002C */  lw    $t3, 0x2c($sp)
/* 018B34 70017F34 240A0003 */  li    $t2, 3
/* 018B38 70017F38 0C00613F */  jal   __osLeoInterrupt_sub2
/* 018B3C 70017F3C AD6A0000 */   sw    $t2, ($t3)
/* 018B40 70017F40 240C0002 */  li    $t4, 2
/* 018B44 70017F44 3C0DA460 */  lui   $t5, %hi(PI_STATUS_REG) # $t5, 0xa460
/* 018B48 70017F48 ADAC0010 */  sw    $t4, %lo(PI_STATUS_REG)($t5)
/* 018B4C 70017F4C 3C0E8002 */  lui   $t6, %hi(__OSGlobalIntMask) 
/* 018B50 70017F50 8DCE698C */  lw    $t6, %lo(__OSGlobalIntMask)($t6)
/* 018B54 70017F54 3C010010 */  lui   $at, (0x00100401 >> 16) # lui $at, 0x10
/* 018B58 70017F58 34210401 */  ori   $at, (0x00100401 & 0xFFFF) # ori $at, $at, 0x401
/* 018B5C 70017F5C 01C17825 */  or    $t7, $t6, $at
/* 018B60 70017F60 3C018002 */  lui   $at, %hi(__OSGlobalIntMask)
/* 018B64 70017F64 AC2F698C */  sw    $t7, %lo(__OSGlobalIntMask)($at)
/* 018B68 70017F68 10000126 */  b     .L70018404
/* 018B6C 70017F6C 24020001 */   li    $v0, 1
.L70017F70:
/* 018B70 70017F70 8FB90030 */  lw    $t9, 0x30($sp)
/* 018B74 70017F74 24010001 */  li    $at, 1
/* 018B78 70017F78 8F380000 */  lw    $t8, ($t9)
/* 018B7C 70017F7C 1701003B */  bne   $t8, $at, .L7001806C
/* 018B80 70017F80 00000000 */   nop   
/* 018B84 70017F84 8FA8003C */  lw    $t0, 0x3c($sp)
/* 018B88 70017F88 3C014000 */  lui   $at, 0x4000
/* 018B8C 70017F8C 01014824 */  and   $t1, $t0, $at
/* 018B90 70017F90 15200021 */  bnez  $t1, .L70018018
/* 018B94 70017F94 00000000 */   nop   
/* 018B98 70017F98 972C0004 */  lhu   $t4, 4($t9)
/* 018B9C 70017F9C 8F2A0008 */  lw    $t2, 8($t9)
/* 018BA0 70017FA0 000C6880 */  sll   $t5, $t4, 2
/* 018BA4 70017FA4 01AC6821 */  addu  $t5, $t5, $t4
/* 018BA8 70017FA8 000D6880 */  sll   $t5, $t5, 2
/* 018BAC 70017FAC 01AC6821 */  addu  $t5, $t5, $t4
/* 018BB0 70017FB0 000D6880 */  sll   $t5, $t5, 2
/* 018BB4 70017FB4 01AC6821 */  addu  $t5, $t5, $t4
/* 018BB8 70017FB8 254B0001 */  addiu $t3, $t2, 1
/* 018BBC 70017FBC 116D0007 */  beq   $t3, $t5, .L70017FDC
/* 018BC0 70017FC0 00000000 */   nop   
/* 018BC4 70017FC4 8FAF002C */  lw    $t7, 0x2c($sp)
/* 018BC8 70017FC8 240E0006 */  li    $t6, 6
/* 018BCC 70017FCC 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018BD0 70017FD0 ADEE0000 */   sw    $t6, ($t7)
/* 018BD4 70017FD4 1000010B */  b     .L70018404
/* 018BD8 70017FD8 24020001 */   li    $v0, 1
.L70017FDC:
/* 018BDC 70017FDC 24180002 */  li    $t8, 2
/* 018BE0 70017FE0 3C08A460 */  lui   $t0, %hi(PI_STATUS_REG) # $t0, 0xa460
/* 018BE4 70017FE4 AD180010 */  sw    $t8, %lo(PI_STATUS_REG)($t0)
/* 018BE8 70017FE8 3C098002 */  lui   $t1, %hi(__OSGlobalIntMask) 
/* 018BEC 70017FEC 8D29698C */  lw    $t1, %lo(__OSGlobalIntMask)($t1)
/* 018BF0 70017FF0 3C010010 */  lui   $at, (0x00100401 >> 16) # lui $at, 0x10
/* 018BF4 70017FF4 34210401 */  ori   $at, (0x00100401 & 0xFFFF) # ori $at, $at, 0x401
/* 018BF8 70017FF8 01215025 */  or    $t2, $t1, $at
/* 018BFC 70017FFC 8FB9002C */  lw    $t9, 0x2c($sp)
/* 018C00 70018000 3C018002 */  lui   $at, %hi(__OSGlobalIntMask)
/* 018C04 70018004 AC2A698C */  sw    $t2, %lo(__OSGlobalIntMask)($at)
/* 018C08 70018008 0C00613F */  jal   __osLeoInterrupt_sub2
/* 018C0C 7001800C AF200000 */   sw    $zero, ($t9)
/* 018C10 70018010 100000FC */  b     .L70018404
/* 018C14 70018014 24020001 */   li    $v0, 1
.L70018018:
/* 018C18 70018018 8FAC002C */  lw    $t4, 0x2c($sp)
/* 018C1C 7001801C 3C048007 */  lui   $a0, %hi(__osDiskHandle)
/* 018C20 70018020 3C060500 */  lui   $a2, (0x05000400 >> 16) # lui $a2, 0x500
/* 018C24 70018024 8D8B0004 */  lw    $t3, 4($t4)
/* 018C28 70018028 8D8D000C */  lw    $t5, 0xc($t4)
/* 018C2C 7001802C 34C60400 */  ori   $a2, (0x05000400 & 0xFFFF) # ori $a2, $a2, 0x400
/* 018C30 70018030 24050001 */  li    $a1, 1
/* 018C34 70018034 016D7021 */  addu  $t6, $t3, $t5
/* 018C38 70018038 AD8E0004 */  sw    $t6, 4($t4)
/* 018C3C 7001803C 8FAF0030 */  lw    $t7, 0x30($sp)
/* 018C40 70018040 8DF80008 */  lw    $t8, 8($t7)
/* 018C44 70018044 27080001 */  addiu $t0, $t8, 1
/* 018C48 70018048 ADE80008 */  sw    $t0, 8($t7)
/* 018C4C 7001804C 8FA9002C */  lw    $t1, 0x2c($sp)
/* 018C50 70018050 8C849074 */  lw    $a0, %lo(__osDiskHandle)($a0)
/* 018C54 70018054 8D2A000C */  lw    $t2, 0xc($t1)
/* 018C58 70018058 8D270004 */  lw    $a3, 4($t1)
/* 018C5C 7001805C 0C00794C */  jal   osEPiRawStartDma
/* 018C60 70018060 AFAA0010 */   sw    $t2, 0x10($sp)
/* 018C64 70018064 100000E7 */  b     .L70018404
/* 018C68 70018068 24020001 */   li    $v0, 1
.L7001806C:
/* 018C6C 7001806C 8FB90030 */  lw    $t9, 0x30($sp)
/* 018C70 70018070 8F2B0000 */  lw    $t3, ($t9)
/* 018C74 70018074 156000DE */  bnez  $t3, .L700183F0
/* 018C78 70018078 00000000 */   nop   
/* 018C7C 7001807C 972D0004 */  lhu   $t5, 4($t9)
/* 018C80 70018080 24010003 */  li    $at, 3
/* 018C84 70018084 15A10017 */  bne   $t5, $at, .L700180E4
/* 018C88 70018088 00000000 */   nop   
/* 018C8C 7001808C 8FAC002C */  lw    $t4, 0x2c($sp)
/* 018C90 70018090 8F2E0008 */  lw    $t6, 8($t9)
/* 018C94 70018094 8D980010 */  lw    $t8, 0x10($t4)
/* 018C98 70018098 27080011 */  addiu $t0, $t8, 0x11
/* 018C9C 7001809C 010E082A */  slt   $at, $t0, $t6
/* 018CA0 700180A0 10200005 */  beqz  $at, .L700180B8
/* 018CA4 700180A4 00000000 */   nop   
/* 018CA8 700180A8 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018CAC 700180AC AD800000 */   sw    $zero, ($t4)
/* 018CB0 700180B0 100000D4 */  b     .L70018404
/* 018CB4 700180B4 24020001 */   li    $v0, 1
.L700180B8:
/* 018CB8 700180B8 8FAF003C */  lw    $t7, 0x3c($sp)
/* 018CBC 700180BC 3C014000 */  lui   $at, 0x4000
/* 018CC0 700180C0 01E14824 */  and   $t1, $t7, $at
/* 018CC4 700180C4 1520000C */  bnez  $t1, .L700180F8
/* 018CC8 700180C8 00000000 */   nop   
/* 018CCC 700180CC 8FAB002C */  lw    $t3, 0x2c($sp)
/* 018CD0 700180D0 240A0011 */  li    $t2, 17
/* 018CD4 700180D4 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018CD8 700180D8 AD6A0000 */   sw    $t2, ($t3)
/* 018CDC 700180DC 100000C9 */  b     .L70018404
/* 018CE0 700180E0 24020001 */   li    $v0, 1
.L700180E4:
/* 018CE4 700180E4 8FAD002C */  lw    $t5, 0x2c($sp)
/* 018CE8 700180E8 8DB90004 */  lw    $t9, 4($t5)
/* 018CEC 700180EC 8DB8000C */  lw    $t8, 0xc($t5)
/* 018CF0 700180F0 03387021 */  addu  $t6, $t9, $t8
/* 018CF4 700180F4 ADAE0004 */  sw    $t6, 4($t5)
.L700180F8:
/* 018CF8 700180F8 3C08A500 */  lui   $t0, %hi(ASIC_BM_STATUS) # $t0, 0xa500
/* 018CFC 700180FC 8D0C0510 */  lw    $t4, %lo(ASIC_BM_STATUS)($t0)
/* 018D00 70018100 3C010020 */  lui   $at, 0x20
/* 018D04 70018104 AFAC0034 */  sw    $t4, 0x34($sp)
/* 018D08 70018108 8FAF0034 */  lw    $t7, 0x34($sp)
/* 018D0C 7001810C 01E14824 */  and   $t1, $t7, $at
/* 018D10 70018110 11200004 */  beqz  $t1, .L70018124
/* 018D14 70018114 3C010040 */   lui   $at, 0x40
/* 018D18 70018118 01E15024 */  and   $t2, $t7, $at
/* 018D1C 7001811C 15400006 */  bnez  $t2, .L70018138
/* 018D20 70018120 00000000 */   nop   
.L70018124:
/* 018D24 70018124 8FAB0034 */  lw    $t3, 0x34($sp)
/* 018D28 70018128 3C010200 */  lui   $at, 0x200
/* 018D2C 7001812C 0161C824 */  and   $t9, $t3, $at
/* 018D30 70018130 13200022 */  beqz  $t9, .L700181BC
/* 018D34 70018134 00000000 */   nop   
.L70018138:
/* 018D38 70018138 8FB8002C */  lw    $t8, 0x2c($sp)
/* 018D3C 7001813C 8F0E0010 */  lw    $t6, 0x10($t8)
/* 018D40 70018140 2DC10004 */  sltiu $at, $t6, 4
/* 018D44 70018144 14200010 */  bnez  $at, .L70018188
/* 018D48 70018148 00000000 */   nop   
/* 018D4C 7001814C 8FAD0030 */  lw    $t5, 0x30($sp)
/* 018D50 70018150 24010003 */  li    $at, 3
/* 018D54 70018154 95A80004 */  lhu   $t0, 4($t5)
/* 018D58 70018158 15010005 */  bne   $t0, $at, .L70018170
/* 018D5C 7001815C 00000000 */   nop   
/* 018D60 70018160 8DAC0008 */  lw    $t4, 8($t5)
/* 018D64 70018164 29810053 */  slti  $at, $t4, 0x53
/* 018D68 70018168 14200010 */  bnez  $at, .L700181AC
/* 018D6C 7001816C 00000000 */   nop   
.L70018170:
/* 018D70 70018170 8FAF002C */  lw    $t7, 0x2c($sp)
/* 018D74 70018174 24090011 */  li    $t1, 17
/* 018D78 70018178 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018D7C 7001817C ADE90000 */   sw    $t1, ($t7)
/* 018D80 70018180 100000A0 */  b     .L70018404
/* 018D84 70018184 24020001 */   li    $v0, 1
.L70018188:
/* 018D88 70018188 8FAA002C */  lw    $t2, 0x2c($sp)
/* 018D8C 7001818C 8FB90030 */  lw    $t9, 0x30($sp)
/* 018D90 70018190 8D4B0010 */  lw    $t3, 0x10($t2)
/* 018D94 70018194 AFAB0028 */  sw    $t3, 0x28($sp)
/* 018D98 70018198 8F380008 */  lw    $t8, 8($t9)
/* 018D9C 7001819C 000B4080 */  sll   $t0, $t3, 2
/* 018DA0 700181A0 01486821 */  addu  $t5, $t2, $t0
/* 018DA4 700181A4 270E0001 */  addiu $t6, $t8, 1
/* 018DA8 700181A8 ADAE0014 */  sw    $t6, 0x14($t5)
.L700181AC:
/* 018DAC 700181AC 8FAC002C */  lw    $t4, 0x2c($sp)
/* 018DB0 700181B0 8D890010 */  lw    $t1, 0x10($t4)
/* 018DB4 700181B4 252F0001 */  addiu $t7, $t1, 1
/* 018DB8 700181B8 AD8F0010 */  sw    $t7, 0x10($t4)
.L700181BC:
/* 018DBC 700181BC 8FB9003C */  lw    $t9, 0x3c($sp)
/* 018DC0 700181C0 3C011000 */  lui   $at, 0x1000
/* 018DC4 700181C4 0321C024 */  and   $t8, $t9, $at
/* 018DC8 700181C8 13000035 */  beqz  $t8, .L700182A0
/* 018DCC 700181CC 00000000 */   nop   
/* 018DD0 700181D0 8FAB0030 */  lw    $t3, 0x30($sp)
/* 018DD4 700181D4 24010057 */  li    $at, 87
/* 018DD8 700181D8 8D6A0008 */  lw    $t2, 8($t3)
/* 018DDC 700181DC 11410005 */  beq   $t2, $at, .L700181F4
/* 018DE0 700181E0 00000000 */   nop   
/* 018DE4 700181E4 8FAE002C */  lw    $t6, 0x2c($sp)
/* 018DE8 700181E8 24080006 */  li    $t0, 6
/* 018DEC 700181EC 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018DF0 700181F0 ADC80000 */   sw    $t0, ($t6)
.L700181F4:
/* 018DF4 700181F4 8FAD0030 */  lw    $t5, 0x30($sp)
/* 018DF8 700181F8 24010002 */  li    $at, 2
/* 018DFC 700181FC 95A90004 */  lhu   $t1, 4($t5)
/* 018E00 70018200 1521000F */  bne   $t1, $at, .L70018240
/* 018E04 70018204 00000000 */   nop   
/* 018E08 70018208 95AF0006 */  lhu   $t7, 6($t5)
/* 018E0C 7001820C 15E0000C */  bnez  $t7, .L70018240
/* 018E10 70018210 00000000 */   nop   
/* 018E14 70018214 240C0001 */  li    $t4, 1
/* 018E18 70018218 A5AC0006 */  sh    $t4, 6($t5)
/* 018E1C 7001821C 8FB80030 */  lw    $t8, 0x30($sp)
/* 018E20 70018220 2419FFFF */  li    $t9, -1
/* 018E24 70018224 AF190008 */  sw    $t9, 8($t8)
/* 018E28 70018228 8FAB0030 */  lw    $t3, 0x30($sp)
/* 018E2C 7001822C 8D6A0040 */  lw    $t2, 0x40($t3)
/* 018E30 70018230 8D680048 */  lw    $t0, 0x48($t3)
/* 018E34 70018234 01487023 */  subu  $t6, $t2, $t0
/* 018E38 70018238 1000000B */  b     .L70018268
/* 018E3C 7001823C AD6E0040 */   sw    $t6, 0x40($t3)
.L70018240:
/* 018E40 70018240 24090002 */  li    $t1, 2
/* 018E44 70018244 3C0FA460 */  lui   $t7, %hi(PI_STATUS_REG) # $t7, 0xa460
/* 018E48 70018248 ADE90010 */  sw    $t1, %lo(PI_STATUS_REG)($t7)
/* 018E4C 7001824C 3C0C8002 */  lui   $t4, %hi(__OSGlobalIntMask) 
/* 018E50 70018250 8D8C698C */  lw    $t4, %lo(__OSGlobalIntMask)($t4)
/* 018E54 70018254 3C010010 */  lui   $at, (0x00100401 >> 16) # lui $at, 0x10
/* 018E58 70018258 34210401 */  ori   $at, (0x00100401 & 0xFFFF) # ori $at, $at, 0x401
/* 018E5C 7001825C 01816825 */  or    $t5, $t4, $at
/* 018E60 70018260 3C018002 */  lui   $at, %hi(__OSGlobalIntMask)
/* 018E64 70018264 AC2D698C */  sw    $t5, %lo(__OSGlobalIntMask)($at)
.L70018268:
/* 018E68 70018268 8FB9002C */  lw    $t9, 0x2c($sp)
/* 018E6C 7001826C 3C048007 */  lui   $a0, %hi(__osDiskHandle)
/* 018E70 70018270 8C849074 */  lw    $a0, %lo(__osDiskHandle)($a0)
/* 018E74 70018274 8F38000C */  lw    $t8, 0xc($t9)
/* 018E78 70018278 8F270008 */  lw    $a3, 8($t9)
/* 018E7C 7001827C 00002825 */  move  $a1, $zero
/* 018E80 70018280 00185080 */  sll   $t2, $t8, 2
/* 018E84 70018284 AFAA0010 */  sw    $t2, 0x10($sp)
/* 018E88 70018288 0C00794C */  jal   osEPiRawStartDma
/* 018E8C 7001828C 3C060500 */   lui   $a2, 0x500
/* 018E90 70018290 8FA8002C */  lw    $t0, 0x2c($sp)
/* 018E94 70018294 24020001 */  li    $v0, 1
/* 018E98 70018298 1000005A */  b     .L70018404
/* 018E9C 7001829C AD000000 */   sw    $zero, ($t0)
.L700182A0:
/* 018EA0 700182A0 8FAE0030 */  lw    $t6, 0x30($sp)
/* 018EA4 700182A4 2401FFFF */  li    $at, -1
/* 018EA8 700182A8 8DCB0008 */  lw    $t3, 8($t6)
/* 018EAC 700182AC 15610021 */  bne   $t3, $at, .L70018334
/* 018EB0 700182B0 00000000 */   nop   
/* 018EB4 700182B4 95C90004 */  lhu   $t1, 4($t6)
/* 018EB8 700182B8 24010002 */  li    $at, 2
/* 018EBC 700182BC 1521001D */  bne   $t1, $at, .L70018334
/* 018EC0 700182C0 00000000 */   nop   
/* 018EC4 700182C4 95CF0006 */  lhu   $t7, 6($t6)
/* 018EC8 700182C8 24010001 */  li    $at, 1
/* 018ECC 700182CC 15E10019 */  bne   $t7, $at, .L70018334
/* 018ED0 700182D0 00000000 */   nop   
/* 018ED4 700182D4 25CC0018 */  addiu $t4, $t6, 0x18
/* 018ED8 700182D8 AFAC0024 */  sw    $t4, 0x24($sp)
/* 018EDC 700182DC 8DCD0028 */  lw    $t5, 0x28($t6)
/* 018EE0 700182E0 15A00011 */  bnez  $t5, .L70018328
/* 018EE4 700182E4 00000000 */   nop   
/* 018EE8 700182E8 8DD90020 */  lw    $t9, 0x20($t6)
/* 018EEC 700182EC 8F380000 */  lw    $t8, ($t9)
/* 018EF0 700182F0 8F2A0004 */  lw    $t2, 4($t9)
/* 018EF4 700182F4 8F2B0008 */  lw    $t3, 8($t9)
/* 018EF8 700182F8 8F2F000C */  lw    $t7, 0xc($t9)
/* 018EFC 700182FC 030A4025 */  or    $t0, $t8, $t2
/* 018F00 70018300 010B4825 */  or    $t1, $t0, $t3
/* 018F04 70018304 01E96025 */  or    $t4, $t7, $t1
/* 018F08 70018308 11800007 */  beqz  $t4, .L70018328
/* 018F0C 7001830C 00000000 */   nop   
/* 018F10 70018310 8FAE002C */  lw    $t6, 0x2c($sp)
/* 018F14 70018314 240D0006 */  li    $t5, 6
/* 018F18 70018318 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018F1C 7001831C ADCD0000 */   sw    $t5, ($t6)
/* 018F20 70018320 10000038 */  b     .L70018404
/* 018F24 70018324 24020001 */   li    $v0, 1
.L70018328:
/* 018F28 70018328 8FB8002C */  lw    $t8, 0x2c($sp)
/* 018F2C 7001832C 0C00613F */  jal   __osLeoInterrupt_sub2
/* 018F30 70018330 AF000000 */   sw    $zero, ($t8)
.L70018334:
/* 018F34 70018334 8FAA0030 */  lw    $t2, 0x30($sp)
/* 018F38 70018338 3C014000 */  lui   $at, 0x4000
/* 018F3C 7001833C 8D480008 */  lw    $t0, 8($t2)
/* 018F40 70018340 250B0001 */  addiu $t3, $t0, 1
/* 018F44 70018344 AD4B0008 */  sw    $t3, 8($t2)
/* 018F48 70018348 8FB9003C */  lw    $t9, 0x3c($sp)
/* 018F4C 7001834C 03217824 */  and   $t7, $t9, $at
/* 018F50 70018350 11E0001A */  beqz  $t7, .L700183BC
/* 018F54 70018354 00000000 */   nop   
/* 018F58 70018358 8FA90030 */  lw    $t1, 0x30($sp)
/* 018F5C 7001835C 8D2C0008 */  lw    $t4, 8($t1)
/* 018F60 70018360 29810055 */  slti  $at, $t4, 0x55
/* 018F64 70018364 14200007 */  bnez  $at, .L70018384
/* 018F68 70018368 00000000 */   nop   
/* 018F6C 7001836C 8FAE002C */  lw    $t6, 0x2c($sp)
/* 018F70 70018370 240D0006 */  li    $t5, 6
/* 018F74 70018374 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018F78 70018378 ADCD0000 */   sw    $t5, ($t6)
/* 018F7C 7001837C 10000021 */  b     .L70018404
/* 018F80 70018380 24020001 */   li    $v0, 1
.L70018384:
/* 018F84 70018384 8FB8002C */  lw    $t8, 0x2c($sp)
/* 018F88 70018388 3C048007 */  lui   $a0, %hi(__osDiskHandle)
/* 018F8C 7001838C 3C060500 */  lui   $a2, (0x05000400 >> 16) # lui $a2, 0x500
/* 018F90 70018390 8F08000C */  lw    $t0, 0xc($t8)
/* 018F94 70018394 8F070004 */  lw    $a3, 4($t8)
/* 018F98 70018398 34C60400 */  ori   $a2, (0x05000400 & 0xFFFF) # ori $a2, $a2, 0x400
/* 018F9C 7001839C 8C849074 */  lw    $a0, %lo(__osDiskHandle)($a0)
/* 018FA0 700183A0 00002825 */  move  $a1, $zero
/* 018FA4 700183A4 0C00794C */  jal   osEPiRawStartDma
/* 018FA8 700183A8 AFA80010 */   sw    $t0, 0x10($sp)
/* 018FAC 700183AC 8FAB002C */  lw    $t3, 0x2c($sp)
/* 018FB0 700183B0 24020001 */  li    $v0, 1
/* 018FB4 700183B4 10000013 */  b     .L70018404
/* 018FB8 700183B8 AD600000 */   sw    $zero, ($t3)
.L700183BC:
/* 018FBC 700183BC 8FAA0030 */  lw    $t2, 0x30($sp)
/* 018FC0 700183C0 8D590008 */  lw    $t9, 8($t2)
/* 018FC4 700183C4 2B210055 */  slti  $at, $t9, 0x55
/* 018FC8 700183C8 10200007 */  beqz  $at, .L700183E8
/* 018FCC 700183CC 00000000 */   nop   
/* 018FD0 700183D0 8FA9002C */  lw    $t1, 0x2c($sp)
/* 018FD4 700183D4 240F0006 */  li    $t7, 6
/* 018FD8 700183D8 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018FDC 700183DC AD2F0000 */   sw    $t7, ($t1)
/* 018FE0 700183E0 10000008 */  b     .L70018404
/* 018FE4 700183E4 24020001 */   li    $v0, 1
.L700183E8:
/* 018FE8 700183E8 10000006 */  b     .L70018404
/* 018FEC 700183EC 24020001 */   li    $v0, 1
.L700183F0:
/* 018FF0 700183F0 8FAD002C */  lw    $t5, 0x2c($sp)
/* 018FF4 700183F4 240C004B */  li    $t4, 75
/* 018FF8 700183F8 0C006105 */  jal   __osLeoInterrupt_sub1
/* 018FFC 700183FC ADAC0000 */   sw    $t4, ($t5)
/* 019000 70018400 24020001 */  li    $v0, 1
.L70018404:
/* 019004 70018404 8FBF001C */  lw    $ra, 0x1c($sp)
/* 019008 70018408 27BD0040 */  addiu $sp, $sp, 0x40
/* 01900C 7001840C 03E00008 */  jr    $ra
/* 019010 70018410 00000000 */   nop   

glabel __osLeoInterrupt_sub1
/* 019014 70018414 3C0E8007 */  lui   $t6, %hi(__osDiskHandle) 
/* 019018 70018418 8DCE9074 */  lw    $t6, %lo(__osDiskHandle)($t6)
/* 01901C 7001841C 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 019020 70018420 AFBF0014 */  sw    $ra, 0x14($sp)
/* 019024 70018424 25CF0014 */  addiu $t7, $t6, 0x14
/* 019028 70018428 AFAF001C */  sw    $t7, 0x1c($sp)
/* 01902C 7001842C 3C18A460 */  lui   $t8, %hi(PI_STATUS_REG) # $t8, 0xa460
/* 019030 70018430 8F190010 */  lw    $t9, %lo(PI_STATUS_REG)($t8)
/* 019034 70018434 AFB90018 */  sw    $t9, 0x18($sp)
/* 019038 70018438 8FA80018 */  lw    $t0, 0x18($sp)
/* 01903C 7001843C 31090002 */  andi  $t1, $t0, 2
/* 019040 70018440 11200008 */  beqz  $t1, .L70018464
/* 019044 70018444 00000000 */   nop   
.L70018448:
/* 019048 70018448 3C0AA460 */  lui   $t2, %hi(PI_STATUS_REG) # $t2, 0xa460
/* 01904C 7001844C 8D4B0010 */  lw    $t3, %lo(PI_STATUS_REG)($t2)
/* 019050 70018450 AFAB0018 */  sw    $t3, 0x18($sp)
/* 019054 70018454 8FAC0018 */  lw    $t4, 0x18($sp)
/* 019058 70018458 318D0002 */  andi  $t5, $t4, 2
/* 01905C 7001845C 15A0FFFA */  bnez  $t5, .L70018448
/* 019060 70018460 00000000 */   nop   
.L70018464:
/* 019064 70018464 8FAE001C */  lw    $t6, 0x1c($sp)
/* 019068 70018468 3C011000 */  lui   $at, 0x1000
/* 01906C 7001846C 3C19A500 */  lui   $t9, %hi(ASIC_BM_STATUS) # $t9, 0xa500
/* 019070 70018470 8DCF0010 */  lw    $t7, 0x10($t6)
/* 019074 70018474 3C08A460 */  lui   $t0, %hi(PI_STATUS_REG) # $t0, 0xa460
/* 019078 70018478 01E1C025 */  or    $t8, $t7, $at
/* 01907C 7001847C AF380510 */  sw    $t8, %lo(ASIC_BM_STATUS)($t9)
/* 019080 70018480 8D090010 */  lw    $t1, %lo(PI_STATUS_REG)($t0)
/* 019084 70018484 AFA90018 */  sw    $t1, 0x18($sp)
/* 019088 70018488 8FAA0018 */  lw    $t2, 0x18($sp)
/* 01908C 7001848C 314B0002 */  andi  $t3, $t2, 2
/* 019090 70018490 11600008 */  beqz  $t3, .L700184B4
/* 019094 70018494 00000000 */   nop   
.L70018498:
/* 019098 70018498 3C0CA460 */  lui   $t4, %hi(PI_STATUS_REG) # $t4, 0xa460
/* 01909C 7001849C 8D8D0010 */  lw    $t5, %lo(PI_STATUS_REG)($t4)
/* 0190A0 700184A0 AFAD0018 */  sw    $t5, 0x18($sp)
/* 0190A4 700184A4 8FAE0018 */  lw    $t6, 0x18($sp)
/* 0190A8 700184A8 31CF0002 */  andi  $t7, $t6, 2
/* 0190AC 700184AC 15E0FFFA */  bnez  $t7, .L70018498
/* 0190B0 700184B0 00000000 */   nop   
.L700184B4:
/* 0190B4 700184B4 8FB8001C */  lw    $t8, 0x1c($sp)
/* 0190B8 700184B8 3C08A500 */  lui   $t0, %hi(ASIC_BM_STATUS) # $t0, 0xa500
/* 0190BC 700184BC 8F190010 */  lw    $t9, 0x10($t8)
/* 0190C0 700184C0 0C00613F */  jal   __osLeoInterrupt_sub2
/* 0190C4 700184C4 AD190510 */   sw    $t9, %lo(ASIC_BM_STATUS)($t0)
/* 0190C8 700184C8 24090002 */  li    $t1, 2
/* 0190CC 700184CC 3C0AA460 */  lui   $t2, %hi(PI_STATUS_REG) # $t2, 0xa460
/* 0190D0 700184D0 AD490010 */  sw    $t1, %lo(PI_STATUS_REG)($t2)
/* 0190D4 700184D4 3C0B8002 */  lui   $t3, %hi(__OSGlobalIntMask) 
/* 0190D8 700184D8 8D6B698C */  lw    $t3, %lo(__OSGlobalIntMask)($t3)
/* 0190DC 700184DC 3C010010 */  lui   $at, (0x00100401 >> 16) # lui $at, 0x10
/* 0190E0 700184E0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0190E4 700184E4 34210401 */  ori   $at, (0x00100401 & 0xFFFF) # ori $at, $at, 0x401
/* 0190E8 700184E8 01616025 */  or    $t4, $t3, $at
/* 0190EC 700184EC 3C018002 */  lui   $at, %hi(__OSGlobalIntMask)
/* 0190F0 700184F0 AC2C698C */  sw    $t4, %lo(__OSGlobalIntMask)($at)
/* 0190F4 700184F4 03E00008 */  jr    $ra
/* 0190F8 700184F8 27BD0020 */   addiu $sp, $sp, 0x20

glabel __osLeoInterrupt_sub2
/* 0190FC 700184FC 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 019100 70018500 3C0E8006 */  lui   $t6, %hi(__osEventStateTab) 
/* 019104 70018504 25CE6A10 */  addiu $t6, %lo(__osEventStateTab) # addiu $t6, $t6, 0x6a10
/* 019108 70018508 25CF0040 */  addiu $t7, $t6, 0x40
/* 01910C 7001850C AFBF001C */  sw    $ra, 0x1c($sp)
/* 019110 70018510 AFB00018 */  sw    $s0, 0x18($sp)
/* 019114 70018514 AFAF002C */  sw    $t7, 0x2c($sp)
/* 019118 70018518 8DD80040 */  lw    $t8, 0x40($t6)
/* 01911C 7001851C 1300002D */  beqz  $t8, .L700185D4
/* 019120 70018520 AFB80028 */   sw    $t8, 0x28($sp)
/* 019124 70018524 8F190008 */  lw    $t9, 8($t8)
/* 019128 70018528 8F080010 */  lw    $t0, 0x10($t8)
/* 01912C 7001852C 0328082A */  slt   $at, $t9, $t0
/* 019130 70018530 10200028 */  beqz  $at, .L700185D4
/* 019134 70018534 00000000 */   nop   
/* 019138 70018538 8FA90028 */  lw    $t1, 0x28($sp)
/* 01913C 7001853C 8FAE002C */  lw    $t6, 0x2c($sp)
/* 019140 70018540 8D2A000C */  lw    $t2, 0xc($t1)
/* 019144 70018544 8D2B0008 */  lw    $t3, 8($t1)
/* 019148 70018548 8D2D0010 */  lw    $t5, 0x10($t1)
/* 01914C 7001854C 014B6021 */  addu  $t4, $t2, $t3
/* 019150 70018550 018D001A */  div   $zero, $t4, $t5
/* 019154 70018554 00007810 */  mfhi  $t7
/* 019158 70018558 AFAF0024 */  sw    $t7, 0x24($sp)
/* 01915C 7001855C 8D280014 */  lw    $t0, 0x14($t1)
/* 019160 70018560 8DD80004 */  lw    $t8, 4($t6)
/* 019164 70018564 000FC880 */  sll   $t9, $t7, 2
/* 019168 70018568 01195021 */  addu  $t2, $t0, $t9
/* 01916C 7001856C AD580000 */  sw    $t8, ($t2)
/* 019170 70018570 8FAB0028 */  lw    $t3, 0x28($sp)
/* 019174 70018574 15A00002 */  bnez  $t5, .L70018580
/* 019178 70018578 00000000 */   nop   
/* 01917C 7001857C 0007000D */  break 7
.L70018580:
/* 019180 70018580 2401FFFF */  li    $at, -1
/* 019184 70018584 15A10004 */  bne   $t5, $at, .L70018598
/* 019188 70018588 3C018000 */   lui   $at, 0x8000
/* 01918C 7001858C 15810002 */  bne   $t4, $at, .L70018598
/* 019190 70018590 00000000 */   nop   
/* 019194 70018594 0006000D */  break 6
.L70018598:
/* 019198 70018598 8D6C0008 */  lw    $t4, 8($t3)
/* 01919C 7001859C 258D0001 */  addiu $t5, $t4, 1
/* 0191A0 700185A0 AD6D0008 */  sw    $t5, 8($t3)
/* 0191A4 700185A4 8FAE0028 */  lw    $t6, 0x28($sp)
/* 0191A8 700185A8 8DCF0000 */  lw    $t7, ($t6)
/* 0191AC 700185AC 8DE90000 */  lw    $t1, ($t7)
/* 0191B0 700185B0 11200008 */  beqz  $t1, .L700185D4
/* 0191B4 700185B4 00000000 */   nop   
/* 0191B8 700185B8 0C00423D */  jal   __osPopThread
/* 0191BC 700185BC 01C02025 */   move  $a0, $t6
/* 0191C0 700185C0 00408025 */  move  $s0, $v0
/* 0191C4 700185C4 3C048002 */  lui   $a0, %hi(__osRunQueue)
/* 0191C8 700185C8 24847728 */  addiu $a0, %lo(__osRunQueue) # addiu $a0, $a0, 0x7728
/* 0191CC 700185CC 0C00422B */  jal   __osEnqueueThread
/* 0191D0 700185D0 02002825 */   move  $a1, $s0
.L700185D4:
/* 0191D4 700185D4 8FBF001C */  lw    $ra, 0x1c($sp)
/* 0191D8 700185D8 8FB00018 */  lw    $s0, 0x18($sp)
/* 0191DC 700185DC 27BD0030 */  addiu $sp, $sp, 0x30
/* 0191E0 700185E0 03E00008 */  jr    $ra
/* 0191E4 700185E4 00000000 */   nop   

/* 0191E8 700185E8 00000000 */  nop   
/* 0191EC 700185EC 00000000 */  nop   
