# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alLoadParam
/* 01A6B0 70019AB0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01A6B4 70019AB4 24010004 */  li    $at, 4
/* 01A6B8 70019AB8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 01A6BC 70019ABC 10A10055 */  beq   $a1, $at, .L70019C14
/* 01A6C0 70019AC0 00803825 */   move  $a3, $a0
/* 01A6C4 70019AC4 24010005 */  li    $at, 5
/* 01A6C8 70019AC8 54A1006B */  bnel  $a1, $at, .L70019C78
/* 01A6CC 70019ACC 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01A6D0 70019AD0 AC860028 */  sw    $a2, 0x28($a0)
/* 01A6D4 70019AD4 8CCE0000 */  lw    $t6, ($a2)
/* 01A6D8 70019AD8 AC800038 */  sw    $zero, 0x38($a0)
/* 01A6DC 70019ADC 3C0F7002 */  lui   $t7, %hi(alAdpcmPull) # $t7, 0x7002
/* 01A6E0 70019AE0 AC8E0044 */  sw    $t6, 0x44($a0)
/* 01A6E4 70019AE4 90C20008 */  lbu   $v0, 8($a2)
/* 01A6E8 70019AE8 50400007 */  beql  $v0, $zero, .L70019B08
/* 01A6EC 70019AEC 8CE20028 */   lw    $v0, 0x28($a3)
/* 01A6F0 70019AF0 24040001 */  li    $a0, 1
/* 01A6F4 70019AF4 10440034 */  beq   $v0, $a0, .L70019BC8
/* 01A6F8 70019AF8 3C087002 */   lui   $t0, %hi(alRaw16Pull) # $t0, 0x7002
/* 01A6FC 70019AFC 1000005E */  b     .L70019C78
/* 01A700 70019B00 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01A704 70019B04 8CE20028 */  lw    $v0, 0x28($a3)
.L70019B08:
/* 01A708 70019B08 25EFA15C */  addiu $t7, %lo(alAdpcmPull) # addiu $t7, $t7, -0x5ea4
/* 01A70C 70019B0C ACEF0004 */  sw    $t7, 4($a3)
/* 01A710 70019B10 8C580004 */  lw    $t8, 4($v0)
/* 01A714 70019B14 24050009 */  li    $a1, 9
/* 01A718 70019B18 0305001A */  div   $zero, $t8, $a1
/* 01A71C 70019B1C 0000C812 */  mflo  $t9
/* 01A720 70019B20 14A00002 */  bnez  $a1, .L70019B2C
/* 01A724 70019B24 00000000 */   nop   
/* 01A728 70019B28 0007000D */  break 7
.L70019B2C:
/* 01A72C 70019B2C 2401FFFF */  li    $at, -1
/* 01A730 70019B30 14A10004 */  bne   $a1, $at, .L70019B44
/* 01A734 70019B34 3C018000 */   lui   $at, 0x8000
/* 01A738 70019B38 17010002 */  bne   $t8, $at, .L70019B44
/* 01A73C 70019B3C 00000000 */   nop   
/* 01A740 70019B40 0006000D */  break 6
.L70019B44:
/* 01A744 70019B44 03250019 */  multu $t9, $a1
/* 01A748 70019B48 00004012 */  mflo  $t0
/* 01A74C 70019B4C AC480004 */  sw    $t0, 4($v0)
/* 01A750 70019B50 8CE20028 */  lw    $v0, 0x28($a3)
/* 01A754 70019B54 8C440010 */  lw    $a0, 0x10($v0)
/* 01A758 70019B58 8C890000 */  lw    $t1, ($a0)
/* 01A75C 70019B5C 8C8B0004 */  lw    $t3, 4($a0)
/* 01A760 70019B60 00095100 */  sll   $t2, $t1, 4
/* 01A764 70019B64 014B0019 */  multu $t2, $t3
/* 01A768 70019B68 00006012 */  mflo  $t4
/* 01A76C 70019B6C ACEC002C */  sw    $t4, 0x2c($a3)
/* 01A770 70019B70 8C43000C */  lw    $v1, 0xc($v0)
/* 01A774 70019B74 50600011 */  beql  $v1, $zero, .L70019BBC
/* 01A778 70019B78 ACE00024 */   sw    $zero, 0x24($a3)
/* 01A77C 70019B7C 8C6D0000 */  lw    $t5, ($v1)
/* 01A780 70019B80 8CE50018 */  lw    $a1, 0x18($a3)
/* 01A784 70019B84 24060020 */  li    $a2, 32
/* 01A788 70019B88 ACED001C */  sw    $t5, 0x1c($a3)
/* 01A78C 70019B8C 8C4E000C */  lw    $t6, 0xc($v0)
/* 01A790 70019B90 8DCF0004 */  lw    $t7, 4($t6)
/* 01A794 70019B94 ACEF0020 */  sw    $t7, 0x20($a3)
/* 01A798 70019B98 8C58000C */  lw    $t8, 0xc($v0)
/* 01A79C 70019B9C 8F190008 */  lw    $t9, 8($t8)
/* 01A7A0 70019BA0 ACF90024 */  sw    $t9, 0x24($a3)
/* 01A7A4 70019BA4 8C44000C */  lw    $a0, 0xc($v0)
/* 01A7A8 70019BA8 0C0075A4 */  jal   alCopy
/* 01A7AC 70019BAC 2484000C */   addiu $a0, $a0, 0xc
/* 01A7B0 70019BB0 10000031 */  b     .L70019C78
/* 01A7B4 70019BB4 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01A7B8 70019BB8 ACE00024 */  sw    $zero, 0x24($a3)
.L70019BBC:
/* 01A7BC 70019BBC ACE00020 */  sw    $zero, 0x20($a3)
/* 01A7C0 70019BC0 1000002C */  b     .L70019C74
/* 01A7C4 70019BC4 ACE0001C */   sw    $zero, 0x1c($a3)
.L70019BC8:
/* 01A7C8 70019BC8 8CE20028 */  lw    $v0, 0x28($a3)
/* 01A7CC 70019BCC 25089C84 */  addiu $t0, %lo(alRaw16Pull) # addiu $t0, $t0, -0x637c
/* 01A7D0 70019BD0 ACE80004 */  sw    $t0, 4($a3)
/* 01A7D4 70019BD4 8C43000C */  lw    $v1, 0xc($v0)
/* 01A7D8 70019BD8 5060000B */  beql  $v1, $zero, .L70019C08
/* 01A7DC 70019BDC ACE00024 */   sw    $zero, 0x24($a3)
/* 01A7E0 70019BE0 8C690000 */  lw    $t1, ($v1)
/* 01A7E4 70019BE4 ACE9001C */  sw    $t1, 0x1c($a3)
/* 01A7E8 70019BE8 8C4A000C */  lw    $t2, 0xc($v0)
/* 01A7EC 70019BEC 8D4B0004 */  lw    $t3, 4($t2)
/* 01A7F0 70019BF0 ACEB0020 */  sw    $t3, 0x20($a3)
/* 01A7F4 70019BF4 8C4C000C */  lw    $t4, 0xc($v0)
/* 01A7F8 70019BF8 8D8D0008 */  lw    $t5, 8($t4)
/* 01A7FC 70019BFC 1000001D */  b     .L70019C74
/* 01A800 70019C00 ACED0024 */   sw    $t5, 0x24($a3)
/* 01A804 70019C04 ACE00024 */  sw    $zero, 0x24($a3)
.L70019C08:
/* 01A808 70019C08 ACE00020 */  sw    $zero, 0x20($a3)
/* 01A80C 70019C0C 10000019 */  b     .L70019C74
/* 01A810 70019C10 ACE0001C */   sw    $zero, 0x1c($a3)
.L70019C14:
/* 01A814 70019C14 8CE20028 */  lw    $v0, 0x28($a3)
/* 01A818 70019C18 24040001 */  li    $a0, 1
/* 01A81C 70019C1C ACE0003C */  sw    $zero, 0x3c($a3)
/* 01A820 70019C20 ACE40040 */  sw    $a0, 0x40($a3)
/* 01A824 70019C24 10400013 */  beqz  $v0, .L70019C74
/* 01A828 70019C28 ACE00038 */   sw    $zero, 0x38($a3)
/* 01A82C 70019C2C 8C4E0000 */  lw    $t6, ($v0)
/* 01A830 70019C30 ACEE0044 */  sw    $t6, 0x44($a3)
/* 01A834 70019C34 90430008 */  lbu   $v1, 8($v0)
/* 01A838 70019C38 14600007 */  bnez  $v1, .L70019C58
/* 01A83C 70019C3C 00000000 */   nop   
/* 01A840 70019C40 8C43000C */  lw    $v1, 0xc($v0)
/* 01A844 70019C44 5060000C */  beql  $v1, $zero, .L70019C78
/* 01A848 70019C48 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01A84C 70019C4C 8C6F0008 */  lw    $t7, 8($v1)
/* 01A850 70019C50 10000008 */  b     .L70019C74
/* 01A854 70019C54 ACEF0024 */   sw    $t7, 0x24($a3)
.L70019C58:
/* 01A858 70019C58 54830007 */  bnel  $a0, $v1, .L70019C78
/* 01A85C 70019C5C 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01A860 70019C60 8C43000C */  lw    $v1, 0xc($v0)
/* 01A864 70019C64 50600004 */  beql  $v1, $zero, .L70019C78
/* 01A868 70019C68 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01A86C 70019C6C 8C780008 */  lw    $t8, 8($v1)
/* 01A870 70019C70 ACF80024 */  sw    $t8, 0x24($a3)
.L70019C74:
/* 01A874 70019C74 8FBF0014 */  lw    $ra, 0x14($sp)
.L70019C78:
/* 01A878 70019C78 27BD0018 */  addiu $sp, $sp, 0x18
/* 01A87C 70019C7C 03E00008 */  jr    $ra
/* 01A880 70019C80 00000000 */   nop   

glabel alRaw16Pull
/* 01A884 70019C84 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 01A888 70019C88 8FA80060 */  lw    $t0, 0x60($sp)
/* 01A88C 70019C8C AFB30020 */  sw    $s3, 0x20($sp)
/* 01A890 70019C90 AFB00014 */  sw    $s0, 0x14($sp)
/* 01A894 70019C94 00808025 */  move  $s0, $a0
/* 01A898 70019C98 00C09825 */  move  $s3, $a2
/* 01A89C 70019C9C AFBF0024 */  sw    $ra, 0x24($sp)
/* 01A8A0 70019CA0 AFB2001C */  sw    $s2, 0x1c($sp)
/* 01A8A4 70019CA4 AFB10018 */  sw    $s1, 0x18($sp)
/* 01A8A8 70019CA8 AFA7005C */  sw    $a3, 0x5c($sp)
/* 01A8AC 70019CAC 00A05025 */  move  $t2, $a1
/* 01A8B0 70019CB0 14C00003 */  bnez  $a2, .L70019CC0
/* 01A8B4 70019CB4 01004825 */   move  $t1, $t0
/* 01A8B8 70019CB8 100000D6 */  b     .L7001A014
/* 01A8BC 70019CBC 01001025 */   move  $v0, $t0
.L70019CC0:
/* 01A8C0 70019CC0 8E020038 */  lw    $v0, 0x38($s0)
/* 01A8C4 70019CC4 8E030020 */  lw    $v1, 0x20($s0)
/* 01A8C8 70019CC8 00537021 */  addu  $t6, $v0, $s3
/* 01A8CC 70019CCC 006E082B */  sltu  $at, $v1, $t6
/* 01A8D0 70019CD0 50200084 */  beql  $at, $zero, .L70019EE4
/* 01A8D4 70019CD4 8E020028 */   lw    $v0, 0x28($s0)
/* 01A8D8 70019CD8 8E0F0024 */  lw    $t7, 0x24($s0)
/* 01A8DC 70019CDC 00629023 */  subu  $s2, $v1, $v0
/* 01A8E0 70019CE0 51E00080 */  beql  $t7, $zero, .L70019EE4
/* 01A8E4 70019CE4 8E020028 */   lw    $v0, 0x28($s0)
/* 01A8E8 70019CE8 1A40001E */  blez  $s2, .L70019D64
/* 01A8EC 70019CEC 00128840 */   sll   $s1, $s2, 1
/* 01A8F0 70019CF0 8E040044 */  lw    $a0, 0x44($s0)
/* 01A8F4 70019CF4 8E060034 */  lw    $a2, 0x34($s0)
/* 01A8F8 70019CF8 AFAA0054 */  sw    $t2, 0x54($sp)
/* 01A8FC 70019CFC 8E190030 */  lw    $t9, 0x30($s0)
/* 01A900 70019D00 02202825 */  move  $a1, $s1
/* 01A904 70019D04 0320F809 */  jalr  $t9
/* 01A908 70019D08 00000000 */  nop   
/* 01A90C 70019D0C 8FAA0054 */  lw    $t2, 0x54($sp)
/* 01A910 70019D10 30460007 */  andi  $a2, $v0, 7
/* 01A914 70019D14 8FA80060 */  lw    $t0, 0x60($sp)
/* 01A918 70019D18 85580000 */  lh    $t8, ($t2)
/* 01A91C 70019D1C 02263821 */  addu  $a3, $s1, $a2
/* 01A920 70019D20 30ED0007 */  andi  $t5, $a3, 7
/* 01A924 70019D24 00ED7023 */  subu  $t6, $a3, $t5
/* 01A928 70019D28 3C010800 */  lui   $at, 0x800
/* 01A92C 70019D2C 330BFFFF */  andi  $t3, $t8, 0xffff
/* 01A930 70019D30 01616025 */  or    $t4, $t3, $at
/* 01A934 70019D34 25CF0008 */  addiu $t7, $t6, 8
/* 01A938 70019D38 25090008 */  addiu $t1, $t0, 8
/* 01A93C 70019D3C 31F9FFFF */  andi  $t9, $t7, 0xffff
/* 01A940 70019D40 01202025 */  move  $a0, $t1
/* 01A944 70019D44 00465823 */  subu  $t3, $v0, $a2
/* 01A948 70019D48 3C180400 */  lui   $t8, 0x400
/* 01A94C 70019D4C AD190004 */  sw    $t9, 4($t0)
/* 01A950 70019D50 AD0C0000 */  sw    $t4, ($t0)
/* 01A954 70019D54 AC8B0004 */  sw    $t3, 4($a0)
/* 01A958 70019D58 AC980000 */  sw    $t8, ($a0)
/* 01A95C 70019D5C 10000002 */  b     .L70019D68
/* 01A960 70019D60 25290008 */   addiu $t1, $t1, 8
.L70019D64:
/* 01A964 70019D64 00003025 */  move  $a2, $zero
.L70019D68:
/* 01A968 70019D68 854C0000 */  lh    $t4, ($t2)
/* 01A96C 70019D6C 0253082A */  slt   $at, $s2, $s3
/* 01A970 70019D70 01866821 */  addu  $t5, $t4, $a2
/* 01A974 70019D74 A54D0000 */  sh    $t5, ($t2)
/* 01A978 70019D78 8E0E0028 */  lw    $t6, 0x28($s0)
/* 01A97C 70019D7C 8E02001C */  lw    $v0, 0x1c($s0)
/* 01A980 70019D80 8DCF0000 */  lw    $t7, ($t6)
/* 01A984 70019D84 0002C840 */  sll   $t9, $v0, 1
/* 01A988 70019D88 AE020038 */  sw    $v0, 0x38($s0)
/* 01A98C 70019D8C 01F9C021 */  addu  $t8, $t7, $t9
/* 01A990 70019D90 AE180044 */  sw    $t8, 0x44($s0)
/* 01A994 70019D94 10200049 */  beqz  $at, .L70019EBC
/* 01A998 70019D98 85480000 */   lh    $t0, ($t2)
/* 01A99C 70019D9C 8E020024 */  lw    $v0, 0x24($s0)
.L70019DA0:
/* 01A9A0 70019DA0 2401FFFF */  li    $at, -1
/* 01A9A4 70019DA4 01114021 */  addu  $t0, $t0, $s1
/* 01A9A8 70019DA8 10410004 */  beq   $v0, $at, .L70019DBC
/* 01A9AC 70019DAC 02729823 */   subu  $s3, $s3, $s2
/* 01A9B0 70019DB0 10400002 */  beqz  $v0, .L70019DBC
/* 01A9B4 70019DB4 244BFFFF */   addiu $t3, $v0, -1
/* 01A9B8 70019DB8 AE0B0024 */  sw    $t3, 0x24($s0)
.L70019DBC:
/* 01A9BC 70019DBC 8E0C0020 */  lw    $t4, 0x20($s0)
/* 01A9C0 70019DC0 8E0D001C */  lw    $t5, 0x1c($s0)
/* 01A9C4 70019DC4 018D1023 */  subu  $v0, $t4, $t5
/* 01A9C8 70019DC8 0262082B */  sltu  $at, $s3, $v0
/* 01A9CC 70019DCC 10200003 */  beqz  $at, .L70019DDC
/* 01A9D0 70019DD0 00409025 */   move  $s2, $v0
/* 01A9D4 70019DD4 10000001 */  b     .L70019DDC
/* 01A9D8 70019DD8 02609025 */   move  $s2, $s3
.L70019DDC:
/* 01A9DC 70019DDC 8E040044 */  lw    $a0, 0x44($s0)
/* 01A9E0 70019DE0 8E060034 */  lw    $a2, 0x34($s0)
/* 01A9E4 70019DE4 AFA9004C */  sw    $t1, 0x4c($sp)
/* 01A9E8 70019DE8 AFA8002C */  sw    $t0, 0x2c($sp)
/* 01A9EC 70019DEC 8E190030 */  lw    $t9, 0x30($s0)
/* 01A9F0 70019DF0 00128840 */  sll   $s1, $s2, 1
/* 01A9F4 70019DF4 02202825 */  move  $a1, $s1
/* 01A9F8 70019DF8 0320F809 */  jalr  $t9
/* 01A9FC 70019DFC 00000000 */  nop   
/* 01AA00 70019E00 8FA8002C */  lw    $t0, 0x2c($sp)
/* 01AA04 70019E04 30450007 */  andi  $a1, $v0, 7
/* 01AA08 70019E08 8FA9004C */  lw    $t1, 0x4c($sp)
/* 01AA0C 70019E0C 31030007 */  andi  $v1, $t0, 7
/* 01AA10 70019E10 10600004 */  beqz  $v1, .L70019E24
/* 01AA14 70019E14 02253821 */   addu  $a3, $s1, $a1
/* 01AA18 70019E18 240E0008 */  li    $t6, 8
/* 01AA1C 70019E1C 10000002 */  b     .L70019E28
/* 01AA20 70019E20 01C33023 */   subu  $a2, $t6, $v1
.L70019E24:
/* 01AA24 70019E24 00003025 */  move  $a2, $zero
.L70019E28:
/* 01AA28 70019E28 01067821 */  addu  $t7, $t0, $a2
/* 01AA2C 70019E2C 30EC0007 */  andi  $t4, $a3, 7
/* 01AA30 70019E30 00EC6823 */  subu  $t5, $a3, $t4
/* 01AA34 70019E34 31F8FFFF */  andi  $t8, $t7, 0xffff
/* 01AA38 70019E38 01201825 */  move  $v1, $t1
/* 01AA3C 70019E3C 3C010800 */  lui   $at, 0x800
/* 01AA40 70019E40 03015825 */  or    $t3, $t8, $at
/* 01AA44 70019E44 25290008 */  addiu $t1, $t1, 8
/* 01AA48 70019E48 25B90008 */  addiu $t9, $t5, 8
/* 01AA4C 70019E4C 332EFFFF */  andi  $t6, $t9, 0xffff
/* 01AA50 70019E50 01202025 */  move  $a0, $t1
/* 01AA54 70019E54 AC6E0004 */  sw    $t6, 4($v1)
/* 01AA58 70019E58 AC6B0000 */  sw    $t3, ($v1)
/* 01AA5C 70019E5C 0045C023 */  subu  $t8, $v0, $a1
/* 01AA60 70019E60 3C0F0400 */  lui   $t7, 0x400
/* 01AA64 70019E64 AC8F0000 */  sw    $t7, ($a0)
/* 01AA68 70019E68 AC980004 */  sw    $t8, 4($a0)
/* 01AA6C 70019E6C 14A00002 */  bnez  $a1, .L70019E78
/* 01AA70 70019E70 25290008 */   addiu $t1, $t1, 8
/* 01AA74 70019E74 10C0000E */  beqz  $a2, .L70019EB0
.L70019E78:
/* 01AA78 70019E78 01055821 */   addu  $t3, $t0, $a1
/* 01AA7C 70019E7C 3C0100FF */  lui   $at, (0x00FFFFFF >> 16) # lui $at, 0xff
/* 01AA80 70019E80 3421FFFF */  ori   $at, (0x00FFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01AA84 70019E84 01666021 */  addu  $t4, $t3, $a2
/* 01AA88 70019E88 01816824 */  and   $t5, $t4, $at
/* 01AA8C 70019E8C 01201025 */  move  $v0, $t1
/* 01AA90 70019E90 3C010A00 */  lui   $at, 0xa00
/* 01AA94 70019E94 00087C00 */  sll   $t7, $t0, 0x10
/* 01AA98 70019E98 3238FFFF */  andi  $t8, $s1, 0xffff
/* 01AA9C 70019E9C 01F85825 */  or    $t3, $t7, $t8
/* 01AAA0 70019EA0 01A1C825 */  or    $t9, $t5, $at
/* 01AAA4 70019EA4 AC590000 */  sw    $t9, ($v0)
/* 01AAA8 70019EA8 AC4B0004 */  sw    $t3, 4($v0)
/* 01AAAC 70019EAC 25290008 */  addiu $t1, $t1, 8
.L70019EB0:
/* 01AAB0 70019EB0 0253082A */  slt   $at, $s2, $s3
/* 01AAB4 70019EB4 5420FFBA */  bnezl $at, .L70019DA0
/* 01AAB8 70019EB8 8E020024 */   lw    $v0, 0x24($s0)
.L70019EBC:
/* 01AABC 70019EBC 8E0C0038 */  lw    $t4, 0x38($s0)
/* 01AAC0 70019EC0 8E190044 */  lw    $t9, 0x44($s0)
/* 01AAC4 70019EC4 00137040 */  sll   $t6, $s3, 1
/* 01AAC8 70019EC8 01936821 */  addu  $t5, $t4, $s3
/* 01AACC 70019ECC 032E7821 */  addu  $t7, $t9, $t6
/* 01AAD0 70019ED0 AE0D0038 */  sw    $t5, 0x38($s0)
/* 01AAD4 70019ED4 AE0F0044 */  sw    $t7, 0x44($s0)
/* 01AAD8 70019ED8 1000004E */  b     .L7001A014
/* 01AADC 70019EDC 01201025 */   move  $v0, $t1
/* 01AAE0 70019EE0 8E020028 */  lw    $v0, 0x28($s0)
.L70019EE4:
/* 01AAE4 70019EE4 8E040044 */  lw    $a0, 0x44($s0)
/* 01AAE8 70019EE8 00138840 */  sll   $s1, $s3, 1
/* 01AAEC 70019EEC 8C580000 */  lw    $t8, ($v0)
/* 01AAF0 70019EF0 8C4C0004 */  lw    $t4, 4($v0)
/* 01AAF4 70019EF4 00911821 */  addu  $v1, $a0, $s1
/* 01AAF8 70019EF8 00785823 */  subu  $t3, $v1, $t8
/* 01AAFC 70019EFC 016C9023 */  subu  $s2, $t3, $t4
/* 01AB00 70019F00 06430003 */  bgezl $s2, .L70019F10
/* 01AB04 70019F04 0232082A */   slt   $at, $s1, $s2
/* 01AB08 70019F08 00009025 */  move  $s2, $zero
/* 01AB0C 70019F0C 0232082A */  slt   $at, $s1, $s2
.L70019F10:
/* 01AB10 70019F10 50200003 */  beql  $at, $zero, .L70019F20
/* 01AB14 70019F14 0251082A */   slt   $at, $s2, $s1
/* 01AB18 70019F18 02209025 */  move  $s2, $s1
/* 01AB1C 70019F1C 0251082A */  slt   $at, $s2, $s1
.L70019F20:
/* 01AB20 70019F20 5020002C */  beql  $at, $zero, .L70019FD4
/* 01AB24 70019F24 AE030044 */   sw    $v1, 0x44($s0)
/* 01AB28 70019F28 1A60001F */  blez  $s3, .L70019FA8
/* 01AB2C 70019F2C 00003025 */   move  $a2, $zero
/* 01AB30 70019F30 8E060034 */  lw    $a2, 0x34($s0)
/* 01AB34 70019F34 02322823 */  subu  $a1, $s1, $s2
/* 01AB38 70019F38 AFA50048 */  sw    $a1, 0x48($sp)
/* 01AB3C 70019F3C AFAA0054 */  sw    $t2, 0x54($sp)
/* 01AB40 70019F40 8E190030 */  lw    $t9, 0x30($s0)
/* 01AB44 70019F44 0320F809 */  jalr  $t9
/* 01AB48 70019F48 00000000 */  nop   
/* 01AB4C 70019F4C 8FAA0054 */  lw    $t2, 0x54($sp)
/* 01AB50 70019F50 8FA70048 */  lw    $a3, 0x48($sp)
/* 01AB54 70019F54 30460007 */  andi  $a2, $v0, 7
/* 01AB58 70019F58 854D0000 */  lh    $t5, ($t2)
/* 01AB5C 70019F5C 8FA80060 */  lw    $t0, 0x60($sp)
/* 01AB60 70019F60 00E63821 */  addu  $a3, $a3, $a2
/* 01AB64 70019F64 30F80007 */  andi  $t8, $a3, 7
/* 01AB68 70019F68 00F85823 */  subu  $t3, $a3, $t8
/* 01AB6C 70019F6C 3C010800 */  lui   $at, 0x800
/* 01AB70 70019F70 31AEFFFF */  andi  $t6, $t5, 0xffff
/* 01AB74 70019F74 01C17825 */  or    $t7, $t6, $at
/* 01AB78 70019F78 256C0008 */  addiu $t4, $t3, 8
/* 01AB7C 70019F7C 25090008 */  addiu $t1, $t0, 8
/* 01AB80 70019F80 3199FFFF */  andi  $t9, $t4, 0xffff
/* 01AB84 70019F84 01202025 */  move  $a0, $t1
/* 01AB88 70019F88 00467023 */  subu  $t6, $v0, $a2
/* 01AB8C 70019F8C 3C0D0400 */  lui   $t5, 0x400
/* 01AB90 70019F90 AD190004 */  sw    $t9, 4($t0)
/* 01AB94 70019F94 AD0F0000 */  sw    $t7, ($t0)
/* 01AB98 70019F98 AC8E0004 */  sw    $t6, 4($a0)
/* 01AB9C 70019F9C AC8D0000 */  sw    $t5, ($a0)
/* 01ABA0 70019FA0 10000001 */  b     .L70019FA8
/* 01ABA4 70019FA4 25290008 */   addiu $t1, $t1, 8
.L70019FA8:
/* 01ABA8 70019FA8 854F0000 */  lh    $t7, ($t2)
/* 01ABAC 70019FAC 01E6C021 */  addu  $t8, $t7, $a2
/* 01ABB0 70019FB0 A5580000 */  sh    $t8, ($t2)
/* 01ABB4 70019FB4 8E0B0038 */  lw    $t3, 0x38($s0)
/* 01ABB8 70019FB8 8E190044 */  lw    $t9, 0x44($s0)
/* 01ABBC 70019FBC 01736021 */  addu  $t4, $t3, $s3
/* 01ABC0 70019FC0 03316821 */  addu  $t5, $t9, $s1
/* 01ABC4 70019FC4 AE0C0038 */  sw    $t4, 0x38($s0)
/* 01ABC8 70019FC8 10000002 */  b     .L70019FD4
/* 01ABCC 70019FCC AE0D0044 */   sw    $t5, 0x44($s0)
/* 01ABD0 70019FD0 AE030044 */  sw    $v1, 0x44($s0)
.L70019FD4:
/* 01ABD4 70019FD4 1240000E */  beqz  $s2, .L7001A010
/* 01ABD8 70019FD8 02321823 */   subu  $v1, $s1, $s2
/* 01ABDC 70019FDC 04610002 */  bgez  $v1, .L70019FE8
/* 01ABE0 70019FE0 01201025 */   move  $v0, $t1
/* 01ABE4 70019FE4 00001825 */  move  $v1, $zero
.L70019FE8:
/* 01ABE8 70019FE8 854E0000 */  lh    $t6, ($t2)
/* 01ABEC 70019FEC 3C0100FF */  lui   $at, (0x00FFFFFF >> 16) # lui $at, 0xff
/* 01ABF0 70019FF0 3421FFFF */  ori   $at, (0x00FFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01ABF4 70019FF4 01C37821 */  addu  $t7, $t6, $v1
/* 01ABF8 70019FF8 01E1C024 */  and   $t8, $t7, $at
/* 01ABFC 70019FFC 3C010200 */  lui   $at, 0x200
/* 01AC00 7001A000 03015825 */  or    $t3, $t8, $at
/* 01AC04 7001A004 AC4B0000 */  sw    $t3, ($v0)
/* 01AC08 7001A008 AC520004 */  sw    $s2, 4($v0)
/* 01AC0C 7001A00C 25290008 */  addiu $t1, $t1, 8
.L7001A010:
/* 01AC10 7001A010 01201025 */  move  $v0, $t1
.L7001A014:
/* 01AC14 7001A014 8FBF0024 */  lw    $ra, 0x24($sp)
/* 01AC18 7001A018 8FB00014 */  lw    $s0, 0x14($sp)
/* 01AC1C 7001A01C 8FB10018 */  lw    $s1, 0x18($sp)
/* 01AC20 7001A020 8FB2001C */  lw    $s2, 0x1c($sp)
/* 01AC24 7001A024 8FB30020 */  lw    $s3, 0x20($sp)
/* 01AC28 7001A028 03E00008 */  jr    $ra
/* 01AC2C 7001A02C 27BD0050 */   addiu $sp, $sp, 0x50

glabel ultra_7001A030
/* 01AC30 7001A030 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01AC34 7001A034 AFB3002C */  sw    $s3, 0x2c($sp)
/* 01AC38 7001A038 AFB50028 */  sw    $s5, 0x28($sp)
/* 01AC3C 7001A03C 00137400 */  sll   $t6, $s3, 0x10
/* 01AC40 7001A040 0015C400 */  sll   $t8, $s5, 0x10
/* 01AC44 7001A044 0018AC03 */  sra   $s5, $t8, 0x10
/* 01AC48 7001A048 000E9C03 */  sra   $s3, $t6, 0x10
/* 01AC4C 7001A04C 1A20001A */  blez  $s1, .L7001A0B8
/* 01AC50 7001A050 AFBF0014 */   sw    $ra, 0x14($sp)
/* 01AC54 7001A054 8E590030 */  lw    $t9, 0x30($s2)
/* 01AC58 7001A058 8E440044 */  lw    $a0, 0x44($s2)
/* 01AC5C 7001A05C 02202825 */  move  $a1, $s1
/* 01AC60 7001A060 0320F809 */  jalr  $t9
/* 01AC64 7001A064 8E460034 */  lw    $a2, 0x34($s2)
/* 01AC68 7001A068 30460007 */  andi  $a2, $v0, 7
/* 01AC6C 7001A06C 02268821 */  addu  $s1, $s1, $a2
/* 01AC70 7001A070 326EFFFF */  andi  $t6, $s3, 0xffff
/* 01AC74 7001A074 3C010800 */  lui   $at, 0x800
/* 01AC78 7001A078 01C17825 */  or    $t7, $t6, $at
/* 01AC7C 7001A07C 32380007 */  andi  $t8, $s1, 7
/* 01AC80 7001A080 02002025 */  move  $a0, $s0
/* 01AC84 7001A084 0238C823 */  subu  $t9, $s1, $t8
/* 01AC88 7001A088 272E0008 */  addiu $t6, $t9, 8
/* 01AC8C 7001A08C AC8F0000 */  sw    $t7, ($a0)
/* 01AC90 7001A090 26100008 */  addiu $s0, $s0, 8
/* 01AC94 7001A094 31CFFFFF */  andi  $t7, $t6, 0xffff
/* 01AC98 7001A098 02002825 */  move  $a1, $s0
/* 01AC9C 7001A09C AC8F0004 */  sw    $t7, 4($a0)
/* 01ACA0 7001A0A0 0046C823 */  subu  $t9, $v0, $a2
/* 01ACA4 7001A0A4 3C180400 */  lui   $t8, 0x400
/* 01ACA8 7001A0A8 ACB80000 */  sw    $t8, ($a1)
/* 01ACAC 7001A0AC ACB90004 */  sw    $t9, 4($a1)
/* 01ACB0 7001A0B0 10000002 */  b     .L7001A0BC
/* 01ACB4 7001A0B4 26100008 */   addiu $s0, $s0, 8
.L7001A0B8:
/* 01ACB8 7001A0B8 00003025 */  move  $a2, $zero
.L7001A0BC:
/* 01ACBC 7001A0BC 328E0002 */  andi  $t6, $s4, 2
/* 01ACC0 7001A0C0 11C00009 */  beqz  $t6, .L7001A0E8
/* 01ACC4 7001A0C4 02001025 */   move  $v0, $s0
/* 01ACC8 7001A0C8 3C0F0F00 */  lui   $t7, 0xf00
/* 01ACCC 7001A0CC AC4F0000 */  sw    $t7, ($v0)
/* 01ACD0 7001A0D0 8E580018 */  lw    $t8, 0x18($s2)
/* 01ACD4 7001A0D4 3C011FFF */  lui   $at, (0x1FFFFFFF >> 16) # lui $at, 0x1fff
/* 01ACD8 7001A0D8 3421FFFF */  ori   $at, (0x1FFFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01ACDC 7001A0DC 0301C824 */  and   $t9, $t8, $at
/* 01ACE0 7001A0E0 AC590004 */  sw    $t9, 4($v0)
/* 01ACE4 7001A0E4 26100008 */  addiu $s0, $s0, 8
.L7001A0E8:
/* 01ACE8 7001A0E8 02667021 */  addu  $t6, $s3, $a2
/* 01ACEC 7001A0EC 31CFFFFF */  andi  $t7, $t6, 0xffff
/* 01ACF0 7001A0F0 3C010800 */  lui   $at, 0x800
/* 01ACF4 7001A0F4 01E1C025 */  or    $t8, $t7, $at
/* 01ACF8 7001A0F8 02001825 */  move  $v1, $s0
/* 01ACFC 7001A0FC AC780000 */  sw    $t8, ($v1)
/* 01AD00 7001A100 00167840 */  sll   $t7, $s6, 1
/* 01AD04 7001A104 31F8FFFF */  andi  $t8, $t7, 0xffff
/* 01AD08 7001A108 00157400 */  sll   $t6, $s5, 0x10
/* 01AD0C 7001A10C 01D8C825 */  or    $t9, $t6, $t8
/* 01AD10 7001A110 328F00FF */  andi  $t7, $s4, 0xff
/* 01AD14 7001A114 26100008 */  addiu $s0, $s0, 8
/* 01AD18 7001A118 000F7400 */  sll   $t6, $t7, 0x10
/* 01AD1C 7001A11C 3C010100 */  lui   $at, 0x100
/* 01AD20 7001A120 AC790004 */  sw    $t9, 4($v1)
/* 01AD24 7001A124 01C1C025 */  or    $t8, $t6, $at
/* 01AD28 7001A128 02002025 */  move  $a0, $s0
/* 01AD2C 7001A12C AC980000 */  sw    $t8, ($a0)
/* 01AD30 7001A130 8E590014 */  lw    $t9, 0x14($s2)
/* 01AD34 7001A134 3C011FFF */  lui   $at, (0x1FFFFFFF >> 16) # lui $at, 0x1fff
/* 01AD38 7001A138 3421FFFF */  ori   $at, (0x1FFFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01AD3C 7001A13C 03217824 */  and   $t7, $t9, $at
/* 01AD40 7001A140 AC8F0004 */  sw    $t7, 4($a0)
/* 01AD44 7001A144 AE400040 */  sw    $zero, 0x40($s2)
/* 01AD48 7001A148 8FBF0014 */  lw    $ra, 0x14($sp)
/* 01AD4C 7001A14C 26100008 */  addiu $s0, $s0, 8
/* 01AD50 7001A150 02001025 */  move  $v0, $s0
/* 01AD54 7001A154 03E00008 */  jr    $ra
/* 01AD58 7001A158 27BD0018 */   addiu $sp, $sp, 0x18

glabel alAdpcmPull
/* 01AD5C 7001A15C 27BDFF50 */  addiu $sp, $sp, -0xb0
/* 01AD60 7001A160 AFB70044 */  sw    $s7, 0x44($sp)
/* 01AD64 7001A164 AFA700BC */  sw    $a3, 0xbc($sp)
/* 01AD68 7001A168 00A03825 */  move  $a3, $a1
/* 01AD6C 7001A16C 0080B825 */  move  $s7, $a0
/* 01AD70 7001A170 AFBF004C */  sw    $ra, 0x4c($sp)
/* 01AD74 7001A174 AFBE0048 */  sw    $fp, 0x48($sp)
/* 01AD78 7001A178 AFB60040 */  sw    $s6, 0x40($sp)
/* 01AD7C 7001A17C AFB5003C */  sw    $s5, 0x3c($sp)
/* 01AD80 7001A180 AFB40038 */  sw    $s4, 0x38($sp)
/* 01AD84 7001A184 AFB30034 */  sw    $s3, 0x34($sp)
/* 01AD88 7001A188 AFB20030 */  sw    $s2, 0x30($sp)
/* 01AD8C 7001A18C AFB1002C */  sw    $s1, 0x2c($sp)
/* 01AD90 7001A190 AFB00028 */  sw    $s0, 0x28($sp)
/* 01AD94 7001A194 AFA500B4 */  sw    $a1, 0xb4($sp)
/* 01AD98 7001A198 00C04025 */  move  $t0, $a2
/* 01AD9C 7001A19C 14C00003 */  bnez  $a2, .L7001A1AC
/* 01ADA0 7001A1A0 00006825 */   move  $t5, $zero
/* 01ADA4 7001A1A4 10000109 */  b     .L7001A5CC
/* 01ADA8 7001A1A8 8FA200C0 */   lw    $v0, 0xc0($sp)
.L7001A1AC:
/* 01ADAC 7001A1AC 8EEE002C */  lw    $t6, 0x2c($s7)
/* 01ADB0 7001A1B0 3C0100FF */  lui   $at, (0x00FFFFFF >> 16) # lui $at, 0xff
/* 01ADB4 7001A1B4 3421FFFF */  ori   $at, (0x00FFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01ADB8 7001A1B8 8FA500C0 */  lw    $a1, 0xc0($sp)
/* 01ADBC 7001A1BC 01C17824 */  and   $t7, $t6, $at
/* 01ADC0 7001A1C0 3C010B00 */  lui   $at, 0xb00
/* 01ADC4 7001A1C4 01E1C025 */  or    $t8, $t7, $at
/* 01ADC8 7001A1C8 ACB80000 */  sw    $t8, ($a1)
/* 01ADCC 7001A1CC 8EF90028 */  lw    $t9, 0x28($s7)
/* 01ADD0 7001A1D0 3C011FFF */  lui   $at, (0x1FFFFFFF >> 16) # lui $at, 0x1fff
/* 01ADD4 7001A1D4 3421FFFF */  ori   $at, (0x1FFFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01ADD8 7001A1D8 8F2E0010 */  lw    $t6, 0x10($t9)
/* 01ADDC 7001A1DC 24AA0008 */  addiu $t2, $a1, 8
/* 01ADE0 7001A1E0 00003025 */  move  $a2, $zero
/* 01ADE4 7001A1E4 25CF0008 */  addiu $t7, $t6, 8
/* 01ADE8 7001A1E8 01E1C024 */  and   $t8, $t7, $at
/* 01ADEC 7001A1EC ACB80004 */  sw    $t8, 4($a1)
/* 01ADF0 7001A1F0 8EE30038 */  lw    $v1, 0x38($s7)
/* 01ADF4 7001A1F4 8EE40020 */  lw    $a0, 0x20($s7)
/* 01ADF8 7001A1F8 01002825 */  move  $a1, $t0
/* 01ADFC 7001A1FC 0068C821 */  addu  $t9, $v1, $t0
/* 01AE00 7001A200 0099482B */  sltu  $t1, $a0, $t9
/* 01AE04 7001A204 11200004 */  beqz  $t1, .L7001A218
/* 01AE08 7001A208 240F0010 */   li    $t7, 16
/* 01AE0C 7001A20C 8EE90024 */  lw    $t1, 0x24($s7)
/* 01AE10 7001A210 0009702B */  sltu  $t6, $zero, $t1
/* 01AE14 7001A214 01C04825 */  move  $t1, $t6
.L7001A218:
/* 01AE18 7001A218 11200003 */  beqz  $t1, .L7001A228
/* 01AE1C 7001A21C 24010009 */   li    $at, 9
/* 01AE20 7001A220 10000001 */  b     .L7001A228
/* 01AE24 7001A224 00832823 */   subu  $a1, $a0, $v1
.L7001A228:
/* 01AE28 7001A228 8EE3003C */  lw    $v1, 0x3c($s7)
/* 01AE2C 7001A22C 01408025 */  move  $s0, $t2
/* 01AE30 7001A230 02E09025 */  move  $s2, $s7
/* 01AE34 7001A234 10600003 */  beqz  $v1, .L7001A244
/* 01AE38 7001A238 00009825 */   move  $s3, $zero
/* 01AE3C 7001A23C 10000001 */  b     .L7001A244
/* 01AE40 7001A240 01E33023 */   subu  $a2, $t7, $v1
.L7001A244:
/* 01AE44 7001A244 00A62023 */  subu  $a0, $a1, $a2
/* 01AE48 7001A248 04810002 */  bgez  $a0, .L7001A254
/* 01AE4C 7001A24C 00000000 */   nop   
/* 01AE50 7001A250 00002025 */  move  $a0, $zero
.L7001A254:
/* 01AE54 7001A254 11200081 */  beqz  $t1, .L7001A45C
/* 01AE58 7001A258 249E000F */   addiu $fp, $a0, 0xf
/* 01AE5C 7001A25C 249E000F */  addiu $fp, $a0, 0xf
/* 01AE60 7001A260 001EC103 */  sra   $t8, $fp, 4
/* 01AE64 7001A264 84F50000 */  lh    $s5, ($a3)
/* 01AE68 7001A268 8EF40040 */  lw    $s4, 0x40($s7)
/* 01AE6C 7001A26C 001848C0 */  sll   $t1, $t8, 3
/* 01AE70 7001A270 01384821 */  addu  $t1, $t1, $t8
/* 01AE74 7001A274 01208825 */  move  $s1, $t1
/* 01AE78 7001A278 AFA9005C */  sw    $t1, 0x5c($sp)
/* 01AE7C 7001A27C AFA800B8 */  sw    $t0, 0xb8($sp)
/* 01AE80 7001A280 AFA700B4 */  sw    $a3, 0xb4($sp)
/* 01AE84 7001A284 AFA5008C */  sw    $a1, 0x8c($sp)
/* 01AE88 7001A288 0300F025 */  move  $fp, $t8
/* 01AE8C 7001A28C 0C00680C */  jal   ultra_7001A030
/* 01AE90 7001A290 0080B025 */   move  $s6, $a0
/* 01AE94 7001A294 8EE3003C */  lw    $v1, 0x3c($s7)
/* 01AE98 7001A298 8FA5008C */  lw    $a1, 0x8c($sp)
/* 01AE9C 7001A29C 8FA700B4 */  lw    $a3, 0xb4($sp)
/* 01AEA0 7001A2A0 8FA800B8 */  lw    $t0, 0xb8($sp)
/* 01AEA4 7001A2A4 8FA9005C */  lw    $t1, 0x5c($sp)
/* 01AEA8 7001A2A8 10600006 */  beqz  $v1, .L7001A2C4
/* 01AEAC 7001A2AC 00405025 */   move  $t2, $v0
/* 01AEB0 7001A2B0 84F90000 */  lh    $t9, ($a3)
/* 01AEB4 7001A2B4 00037040 */  sll   $t6, $v1, 1
/* 01AEB8 7001A2B8 032E7821 */  addu  $t7, $t9, $t6
/* 01AEBC 7001A2BC 10000004 */  b     .L7001A2D0
/* 01AEC0 7001A2C0 A4EF0000 */   sh    $t7, ($a3)
.L7001A2C4:
/* 01AEC4 7001A2C4 84F80000 */  lh    $t8, ($a3)
/* 01AEC8 7001A2C8 27190020 */  addiu $t9, $t8, 0x20
/* 01AECC 7001A2CC A4F90000 */  sh    $t9, ($a3)
.L7001A2D0:
/* 01AED0 7001A2D0 8EE2001C */  lw    $v0, 0x1c($s7)
/* 01AED4 7001A2D4 8EEF0028 */  lw    $t7, 0x28($s7)
/* 01AED8 7001A2D8 00A8082A */  slt   $at, $a1, $t0
/* 01AEDC 7001A2DC 304E000F */  andi  $t6, $v0, 0xf
/* 01AEE0 7001A2E0 AEEE003C */  sw    $t6, 0x3c($s7)
/* 01AEE4 7001A2E4 8DF80000 */  lw    $t8, ($t7)
/* 01AEE8 7001A2E8 0002C902 */  srl   $t9, $v0, 4
/* 01AEEC 7001A2EC 001970C0 */  sll   $t6, $t9, 3
/* 01AEF0 7001A2F0 01D97021 */  addu  $t6, $t6, $t9
/* 01AEF4 7001A2F4 030E7821 */  addu  $t7, $t8, $t6
/* 01AEF8 7001A2F8 25F90009 */  addiu $t9, $t7, 9
/* 01AEFC 7001A2FC AEF90044 */  sw    $t9, 0x44($s7)
/* 01AF00 7001A300 AEE20038 */  sw    $v0, 0x38($s7)
/* 01AF04 7001A304 10200049 */  beqz  $at, .L7001A42C
/* 01AF08 7001A308 84E60000 */   lh    $a2, ($a3)
/* 01AF0C 7001A30C 00051840 */  sll   $v1, $a1, 1
.L7001A310:
/* 01AF10 7001A310 27D80001 */  addiu $t8, $fp, 1
/* 01AF14 7001A314 00187140 */  sll   $t6, $t8, 5
/* 01AF18 7001A318 8EE20024 */  lw    $v0, 0x24($s7)
/* 01AF1C 7001A31C 01C63821 */  addu  $a3, $t6, $a2
/* 01AF20 7001A320 2401FFE0 */  li    $at, -32
/* 01AF24 7001A324 00E17824 */  and   $t7, $a3, $at
/* 01AF28 7001A328 2401FFFF */  li    $at, -1
/* 01AF2C 7001A32C 01054023 */  subu  $t0, $t0, $a1
/* 01AF30 7001A330 01E03825 */  move  $a3, $t7
/* 01AF34 7001A334 10410004 */  beq   $v0, $at, .L7001A348
/* 01AF38 7001A338 00C33021 */   addu  $a2, $a2, $v1
/* 01AF3C 7001A33C 10400002 */  beqz  $v0, .L7001A348
/* 01AF40 7001A340 2459FFFF */   addiu $t9, $v0, -1
/* 01AF44 7001A344 AEF90024 */  sw    $t9, 0x24($s7)
.L7001A348:
/* 01AF48 7001A348 8EF80020 */  lw    $t8, 0x20($s7)
/* 01AF4C 7001A34C 8EEE001C */  lw    $t6, 0x1c($s7)
/* 01AF50 7001A350 01408025 */  move  $s0, $t2
/* 01AF54 7001A354 02E09025 */  move  $s2, $s7
/* 01AF58 7001A358 030E1023 */  subu  $v0, $t8, $t6
/* 01AF5C 7001A35C 0102082B */  sltu  $at, $t0, $v0
/* 01AF60 7001A360 10200003 */  beqz  $at, .L7001A370
/* 01AF64 7001A364 0007AC00 */   sll   $s5, $a3, 0x10
/* 01AF68 7001A368 10000002 */  b     .L7001A374
/* 01AF6C 7001A36C 01002825 */   move  $a1, $t0
.L7001A370:
/* 01AF70 7001A370 00402825 */  move  $a1, $v0
.L7001A374:
/* 01AF74 7001A374 8EEF003C */  lw    $t7, 0x3c($s7)
/* 01AF78 7001A378 0015C403 */  sra   $t8, $s5, 0x10
/* 01AF7C 7001A37C 0300A825 */  move  $s5, $t8
/* 01AF80 7001A380 00AF2021 */  addu  $a0, $a1, $t7
/* 01AF84 7001A384 2484FFF0 */  addiu $a0, $a0, -0x10
/* 01AF88 7001A388 04810002 */  bgez  $a0, .L7001A394
/* 01AF8C 7001A38C 00009825 */   move  $s3, $zero
/* 01AF90 7001A390 00002025 */  move  $a0, $zero
.L7001A394:
/* 01AF94 7001A394 8EF40040 */  lw    $s4, 0x40($s7)
/* 01AF98 7001A398 249E000F */  addiu $fp, $a0, 0xf
/* 01AF9C 7001A39C 001EC903 */  sra   $t9, $fp, 4
/* 01AFA0 7001A3A0 001948C0 */  sll   $t1, $t9, 3
/* 01AFA4 7001A3A4 01394821 */  addu  $t1, $t1, $t9
/* 01AFA8 7001A3A8 368E0002 */  ori   $t6, $s4, 2
/* 01AFAC 7001A3AC 01C0A025 */  move  $s4, $t6
/* 01AFB0 7001A3B0 01208825 */  move  $s1, $t1
/* 01AFB4 7001A3B4 AFA9005C */  sw    $t1, 0x5c($sp)
/* 01AFB8 7001A3B8 0320F025 */  move  $fp, $t9
/* 01AFBC 7001A3BC AFA800B8 */  sw    $t0, 0xb8($sp)
/* 01AFC0 7001A3C0 AFA70088 */  sw    $a3, 0x88($sp)
/* 01AFC4 7001A3C4 AFA60080 */  sw    $a2, 0x80($sp)
/* 01AFC8 7001A3C8 AFA5008C */  sw    $a1, 0x8c($sp)
/* 01AFCC 7001A3CC 0C00680C */  jal   ultra_7001A030
/* 01AFD0 7001A3D0 0080B025 */   move  $s6, $a0
/* 01AFD4 7001A3D4 8EEF003C */  lw    $t7, 0x3c($s7)
/* 01AFD8 7001A3D8 8FA70088 */  lw    $a3, 0x88($sp)
/* 01AFDC 7001A3DC 3C0100FF */  lui   $at, (0x00FFFFFF >> 16) # lui $at, 0xff
/* 01AFE0 7001A3E0 000FC840 */  sll   $t9, $t7, 1
/* 01AFE4 7001A3E4 3421FFFF */  ori   $at, (0x00FFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01AFE8 7001A3E8 0327C021 */  addu  $t8, $t9, $a3
/* 01AFEC 7001A3EC 03017024 */  and   $t6, $t8, $at
/* 01AFF0 7001A3F0 8FA5008C */  lw    $a1, 0x8c($sp)
/* 01AFF4 7001A3F4 3C010A00 */  lui   $at, 0xa00
/* 01AFF8 7001A3F8 8FA60080 */  lw    $a2, 0x80($sp)
/* 01AFFC 7001A3FC 01C17825 */  or    $t7, $t6, $at
/* 01B000 7001A400 8FA800B8 */  lw    $t0, 0xb8($sp)
/* 01B004 7001A404 8FA9005C */  lw    $t1, 0x5c($sp)
/* 01B008 7001A408 00051840 */  sll   $v1, $a1, 1
/* 01B00C 7001A40C 306EFFFF */  andi  $t6, $v1, 0xffff
/* 01B010 7001A410 AC4F0000 */  sw    $t7, ($v0)
/* 01B014 7001A414 0006C400 */  sll   $t8, $a2, 0x10
/* 01B018 7001A418 030E7825 */  or    $t7, $t8, $t6
/* 01B01C 7001A41C 00A8082A */  slt   $at, $a1, $t0
/* 01B020 7001A420 AC4F0004 */  sw    $t7, 4($v0)
/* 01B024 7001A424 1420FFBA */  bnez  $at, .L7001A310
/* 01B028 7001A428 244A0008 */   addiu $t2, $v0, 8
.L7001A42C:
/* 01B02C 7001A42C 8EF9003C */  lw    $t9, 0x3c($s7)
/* 01B030 7001A430 8EEF0038 */  lw    $t7, 0x38($s7)
/* 01B034 7001A434 01401025 */  move  $v0, $t2
/* 01B038 7001A438 0328C021 */  addu  $t8, $t9, $t0
/* 01B03C 7001A43C 330E000F */  andi  $t6, $t8, 0xf
/* 01B040 7001A440 8EF80044 */  lw    $t8, 0x44($s7)
/* 01B044 7001A444 AEEE003C */  sw    $t6, 0x3c($s7)
/* 01B048 7001A448 01E8C821 */  addu  $t9, $t7, $t0
/* 01B04C 7001A44C 03097021 */  addu  $t6, $t8, $t1
/* 01B050 7001A450 AEF90038 */  sw    $t9, 0x38($s7)
/* 01B054 7001A454 1000005D */  b     .L7001A5CC
/* 01B058 7001A458 AEEE0044 */   sw    $t6, 0x44($s7)
.L7001A45C:
/* 01B05C 7001A45C 8EE20028 */  lw    $v0, 0x28($s7)
/* 01B060 7001A460 001E7903 */  sra   $t7, $fp, 4
/* 01B064 7001A464 8EF90044 */  lw    $t9, 0x44($s7)
/* 01B068 7001A468 000F48C0 */  sll   $t1, $t7, 3
/* 01B06C 7001A46C 8C580000 */  lw    $t8, ($v0)
/* 01B070 7001A470 012F4821 */  addu  $t1, $t1, $t7
/* 01B074 7001A474 01E0F025 */  move  $fp, $t7
/* 01B078 7001A478 8C4F0004 */  lw    $t7, 4($v0)
/* 01B07C 7001A47C 03295821 */  addu  $t3, $t9, $t1
/* 01B080 7001A480 01787023 */  subu  $t6, $t3, $t8
/* 01B084 7001A484 01CF1823 */  subu  $v1, $t6, $t7
/* 01B088 7001A488 04610002 */  bgez  $v1, .L7001A494
/* 01B08C 7001A48C 001E2900 */   sll   $a1, $fp, 4
/* 01B090 7001A490 00001825 */  move  $v1, $zero
.L7001A494:
/* 01B094 7001A494 0061001A */  div   $zero, $v1, $at
/* 01B098 7001A498 00001012 */  mflo  $v0
/* 01B09C 7001A49C 00022100 */  sll   $a0, $v0, 4
/* 01B0A0 7001A4A0 00A66021 */  addu  $t4, $a1, $a2
/* 01B0A4 7001A4A4 0184082A */  slt   $at, $t4, $a0
/* 01B0A8 7001A4A8 10200002 */  beqz  $at, .L7001A4B4
/* 01B0AC 7001A4AC 01408025 */   move  $s0, $t2
/* 01B0B0 7001A4B0 01802025 */  move  $a0, $t4
.L7001A4B4:
/* 01B0B4 7001A4B4 3098000F */  andi  $t8, $a0, 0xf
/* 01B0B8 7001A4B8 00987023 */  subu  $t6, $a0, $t8
/* 01B0BC 7001A4BC 01C8082A */  slt   $at, $t6, $t0
/* 01B0C0 7001A4C0 1020002B */  beqz  $at, .L7001A570
/* 01B0C4 7001A4C4 01233023 */   subu  $a2, $t1, $v1
/* 01B0C8 7001A4C8 84F50000 */  lh    $s5, ($a3)
/* 01B0CC 7001A4CC 8EF40040 */  lw    $s4, 0x40($s7)
/* 01B0D0 7001A4D0 240D0001 */  li    $t5, 1
/* 01B0D4 7001A4D4 AFAD007C */  sw    $t5, 0x7c($sp)
/* 01B0D8 7001A4D8 AFAC0050 */  sw    $t4, 0x50($sp)
/* 01B0DC 7001A4DC AFA9005C */  sw    $t1, 0x5c($sp)
/* 01B0E0 7001A4E0 AFA800B8 */  sw    $t0, 0xb8($sp)
/* 01B0E4 7001A4E4 AFA700B4 */  sw    $a3, 0xb4($sp)
/* 01B0E8 7001A4E8 AFA40090 */  sw    $a0, 0x90($sp)
/* 01B0EC 7001A4EC 02E09025 */  move  $s2, $s7
/* 01B0F0 7001A4F0 00A4B023 */  subu  $s6, $a1, $a0
/* 01B0F4 7001A4F4 00C08825 */  move  $s1, $a2
/* 01B0F8 7001A4F8 0C00680C */  jal   ultra_7001A030
/* 01B0FC 7001A4FC 00009825 */   move  $s3, $zero
/* 01B100 7001A500 8EE3003C */  lw    $v1, 0x3c($s7)
/* 01B104 7001A504 8FA40090 */  lw    $a0, 0x90($sp)
/* 01B108 7001A508 8FA700B4 */  lw    $a3, 0xb4($sp)
/* 01B10C 7001A50C 8FA800B8 */  lw    $t0, 0xb8($sp)
/* 01B110 7001A510 8FA9005C */  lw    $t1, 0x5c($sp)
/* 01B114 7001A514 8FAC0050 */  lw    $t4, 0x50($sp)
/* 01B118 7001A518 8FAD007C */  lw    $t5, 0x7c($sp)
/* 01B11C 7001A51C 10600006 */  beqz  $v1, .L7001A538
/* 01B120 7001A520 00405025 */   move  $t2, $v0
/* 01B124 7001A524 84EF0000 */  lh    $t7, ($a3)
/* 01B128 7001A528 0003C840 */  sll   $t9, $v1, 1
/* 01B12C 7001A52C 01F9C021 */  addu  $t8, $t7, $t9
/* 01B130 7001A530 10000004 */  b     .L7001A544
/* 01B134 7001A534 A4F80000 */   sh    $t8, ($a3)
.L7001A538:
/* 01B138 7001A538 84EE0000 */  lh    $t6, ($a3)
/* 01B13C 7001A53C 25CF0020 */  addiu $t7, $t6, 0x20
/* 01B140 7001A540 A4EF0000 */  sh    $t7, ($a3)
.L7001A544:
/* 01B144 7001A544 8EF9003C */  lw    $t9, 0x3c($s7)
/* 01B148 7001A548 8EEF0038 */  lw    $t7, 0x38($s7)
/* 01B14C 7001A54C 0328C021 */  addu  $t8, $t9, $t0
/* 01B150 7001A550 330E000F */  andi  $t6, $t8, 0xf
/* 01B154 7001A554 8EF80044 */  lw    $t8, 0x44($s7)
/* 01B158 7001A558 AEEE003C */  sw    $t6, 0x3c($s7)
/* 01B15C 7001A55C 01E8C821 */  addu  $t9, $t7, $t0
/* 01B160 7001A560 03097021 */  addu  $t6, $t8, $t1
/* 01B164 7001A564 AEF90038 */  sw    $t9, 0x38($s7)
/* 01B168 7001A568 10000003 */  b     .L7001A578
/* 01B16C 7001A56C AEEE0044 */   sw    $t6, 0x44($s7)
.L7001A570:
/* 01B170 7001A570 AEE0003C */  sw    $zero, 0x3c($s7)
/* 01B174 7001A574 AEEB0044 */  sw    $t3, 0x44($s7)
.L7001A578:
/* 01B178 7001A578 10800013 */  beqz  $a0, .L7001A5C8
/* 01B17C 7001A57C 01401025 */   move  $v0, $t2
/* 01B180 7001A580 11A00005 */  beqz  $t5, .L7001A598
/* 01B184 7001A584 AEE0003C */   sw    $zero, 0x3c($s7)
/* 01B188 7001A588 01841823 */  subu  $v1, $t4, $a0
/* 01B18C 7001A58C 00037840 */  sll   $t7, $v1, 1
/* 01B190 7001A590 10000002 */  b     .L7001A59C
/* 01B194 7001A594 01E01825 */   move  $v1, $t7
.L7001A598:
/* 01B198 7001A598 00001825 */  move  $v1, $zero
.L7001A59C:
/* 01B19C 7001A59C 84F90000 */  lh    $t9, ($a3)
/* 01B1A0 7001A5A0 3C0100FF */  lui   $at, (0x00FFFFFF >> 16) # lui $at, 0xff
/* 01B1A4 7001A5A4 3421FFFF */  ori   $at, (0x00FFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01B1A8 7001A5A8 0323C021 */  addu  $t8, $t9, $v1
/* 01B1AC 7001A5AC 03017024 */  and   $t6, $t8, $at
/* 01B1B0 7001A5B0 3C010200 */  lui   $at, 0x200
/* 01B1B4 7001A5B4 01C17825 */  or    $t7, $t6, $at
/* 01B1B8 7001A5B8 0004C840 */  sll   $t9, $a0, 1
/* 01B1BC 7001A5BC AC590004 */  sw    $t9, 4($v0)
/* 01B1C0 7001A5C0 AC4F0000 */  sw    $t7, ($v0)
/* 01B1C4 7001A5C4 254A0008 */  addiu $t2, $t2, 8
.L7001A5C8:
/* 01B1C8 7001A5C8 01401025 */  move  $v0, $t2
.L7001A5CC:
/* 01B1CC 7001A5CC 8FBF004C */  lw    $ra, 0x4c($sp)
/* 01B1D0 7001A5D0 8FB00028 */  lw    $s0, 0x28($sp)
/* 01B1D4 7001A5D4 8FB1002C */  lw    $s1, 0x2c($sp)
/* 01B1D8 7001A5D8 8FB20030 */  lw    $s2, 0x30($sp)
/* 01B1DC 7001A5DC 8FB30034 */  lw    $s3, 0x34($sp)
/* 01B1E0 7001A5E0 8FB40038 */  lw    $s4, 0x38($sp)
/* 01B1E4 7001A5E4 8FB5003C */  lw    $s5, 0x3c($sp)
/* 01B1E8 7001A5E8 8FB60040 */  lw    $s6, 0x40($sp)
/* 01B1EC 7001A5EC 8FB70044 */  lw    $s7, 0x44($sp)
/* 01B1F0 7001A5F0 8FBE0048 */  lw    $fp, 0x48($sp)
/* 01B1F4 7001A5F4 03E00008 */  jr    $ra
/* 01B1F8 7001A5F8 27BD00B0 */   addiu $sp, $sp, 0xb0

