# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alMainBusParam
/* 01A560 70019960 24010002 */  li    $at, 2
/* 01A564 70019964 14A10008 */  bne   $a1, $at, .L70019988
/* 01A568 70019968 8C82001C */   lw    $v0, 0x1c($a0)
/* 01A56C 7001996C 8C8E0014 */  lw    $t6, 0x14($a0)
/* 01A570 70019970 000E7880 */  sll   $t7, $t6, 2
/* 01A574 70019974 004FC021 */  addu  $t8, $v0, $t7
/* 01A578 70019978 AF060000 */  sw    $a2, ($t8)
/* 01A57C 7001997C 8C990014 */  lw    $t9, 0x14($a0)
/* 01A580 70019980 27280001 */  addiu $t0, $t9, 1
/* 01A584 70019984 AC880014 */  sw    $t0, 0x14($a0)
.L70019988:
/* 01A588 70019988 03E00008 */  jr    $ra
/* 01A58C 7001998C 00001025 */   move  $v0, $zero

glabel alMainBusPull
/* 01A590 70019990 27BDFFB8 */  addiu $sp, $sp, -0x48
/* 01A594 70019994 8FA80058 */  lw    $t0, 0x58($sp)
/* 01A598 70019998 AFBF0044 */  sw    $ra, 0x44($sp)
/* 01A59C 7001999C AFBE0040 */  sw    $fp, 0x40($sp)
/* 01A5A0 700199A0 AFB7003C */  sw    $s7, 0x3c($sp)
/* 01A5A4 700199A4 AFB60038 */  sw    $s6, 0x38($sp)
/* 01A5A8 700199A8 AFB50034 */  sw    $s5, 0x34($sp)
/* 01A5AC 700199AC AFB40030 */  sw    $s4, 0x30($sp)
/* 01A5B0 700199B0 AFB3002C */  sw    $s3, 0x2c($sp)
/* 01A5B4 700199B4 AFB20028 */  sw    $s2, 0x28($sp)
/* 01A5B8 700199B8 AFB10024 */  sw    $s1, 0x24($sp)
/* 01A5BC 700199BC AFB00020 */  sw    $s0, 0x20($sp)
/* 01A5C0 700199C0 8C83001C */  lw    $v1, 0x1c($a0)
/* 01A5C4 700199C4 3C0E0200 */  lui   $t6, (0x02000440 >> 16) # lui $t6, 0x200
/* 01A5C8 700199C8 00061040 */  sll   $v0, $a2, 1
/* 01A5CC 700199CC 3C0F0200 */  lui   $t7, (0x02000580 >> 16) # lui $t7, 0x200
/* 01A5D0 700199D0 35CE0440 */  ori   $t6, (0x02000440 & 0xFFFF) # ori $t6, $t6, 0x440
/* 01A5D4 700199D4 35EF0580 */  ori   $t7, (0x02000580 & 0xFFFF) # ori $t7, $t7, 0x580
/* 01A5D8 700199D8 AD0E0000 */  sw    $t6, ($t0)
/* 01A5DC 700199DC AD020004 */  sw    $v0, 4($t0)
/* 01A5E0 700199E0 AD0F0008 */  sw    $t7, 8($t0)
/* 01A5E4 700199E4 AD02000C */  sw    $v0, 0xc($t0)
/* 01A5E8 700199E8 8C980014 */  lw    $t8, 0x14($a0)
/* 01A5EC 700199EC 00C0A825 */  move  $s5, $a2
/* 01A5F0 700199F0 00A0B825 */  move  $s7, $a1
/* 01A5F4 700199F4 00E0F025 */  move  $fp, $a3
/* 01A5F8 700199F8 0080A025 */  move  $s4, $a0
/* 01A5FC 700199FC 00008025 */  move  $s0, $zero
/* 01A600 70019A00 1B00001E */  blez  $t8, .L70019A7C
/* 01A604 70019A04 25130010 */   addiu $s3, $t0, 0x10
/* 01A608 70019A08 3C120C00 */  lui   $s2, (0x0C007FFF >> 16) # lui $s2, 0xc00
/* 01A60C 70019A0C 36527FFF */  ori   $s2, (0x0C007FFF & 0xFFFF) # ori $s2, $s2, 0x7fff
/* 01A610 70019A10 00608825 */  move  $s1, $v1
/* 01A614 70019A14 3056FFFF */  andi  $s6, $v0, 0xffff
.L70019A18:
/* 01A618 70019A18 8E240000 */  lw    $a0, ($s1)
/* 01A61C 70019A1C AFB30010 */  sw    $s3, 0x10($sp)
/* 01A620 70019A20 02E02825 */  move  $a1, $s7
/* 01A624 70019A24 8C990004 */  lw    $t9, 4($a0)
/* 01A628 70019A28 02A03025 */  move  $a2, $s5
/* 01A62C 70019A2C 03C03825 */  move  $a3, $fp
/* 01A630 70019A30 0320F809 */  jalr  $t9
/* 01A634 70019A34 00000000 */  nop   
/* 01A638 70019A38 3C0A06C0 */  lui   $t2, (0x06C00440 >> 16) # lui $t2, 0x6c0
/* 01A63C 70019A3C 3C0B0800 */  lui   $t3, (0x08000580 >> 16) # lui $t3, 0x800
/* 01A640 70019A40 3C090800 */  lui   $t1, 0x800
/* 01A644 70019A44 354A0440 */  ori   $t2, (0x06C00440 & 0xFFFF) # ori $t2, $t2, 0x440
/* 01A648 70019A48 356B0580 */  ori   $t3, (0x08000580 & 0xFFFF) # ori $t3, $t3, 0x580
/* 01A64C 70019A4C AC490000 */  sw    $t1, ($v0)
/* 01A650 70019A50 AC560004 */  sw    $s6, 4($v0)
/* 01A654 70019A54 AC4A000C */  sw    $t2, 0xc($v0)
/* 01A658 70019A58 AC520008 */  sw    $s2, 8($v0)
/* 01A65C 70019A5C AC4B0014 */  sw    $t3, 0x14($v0)
/* 01A660 70019A60 AC520010 */  sw    $s2, 0x10($v0)
/* 01A664 70019A64 8E8C0014 */  lw    $t4, 0x14($s4)
/* 01A668 70019A68 26100001 */  addiu $s0, $s0, 1
/* 01A66C 70019A6C 26310004 */  addiu $s1, $s1, 4
/* 01A670 70019A70 020C082A */  slt   $at, $s0, $t4
/* 01A674 70019A74 1420FFE8 */  bnez  $at, .L70019A18
/* 01A678 70019A78 24530018 */   addiu $s3, $v0, 0x18
.L70019A7C:
/* 01A67C 70019A7C 8FBF0044 */  lw    $ra, 0x44($sp)
/* 01A680 70019A80 02601025 */  move  $v0, $s3
/* 01A684 70019A84 8FB3002C */  lw    $s3, 0x2c($sp)
/* 01A688 70019A88 8FB00020 */  lw    $s0, 0x20($sp)
/* 01A68C 70019A8C 8FB10024 */  lw    $s1, 0x24($sp)
/* 01A690 70019A90 8FB20028 */  lw    $s2, 0x28($sp)
/* 01A694 70019A94 8FB40030 */  lw    $s4, 0x30($sp)
/* 01A698 70019A98 8FB50034 */  lw    $s5, 0x34($sp)
/* 01A69C 70019A9C 8FB60038 */  lw    $s6, 0x38($sp)
/* 01A6A0 70019AA0 8FB7003C */  lw    $s7, 0x3c($sp)
/* 01A6A4 70019AA4 8FBE0040 */  lw    $fp, 0x40($sp)
/* 01A6A8 70019AA8 03E00008 */  jr    $ra
/* 01A6AC 70019AAC 27BD0048 */   addiu $sp, $sp, 0x48
