# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel guNormalize
/* 020350 7001F750 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 020354 7001F754 AFBF0014 */  sw    $ra, 0x14($sp)
/* 020358 7001F758 C4820000 */  lwc1  $f2, ($a0)
/* 02035C 7001F75C C4AE0000 */  lwc1  $f14, ($a1)
/* 020360 7001F760 C4C00000 */  lwc1  $f0, ($a2)
/* 020364 7001F764 46021102 */  mul.s $f4, $f2, $f2
/* 020368 7001F768 AFA60020 */  sw    $a2, 0x20($sp)
/* 02036C 7001F76C AFA5001C */  sw    $a1, 0x1c($sp)
/* 020370 7001F770 460E7182 */  mul.s $f6, $f14, $f14
/* 020374 7001F774 AFA40018 */  sw    $a0, 0x18($sp)
/* 020378 7001F778 46000282 */  mul.s $f10, $f0, $f0
/* 02037C 7001F77C 46062200 */  add.s $f8, $f4, $f6
/* 020380 7001F780 0C007DF8 */  jal   sqrtf
/* 020384 7001F784 46085300 */   add.s $f12, $f10, $f8
/* 020388 7001F788 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 02038C 7001F78C 44818000 */  mtc1  $at, $f16
/* 020390 7001F790 8FA40018 */  lw    $a0, 0x18($sp)
/* 020394 7001F794 8FA5001C */  lw    $a1, 0x1c($sp)
/* 020398 7001F798 46008083 */  div.s $f2, $f16, $f0
/* 02039C 7001F79C C4920000 */  lwc1  $f18, ($a0)
/* 0203A0 7001F7A0 8FA60020 */  lw    $a2, 0x20($sp)
/* 0203A4 7001F7A4 46029102 */  mul.s $f4, $f18, $f2
/* 0203A8 7001F7A8 E4840000 */  swc1  $f4, ($a0)
/* 0203AC 7001F7AC C4A60000 */  lwc1  $f6, ($a1)
/* 0203B0 7001F7B0 46023282 */  mul.s $f10, $f6, $f2
/* 0203B4 7001F7B4 E4AA0000 */  swc1  $f10, ($a1)
/* 0203B8 7001F7B8 C4C80000 */  lwc1  $f8, ($a2)
/* 0203BC 7001F7BC 46024402 */  mul.s $f16, $f8, $f2
/* 0203C0 7001F7C0 E4D00000 */  swc1  $f16, ($a2)
/* 0203C4 7001F7C4 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0203C8 7001F7C8 27BD0018 */  addiu $sp, $sp, 0x18
/* 0203CC 7001F7CC 03E00008 */  jr    $ra
/* 0203D0 7001F7D0 00000000 */   nop   
