# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osPfsIsPlug
/* 0166A0 70015AA0 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 0166A4 70015AA4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0166A8 70015AA8 240E0003 */  li    $t6, 3
/* 0166AC 70015AAC AFA40040 */  sw    $a0, 0x40($sp)
/* 0166B0 70015AB0 AFA50044 */  sw    $a1, 0x44($sp)
/* 0166B4 70015AB4 AFA0003C */  sw    $zero, 0x3c($sp)
/* 0166B8 70015AB8 A3A0001F */  sb    $zero, 0x1f($sp)
/* 0166BC 70015ABC 0C005798 */  jal   __osSiGetAccess
/* 0166C0 70015AC0 AFAE0018 */   sw    $t6, 0x18($sp)
.L70015AC4:
/* 0166C4 70015AC4 0C005710 */  jal   __osPfsRequestData
/* 0166C8 70015AC8 00002025 */   move  $a0, $zero
/* 0166CC 70015ACC 3C058006 */  lui   $a1, %hi(__osPfsPifRam)
/* 0166D0 70015AD0 24A57D70 */  addiu $a1, %lo(__osPfsPifRam) # addiu $a1, $a1, 0x7d70
/* 0166D4 70015AD4 0C0057B4 */  jal   __osSiRawStartDma
/* 0166D8 70015AD8 24040001 */   li    $a0, 1
/* 0166DC 70015ADC AFA2003C */  sw    $v0, 0x3c($sp)
/* 0166E0 70015AE0 8FA40040 */  lw    $a0, 0x40($sp)
/* 0166E4 70015AE4 27A50038 */  addiu $a1, $sp, 0x38
/* 0166E8 70015AE8 0C003774 */  jal   osRecvMesg
/* 0166EC 70015AEC 24060001 */   li    $a2, 1
/* 0166F0 70015AF0 3C058006 */  lui   $a1, %hi(__osPfsPifRam)
/* 0166F4 70015AF4 24A57D70 */  addiu $a1, %lo(__osPfsPifRam) # addiu $a1, $a1, 0x7d70
/* 0166F8 70015AF8 0C0057B4 */  jal   __osSiRawStartDma
/* 0166FC 70015AFC 00002025 */   move  $a0, $zero
/* 016700 70015B00 AFA2003C */  sw    $v0, 0x3c($sp)
/* 016704 70015B04 8FA40040 */  lw    $a0, 0x40($sp)
/* 016708 70015B08 27A50038 */  addiu $a1, $sp, 0x38
/* 01670C 70015B0C 0C003774 */  jal   osRecvMesg
/* 016710 70015B10 24060001 */   li    $a2, 1
/* 016714 70015B14 27A40037 */  addiu $a0, $sp, 0x37
/* 016718 70015B18 0C00574F */  jal   __osPfsGetInitData
/* 01671C 70015B1C 27A50024 */   addiu $a1, $sp, 0x24
/* 016720 70015B20 3C0F8006 */  lui   $t7, %hi(__osMaxControllers) 
/* 016724 70015B24 91EF7CE1 */  lbu   $t7, %lo(__osMaxControllers)($t7)
/* 016728 70015B28 AFA00020 */  sw    $zero, 0x20($sp)
/* 01672C 70015B2C 19E00014 */  blez  $t7, .L70015B80
/* 016730 70015B30 00000000 */   nop   
.L70015B34:
/* 016734 70015B34 8FB80020 */  lw    $t8, 0x20($sp)
/* 016738 70015B38 0018C880 */  sll   $t9, $t8, 2
/* 01673C 70015B3C 03B94021 */  addu  $t0, $sp, $t9
/* 016740 70015B40 91080026 */  lbu   $t0, 0x26($t0)
/* 016744 70015B44 31090004 */  andi  $t1, $t0, 4
/* 016748 70015B48 15200005 */  bnez  $t1, .L70015B60
/* 01674C 70015B4C 00000000 */   nop   
/* 016750 70015B50 8FAA0018 */  lw    $t2, 0x18($sp)
/* 016754 70015B54 254BFFFF */  addiu $t3, $t2, -1
/* 016758 70015B58 10000009 */  b     .L70015B80
/* 01675C 70015B5C AFAB0018 */   sw    $t3, 0x18($sp)
.L70015B60:
/* 016760 70015B60 8FAC0020 */  lw    $t4, 0x20($sp)
/* 016764 70015B64 3C0E8006 */  lui   $t6, %hi(__osMaxControllers) 
/* 016768 70015B68 91CE7CE1 */  lbu   $t6, %lo(__osMaxControllers)($t6)
/* 01676C 70015B6C 258D0001 */  addiu $t5, $t4, 1
/* 016770 70015B70 AFAD0020 */  sw    $t5, 0x20($sp)
/* 016774 70015B74 01AE082A */  slt   $at, $t5, $t6
/* 016778 70015B78 1420FFEE */  bnez  $at, .L70015B34
/* 01677C 70015B7C 00000000 */   nop   
.L70015B80:
/* 016780 70015B80 3C0F8006 */  lui   $t7, %hi(__osMaxControllers) 
/* 016784 70015B84 91EF7CE1 */  lbu   $t7, %lo(__osMaxControllers)($t7)
/* 016788 70015B88 8FB80020 */  lw    $t8, 0x20($sp)
/* 01678C 70015B8C 15F80002 */  bne   $t7, $t8, .L70015B98
/* 016790 70015B90 00000000 */   nop   
/* 016794 70015B94 AFA00018 */  sw    $zero, 0x18($sp)
.L70015B98:
/* 016798 70015B98 8FB90018 */  lw    $t9, 0x18($sp)
/* 01679C 70015B9C 1F20FFC9 */  bgtz  $t9, .L70015AC4
/* 0167A0 70015BA0 00000000 */   nop   
/* 0167A4 70015BA4 3C088006 */  lui   $t0, %hi(__osMaxControllers) 
/* 0167A8 70015BA8 91087CE1 */  lbu   $t0, %lo(__osMaxControllers)($t0)
/* 0167AC 70015BAC AFA00020 */  sw    $zero, 0x20($sp)
/* 0167B0 70015BB0 19000019 */  blez  $t0, .L70015C18
/* 0167B4 70015BB4 00000000 */   nop   
.L70015BB8:
/* 0167B8 70015BB8 8FA90020 */  lw    $t1, 0x20($sp)
/* 0167BC 70015BBC 27AB0024 */  addiu $t3, $sp, 0x24
/* 0167C0 70015BC0 00095080 */  sll   $t2, $t1, 2
/* 0167C4 70015BC4 014B6021 */  addu  $t4, $t2, $t3
/* 0167C8 70015BC8 918D0003 */  lbu   $t5, 3($t4)
/* 0167CC 70015BCC 15A0000A */  bnez  $t5, .L70015BF8
/* 0167D0 70015BD0 00000000 */   nop   
/* 0167D4 70015BD4 918E0002 */  lbu   $t6, 2($t4)
/* 0167D8 70015BD8 31CF0001 */  andi  $t7, $t6, 1
/* 0167DC 70015BDC 11E00006 */  beqz  $t7, .L70015BF8
/* 0167E0 70015BE0 00000000 */   nop   
/* 0167E4 70015BE4 93B8001F */  lbu   $t8, 0x1f($sp)
/* 0167E8 70015BE8 24190001 */  li    $t9, 1
/* 0167EC 70015BEC 01394004 */  sllv  $t0, $t9, $t1
/* 0167F0 70015BF0 03085025 */  or    $t2, $t8, $t0
/* 0167F4 70015BF4 A3AA001F */  sb    $t2, 0x1f($sp)
.L70015BF8:
/* 0167F8 70015BF8 8FAB0020 */  lw    $t3, 0x20($sp)
/* 0167FC 70015BFC 3C0C8006 */  lui   $t4, %hi(__osMaxControllers) 
/* 016800 70015C00 918C7CE1 */  lbu   $t4, %lo(__osMaxControllers)($t4)
/* 016804 70015C04 256D0001 */  addiu $t5, $t3, 1
/* 016808 70015C08 AFAD0020 */  sw    $t5, 0x20($sp)
/* 01680C 70015C0C 01AC082A */  slt   $at, $t5, $t4
/* 016810 70015C10 1420FFE9 */  bnez  $at, .L70015BB8
/* 016814 70015C14 00000000 */   nop   
.L70015C18:
/* 016818 70015C18 0C0057A9 */  jal   __osSiRelAccess
/* 01681C 70015C1C 00000000 */   nop   
/* 016820 70015C20 93AE001F */  lbu   $t6, 0x1f($sp)
/* 016824 70015C24 8FAF0044 */  lw    $t7, 0x44($sp)
/* 016828 70015C28 A1EE0000 */  sb    $t6, ($t7)
/* 01682C 70015C2C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 016830 70015C30 8FA2003C */  lw    $v0, 0x3c($sp)
/* 016834 70015C34 27BD0040 */  addiu $sp, $sp, 0x40
/* 016838 70015C38 03E00008 */  jr    $ra
/* 01683C 70015C3C 00000000 */   nop   

glabel __osPfsRequestData
/* 016840 70015C40 27BDFFF0 */  addiu $sp, $sp, -0x10
/* 016844 70015C44 308400FF */  andi  $a0, $a0, 0xff
/* 016848 70015C48 3C018006 */  lui   $at, %hi(__osContLastCmd)
/* 01684C 70015C4C A0247CE0 */  sb    $a0, %lo(__osContLastCmd)($at)
/* 016850 70015C50 AFA00000 */  sw    $zero, ($sp)
.L70015C54:
/* 016854 70015C54 8FAE0000 */  lw    $t6, ($sp)
/* 016858 70015C58 8FB80000 */  lw    $t8, ($sp)
/* 01685C 70015C5C 3C018006 */  lui   $at, %hi(__osPfsPifRam)
/* 016860 70015C60 000E7880 */  sll   $t7, $t6, 2
/* 016864 70015C64 002F0821 */  addu  $at, $at, $t7
/* 016868 70015C68 AC207D70 */  sw    $zero, %lo(__osPfsPifRam)($at)
/* 01686C 70015C6C 27190001 */  addiu $t9, $t8, 1
/* 016870 70015C70 2B210010 */  slti  $at, $t9, 0x10
/* 016874 70015C74 1420FFF7 */  bnez  $at, .L70015C54
/* 016878 70015C78 AFB90000 */   sw    $t9, ($sp)
/* 01687C 70015C7C 3C198006 */  lui   $t9, %hi(__osMaxControllers) 
/* 016880 70015C80 93397CE1 */  lbu   $t9, %lo(__osMaxControllers)($t9)
/* 016884 70015C84 3C098006 */  lui   $t1, %hi(__osPfsPifRam) 
/* 016888 70015C88 24080001 */  li    $t0, 1
/* 01688C 70015C8C 3C018006 */  lui   $at, %hi(__osPfsPifRam+0x3c)
/* 016890 70015C90 25297D70 */  addiu $t1, %lo(__osPfsPifRam) # addiu $t1, $t1, 0x7d70
/* 016894 70015C94 240A00FF */  li    $t2, 255
/* 016898 70015C98 240B0001 */  li    $t3, 1
/* 01689C 70015C9C 240C0003 */  li    $t4, 3
/* 0168A0 70015CA0 240D00FF */  li    $t5, 255
/* 0168A4 70015CA4 240E00FF */  li    $t6, 255
/* 0168A8 70015CA8 240F00FF */  li    $t7, 255
/* 0168AC 70015CAC 241800FF */  li    $t8, 255
/* 0168B0 70015CB0 AC287DAC */  sw    $t0, %lo(__osPfsPifRam+0x3c)($at)
/* 0168B4 70015CB4 AFA9000C */  sw    $t1, 0xc($sp)
/* 0168B8 70015CB8 A3AA0004 */  sb    $t2, 4($sp)
/* 0168BC 70015CBC A3AB0005 */  sb    $t3, 5($sp)
/* 0168C0 70015CC0 A3AC0006 */  sb    $t4, 6($sp)
/* 0168C4 70015CC4 A3A40007 */  sb    $a0, 7($sp)
/* 0168C8 70015CC8 A3AD0008 */  sb    $t5, 8($sp)
/* 0168CC 70015CCC A3AE0009 */  sb    $t6, 9($sp)
/* 0168D0 70015CD0 A3AF000A */  sb    $t7, 0xa($sp)
/* 0168D4 70015CD4 A3B8000B */  sb    $t8, 0xb($sp)
/* 0168D8 70015CD8 1B200013 */  blez  $t9, .L70015D28
/* 0168DC 70015CDC AFA00000 */   sw    $zero, ($sp)
.L70015CE0:
/* 0168E0 70015CE0 27A90004 */  addiu $t1, $sp, 4
/* 0168E4 70015CE4 8D210000 */  lw    $at, ($t1)
/* 0168E8 70015CE8 8FA8000C */  lw    $t0, 0xc($sp)
/* 0168EC 70015CEC 3C188006 */  lui   $t8, %hi(__osMaxControllers) 
/* 0168F0 70015CF0 A9010000 */  swl   $at, ($t0)
/* 0168F4 70015CF4 B9010003 */  swr   $at, 3($t0)
/* 0168F8 70015CF8 8D2B0004 */  lw    $t3, 4($t1)
/* 0168FC 70015CFC A90B0004 */  swl   $t3, 4($t0)
/* 016900 70015D00 B90B0007 */  swr   $t3, 7($t0)
/* 016904 70015D04 8FAE0000 */  lw    $t6, ($sp)
/* 016908 70015D08 93187CE1 */  lbu   $t8, %lo(__osMaxControllers)($t8)
/* 01690C 70015D0C 8FAC000C */  lw    $t4, 0xc($sp)
/* 016910 70015D10 25CF0001 */  addiu $t7, $t6, 1
/* 016914 70015D14 01F8082A */  slt   $at, $t7, $t8
/* 016918 70015D18 258D0008 */  addiu $t5, $t4, 8
/* 01691C 70015D1C AFAF0000 */  sw    $t7, ($sp)
/* 016920 70015D20 1420FFEF */  bnez  $at, .L70015CE0
/* 016924 70015D24 AFAD000C */   sw    $t5, 0xc($sp)
.L70015D28:
/* 016928 70015D28 8FAA000C */  lw    $t2, 0xc($sp)
/* 01692C 70015D2C 241900FE */  li    $t9, 254
/* 016930 70015D30 27BD0010 */  addiu $sp, $sp, 0x10
/* 016934 70015D34 03E00008 */  jr    $ra
/* 016938 70015D38 A1590000 */   sb    $t9, ($t2)

glabel __osPfsGetInitData
/* 01693C 70015D3C 3C0F8006 */  lui   $t7, %hi(__osMaxControllers) 
/* 016940 70015D40 91EF7CE1 */  lbu   $t7, %lo(__osMaxControllers)($t7)
/* 016944 70015D44 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 016948 70015D48 3C0E8006 */  lui   $t6, %hi(__osPfsPifRam) 
/* 01694C 70015D4C 25CE7D70 */  addiu $t6, %lo(__osPfsPifRam) # addiu $t6, $t6, 0x7d70
/* 016950 70015D50 A3A00007 */  sb    $zero, 7($sp)
/* 016954 70015D54 AFAE0014 */  sw    $t6, 0x14($sp)
/* 016958 70015D58 19E00028 */  blez  $t7, .L70015DFC
/* 01695C 70015D5C AFA00008 */   sw    $zero, 8($sp)
.L70015D60:
/* 016960 70015D60 8FB90014 */  lw    $t9, 0x14($sp)
/* 016964 70015D64 27B8000C */  addiu $t8, $sp, 0xc
/* 016968 70015D68 8B210000 */  lwl   $at, ($t9)
/* 01696C 70015D6C 9B210003 */  lwr   $at, 3($t9)
/* 016970 70015D70 AF010000 */  sw    $at, ($t8)
/* 016974 70015D74 8B290004 */  lwl   $t1, 4($t9)
/* 016978 70015D78 9B290007 */  lwr   $t1, 7($t9)
/* 01697C 70015D7C AF090004 */  sw    $t1, 4($t8)
/* 016980 70015D80 93AA000E */  lbu   $t2, 0xe($sp)
/* 016984 70015D84 314B00C0 */  andi  $t3, $t2, 0xc0
/* 016988 70015D88 000B6103 */  sra   $t4, $t3, 4
/* 01698C 70015D8C A0AC0003 */  sb    $t4, 3($a1)
/* 016990 70015D90 90AD0003 */  lbu   $t5, 3($a1)
/* 016994 70015D94 15A0000E */  bnez  $t5, .L70015DD0
/* 016998 70015D98 00000000 */   nop   
/* 01699C 70015D9C 93AE0011 */  lbu   $t6, 0x11($sp)
/* 0169A0 70015DA0 93A80010 */  lbu   $t0, 0x10($sp)
/* 0169A4 70015DA4 240B0001 */  li    $t3, 1
/* 0169A8 70015DA8 000E7A00 */  sll   $t7, $t6, 8
/* 0169AC 70015DAC 01E8C025 */  or    $t8, $t7, $t0
/* 0169B0 70015DB0 A4B80000 */  sh    $t8, ($a1)
/* 0169B4 70015DB4 93B90012 */  lbu   $t9, 0x12($sp)
/* 0169B8 70015DB8 A0B90002 */  sb    $t9, 2($a1)
/* 0169BC 70015DBC 8FAA0008 */  lw    $t2, 8($sp)
/* 0169C0 70015DC0 93A90007 */  lbu   $t1, 7($sp)
/* 0169C4 70015DC4 014B6004 */  sllv  $t4, $t3, $t2
/* 0169C8 70015DC8 012C6825 */  or    $t5, $t1, $t4
/* 0169CC 70015DCC A3AD0007 */  sb    $t5, 7($sp)
.L70015DD0:
/* 0169D0 70015DD0 8FAE0008 */  lw    $t6, 8($sp)
/* 0169D4 70015DD4 3C198006 */  lui   $t9, %hi(__osMaxControllers) 
/* 0169D8 70015DD8 93397CE1 */  lbu   $t9, %lo(__osMaxControllers)($t9)
/* 0169DC 70015DDC 8FA80014 */  lw    $t0, 0x14($sp)
/* 0169E0 70015DE0 25CF0001 */  addiu $t7, $t6, 1
/* 0169E4 70015DE4 01F9082A */  slt   $at, $t7, $t9
/* 0169E8 70015DE8 25180008 */  addiu $t8, $t0, 8
/* 0169EC 70015DEC AFB80014 */  sw    $t8, 0x14($sp)
/* 0169F0 70015DF0 AFAF0008 */  sw    $t7, 8($sp)
/* 0169F4 70015DF4 1420FFDA */  bnez  $at, .L70015D60
/* 0169F8 70015DF8 24A50004 */   addiu $a1, $a1, 4
.L70015DFC:
/* 0169FC 70015DFC 93AB0007 */  lbu   $t3, 7($sp)
/* 016A00 70015E00 27BD0018 */  addiu $sp, $sp, 0x18
/* 016A04 70015E04 03E00008 */  jr    $ra
/* 016A08 70015E08 A08B0000 */   sb    $t3, ($a0)

/* 016A0C 70015E0C 00000000 */  nop   
.section .bss
glabel __osPfsPifRam
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0


