# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osPiCreateAccessQueue
/* 01E310 7001D710 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01E314 7001D714 AFBF0014 */  sw    $ra, 0x14($sp)
/* 01E318 7001D718 240E0001 */  li    $t6, 1
/* 01E31C 7001D71C 3C018003 */  lui   $at, %hi(__osPiAccessQueueEnabled)
/* 01E320 7001D720 3C048007 */  lui   $a0, %hi(__osPiAccessQueue)
/* 01E324 7001D724 3C058007 */  lui   $a1, %hi(piAccessBuf)
/* 01E328 7001D728 AC2E82E0 */  sw    $t6, %lo(__osPiAccessQueueEnabled)($at)
/* 01E32C 7001D72C 24A58FE0 */  addiu $a1, %lo(piAccessBuf) # addiu $a1, $a1, -0x7020
/* 01E330 7001D730 24848FE8 */  addiu $a0, %lo(__osPiAccessQueue) # addiu $a0, $a0, -0x7018
/* 01E334 7001D734 0C0035B4 */  jal   osCreateMesgQueue
/* 01E338 7001D738 24060001 */   li    $a2, 1
/* 01E33C 7001D73C 3C048007 */  lui   $a0, %hi(__osPiAccessQueue)
/* 01E340 7001D740 24848FE8 */  addiu $a0, %lo(__osPiAccessQueue) # addiu $a0, $a0, -0x7018
/* 01E344 7001D744 00002825 */  move  $a1, $zero
/* 01E348 7001D748 0C0037C4 */  jal   osSendMesg
/* 01E34C 7001D74C 00003025 */   move  $a2, $zero
/* 01E350 7001D750 8FBF0014 */  lw    $ra, 0x14($sp)
/* 01E354 7001D754 27BD0018 */  addiu $sp, $sp, 0x18
/* 01E358 7001D758 03E00008 */  jr    $ra
/* 01E35C 7001D75C 00000000 */   nop   

glabel __osPiGetAccess
/* 01E360 7001D760 3C0E8003 */  lui   $t6, %hi(__osPiAccessQueueEnabled) 
/* 01E364 7001D764 8DCE82E0 */  lw    $t6, %lo(__osPiAccessQueueEnabled)($t6)
/* 01E368 7001D768 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 01E36C 7001D76C AFBF0014 */  sw    $ra, 0x14($sp)
/* 01E370 7001D770 15C00003 */  bnez  $t6, .L7001D780
/* 01E374 7001D774 00000000 */   nop   
/* 01E378 7001D778 0C0075C4 */  jal   __osPiCreateAccessQueue
/* 01E37C 7001D77C 00000000 */   nop   
.L7001D780:
/* 01E380 7001D780 3C048007 */  lui   $a0, %hi(__osPiAccessQueue)
/* 01E384 7001D784 24848FE8 */  addiu $a0, %lo(__osPiAccessQueue) # addiu $a0, $a0, -0x7018
/* 01E388 7001D788 27A5001C */  addiu $a1, $sp, 0x1c
/* 01E38C 7001D78C 0C003774 */  jal   osRecvMesg
/* 01E390 7001D790 24060001 */   li    $a2, 1
/* 01E394 7001D794 8FBF0014 */  lw    $ra, 0x14($sp)
/* 01E398 7001D798 27BD0020 */  addiu $sp, $sp, 0x20
/* 01E39C 7001D79C 03E00008 */  jr    $ra
/* 01E3A0 7001D7A0 00000000 */   nop   

glabel __osPiRelAccess
/* 01E3A4 7001D7A4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01E3A8 7001D7A8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 01E3AC 7001D7AC 3C048007 */  lui   $a0, %hi(__osPiAccessQueue)
/* 01E3B0 7001D7B0 24848FE8 */  addiu $a0, %lo(__osPiAccessQueue) # addiu $a0, $a0, -0x7018
/* 01E3B4 7001D7B4 00002825 */  move  $a1, $zero
/* 01E3B8 7001D7B8 0C0037C4 */  jal   osSendMesg
/* 01E3BC 7001D7BC 00003025 */   move  $a2, $zero
/* 01E3C0 7001D7C0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 01E3C4 7001D7C4 27BD0018 */  addiu $sp, $sp, 0x18
/* 01E3C8 7001D7C8 03E00008 */  jr    $ra
/* 01E3CC 7001D7CC 00000000 */   nop   

.section .data
glabel __osPiAccessQueueEnabled
.word 0
.align 4

.section .bss
glabel piAccessBuf
.word 0
.word 0
glabel __osPiAccessQueue
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
