# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osPiGetCmdQueue
/* 01C400 7001B800 3C0E8002 */  lui   $t6, %hi(__osPiDevMgr) 
/* 01C404 7001B804 8DCE7790 */  lw    $t6, %lo(__osPiDevMgr)($t6)
/* 01C408 7001B808 15C00003 */  bnez  $t6, .L7001B818
/* 01C40C 7001B80C 00000000 */   nop   
/* 01C410 7001B810 03E00008 */  jr    $ra
/* 01C414 7001B814 00001025 */   move  $v0, $zero

.L7001B818:
/* 01C418 7001B818 3C028002 */  lui   $v0, %hi(__osPiDevMgr+0x8)
/* 01C41C 7001B81C 8C427798 */  lw    $v0, %lo(__osPiDevMgr+0x8)($v0)
/* 01C420 7001B820 03E00008 */  jr    $ra
/* 01C424 7001B824 00000000 */   nop   

