# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel osPiRawReadIo
/* 0187E0 70017BE0 3C0EA460 */  lui   $t6, %hi(PI_STATUS_REG) # $t6, 0xa460
/* 0187E4 70017BE4 8DC60010 */  lw    $a2, %lo(PI_STATUS_REG)($t6)
/* 0187E8 70017BE8 27BDFFF8 */  addiu $sp, $sp, -8
/* 0187EC 70017BEC 30CF0003 */  andi  $t7, $a2, 3
/* 0187F0 70017BF0 11E00006 */  beqz  $t7, .L70017C0C
/* 0187F4 70017BF4 00000000 */   nop   
.L70017BF8:
/* 0187F8 70017BF8 3C18A460 */  lui   $t8, %hi(PI_STATUS_REG) # $t8, 0xa460
/* 0187FC 70017BFC 8F060010 */  lw    $a2, %lo(PI_STATUS_REG)($t8)
/* 018800 70017C00 30D90003 */  andi  $t9, $a2, 3
/* 018804 70017C04 1720FFFC */  bnez  $t9, .L70017BF8
/* 018808 70017C08 00000000 */   nop   
.L70017C0C:
/* 01880C 70017C0C 3C088000 */  lui   $t0, %hi(osRomBase) 
/* 018810 70017C10 8D080308 */  lw    $t0, %lo(osRomBase)($t0)
/* 018814 70017C14 3C01A000 */  lui   $at, 0xa000
/* 018818 70017C18 00001025 */  move  $v0, $zero
/* 01881C 70017C1C 01044825 */  or    $t1, $t0, $a0
/* 018820 70017C20 01215025 */  or    $t2, $t1, $at
/* 018824 70017C24 8D4B0000 */  lw    $t3, ($t2)
/* 018828 70017C28 27BD0008 */  addiu $sp, $sp, 8
/* 01882C 70017C2C 03E00008 */  jr    $ra
/* 018830 70017C30 ACAB0000 */   sw    $t3, ($a1)

/* 018834 70017C34 00000000 */  nop   
/* 018838 70017C38 00000000 */  nop   
/* 01883C 70017C3C 00000000 */  nop  
