# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alResampleParam
/* 01B200 7001A600 24AEFFFF */  addiu $t6, $a1, -1
/* 01B204 7001A604 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 01B208 7001A608 2DC10009 */  sltiu $at, $t6, 9
/* 01B20C 7001A60C AFBF0014 */  sw    $ra, 0x14($sp)
/* 01B210 7001A610 1020002B */  beqz  $at, .L7001A6C0
/* 01B214 7001A614 00803825 */   move  $a3, $a0
/* 01B218 7001A618 000E7080 */  sll   $t6, $t6, 2
/* 01B21C 7001A61C 3C018003 */  lui   $at, %hi(jpt_80029850)
/* 01B220 7001A620 002E0821 */  addu  $at, $at, $t6
/* 01B224 7001A624 8C2E9850 */  lw    $t6, %lo(jpt_80029850)($at)
/* 01B228 7001A628 01C00008 */  jr    $t6
/* 01B22C 7001A62C 00000000 */   nop   
.L7001A630:
/* 01B230 7001A630 10000029 */  b     .L7001A6D8
/* 01B234 7001A634 ACE60000 */   sw    $a2, ($a3)
.L7001A638:
/* 01B238 7001A638 8CE40000 */  lw    $a0, ($a3)
/* 01B23C 7001A63C 44802000 */  mtc1  $zero, $f4
/* 01B240 7001A640 240F0001 */  li    $t7, 1
/* 01B244 7001A644 ACEF0024 */  sw    $t7, 0x24($a3)
/* 01B248 7001A648 ACE00030 */  sw    $zero, 0x30($a3)
/* 01B24C 7001A64C ACE0001C */  sw    $zero, 0x1c($a3)
/* 01B250 7001A650 10800021 */  beqz  $a0, .L7001A6D8
/* 01B254 7001A654 E4E40020 */   swc1  $f4, 0x20($a3)
/* 01B258 7001A658 8C990008 */  lw    $t9, 8($a0)
/* 01B25C 7001A65C 24050004 */  li    $a1, 4
/* 01B260 7001A660 00003025 */  move  $a2, $zero
/* 01B264 7001A664 0320F809 */  jalr  $t9
/* 01B268 7001A668 00000000 */  nop   
/* 01B26C 7001A66C 1000001B */  b     .L7001A6DC
/* 01B270 7001A670 8FBF0014 */   lw    $ra, 0x14($sp)
.L7001A674:
/* 01B274 7001A674 8CE40000 */  lw    $a0, ($a3)
/* 01B278 7001A678 24180001 */  li    $t8, 1
/* 01B27C 7001A67C ACF80030 */  sw    $t8, 0x30($a3)
/* 01B280 7001A680 50800016 */  beql  $a0, $zero, .L7001A6DC
/* 01B284 7001A684 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01B288 7001A688 8C990008 */  lw    $t9, 8($a0)
/* 01B28C 7001A68C 24050009 */  li    $a1, 9
/* 01B290 7001A690 00003025 */  move  $a2, $zero
/* 01B294 7001A694 0320F809 */  jalr  $t9
/* 01B298 7001A698 00000000 */  nop   
/* 01B29C 7001A69C 1000000F */  b     .L7001A6DC
/* 01B2A0 7001A6A0 8FBF0014 */   lw    $ra, 0x14($sp)
.L7001A6A4:
/* 01B2A4 7001A6A4 AFA6001C */  sw    $a2, 0x1c($sp)
/* 01B2A8 7001A6A8 C7A6001C */  lwc1  $f6, 0x1c($sp)
/* 01B2AC 7001A6AC 1000000A */  b     .L7001A6D8
/* 01B2B0 7001A6B0 E4E60018 */   swc1  $f6, 0x18($a3)
.L7001A6B4:
/* 01B2B4 7001A6B4 24080001 */  li    $t0, 1
/* 01B2B8 7001A6B8 10000007 */  b     .L7001A6D8
/* 01B2BC 7001A6BC ACE8001C */   sw    $t0, 0x1c($a3)
.L7001A6C0:
/* 01B2C0 7001A6C0 8CE40000 */  lw    $a0, ($a3)
/* 01B2C4 7001A6C4 50800005 */  beql  $a0, $zero, .L7001A6DC
/* 01B2C8 7001A6C8 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01B2CC 7001A6CC 8C990008 */  lw    $t9, 8($a0)
/* 01B2D0 7001A6D0 0320F809 */  jalr  $t9
/* 01B2D4 7001A6D4 00000000 */  nop   
.L7001A6D8:
/* 01B2D8 7001A6D8 8FBF0014 */  lw    $ra, 0x14($sp)
.L7001A6DC:
/* 01B2DC 7001A6DC 27BD0028 */  addiu $sp, $sp, 0x28
/* 01B2E0 7001A6E0 00001025 */  move  $v0, $zero
/* 01B2E4 7001A6E4 03E00008 */  jr    $ra
/* 01B2E8 7001A6E8 00000000 */   nop   

glabel alResamplePull
/* 01B2EC 7001A6EC 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 01B2F0 7001A6F0 AFBF001C */  sw    $ra, 0x1c($sp)
/* 01B2F4 7001A6F4 AFA50054 */  sw    $a1, 0x54($sp)
/* 01B2F8 7001A6F8 8C890000 */  lw    $t1, ($a0)
/* 01B2FC 7001A6FC 240E0140 */  li    $t6, 320
/* 01B300 7001A700 00804025 */  move  $t0, $a0
/* 01B304 7001A704 00C05025 */  move  $t2, $a2
/* 01B308 7001A708 14C00003 */  bnez  $a2, .L7001A718
/* 01B30C 7001A70C A7AE0046 */   sh    $t6, 0x46($sp)
/* 01B310 7001A710 10000074 */  b     .L7001A8E4
/* 01B314 7001A714 8FA20060 */   lw    $v0, 0x60($sp)
.L7001A718:
/* 01B318 7001A718 8D0F001C */  lw    $t7, 0x1c($t0)
/* 01B31C 7001A71C 8FB80060 */  lw    $t8, 0x60($sp)
/* 01B320 7001A720 51E0001A */  beql  $t7, $zero, .L7001A78C
/* 01B324 7001A724 C5020018 */   lwc1  $f2, 0x18($t0)
/* 01B328 7001A728 AFB80010 */  sw    $t8, 0x10($sp)
/* 01B32C 7001A72C AFAA0058 */  sw    $t2, 0x58($sp)
/* 01B330 7001A730 8D390004 */  lw    $t9, 4($t1)
/* 01B334 7001A734 01202025 */  move  $a0, $t1
/* 01B338 7001A738 27A50046 */  addiu $a1, $sp, 0x46
/* 01B33C 7001A73C 0320F809 */  jalr  $t9
/* 01B340 7001A740 01403025 */  move  $a2, $t2
/* 01B344 7001A744 87AB0046 */  lh    $t3, 0x46($sp)
/* 01B348 7001A748 3C0100FF */  lui   $at, (0x00FFFFFF >> 16) # lui $at, 0xff
/* 01B34C 7001A74C 3421FFFF */  ori   $at, (0x00FFFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 01B350 7001A750 01616024 */  and   $t4, $t3, $at
/* 01B354 7001A754 3C010A00 */  lui   $at, 0xa00
/* 01B358 7001A758 8FAA0058 */  lw    $t2, 0x58($sp)
/* 01B35C 7001A75C 01816825 */  or    $t5, $t4, $at
/* 01B360 7001A760 AC4D0000 */  sw    $t5, ($v0)
/* 01B364 7001A764 8FAE0054 */  lw    $t6, 0x54($sp)
/* 01B368 7001A768 000A5840 */  sll   $t3, $t2, 1
/* 01B36C 7001A76C 316CFFFF */  andi  $t4, $t3, 0xffff
/* 01B370 7001A770 85D80000 */  lh    $t8, ($t6)
/* 01B374 7001A774 24450008 */  addiu $a1, $v0, 8
/* 01B378 7001A778 0018CC00 */  sll   $t9, $t8, 0x10
/* 01B37C 7001A77C 032C6825 */  or    $t5, $t9, $t4
/* 01B380 7001A780 10000057 */  b     .L7001A8E0
/* 01B384 7001A784 AC4D0004 */   sw    $t5, 4($v0)
/* 01B388 7001A788 C5020018 */  lwc1  $f2, 0x18($t0)
.L7001A78C:
/* 01B38C 7001A78C 3C018003 */  lui   $at, %hi(F64_80029878)
/* 01B390 7001A790 D4249878 */  ldc1  $f4, %lo(F64_80029878)($at)
/* 01B394 7001A794 460011A1 */  cvt.d.s $f6, $f2
/* 01B398 7001A798 3C018003 */  lui   $at, %hi(F64_80029880)
/* 01B39C 7001A79C 4626203C */  c.lt.d $f4, $f6
/* 01B3A0 7001A7A0 00000000 */  nop   
/* 01B3A4 7001A7A4 45020005 */  bc1fl .L7001A7BC
/* 01B3A8 7001A7A8 3C014700 */   lui   $at, 0x4700
/* 01B3AC 7001A7AC C4289880 */  lwc1  $f8, %lo(F64_80029880)($at)
/* 01B3B0 7001A7B0 E5080018 */  swc1  $f8, 0x18($t0)
/* 01B3B4 7001A7B4 C5020018 */  lwc1  $f2, 0x18($t0)
/* 01B3B8 7001A7B8 3C014700 */  li    $at, 0x47000000 # 32768.000000
.L7001A7BC:
/* 01B3BC 7001A7BC 44816000 */  mtc1  $at, $f12
/* 01B3C0 7001A7C0 01202025 */  move  $a0, $t1
/* 01B3C4 7001A7C4 27A50046 */  addiu $a1, $sp, 0x46
/* 01B3C8 7001A7C8 460C1282 */  mul.s $f10, $f2, $f12
/* 01B3CC 7001A7CC 4600540D */  trunc.w.s $f16, $f10
/* 01B3D0 7001A7D0 440F8000 */  mfc1  $t7, $f16
/* 01B3D4 7001A7D4 448A8000 */  mtc1  $t2, $f16
/* 01B3D8 7001A7D8 448F9000 */  mtc1  $t7, $f18
/* 01B3DC 7001A7DC 00000000 */  nop   
/* 01B3E0 7001A7E0 46809120 */  cvt.s.w $f4, $f18
/* 01B3E4 7001A7E4 468084A0 */  cvt.s.w $f18, $f16
/* 01B3E8 7001A7E8 E5040018 */  swc1  $f4, 0x18($t0)
/* 01B3EC 7001A7EC C5060018 */  lwc1  $f6, 0x18($t0)
/* 01B3F0 7001A7F0 460C3203 */  div.s $f8, $f6, $f12
/* 01B3F4 7001A7F4 C5060020 */  lwc1  $f6, 0x20($t0)
/* 01B3F8 7001A7F8 E5080018 */  swc1  $f8, 0x18($t0)
/* 01B3FC 7001A7FC C50A0018 */  lwc1  $f10, 0x18($t0)
/* 01B400 7001A800 46125102 */  mul.s $f4, $f10, $f18
/* 01B404 7001A804 46043000 */  add.s $f0, $f6, $f4
/* 01B408 7001A808 4600020D */  trunc.w.s $f8, $f0
/* 01B40C 7001A80C 44064000 */  mfc1  $a2, $f8
/* 01B410 7001A810 00000000 */  nop   
/* 01B414 7001A814 44868000 */  mtc1  $a2, $f16
/* 01B418 7001A818 00000000 */  nop   
/* 01B41C 7001A81C 468082A0 */  cvt.s.w $f10, $f16
/* 01B420 7001A820 460A0481 */  sub.s $f18, $f0, $f10
/* 01B424 7001A824 E5120020 */  swc1  $f18, 0x20($t0)
/* 01B428 7001A828 8FAB0060 */  lw    $t3, 0x60($sp)
/* 01B42C 7001A82C AFAA0058 */  sw    $t2, 0x58($sp)
/* 01B430 7001A830 AFA80050 */  sw    $t0, 0x50($sp)
/* 01B434 7001A834 AFAB0010 */  sw    $t3, 0x10($sp)
/* 01B438 7001A838 8D390004 */  lw    $t9, 4($t1)
/* 01B43C 7001A83C 0320F809 */  jalr  $t9
/* 01B440 7001A840 00000000 */  nop   
/* 01B444 7001A844 8FA80050 */  lw    $t0, 0x50($sp)
/* 01B448 7001A848 87AD0046 */  lh    $t5, 0x46($sp)
/* 01B44C 7001A84C 3C014700 */  li    $at, 0x47000000 # 32768.000000
/* 01B450 7001A850 44812000 */  mtc1  $at, $f4
/* 01B454 7001A854 C5060018 */  lwc1  $f6, 0x18($t0)
/* 01B458 7001A858 3C010800 */  lui   $at, 0x800
/* 01B45C 7001A85C 31AEFFFF */  andi  $t6, $t5, 0xffff
/* 01B460 7001A860 8FAA0058 */  lw    $t2, 0x58($sp)
/* 01B464 7001A864 01C17825 */  or    $t7, $t6, $at
/* 01B468 7001A868 AC4F0000 */  sw    $t7, ($v0)
/* 01B46C 7001A86C 8FB80054 */  lw    $t8, 0x54($sp)
/* 01B470 7001A870 46043202 */  mul.s $f8, $f6, $f4
/* 01B474 7001A874 000A6840 */  sll   $t5, $t2, 1
/* 01B478 7001A878 87190000 */  lh    $t9, ($t8)
/* 01B47C 7001A87C 31AEFFFF */  andi  $t6, $t5, 0xffff
/* 01B480 7001A880 24580008 */  addiu $t8, $v0, 8
/* 01B484 7001A884 00196400 */  sll   $t4, $t9, 0x10
/* 01B488 7001A888 018E7825 */  or    $t7, $t4, $t6
/* 01B48C 7001A88C 4600440D */  trunc.w.s $f16, $f8
/* 01B490 7001A890 AC4F0004 */  sw    $t7, 4($v0)
/* 01B494 7001A894 AFB80028 */  sw    $t8, 0x28($sp)
/* 01B498 7001A898 8D0B0024 */  lw    $t3, 0x24($t0)
/* 01B49C 7001A89C 44038000 */  mfc1  $v1, $f16
/* 01B4A0 7001A8A0 3C010500 */  lui   $at, 0x500
/* 01B4A4 7001A8A4 317900FF */  andi  $t9, $t3, 0xff
/* 01B4A8 7001A8A8 00196C00 */  sll   $t5, $t9, 0x10
/* 01B4AC 7001A8AC 01A16025 */  or    $t4, $t5, $at
/* 01B4B0 7001A8B0 306EFFFF */  andi  $t6, $v1, 0xffff
/* 01B4B4 7001A8B4 018E7825 */  or    $t7, $t4, $t6
/* 01B4B8 7001A8B8 AC4F0008 */  sw    $t7, 8($v0)
/* 01B4BC 7001A8BC 24450010 */  addiu $a1, $v0, 0x10
/* 01B4C0 7001A8C0 8D040014 */  lw    $a0, 0x14($t0)
/* 01B4C4 7001A8C4 0C003A2C */  jal   osVirtualToPhysical
/* 01B4C8 7001A8C8 AFA50048 */   sw    $a1, 0x48($sp)
/* 01B4CC 7001A8CC 8FB80028 */  lw    $t8, 0x28($sp)
/* 01B4D0 7001A8D0 8FA80050 */  lw    $t0, 0x50($sp)
/* 01B4D4 7001A8D4 8FA50048 */  lw    $a1, 0x48($sp)
/* 01B4D8 7001A8D8 AF020004 */  sw    $v0, 4($t8)
/* 01B4DC 7001A8DC AD000024 */  sw    $zero, 0x24($t0)
.L7001A8E0:
/* 01B4E0 7001A8E0 00A01025 */  move  $v0, $a1
.L7001A8E4:
/* 01B4E4 7001A8E4 8FBF001C */  lw    $ra, 0x1c($sp)
/* 01B4E8 7001A8E8 27BD0050 */  addiu $sp, $sp, 0x50
/* 01B4EC 7001A8EC 03E00008 */  jr    $ra
/* 01B4F0 7001A8F0 00000000 */   nop   
.align 4

.section .rodata
glabel jpt_80029850
.word .L7001A630
.word .L7001A6C0
.word .L7001A6C0
.word .L7001A638
.word .L7001A6C0
.word .L7001A6C0
.word .L7001A6A4
.word .L7001A6B4
.word .L7001A674
.align 3
glabel F64_80029878
.double 1.99996
glabel F64_80029880
.float 1.9999599
.word 0
.word 0
.word 0
