# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alSaveParam
/* 01C1F0 7001B5F0 24010001 */  li    $at, 1
/* 01C1F4 7001B5F4 10A10006 */  beq   $a1, $at, .L7001B610
/* 01C1F8 7001B5F8 00001025 */   move  $v0, $zero
/* 01C1FC 7001B5FC 24010006 */  li    $at, 6
/* 01C200 7001B600 50A10006 */  beql  $a1, $at, .L7001B61C
/* 01C204 7001B604 AC860014 */   sw    $a2, 0x14($a0)
/* 01C208 7001B608 03E00008 */  jr    $ra
/* 01C20C 7001B60C 00001025 */   move  $v0, $zero

.L7001B610:
/* 01C210 7001B610 03E00008 */  jr    $ra
/* 01C214 7001B614 AC860000 */   sw    $a2, ($a0)

/* 01C218 7001B618 AC860014 */  sw    $a2, 0x14($a0)
.L7001B61C:
/* 01C21C 7001B61C 03E00008 */  jr    $ra
/* 01C220 7001B620 00001025 */   move  $v0, $zero

glabel alSavePull
/* 01C224 7001B624 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 01C228 7001B628 AFBF001C */  sw    $ra, 0x1c($sp)
/* 01C22C 7001B62C AFA40020 */  sw    $a0, 0x20($sp)
/* 01C230 7001B630 8C840000 */  lw    $a0, ($a0)
/* 01C234 7001B634 8FAF0030 */  lw    $t7, 0x30($sp)
/* 01C238 7001B638 AFA60028 */  sw    $a2, 0x28($sp)
/* 01C23C 7001B63C AFAF0010 */  sw    $t7, 0x10($sp)
/* 01C240 7001B640 8C990004 */  lw    $t9, 4($a0)
/* 01C244 7001B644 0320F809 */  jalr  $t9
/* 01C248 7001B648 00000000 */  nop   
/* 01C24C 7001B64C 8FA60028 */  lw    $a2, 0x28($sp)
/* 01C250 7001B650 3C030800 */  lui   $v1, 0x800
/* 01C254 7001B654 3C0A0440 */  lui   $t2, (0x04400580 >> 16) # lui $t2, 0x440
/* 01C258 7001B658 0006C040 */  sll   $t8, $a2, 1
/* 01C25C 7001B65C 00065880 */  sll   $t3, $a2, 2
/* 01C260 7001B660 3308FFFF */  andi  $t0, $t8, 0xffff
/* 01C264 7001B664 354A0580 */  ori   $t2, (0x04400580 & 0xFFFF) # ori $t2, $t2, 0x580
/* 01C268 7001B668 3C090D00 */  lui   $t1, 0xd00
/* 01C26C 7001B66C 316CFFFF */  andi  $t4, $t3, 0xffff
/* 01C270 7001B670 3C0D0600 */  lui   $t5, 0x600
/* 01C274 7001B674 AC480004 */  sw    $t0, 4($v0)
/* 01C278 7001B678 AC430000 */  sw    $v1, ($v0)
/* 01C27C 7001B67C AC490008 */  sw    $t1, 8($v0)
/* 01C280 7001B680 AC4A000C */  sw    $t2, 0xc($v0)
/* 01C284 7001B684 AC4C0014 */  sw    $t4, 0x14($v0)
/* 01C288 7001B688 AC430010 */  sw    $v1, 0x10($v0)
/* 01C28C 7001B68C AC4D0018 */  sw    $t5, 0x18($v0)
/* 01C290 7001B690 8FAE0020 */  lw    $t6, 0x20($sp)
/* 01C294 7001B694 24420020 */  addiu $v0, $v0, 0x20
/* 01C298 7001B698 8DCF0014 */  lw    $t7, 0x14($t6)
/* 01C29C 7001B69C AC4FFFFC */  sw    $t7, -4($v0)
/* 01C2A0 7001B6A0 8FBF001C */  lw    $ra, 0x1c($sp)
/* 01C2A4 7001B6A4 27BD0020 */  addiu $sp, $sp, 0x20
/* 01C2A8 7001B6A8 03E00008 */  jr    $ra
/* 01C2AC 7001B6AC 00000000 */   nop   
