# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel guScaleF
/* 017A90 70016E90 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 017A94 70016E94 AFBF0014 */  sw    $ra, 0x14($sp)
/* 017A98 70016E98 AFA5001C */  sw    $a1, 0x1c($sp)
/* 017A9C 70016E9C AFA60020 */  sw    $a2, 0x20($sp)
/* 017AA0 70016EA0 AFA70024 */  sw    $a3, 0x24($sp)
/* 017AA4 70016EA4 0C004004 */  jal   guMtxIdentF
/* 017AA8 70016EA8 AFA40018 */   sw    $a0, 0x18($sp)
/* 017AAC 70016EAC 8FA40018 */  lw    $a0, 0x18($sp)
/* 017AB0 70016EB0 C7A4001C */  lwc1  $f4, 0x1c($sp)
/* 017AB4 70016EB4 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 017AB8 70016EB8 44815000 */  mtc1  $at, $f10
/* 017ABC 70016EBC E4840000 */  swc1  $f4, ($a0)
/* 017AC0 70016EC0 C7A60020 */  lwc1  $f6, 0x20($sp)
/* 017AC4 70016EC4 E4860014 */  swc1  $f6, 0x14($a0)
/* 017AC8 70016EC8 C7A80024 */  lwc1  $f8, 0x24($sp)
/* 017ACC 70016ECC E48A003C */  swc1  $f10, 0x3c($a0)
/* 017AD0 70016ED0 E4880028 */  swc1  $f8, 0x28($a0)
/* 017AD4 70016ED4 8FBF0014 */  lw    $ra, 0x14($sp)
/* 017AD8 70016ED8 27BD0018 */  addiu $sp, $sp, 0x18
/* 017ADC 70016EDC 03E00008 */  jr    $ra
/* 017AE0 70016EE0 00000000 */   nop   

glabel guScale
/* 017AE4 70016EE4 44856000 */  mtc1  $a1, $f12
/* 017AE8 70016EE8 44867000 */  mtc1  $a2, $f14
/* 017AEC 70016EEC 44878000 */  mtc1  $a3, $f16
/* 017AF0 70016EF0 27BDFFA8 */  addiu $sp, $sp, -0x58
/* 017AF4 70016EF4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 017AF8 70016EF8 AFA40058 */  sw    $a0, 0x58($sp)
/* 017AFC 70016EFC 44056000 */  mfc1  $a1, $f12
/* 017B00 70016F00 44067000 */  mfc1  $a2, $f14
/* 017B04 70016F04 44078000 */  mfc1  $a3, $f16
/* 017B08 70016F08 0C005BA4 */  jal   guScaleF
/* 017B0C 70016F0C 27A40018 */   addiu $a0, $sp, 0x18
/* 017B10 70016F10 27A40018 */  addiu $a0, $sp, 0x18
/* 017B14 70016F14 0C003FC4 */  jal   guMtxF2L
/* 017B18 70016F18 8FA50058 */   lw    $a1, 0x58($sp)
/* 017B1C 70016F1C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 017B20 70016F20 27BD0058 */  addiu $sp, $sp, 0x58
/* 017B24 70016F24 03E00008 */  jr    $ra
/* 017B28 70016F28 00000000 */   nop   

