# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSetCompare
/* 0204E0 7001F8E0 40845800 */  mtc0  $a0, $11
/* 0204E4 7001F8E4 03E00008 */  jr    $ra
/* 0204E8 7001F8E8 00000000 */   nop   

