# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSetHWIntrRoutine
/* 0188E0 70017CE0 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 0188E4 70017CE4 AFBF001C */  sw    $ra, 0x1c($sp)
/* 0188E8 70017CE8 AFA40028 */  sw    $a0, 0x28($sp)
/* 0188EC 70017CEC AFA5002C */  sw    $a1, 0x2c($sp)
/* 0188F0 70017CF0 0C00617C */  jal   __osDisableInt
/* 0188F4 70017CF4 AFB00018 */   sw    $s0, 0x18($sp)
/* 0188F8 70017CF8 8FAF0028 */  lw    $t7, 0x28($sp)
/* 0188FC 70017CFC 8FAE002C */  lw    $t6, 0x2c($sp)
/* 018900 70017D00 3C018002 */  lui   $at, %hi(__osHwIntTable)
/* 018904 70017D04 000FC080 */  sll   $t8, $t7, 2
/* 018908 70017D08 00408025 */  move  $s0, $v0
/* 01890C 70017D0C 00380821 */  addu  $at, $at, $t8
/* 018910 70017D10 02002025 */  move  $a0, $s0
/* 018914 70017D14 0C006184 */  jal   __osRestoreInt
/* 018918 70017D18 AC2E7700 */   sw    $t6, %lo(__osHwIntTable)($at)
/* 01891C 70017D1C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 018920 70017D20 8FB00018 */  lw    $s0, 0x18($sp)
/* 018924 70017D24 27BD0028 */  addiu $sp, $sp, 0x28
/* 018928 70017D28 03E00008 */  jr    $ra
/* 01892C 70017D2C 00000000 */   nop   
