# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSiDeviceBusy
/* 020320 7001F720 3C0EA480 */  lui   $t6, %hi(SI_STATUS_REG) # $t6, 0xa480
/* 020324 7001F724 8DC40018 */  lw    $a0, %lo(SI_STATUS_REG)($t6)
/* 020328 7001F728 27BDFFF8 */  addiu $sp, $sp, -8
/* 02032C 7001F72C 308F0003 */  andi  $t7, $a0, 3
/* 020330 7001F730 11E00003 */  beqz  $t7, .L7001F740
/* 020334 7001F734 00000000 */   nop   
/* 020338 7001F738 10000002 */  b     .L7001F744
/* 02033C 7001F73C 24020001 */   li    $v0, 1
.L7001F740:
/* 020340 7001F740 00001025 */  move  $v0, $zero
.L7001F744:
/* 020344 7001F744 03E00008 */  jr    $ra
/* 020348 7001F748 27BD0008 */   addiu $sp, $sp, 8

