# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSiCreateAccessQueue
/* 016A10 70015E10 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 016A14 70015E14 AFBF0014 */  sw    $ra, 0x14($sp)
/* 016A18 70015E18 240E0001 */  li    $t6, 1
/* 016A1C 70015E1C 3C018002 */  lui   $at, %hi(__osSiAccessQueueEnabled)
/* 016A20 70015E20 3C048006 */  lui   $a0, %hi(__osSiAccessQueue)
/* 016A24 70015E24 3C058006 */  lui   $a1, %hi(__osSiAccessBuf)
/* 016A28 70015E28 AC2E77C0 */  sw    $t6, %lo(__osSiAccessQueueEnabled)($at)
/* 016A2C 70015E2C 24A57DB0 */  addiu $a1, %lo(__osSiAccessBuf) # addiu $a1, $a1, 0x7db0
/* 016A30 70015E30 24847DB8 */  addiu $a0, %lo(__osSiAccessQueue) # addiu $a0, $a0, 0x7db8
/* 016A34 70015E34 0C0035B4 */  jal   osCreateMesgQueue
/* 016A38 70015E38 24060001 */   li    $a2, 1
/* 016A3C 70015E3C 3C048006 */  lui   $a0, %hi(__osSiAccessQueue)
/* 016A40 70015E40 24847DB8 */  addiu $a0, %lo(__osSiAccessQueue) # addiu $a0, $a0, 0x7db8
/* 016A44 70015E44 00002825 */  move  $a1, $zero
/* 016A48 70015E48 0C0037C4 */  jal   osSendMesg
/* 016A4C 70015E4C 00003025 */   move  $a2, $zero
/* 016A50 70015E50 8FBF0014 */  lw    $ra, 0x14($sp)
/* 016A54 70015E54 27BD0018 */  addiu $sp, $sp, 0x18
/* 016A58 70015E58 03E00008 */  jr    $ra
/* 016A5C 70015E5C 00000000 */   nop   

glabel __osSiGetAccess
/* 016A60 70015E60 3C0E8002 */  lui   $t6, %hi(__osSiAccessQueueEnabled) 
/* 016A64 70015E64 8DCE77C0 */  lw    $t6, %lo(__osSiAccessQueueEnabled)($t6)
/* 016A68 70015E68 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 016A6C 70015E6C AFBF0014 */  sw    $ra, 0x14($sp)
/* 016A70 70015E70 15C00003 */  bnez  $t6, .L70015E80
/* 016A74 70015E74 00000000 */   nop   
/* 016A78 70015E78 0C005784 */  jal   __osSiCreateAccessQueue
/* 016A7C 70015E7C 00000000 */   nop   
.L70015E80:
/* 016A80 70015E80 3C048006 */  lui   $a0, %hi(__osSiAccessQueue)
/* 016A84 70015E84 24847DB8 */  addiu $a0, %lo(__osSiAccessQueue) # addiu $a0, $a0, 0x7db8
/* 016A88 70015E88 27A5001C */  addiu $a1, $sp, 0x1c
/* 016A8C 70015E8C 0C003774 */  jal   osRecvMesg
/* 016A90 70015E90 24060001 */   li    $a2, 1
/* 016A94 70015E94 8FBF0014 */  lw    $ra, 0x14($sp)
/* 016A98 70015E98 27BD0020 */  addiu $sp, $sp, 0x20
/* 016A9C 70015E9C 03E00008 */  jr    $ra
/* 016AA0 70015EA0 00000000 */   nop   

glabel __osSiRelAccess
/* 016AA4 70015EA4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 016AA8 70015EA8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 016AAC 70015EAC 3C048006 */  lui   $a0, %hi(__osSiAccessQueue)
/* 016AB0 70015EB0 24847DB8 */  addiu $a0, %lo(__osSiAccessQueue) # addiu $a0, $a0, 0x7db8
/* 016AB4 70015EB4 00002825 */  move  $a1, $zero
/* 016AB8 70015EB8 0C0037C4 */  jal   osSendMesg
/* 016ABC 70015EBC 00003025 */   move  $a2, $zero
/* 016AC0 70015EC0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 016AC4 70015EC4 27BD0018 */  addiu $sp, $sp, 0x18
/* 016AC8 70015EC8 03E00008 */  jr    $ra
/* 016ACC 70015ECC 00000000 */   nop   

.section .data
__osSiAccessQueueEnabled:
glabel __osSiAccessQueueEnabled
.word 0

.align 4
.section .bss
glabel __osSiAccessBuf
.word 0, 0
glabel __osSiAccessQueue
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0
.byte 0, 0, 0, 0

