# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSiRawStartDma
/* 016AD0 70015ED0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 016AD4 70015ED4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 016AD8 70015ED8 AFA40018 */  sw    $a0, 0x18($sp)
/* 016ADC 70015EDC 0C007DC8 */  jal   __osSiDeviceBusy
/* 016AE0 70015EE0 AFA5001C */   sw    $a1, 0x1c($sp)
/* 016AE4 70015EE4 10400003 */  beqz  $v0, .L70015EF4
/* 016AE8 70015EE8 00000000 */   nop   
/* 016AEC 70015EEC 1000001F */  b     .L70015F6C
/* 016AF0 70015EF0 2402FFFF */   li    $v0, -1
.L70015EF4:
/* 016AF4 70015EF4 8FAE0018 */  lw    $t6, 0x18($sp)
/* 016AF8 70015EF8 24010001 */  li    $at, 1
/* 016AFC 70015EFC 15C10004 */  bne   $t6, $at, .L70015F10
/* 016B00 70015F00 00000000 */   nop   
/* 016B04 70015F04 8FA4001C */  lw    $a0, 0x1c($sp)
/* 016B08 70015F08 0C0042F4 */  jal   osWritebackDCache
/* 016B0C 70015F0C 24050040 */   li    $a1, 64
.L70015F10:
/* 016B10 70015F10 0C003A2C */  jal   osVirtualToPhysical
/* 016B14 70015F14 8FA4001C */   lw    $a0, 0x1c($sp)
/* 016B18 70015F18 3C0FA480 */  lui   $t7, 0xa480
/* 016B1C 70015F1C ADE20000 */  sw    $v0, ($t7)
/* 016B20 70015F20 8FB80018 */  lw    $t8, 0x18($sp)
/* 016B24 70015F24 17000006 */  bnez  $t8, .L70015F40
/* 016B28 70015F28 00000000 */   nop   
/* 016B2C 70015F2C 3C191FC0 */  lui   $t9, (0x1FC007C0 >> 16) # lui $t9, 0x1fc0
/* 016B30 70015F30 373907C0 */  ori   $t9, (0x1FC007C0 & 0xFFFF) # ori $t9, $t9, 0x7c0
/* 016B34 70015F34 3C08A480 */  lui   $t0, %hi(SI_PIF_ADDR_RD64B_REG) # $t0, 0xa480
/* 016B38 70015F38 10000005 */  b     .L70015F50
/* 016B3C 70015F3C AD190004 */   sw    $t9, %lo(SI_PIF_ADDR_RD64B_REG)($t0)
.L70015F40:
/* 016B40 70015F40 3C091FC0 */  lui   $t1, (0x1FC007C0 >> 16) # lui $t1, 0x1fc0
/* 016B44 70015F44 352907C0 */  ori   $t1, (0x1FC007C0 & 0xFFFF) # ori $t1, $t1, 0x7c0
/* 016B48 70015F48 3C0AA480 */  lui   $t2, %hi(SI_PIF_ADDR_WR64B_REG) # $t2, 0xa480
/* 016B4C 70015F4C AD490010 */  sw    $t1, %lo(SI_PIF_ADDR_WR64B_REG)($t2)
.L70015F50:
/* 016B50 70015F50 8FAB0018 */  lw    $t3, 0x18($sp)
/* 016B54 70015F54 15600004 */  bnez  $t3, .L70015F68
/* 016B58 70015F58 00000000 */   nop   
/* 016B5C 70015F5C 8FA4001C */  lw    $a0, 0x1c($sp)
/* 016B60 70015F60 0C0042C8 */  jal   osInvalDCache
/* 016B64 70015F64 24050040 */   li    $a1, 64
.L70015F68:
/* 016B68 70015F68 00001025 */  move  $v0, $zero
.L70015F6C:
/* 016B6C 70015F6C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 016B70 70015F70 27BD0018 */  addiu $sp, $sp, 0x18
/* 016B74 70015F74 03E00008 */  jr    $ra
/* 016B78 70015F78 00000000 */   nop   

/* 016B7C 70015F7C 00000000 */  nop   
