# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSiRawWriteIo
/* 018790 70017B90 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 018794 70017B94 AFBF0014 */  sw    $ra, 0x14($sp)
/* 018798 70017B98 AFA40018 */  sw    $a0, 0x18($sp)
/* 01879C 70017B9C 0C007DC8 */  jal   __osSiDeviceBusy
/* 0187A0 70017BA0 AFA5001C */   sw    $a1, 0x1c($sp)
/* 0187A4 70017BA4 10400003 */  beqz  $v0, .L70017BB4
/* 0187A8 70017BA8 00000000 */   nop   
/* 0187AC 70017BAC 10000007 */  b     .L70017BCC
/* 0187B0 70017BB0 2402FFFF */   li    $v0, -1
.L70017BB4:
/* 0187B4 70017BB4 8FAF0018 */  lw    $t7, 0x18($sp)
/* 0187B8 70017BB8 8FAE001C */  lw    $t6, 0x1c($sp)
/* 0187BC 70017BBC 3C01A000 */  lui   $at, 0xa000
/* 0187C0 70017BC0 01E1C025 */  or    $t8, $t7, $at
/* 0187C4 70017BC4 00001025 */  move  $v0, $zero
/* 0187C8 70017BC8 AF0E0000 */  sw    $t6, ($t8)
.L70017BCC:
/* 0187CC 70017BCC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0187D0 70017BD0 27BD0018 */  addiu $sp, $sp, 0x18
/* 0187D4 70017BD4 03E00008 */  jr    $ra
/* 0187D8 70017BD8 00000000 */   nop   

/* 0187DC 70017BDC 00000000 */  nop   
