# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSiRawReadIo
/* 018740 70017B40 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 018744 70017B44 AFBF0014 */  sw    $ra, 0x14($sp)
/* 018748 70017B48 AFA40018 */  sw    $a0, 0x18($sp)
/* 01874C 70017B4C 0C007DC8 */  jal   __osSiDeviceBusy
/* 018750 70017B50 AFA5001C */   sw    $a1, 0x1c($sp)
/* 018754 70017B54 10400003 */  beqz  $v0, .L70017B64
/* 018758 70017B58 00000000 */   nop   
/* 01875C 70017B5C 10000008 */  b     .L70017B80
/* 018760 70017B60 2402FFFF */   li    $v0, -1
.L70017B64:
/* 018764 70017B64 8FAE0018 */  lw    $t6, 0x18($sp)
/* 018768 70017B68 3C01A000 */  lui   $at, 0xa000
/* 01876C 70017B6C 8FB9001C */  lw    $t9, 0x1c($sp)
/* 018770 70017B70 01C17825 */  or    $t7, $t6, $at
/* 018774 70017B74 8DF80000 */  lw    $t8, ($t7)
/* 018778 70017B78 00001025 */  move  $v0, $zero
/* 01877C 70017B7C AF380000 */  sw    $t8, ($t9)
.L70017B80:
/* 018780 70017B80 8FBF0014 */  lw    $ra, 0x14($sp)
/* 018784 70017B84 27BD0018 */  addiu $sp, $sp, 0x18
/* 018788 70017B88 03E00008 */  jr    $ra
/* 01878C 70017B8C 00000000 */   nop   
