# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSpDeviceBusy
/* 019BC0 70018FC0 3C0EA404 */  lui   $t6, %hi(SP_STATUS_REG) # $t6, 0xa404
/* 019BC4 70018FC4 8DC40010 */  lw    $a0, %lo(SP_STATUS_REG)($t6)
/* 019BC8 70018FC8 27BDFFF8 */  addiu $sp, $sp, -8
/* 019BCC 70018FCC 308F001C */  andi  $t7, $a0, 0x1c
/* 019BD0 70018FD0 11E00003 */  beqz  $t7, .L70018FE0
/* 019BD4 70018FD4 00000000 */   nop   
/* 019BD8 70018FD8 10000002 */  b     .L70018FE4
/* 019BDC 70018FDC 24020001 */   li    $v0, 1
.L70018FE0:
/* 019BE0 70018FE0 00001025 */  move  $v0, $zero
.L70018FE4:
/* 019BE4 70018FE4 03E00008 */  jr    $ra
/* 019BE8 70018FE8 27BD0008 */   addiu $sp, $sp, 8

