# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSpGetStatus
/* 019AD0 70018ED0 3C0EA404 */  lui   $t6, 0xa404
/* 019AD4 70018ED4 03E00008 */  jr    $ra
/* 019AD8 70018ED8 8DC20010 */   lw    $v0, 0x10($t6)


