# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSpSetPc
/* 019AF0 70018EF0 3C0EA404 */  lui   $t6, %hi(SP_STATUS_REG) # $t6, 0xa404
/* 019AF4 70018EF4 8DC50010 */  lw    $a1, %lo(SP_STATUS_REG)($t6)
/* 019AF8 70018EF8 27BDFFF8 */  addiu $sp, $sp, -8
/* 019AFC 70018EFC 30AF0001 */  andi  $t7, $a1, 1
/* 019B00 70018F00 15E00003 */  bnez  $t7, .L70018F10
/* 019B04 70018F04 00000000 */   nop   
/* 019B08 70018F08 10000004 */  b     .L70018F1C
/* 019B0C 70018F0C 2402FFFF */   li    $v0, -1
.L70018F10:
/* 019B10 70018F10 3C18A408 */  lui   $t8, 0xa408
/* 019B14 70018F14 AF040000 */  sw    $a0, ($t8)
/* 019B18 70018F18 00001025 */  move  $v0, $zero
.L70018F1C:
/* 019B1C 70018F1C 03E00008 */  jr    $ra
/* 019B20 70018F20 27BD0008 */   addiu $sp, $sp, 8

