# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osSpSetStatus
/* 019AE0 70018EE0 3C0EA404 */  lui   $t6, 0xa404
/* 019AE4 70018EE4 03E00008 */  jr    $ra
/* 019AE8 70018EE8 ADC40010 */   sw    $a0, 0x10($t6)

