# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alSynAllocFX
/* 01A4C0 700198C0 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 01A4C4 700198C4 00054400 */  sll   $t0, $a1, 0x10
/* 01A4C8 700198C8 00087403 */  sra   $t6, $t0, 0x10
/* 01A4CC 700198CC AFB10018 */  sw    $s1, 0x18($sp)
/* 01A4D0 700198D0 000E8880 */  sll   $s1, $t6, 2
/* 01A4D4 700198D4 AFBF001C */  sw    $ra, 0x1c($sp)
/* 01A4D8 700198D8 AFB00014 */  sw    $s0, 0x14($sp)
/* 01A4DC 700198DC AFA50024 */  sw    $a1, 0x24($sp)
/* 01A4E0 700198E0 022E8821 */  addu  $s1, $s1, $t6
/* 01A4E4 700198E4 8C8F0034 */  lw    $t7, 0x34($a0)
/* 01A4E8 700198E8 00118880 */  sll   $s1, $s1, 2
/* 01A4EC 700198EC 022E8823 */  subu  $s1, $s1, $t6
/* 01A4F0 700198F0 00808025 */  move  $s0, $a0
/* 01A4F4 700198F4 00118880 */  sll   $s1, $s1, 2
/* 01A4F8 700198F8 00C02825 */  move  $a1, $a2
/* 01A4FC 700198FC 01F12021 */  addu  $a0, $t7, $s1
/* 01A500 70019900 24840020 */  addiu $a0, $a0, 0x20
/* 01A504 70019904 0C006520 */  jal   alFxNew
/* 01A508 70019908 00E03025 */   move  $a2, $a3
/* 01A50C 7001990C 8E180034 */  lw    $t8, 0x34($s0)
/* 01A510 70019910 24050001 */  li    $a1, 1
/* 01A514 70019914 03113021 */  addu  $a2, $t8, $s1
/* 01A518 70019918 0C008070 */  jal   alFxParam
/* 01A51C 7001991C 24C40020 */   addiu $a0, $a2, 0x20
/* 01A520 70019920 8E190034 */  lw    $t9, 0x34($s0)
/* 01A524 70019924 8E040030 */  lw    $a0, 0x30($s0)
/* 01A528 70019928 24050002 */  li    $a1, 2
/* 01A52C 7001992C 03313021 */  addu  $a2, $t9, $s1
/* 01A530 70019930 0C006658 */  jal   alMainBusParam
/* 01A534 70019934 24C60020 */   addiu $a2, $a2, 0x20
/* 01A538 70019938 8E0A0034 */  lw    $t2, 0x34($s0)
/* 01A53C 7001993C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 01A540 70019940 8FB00014 */  lw    $s0, 0x14($sp)
/* 01A544 70019944 01511021 */  addu  $v0, $t2, $s1
/* 01A548 70019948 8FB10018 */  lw    $s1, 0x18($sp)
/* 01A54C 7001994C 27BD0020 */  addiu $sp, $sp, 0x20
/* 01A550 70019950 03E00008 */  jr    $ra
/* 01A554 70019954 24420020 */   addiu $v0, $v0, 0x20

