# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alSynDelete
/* 019CE0 700190E0 03E00008 */  jr    $ra
/* 019CE4 700190E4 AC800000 */   sw    $zero, ($a0)

