# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alSynStartVoiceParams
/* 01E1A0 7001D5A0 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 01E1A4 7001D5A4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 01E1A8 7001D5A8 AFA50024 */  sw    $a1, 0x24($sp)
/* 01E1AC 7001D5AC AFA60028 */  sw    $a2, 0x28($sp)
/* 01E1B0 7001D5B0 AFA7002C */  sw    $a3, 0x2c($sp)
/* 01E1B4 7001D5B4 8CAE0008 */  lw    $t6, 8($a1)
/* 01E1B8 7001D5B8 51C0002F */  beql  $t6, $zero, .L7001D678
/* 01E1BC 7001D5BC 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01E1C0 7001D5C0 AFA40020 */  sw    $a0, 0x20($sp)
/* 01E1C4 7001D5C4 0C003C34 */  jal   __allocParam
/* 01E1C8 7001D5C8 AFA50024 */   sw    $a1, 0x24($sp)
/* 01E1CC 7001D5CC 8FA40020 */  lw    $a0, 0x20($sp)
/* 01E1D0 7001D5D0 8FA70024 */  lw    $a3, 0x24($sp)
/* 01E1D4 7001D5D4 10400027 */  beqz  $v0, .L7001D674
/* 01E1D8 7001D5D8 00403025 */   move  $a2, $v0
/* 01E1DC 7001D5DC 93A3003B */  lbu   $v1, 0x3b($sp)
/* 01E1E0 7001D5E0 04610004 */  bgez  $v1, .L7001D5F4
/* 01E1E4 7001D5E4 00601025 */   move  $v0, $v1
/* 01E1E8 7001D5E8 00021823 */  negu  $v1, $v0
/* 01E1EC 7001D5EC 306F00FF */  andi  $t7, $v1, 0xff
/* 01E1F0 7001D5F0 01E01825 */  move  $v1, $t7
.L7001D5F4:
/* 01E1F4 7001D5F4 8CF90008 */  lw    $t9, 8($a3)
/* 01E1F8 7001D5F8 8C98001C */  lw    $t8, 0x1c($a0)
/* 01E1FC 7001D5FC 240A000D */  li    $t2, 13
/* 01E200 7001D600 8F2800D8 */  lw    $t0, 0xd8($t9)
/* 01E204 7001D604 ACC00000 */  sw    $zero, ($a2)
/* 01E208 7001D608 A4CA0008 */  sh    $t2, 8($a2)
/* 01E20C 7001D60C 03084821 */  addu  $t1, $t8, $t0
/* 01E210 7001D610 ACC90004 */  sw    $t1, 4($a2)
/* 01E214 7001D614 84EB001A */  lh    $t3, 0x1a($a3)
/* 01E218 7001D618 A4CB000A */  sh    $t3, 0xa($a2)
/* 01E21C 7001D61C 93AC0037 */  lbu   $t4, 0x37($sp)
/* 01E220 7001D620 A0CC0012 */  sb    $t4, 0x12($a2)
/* 01E224 7001D624 87AD0032 */  lh    $t5, 0x32($sp)
/* 01E228 7001D628 A0C30013 */  sb    $v1, 0x13($a2)
/* 01E22C 7001D62C A4CD0010 */  sh    $t5, 0x10($a2)
/* 01E230 7001D630 C7A4002C */  lwc1  $f4, 0x2c($sp)
/* 01E234 7001D634 E4C4000C */  swc1  $f4, 0xc($a2)
/* 01E238 7001D638 AFA70024 */  sw    $a3, 0x24($sp)
/* 01E23C 7001D63C AFA6001C */  sw    $a2, 0x1c($sp)
/* 01E240 7001D640 0C003BF2 */  jal   _timeToSamples
/* 01E244 7001D644 8FA5003C */   lw    $a1, 0x3c($sp)
/* 01E248 7001D648 8FA6001C */  lw    $a2, 0x1c($sp)
/* 01E24C 7001D64C 8FA70024 */  lw    $a3, 0x24($sp)
/* 01E250 7001D650 24050003 */  li    $a1, 3
/* 01E254 7001D654 ACC20014 */  sw    $v0, 0x14($a2)
/* 01E258 7001D658 8FAE0028 */  lw    $t6, 0x28($sp)
/* 01E25C 7001D65C ACCE0018 */  sw    $t6, 0x18($a2)
/* 01E260 7001D660 8CEF0008 */  lw    $t7, 8($a3)
/* 01E264 7001D664 8DE4000C */  lw    $a0, 0xc($t7)
/* 01E268 7001D668 8C990008 */  lw    $t9, 8($a0)
/* 01E26C 7001D66C 0320F809 */  jalr  $t9
/* 01E270 7001D670 00000000 */  nop   
.L7001D674:
/* 01E274 7001D674 8FBF0014 */  lw    $ra, 0x14($sp)
.L7001D678:
/* 01E278 7001D678 27BD0020 */  addiu $sp, $sp, 0x20
/* 01E27C 7001D67C 03E00008 */  jr    $ra
/* 01E280 7001D680 00000000 */   nop   

