# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel alSynSetPriority
/* 021740 70020B40 AFA40000 */  sw    $a0, ($sp)
/* 021744 70020B44 AFA60008 */  sw    $a2, 8($sp)
/* 021748 70020B48 03E00008 */  jr    $ra
/* 02174C 70020B4C A4A60016 */   sh    $a2, 0x16($a1)
