# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osTimerServicesInit
/* 019230 70018630 3C018007 */  lui   $at, %hi(__osCurrentTime)
/* 019234 70018634 240E0000 */  li    $t6, 0
/* 019238 70018638 240F0000 */  li    $t7, 0
/* 01923C 7001863C AC2F8E14 */  sw    $t7, %lo(__osCurrentTime+4)($at)
/* 019240 70018640 AC2E8E10 */  sw    $t6, %lo(__osCurrentTime)($at)
/* 019244 70018644 3C018007 */  lui   $at, %hi(__osBaseCounter)
/* 019248 70018648 3C188002 */  lui   $t8, %hi(__osTimerList) 
/* 01924C 7001864C 8F187FD0 */  lw    $t8, %lo(__osTimerList)($t8)
/* 019250 70018650 AC208E18 */  sw    $zero, %lo(__osBaseCounter)($at)
/* 019254 70018654 3C018007 */  lui   $at, %hi(__osViIntrCount)
/* 019258 70018658 AC208E1C */  sw    $zero, %lo(__osViIntrCount)($at)
/* 01925C 7001865C 3C198002 */  lui   $t9, %hi(__osTimerList) 
/* 019260 70018660 AF180004 */  sw    $t8, 4($t8)
/* 019264 70018664 8F397FD0 */  lw    $t9, %lo(__osTimerList)($t9)
/* 019268 70018668 3C098002 */  lui   $t1, %hi(__osTimerList) 
/* 01926C 7001866C 240A0000 */  li    $t2, 0
/* 019270 70018670 8F280004 */  lw    $t0, 4($t9)
/* 019274 70018674 240B0000 */  li    $t3, 0
/* 019278 70018678 3C0C8002 */  lui   $t4, %hi(__osTimerList) 
/* 01927C 7001867C AF280000 */  sw    $t0, ($t9)
/* 019280 70018680 8D297FD0 */  lw    $t1, %lo(__osTimerList)($t1)
/* 019284 70018684 3C0D8002 */  lui   $t5, %hi(__osTimerList) 
/* 019288 70018688 3C188002 */  lui   $t8, %hi(__osTimerList) 
/* 01928C 7001868C AD2A0010 */  sw    $t2, 0x10($t1)
/* 019290 70018690 AD2B0014 */  sw    $t3, 0x14($t1)
/* 019294 70018694 8D8C7FD0 */  lw    $t4, %lo(__osTimerList)($t4)
/* 019298 70018698 8D8E0010 */  lw    $t6, 0x10($t4)
/* 01929C 7001869C 8D8F0014 */  lw    $t7, 0x14($t4)
/* 0192A0 700186A0 AD8E0008 */  sw    $t6, 8($t4)
/* 0192A4 700186A4 AD8F000C */  sw    $t7, 0xc($t4)
/* 0192A8 700186A8 8DAD7FD0 */  lw    $t5, %lo(__osTimerList)($t5)
/* 0192AC 700186AC ADA00018 */  sw    $zero, 0x18($t5)
/* 0192B0 700186B0 8F187FD0 */  lw    $t8, %lo(__osTimerList)($t8)
/* 0192B4 700186B4 03E00008 */  jr    $ra
/* 0192B8 700186B8 AF00001C */   sw    $zero, 0x1c($t8)

glabel __osTimerInterrupt
/* 0192BC 700186BC 3C0E8002 */  lui   $t6, %hi(__osTimerList) 
/* 0192C0 700186C0 8DCE7FD0 */  lw    $t6, %lo(__osTimerList)($t6)
/* 0192C4 700186C4 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 0192C8 700186C8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0192CC 700186CC 8DCF0000 */  lw    $t7, ($t6)
/* 0192D0 700186D0 11EE0054 */  beq   $t7, $t6, .L70018824
/* 0192D4 700186D4 00000000 */   nop   
.L700186D8:
/* 0192D8 700186D8 3C188002 */  lui   $t8, %hi(__osTimerList) 
/* 0192DC 700186DC 8F187FD0 */  lw    $t8, %lo(__osTimerList)($t8)
/* 0192E0 700186E0 8F190000 */  lw    $t9, ($t8)
/* 0192E4 700186E4 17380006 */  bne   $t9, $t8, .L70018700
/* 0192E8 700186E8 AFB90024 */   sw    $t9, 0x24($sp)
/* 0192EC 700186EC 0C007E38 */  jal   __osSetCompare
/* 0192F0 700186F0 00002025 */   move  $a0, $zero
/* 0192F4 700186F4 3C018007 */  lui   $at, %hi(__osTimerCounter)
/* 0192F8 700186F8 1000004A */  b     .L70018824
/* 0192FC 700186FC AC208E20 */   sw    $zero, %lo(__osTimerCounter)($at)
.L70018700:
/* 019300 70018700 0C003638 */  jal   osGetCount
/* 019304 70018704 00000000 */   nop   
/* 019308 70018708 AFA20020 */  sw    $v0, 0x20($sp)
/* 01930C 7001870C 3C098007 */  lui   $t1, %hi(__osTimerCounter) 
/* 019310 70018710 8D298E20 */  lw    $t1, %lo(__osTimerCounter)($t1)
/* 019314 70018714 8FA80020 */  lw    $t0, 0x20($sp)
/* 019318 70018718 8FAF0024 */  lw    $t7, 0x24($sp)
/* 01931C 7001871C 3C018007 */  lui   $at, %hi(__osTimerCounter)
/* 019320 70018720 01095023 */  subu  $t2, $t0, $t1
/* 019324 70018724 AFAA001C */  sw    $t2, 0x1c($sp)
/* 019328 70018728 AC288E20 */  sw    $t0, %lo(__osTimerCounter)($at)
/* 01932C 7001872C 8DEE0010 */  lw    $t6, 0x10($t7)
/* 019330 70018730 8FAB001C */  lw    $t3, 0x1c($sp)
/* 019334 70018734 240C0000 */  li    $t4, 0
/* 019338 70018738 01E0C825 */  move  $t9, $t7
/* 01933C 7001873C 01CC082B */  sltu  $at, $t6, $t4
/* 019340 70018740 8DEF0014 */  lw    $t7, 0x14($t7)
/* 019344 70018744 14200016 */  bnez  $at, .L700187A0
/* 019348 70018748 01606825 */   move  $t5, $t3
/* 01934C 7001874C 018E082B */  sltu  $at, $t4, $t6
/* 019350 70018750 14200003 */  bnez  $at, .L70018760
/* 019354 70018754 01AF082B */   sltu  $at, $t5, $t7
/* 019358 70018758 10200011 */  beqz  $at, .L700187A0
/* 01935C 7001875C 00000000 */   nop   
.L70018760:
/* 019360 70018760 27380010 */  addiu $t8, $t9, 0x10
/* 019364 70018764 AFB80018 */  sw    $t8, 0x18($sp)
/* 019368 70018768 8F2B0014 */  lw    $t3, 0x14($t9)
/* 01936C 7001876C 8F2A0010 */  lw    $t2, 0x10($t9)
/* 019370 70018770 016D082B */  sltu  $at, $t3, $t5
/* 019374 70018774 014C4023 */  subu  $t0, $t2, $t4
/* 019378 70018778 01014023 */  subu  $t0, $t0, $at
/* 01937C 7001877C 016D4823 */  subu  $t1, $t3, $t5
/* 019380 70018780 AF290014 */  sw    $t1, 0x14($t9)
/* 019384 70018784 AF280010 */  sw    $t0, 0x10($t9)
/* 019388 70018788 8FAE0024 */  lw    $t6, 0x24($sp)
/* 01938C 7001878C 8DC40010 */  lw    $a0, 0x10($t6)
/* 019390 70018790 0C00620D */  jal   __osSetTimerIntr
/* 019394 70018794 8DC50014 */   lw    $a1, 0x14($t6)
/* 019398 70018798 10000022 */  b     .L70018824
/* 01939C 7001879C 00000000 */   nop   
.L700187A0:
/* 0193A0 700187A0 8FAF0024 */  lw    $t7, 0x24($sp)
/* 0193A4 700187A4 8DF80000 */  lw    $t8, ($t7)
/* 0193A8 700187A8 8DEA0004 */  lw    $t2, 4($t7)
/* 0193AC 700187AC AD580000 */  sw    $t8, ($t2)
/* 0193B0 700187B0 8FAB0024 */  lw    $t3, 0x24($sp)
/* 0193B4 700187B4 8D6C0004 */  lw    $t4, 4($t3)
/* 0193B8 700187B8 8D6D0000 */  lw    $t5, ($t3)
/* 0193BC 700187BC ADAC0004 */  sw    $t4, 4($t5)
/* 0193C0 700187C0 8FA80024 */  lw    $t0, 0x24($sp)
/* 0193C4 700187C4 AD000000 */  sw    $zero, ($t0)
/* 0193C8 700187C8 8FA90024 */  lw    $t1, 0x24($sp)
/* 0193CC 700187CC AD200004 */  sw    $zero, 4($t1)
/* 0193D0 700187D0 8FB90024 */  lw    $t9, 0x24($sp)
/* 0193D4 700187D4 8F2E0018 */  lw    $t6, 0x18($t9)
/* 0193D8 700187D8 11C00005 */  beqz  $t6, .L700187F0
/* 0193DC 700187DC 00000000 */   nop   
/* 0193E0 700187E0 01C02025 */  move  $a0, $t6
/* 0193E4 700187E4 8F25001C */  lw    $a1, 0x1c($t9)
/* 0193E8 700187E8 0C0037C4 */  jal   osSendMesg
/* 0193EC 700187EC 00003025 */   move  $a2, $zero
.L700187F0:
/* 0193F0 700187F0 8FAF0024 */  lw    $t7, 0x24($sp)
/* 0193F4 700187F4 8DF80008 */  lw    $t8, 8($t7)
/* 0193F8 700187F8 8DF9000C */  lw    $t9, 0xc($t7)
/* 0193FC 700187FC 17000003 */  bnez  $t8, .L7001880C
/* 019400 70018800 00000000 */   nop   
/* 019404 70018804 1320FFB4 */  beqz  $t9, .L700186D8
/* 019408 70018808 00000000 */   nop   
.L7001880C:
/* 01940C 7001880C ADF80010 */  sw    $t8, 0x10($t7)
/* 019410 70018810 ADF90014 */  sw    $t9, 0x14($t7)
/* 019414 70018814 0C00622A */  jal   __osInsertTimer
/* 019418 70018818 8FA40024 */   lw    $a0, 0x24($sp)
/* 01941C 7001881C 1000FFAE */  b     .L700186D8
/* 019420 70018820 00000000 */   nop   
.L70018824:
/* 019424 70018824 8FBF0014 */  lw    $ra, 0x14($sp)
/* 019428 70018828 27BD0028 */  addiu $sp, $sp, 0x28
/* 01942C 7001882C 03E00008 */  jr    $ra
/* 019430 70018830 00000000 */   nop   

glabel __osSetTimerIntr
/* 019434 70018834 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 019438 70018838 AFBF0014 */  sw    $ra, 0x14($sp)
/* 01943C 7001883C AFA40028 */  sw    $a0, 0x28($sp)
/* 019440 70018840 0C00617C */  jal   __osDisableInt
/* 019444 70018844 AFA5002C */   sw    $a1, 0x2c($sp)
/* 019448 70018848 0C003638 */  jal   osGetCount
/* 01944C 7001884C AFA2001C */   sw    $v0, 0x1c($sp)
/* 019450 70018850 3C018007 */  lui   $at, %hi(__osTimerCounter)
/* 019454 70018854 AC228E20 */  sw    $v0, %lo(__osTimerCounter)($at)
/* 019458 70018858 3C0E8007 */  lui   $t6, %hi(__osTimerCounter) 
/* 01945C 7001885C 8DCE8E20 */  lw    $t6, %lo(__osTimerCounter)($t6)
/* 019460 70018860 8FA9002C */  lw    $t1, 0x2c($sp)
/* 019464 70018864 8FA80028 */  lw    $t0, 0x28($sp)
/* 019468 70018868 01C0C825 */  move  $t9, $t6
/* 01946C 7001886C 03295821 */  addu  $t3, $t9, $t1
/* 019470 70018870 24180000 */  li    $t8, 0
/* 019474 70018874 0169082B */  sltu  $at, $t3, $t1
/* 019478 70018878 00385021 */  addu  $t2, $at, $t8
/* 01947C 7001887C 01485021 */  addu  $t2, $t2, $t0
/* 019480 70018880 AFAA0020 */  sw    $t2, 0x20($sp)
/* 019484 70018884 AFAB0024 */  sw    $t3, 0x24($sp)
/* 019488 70018888 0C007E38 */  jal   __osSetCompare
/* 01948C 7001888C 01602025 */   move  $a0, $t3
/* 019490 70018890 0C006184 */  jal   __osRestoreInt
/* 019494 70018894 8FA4001C */   lw    $a0, 0x1c($sp)
/* 019498 70018898 8FBF0014 */  lw    $ra, 0x14($sp)
/* 01949C 7001889C 27BD0028 */  addiu $sp, $sp, 0x28
/* 0194A0 700188A0 03E00008 */  jr    $ra
/* 0194A4 700188A4 00000000 */   nop   

glabel __osInsertTimer
/* 0194A8 700188A8 27BDFFC8 */  addiu $sp, $sp, -0x38
/* 0194AC 700188AC AFBF0014 */  sw    $ra, 0x14($sp)
/* 0194B0 700188B0 0C00617C */  jal   __osDisableInt
/* 0194B4 700188B4 AFA40038 */   sw    $a0, 0x38($sp)
/* 0194B8 700188B8 3C0E8002 */  lui   $t6, %hi(__osTimerList) 
/* 0194BC 700188BC 8DCE7FD0 */  lw    $t6, %lo(__osTimerList)($t6)
/* 0194C0 700188C0 AFA20024 */  sw    $v0, 0x24($sp)
/* 0194C4 700188C4 8FB80038 */  lw    $t8, 0x38($sp)
/* 0194C8 700188C8 8DCF0000 */  lw    $t7, ($t6)
/* 0194CC 700188CC AFAF0034 */  sw    $t7, 0x34($sp)
/* 0194D0 700188D0 8F090014 */  lw    $t1, 0x14($t8)
/* 0194D4 700188D4 8F080010 */  lw    $t0, 0x10($t8)
/* 0194D8 700188D8 AFA9002C */  sw    $t1, 0x2c($sp)
/* 0194DC 700188DC 11EE0029 */  beq   $t7, $t6, .L70018984
/* 0194E0 700188E0 AFA80028 */   sw    $t0, 0x28($sp)
/* 0194E4 700188E4 8DEA0010 */  lw    $t2, 0x10($t7)
/* 0194E8 700188E8 8DEB0014 */  lw    $t3, 0x14($t7)
/* 0194EC 700188EC 010A082B */  sltu  $at, $t0, $t2
/* 0194F0 700188F0 14200024 */  bnez  $at, .L70018984
/* 0194F4 700188F4 0148082B */   sltu  $at, $t2, $t0
/* 0194F8 700188F8 14200003 */  bnez  $at, .L70018908
/* 0194FC 700188FC 0169082B */   sltu  $at, $t3, $t1
/* 019500 70018900 10200020 */  beqz  $at, .L70018984
/* 019504 70018904 00000000 */   nop   
.L70018908:
/* 019508 70018908 27B90028 */  addiu $t9, $sp, 0x28
/* 01950C 7001890C 8FB80034 */  lw    $t8, 0x34($sp)
/* 019510 70018910 AFB90020 */  sw    $t9, 0x20($sp)
/* 019514 70018914 8F2D0004 */  lw    $t5, 4($t9)
/* 019518 70018918 8F2C0000 */  lw    $t4, ($t9)
/* 01951C 7001891C 8F0F0014 */  lw    $t7, 0x14($t8)
/* 019520 70018920 8F0E0010 */  lw    $t6, 0x10($t8)
/* 019524 70018924 3C188002 */  lui   $t8, %hi(__osTimerList) 
/* 019528 70018928 01AF082B */  sltu  $at, $t5, $t7
/* 01952C 7001892C 018E4023 */  subu  $t0, $t4, $t6
/* 019530 70018930 01014023 */  subu  $t0, $t0, $at
/* 019534 70018934 01AF4823 */  subu  $t1, $t5, $t7
/* 019538 70018938 AF290004 */  sw    $t1, 4($t9)
/* 01953C 7001893C AF280000 */  sw    $t0, ($t9)
/* 019540 70018940 8FAA0034 */  lw    $t2, 0x34($sp)
/* 019544 70018944 8F187FD0 */  lw    $t8, %lo(__osTimerList)($t8)
/* 019548 70018948 8D4B0000 */  lw    $t3, ($t2)
/* 01954C 7001894C 1178000D */  beq   $t3, $t8, .L70018984
/* 019550 70018950 AFAB0034 */   sw    $t3, 0x34($sp)
/* 019554 70018954 8FAC0028 */  lw    $t4, 0x28($sp)
/* 019558 70018958 8D6E0010 */  lw    $t6, 0x10($t3)
/* 01955C 7001895C 8FAD002C */  lw    $t5, 0x2c($sp)
/* 019560 70018960 8D6F0014 */  lw    $t7, 0x14($t3)
/* 019564 70018964 01CC082B */  sltu  $at, $t6, $t4
/* 019568 70018968 1420FFE7 */  bnez  $at, .L70018908
/* 01956C 7001896C 00000000 */   nop   
/* 019570 70018970 018E082B */  sltu  $at, $t4, $t6
/* 019574 70018974 14200003 */  bnez  $at, .L70018984
/* 019578 70018978 01ED082B */   sltu  $at, $t7, $t5
/* 01957C 7001897C 1420FFE2 */  bnez  $at, .L70018908
/* 019580 70018980 00000000 */   nop   
.L70018984:
/* 019584 70018984 8FB90038 */  lw    $t9, 0x38($sp)
/* 019588 70018988 8FA80028 */  lw    $t0, 0x28($sp)
/* 01958C 7001898C 8FA9002C */  lw    $t1, 0x2c($sp)
/* 019590 70018990 3C188002 */  lui   $t8, %hi(__osTimerList) 
/* 019594 70018994 AF280010 */  sw    $t0, 0x10($t9)
/* 019598 70018998 AF290014 */  sw    $t1, 0x14($t9)
/* 01959C 7001899C 8F187FD0 */  lw    $t8, %lo(__osTimerList)($t8)
/* 0195A0 700189A0 8FAA0034 */  lw    $t2, 0x34($sp)
/* 0195A4 700189A4 1158000D */  beq   $t2, $t8, .L700189DC
/* 0195A8 700189A8 00000000 */   nop   
/* 0195AC 700189AC 254B0010 */  addiu $t3, $t2, 0x10
/* 0195B0 700189B0 AFAB001C */  sw    $t3, 0x1c($sp)
/* 0195B4 700189B4 8D4D0014 */  lw    $t5, 0x14($t2)
/* 0195B8 700189B8 8D4C0010 */  lw    $t4, 0x10($t2)
/* 0195BC 700189BC 8FAE0028 */  lw    $t6, 0x28($sp)
/* 0195C0 700189C0 8FAF002C */  lw    $t7, 0x2c($sp)
/* 0195C4 700189C4 018E4023 */  subu  $t0, $t4, $t6
/* 0195C8 700189C8 01AF082B */  sltu  $at, $t5, $t7
/* 0195CC 700189CC 01014023 */  subu  $t0, $t0, $at
/* 0195D0 700189D0 01AF4823 */  subu  $t1, $t5, $t7
/* 0195D4 700189D4 AD490014 */  sw    $t1, 0x14($t2)
/* 0195D8 700189D8 AD480010 */  sw    $t0, 0x10($t2)
.L700189DC:
/* 0195DC 700189DC 8FB90034 */  lw    $t9, 0x34($sp)
/* 0195E0 700189E0 8FB80038 */  lw    $t8, 0x38($sp)
/* 0195E4 700189E4 AF190000 */  sw    $t9, ($t8)
/* 0195E8 700189E8 8FAB0034 */  lw    $t3, 0x34($sp)
/* 0195EC 700189EC 8FAD0038 */  lw    $t5, 0x38($sp)
/* 0195F0 700189F0 8D6C0004 */  lw    $t4, 4($t3)
/* 0195F4 700189F4 ADAC0004 */  sw    $t4, 4($t5)
/* 0195F8 700189F8 8FAF0034 */  lw    $t7, 0x34($sp)
/* 0195FC 700189FC 8FAE0038 */  lw    $t6, 0x38($sp)
/* 019600 70018A00 8DE80004 */  lw    $t0, 4($t7)
/* 019604 70018A04 AD0E0000 */  sw    $t6, ($t0)
/* 019608 70018A08 8FAA0034 */  lw    $t2, 0x34($sp)
/* 01960C 70018A0C 8FA90038 */  lw    $t1, 0x38($sp)
/* 019610 70018A10 AD490004 */  sw    $t1, 4($t2)
/* 019614 70018A14 0C006184 */  jal   __osRestoreInt
/* 019618 70018A18 8FA40024 */   lw    $a0, 0x24($sp)
/* 01961C 70018A1C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 019620 70018A20 8FA20028 */  lw    $v0, 0x28($sp)
/* 019624 70018A24 8FA3002C */  lw    $v1, 0x2c($sp)
/* 019628 70018A28 03E00008 */  jr    $ra
/* 01962C 70018A2C 27BD0038 */   addiu $sp, $sp, 0x38

.section .data
glabel __osTimerList
.word __osBaseTimer
.align 4
.section .bss
glabel __osBaseTimer
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
.byte 0
glabel __osCurrentTime
.word 0,0
glabel __osBaseCounter
.word 0
glabel __osViIntrCount
.word 0
glabel __osTimerCounter
.word 0
.word 0,0,0
