# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel guTranslateF
/* 0178D0 70016CD0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0178D4 70016CD4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0178D8 70016CD8 AFA5001C */  sw    $a1, 0x1c($sp)
/* 0178DC 70016CDC AFA60020 */  sw    $a2, 0x20($sp)
/* 0178E0 70016CE0 AFA70024 */  sw    $a3, 0x24($sp)
/* 0178E4 70016CE4 0C004004 */  jal   guMtxIdentF
/* 0178E8 70016CE8 AFA40018 */   sw    $a0, 0x18($sp)
/* 0178EC 70016CEC 8FA40018 */  lw    $a0, 0x18($sp)
/* 0178F0 70016CF0 C7A4001C */  lwc1  $f4, 0x1c($sp)
/* 0178F4 70016CF4 E4840030 */  swc1  $f4, 0x30($a0)
/* 0178F8 70016CF8 C7A60020 */  lwc1  $f6, 0x20($sp)
/* 0178FC 70016CFC E4860034 */  swc1  $f6, 0x34($a0)
/* 017900 70016D00 C7A80024 */  lwc1  $f8, 0x24($sp)
/* 017904 70016D04 E4880038 */  swc1  $f8, 0x38($a0)
/* 017908 70016D08 8FBF0014 */  lw    $ra, 0x14($sp)
/* 01790C 70016D0C 27BD0018 */  addiu $sp, $sp, 0x18
/* 017910 70016D10 03E00008 */  jr    $ra
/* 017914 70016D14 00000000 */   nop   

glabel guTranslate
/* 017918 70016D18 27BDFF98 */  addiu $sp, $sp, -0x68
/* 01791C 70016D1C AFBF0014 */  sw    $ra, 0x14($sp)
/* 017920 70016D20 AFA40068 */  sw    $a0, 0x68($sp)
/* 017924 70016D24 AFA5006C */  sw    $a1, 0x6c($sp)
/* 017928 70016D28 AFA60070 */  sw    $a2, 0x70($sp)
/* 01792C 70016D2C AFA70074 */  sw    $a3, 0x74($sp)
/* 017930 70016D30 0C004004 */  jal   guMtxIdentF
/* 017934 70016D34 27A40028 */   addiu $a0, $sp, 0x28
/* 017938 70016D38 C7A4006C */  lwc1  $f4, 0x6c($sp)
/* 01793C 70016D3C C7A60070 */  lwc1  $f6, 0x70($sp)
/* 017940 70016D40 C7A80074 */  lwc1  $f8, 0x74($sp)
/* 017944 70016D44 27A40028 */  addiu $a0, $sp, 0x28
/* 017948 70016D48 8FA50068 */  lw    $a1, 0x68($sp)
/* 01794C 70016D4C E7A40058 */  swc1  $f4, 0x58($sp)
/* 017950 70016D50 E7A6005C */  swc1  $f6, 0x5c($sp)
/* 017954 70016D54 0C003FC4 */  jal   guMtxF2L
/* 017958 70016D58 E7A80060 */   swc1  $f8, 0x60($sp)
/* 01795C 70016D5C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 017960 70016D60 27BD0068 */  addiu $sp, $sp, 0x68
/* 017964 70016D64 03E00008 */  jr    $ra
/* 017968 70016D68 00000000 */   nop   

