# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __sinf
/* 01C5A0 7001B9A0 E7AC0000 */  swc1  $f12, ($sp)
/* 01C5A4 7001B9A4 8FA20000 */  lw    $v0, ($sp)
/* 01C5A8 7001B9A8 C7A40000 */  lwc1  $f4, ($sp)
/* 01C5AC 7001B9AC 00021D83 */  sra   $v1, $v0, 0x16
/* 01C5B0 7001B9B0 306E01FF */  andi  $t6, $v1, 0x1ff
/* 01C5B4 7001B9B4 29C100FF */  slti  $at, $t6, 0xff
/* 01C5B8 7001B9B8 10200019 */  beqz  $at, .L7001BA20
/* 01C5BC 7001B9BC 01C01825 */   move  $v1, $t6
/* 01C5C0 7001B9C0 29C100E6 */  slti  $at, $t6, 0xe6
/* 01C5C4 7001B9C4 14200014 */  bnez  $at, .L7001BA18
/* 01C5C8 7001B9C8 460020A1 */   cvt.d.s $f2, $f4
/* 01C5CC 7001B9CC 46221302 */  mul.d $f12, $f2, $f2
/* 01C5D0 7001B9D0 3C038003 */  lui   $v1, %hi(F64_80029A00)
/* 01C5D4 7001B9D4 24639A00 */  addiu $v1, %lo(F64_80029A00) # addiu $v1, $v1, -0x6600
/* 01C5D8 7001B9D8 D4660020 */  ldc1  $f6, 0x20($v1)
/* 01C5DC 7001B9DC D46A0018 */  ldc1  $f10, 0x18($v1)
/* 01C5E0 7001B9E0 D4640010 */  ldc1  $f4, 0x10($v1)
/* 01C5E4 7001B9E4 462C3202 */  mul.d $f8, $f6, $f12
/* 01C5E8 7001B9E8 462A4400 */  add.d $f16, $f8, $f10
/* 01C5EC 7001B9EC D46A0008 */  ldc1  $f10, 8($v1)
/* 01C5F0 7001B9F0 462C8482 */  mul.d $f18, $f16, $f12
/* 01C5F4 7001B9F4 46249180 */  add.d $f6, $f18, $f4
/* 01C5F8 7001B9F8 462C3202 */  mul.d $f8, $f6, $f12
/* 01C5FC 7001B9FC 46285380 */  add.d $f14, $f10, $f8
/* 01C600 7001BA00 462C1402 */  mul.d $f16, $f2, $f12
/* 01C604 7001BA04 00000000 */  nop   
/* 01C608 7001BA08 462E8482 */  mul.d $f18, $f16, $f14
/* 01C60C 7001BA0C 46229100 */  add.d $f4, $f18, $f2
/* 01C610 7001BA10 03E00008 */  jr    $ra
/* 01C614 7001BA14 46202020 */   cvt.s.d $f0, $f4

.L7001BA18:
/* 01C618 7001BA18 03E00008 */  jr    $ra
/* 01C61C 7001BA1C C7A00000 */   lwc1  $f0, ($sp)

.L7001BA20:
/* 01C620 7001BA20 28610136 */  slti  $at, $v1, 0x136
/* 01C624 7001BA24 10200044 */  beqz  $at, .L7001BB38
/* 01C628 7001BA28 C7A40000 */   lwc1  $f4, ($sp)
/* 01C62C 7001BA2C C7A60000 */  lwc1  $f6, ($sp)
/* 01C630 7001BA30 3C018003 */  lui    $at, %hi(F64_80029A28)
/* 01C634 7001BA34 D42A9A28 */  ldc1  $f10, %lo(F64_80029A28)($at)
/* 01C638 7001BA38 460030A1 */  cvt.d.s $f2, $f6
/* 01C63C 7001BA3C 44804800 */  mtc1  $zero, $f9
/* 01C640 7001BA40 462A1002 */  mul.d $f0, $f2, $f10
/* 01C644 7001BA44 44804000 */  mtc1  $zero, $f8
/* 01C648 7001BA48 3C013FE0 */  li    $at, 0x3FE00000 # 1.750000
/* 01C64C 7001BA4C 4620403E */  c.le.d $f8, $f0
/* 01C650 7001BA50 00000000 */  nop   
/* 01C654 7001BA54 4502000B */  bc1fl .L7001BA84
/* 01C658 7001BA58 44813800 */   mtc1  $at, $f7
/* 01C65C 7001BA5C 3C013FE0 */  li    $at, 0x3FE00000 # 1.750000
/* 01C660 7001BA60 44818800 */  mtc1  $at, $f17
/* 01C664 7001BA64 44808000 */  mtc1  $zero, $f16
/* 01C668 7001BA68 00000000 */  nop   
/* 01C66C 7001BA6C 46300480 */  add.d $f18, $f0, $f16
/* 01C670 7001BA70 4620910D */  trunc.w.d $f4, $f18
/* 01C674 7001BA74 44022000 */  mfc1  $v0, $f4
/* 01C678 7001BA78 10000009 */  b     .L7001BAA0
/* 01C67C 7001BA7C 44828000 */   mtc1  $v0, $f16
/* 01C680 7001BA80 44813800 */  mtc1  $at, $f7
.L7001BA84:
/* 01C684 7001BA84 44803000 */  mtc1  $zero, $f6
/* 01C688 7001BA88 00000000 */  nop   
/* 01C68C 7001BA8C 46260281 */  sub.d $f10, $f0, $f6
/* 01C690 7001BA90 4620520D */  trunc.w.d $f8, $f10
/* 01C694 7001BA94 44024000 */  mfc1  $v0, $f8
/* 01C698 7001BA98 00000000 */  nop   
/* 01C69C 7001BA9C 44828000 */  mtc1  $v0, $f16
.L7001BAA0:
/* 01C6A0 7001BAA0 3C018003 */  lui   $at, %hi(F64_80029A30)
/* 01C6A4 7001BAA4 D4329A30 */  ldc1  $f18, %lo(F64_80029A30)($at)
/* 01C6A8 7001BAA8 46808021 */  cvt.d.w $f0, $f16
/* 01C6AC 7001BAAC 3C018003 */  lui   $at, %hi(F64_80029A38)
/* 01C6B0 7001BAB0 D4269A38 */  ldc1  $f6, %lo(F64_80029A38)($at)
/* 01C6B4 7001BAB4 3C038003 */  lui   $v1, %hi(F64_80029A00)
/* 01C6B8 7001BAB8 24639A00 */  addiu $v1, %lo(F64_80029A00) # addiu $v1, $v1, -0x6600
/* 01C6BC 7001BABC 46320102 */  mul.d $f4, $f0, $f18
/* 01C6C0 7001BAC0 D4680020 */  ldc1  $f8, 0x20($v1)
/* 01C6C4 7001BAC4 D4720018 */  ldc1  $f18, 0x18($v1)
/* 01C6C8 7001BAC8 30590001 */  andi  $t9, $v0, 1
/* 01C6CC 7001BACC 46260282 */  mul.d $f10, $f0, $f6
/* 01C6D0 7001BAD0 46241081 */  sub.d $f2, $f2, $f4
/* 01C6D4 7001BAD4 462A1081 */  sub.d $f2, $f2, $f10
/* 01C6D8 7001BAD8 D46A0010 */  ldc1  $f10, 0x10($v1)
/* 01C6DC 7001BADC 46221302 */  mul.d $f12, $f2, $f2
/* 01C6E0 7001BAE0 00000000 */  nop   
/* 01C6E4 7001BAE4 462C4402 */  mul.d $f16, $f8, $f12
/* 01C6E8 7001BAE8 46328100 */  add.d $f4, $f16, $f18
/* 01C6EC 7001BAEC D4720008 */  ldc1  $f18, 8($v1)
/* 01C6F0 7001BAF0 462C2182 */  mul.d $f6, $f4, $f12
/* 01C6F4 7001BAF4 462A3200 */  add.d $f8, $f6, $f10
/* 01C6F8 7001BAF8 462C4402 */  mul.d $f16, $f8, $f12
/* 01C6FC 7001BAFC 17200007 */  bnez  $t9, .L7001BB1C
/* 01C700 7001BB00 46309380 */   add.d $f14, $f18, $f16
/* 01C704 7001BB04 462C1102 */  mul.d $f4, $f2, $f12
/* 01C708 7001BB08 00000000 */  nop   
/* 01C70C 7001BB0C 462E2182 */  mul.d $f6, $f4, $f14
/* 01C710 7001BB10 46223280 */  add.d $f10, $f6, $f2
/* 01C714 7001BB14 03E00008 */  jr    $ra
/* 01C718 7001BB18 46205020 */   cvt.s.d $f0, $f10

.L7001BB1C:
/* 01C71C 7001BB1C 462C1202 */  mul.d $f8, $f2, $f12
/* 01C720 7001BB20 00000000 */  nop   
/* 01C724 7001BB24 462E4482 */  mul.d $f18, $f8, $f14
/* 01C728 7001BB28 46229400 */  add.d $f16, $f18, $f2
/* 01C72C 7001BB2C 46208020 */  cvt.s.d $f0, $f16
/* 01C730 7001BB30 03E00008 */  jr    $ra
/* 01C734 7001BB34 46000007 */   neg.s $f0, $f0

.L7001BB38:
/* 01C738 7001BB38 46042032 */  c.eq.s $f4, $f4
/* 01C73C 7001BB3C 3C018003 */  lui   $at, %hi(F64_80029A40)
/* 01C740 7001BB40 45010004 */  bc1t  .L7001BB54
/* 01C744 7001BB44 00000000 */   nop   
/* 01C748 7001BB48 3C018003 */  lui   $at, %hi(__libm_qnan_f)
/* 01C74C 7001BB4C 03E00008 */  jr    $ra
/* 01C750 7001BB50 C4209D40 */   lwc1  $f0, %lo(__libm_qnan_f)($at)

.L7001BB54:
/* 01C754 7001BB54 C4209A40 */  lwc1  $f0, %lo(F64_80029A40)($at)
/* 01C758 7001BB58 03E00008 */  jr    $ra
/* 01C75C 7001BB5C 00000000 */   nop   

.section .rodata
glabel F64_80029A00
.double 1.0
glabel F64_80029A08
.double -0.16666659550427756
glabel F64_80029A10
.double 0.008333066246082155
glabel F64_80029A18
.double -0.0001980960290193795
glabel F64_80029A20
.double 0.000002605780637968037
glabel F64_80029A28
.double 0.3183098861837907
glabel F64_80029A30
.double 3.1415926218032837
glabel F64_80029A38
.double 3.178650954705639e-8
glabel F64_80029A40
.double 0.0
                    .word 0
                    .word 0

