# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osViGetCurrentContext
/* 019760 70018B60 3C028003 */  lui   $v0, %hi(__osViCurr)
/* 019764 70018B64 03E00008 */  jr    $ra
/* 019768 70018B68 8C428040 */   lw    $v0, %lo(__osViCurr)($v0)

