# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .data
glabel osViModePalLan1
.word 0x10000000,    0x311E,     0x140, 0x404233A
.word      0x271,  0x150C69, 0xC6F0C6E,  0x800300
.word      0x200,         0,     0x280,     0x400
.word   0x5F0239,   0x9026B,         2,     0x280
.word      0x400,  0x5F0239,   0x9026B,         2


