//TODO: Autogenerate me
#include "file_resource_id_enums.h"

struct fileentry file_resource_table[] = {
    {NULLFILE, "", 0},
    {BG_SEV_ALL_P, "bg/bg_sev_all_p.seg", &bg_sev_all_p_seg},
    {BG_SILO_ALL_P, "bg/bg_silo_all_p.seg", &bg_silo_all_p_seg},
    {BG_STAT_ALL_P, "bg/bg_stat_all_p.seg", &bg_stat_all_p_seg},
    {BG_AREC_ALL_P, "bg/bg_arec_all_p.seg", &bg_arec_all_p_seg},
    {BG_ARCH_ALL_P, "bg/bg_arch_all_p.seg", &bg_arch_all_p_seg},
    {BG_TRA_ALL_P, "bg/bg_tra_all_p.seg", &bg_tra_all_p_seg},
    {BG_DEST_ALL_P, "bg/bg_dest_all_p.seg", &bg_dest_all_p_seg},
    {BG_SEVB_ALL_P, "bg/bg_sevb_all_p.seg", &bg_sevb_all_p_seg},
    {BG_AZT_ALL_P, "bg/bg_azt_all_p.seg", &bg_azt_all_p_seg},
    {BG_PETE_ALL_P, "bg/bg_pete_all_p.seg", &bg_pete_all_p_seg},
    {BG_DEPO_ALL_P, "bg/bg_depo_all_p.seg", &bg_depo_all_p_seg},
    {BG_REF_ALL_P, "bg/bg_ref_all_p.seg", &bg_ref_all_p_seg},
    {BG_CRYP_ALL_P, "bg/bg_cryp_all_p.seg", &bg_cryp_all_p_seg},
    {BG_DAM_ALL_P, "bg/bg_dam_all_p.seg", &bg_dam_all_p_seg},
    {BG_ARK_ALL_P, "bg/bg_ark_all_p.seg", &bg_ark_all_p_seg},
    {BG_RUN_ALL_P, "bg/bg_run_all_p.seg", &bg_run_all_p_seg},
    {BG_SEVX_ALL_P, "bg/bg_sevx_all_p.seg", &bg_sevx_all_p_seg},
    {BG_JUN_ALL_P, "bg/bg_jun_all_p.seg", &bg_jun_all_p_seg},
    {BG_DISH_ALL_P, "bg/bg_dish_all_p.seg", &bg_dish_all_p_seg},
    {BG_CAVE_ALL_P, "bg/bg_cave_all_p.seg", &bg_cave_all_p_seg},
    {BG_CAT_ALL_P, "bg/bg_cat_all_p.seg", &bg_cat_all_p_seg},
    {BG_CRAD_ALL_P, "bg/bg_crad_all_p.seg", &bg_crad_all_p_seg},
    {BG_SHO_ALL_P, "bg/bg_sho_all_p.seg", &bg_sho_all_p_seg},
    {BG_ELD_ALL_P, "bg/bg_eld_all_p.seg", &bg_imp_all_p_seg},
    {BG_IMP_ALL_P, "bg/bg_imp_all_p.seg", &bg_imp_all_p_seg},
    {BG_ASH_ALL_P, "bg/bg_ash_all_p.seg", &bg_imp_all_p_seg},
    {BG_LUE_ALL_P, "bg/bg_lue_all_p.seg", &bg_imp_all_p_seg},
    {BG_AME_ALL_P, "bg/bg_ame_all_p.seg", &bg_imp_all_p_seg},
    {BG_RIT_ALL_P, "bg/bg_rit_all_p.seg", &bg_rit_all_p_seg},
    {BG_OAT_ALL_P, "bg/bg_oat_all_p.seg", &bg_oat_all_p_seg},
    {BG_EAR_ALL_P, "bg/bg_ear_all_p.seg", &bg_ear_all_p_seg},
    {BG_LEE_ALL_P, "bg/bg_lee_all_p.seg", &bg_lee_all_p_seg},
    {BG_LIP_ALL_P, "bg/bg_lip_all_p.seg", &bg_lip_all_p_seg},
    {BG_LEN_ALL_P, "bg/bg_len_all_p.seg", &bg_len_all_p_seg},
    {BG_WAX_ALL_P, "bg/bg_wax_all_p.seg", &bg_wax_all_p_seg},
    {BG_PAM_ALL_P, "bg/bg_pam_all_p.seg", &bg_pam_all_p_seg},

    {ARMOURGUARD, "CarmourguardZ", &CarmourguardZ},
    {BARONSAMEDI, "CbaronsamediZ", &CbaronsamediZ},
    {BLUECAMGUARD, "CbluecamguardZ", &CbluecamguardZ},
    {BLUEMAN, "CbluemanZ", &CbluemanZ},
    {BLUEWOMAN, "CbluewomanZ", &CbluewomanZ},
    {BOILERBOND, "CboilerbondZ", &CboilerbondZ},
    {BOILERTREV, "CboilertrevZ", &CboilertrevZ},
    {BORIS, "CborisZ", &CborisZ},
    {CAMGUARD, "CcamguardZ", &CcamguardZ},
    {CARDIMAN, "CcardimanZ", &CcardimanZ},
    {CHECKMAN, "CcheckmanZ", &CcheckmanZ},
    {COMMGUARD, "CcommguardZ", &CcommguardZ},
    {DJBOND, "CdjbondZ", &CdjbondZ},
    {FATTECHWOMAN, "CfattechwomanZ", &CfattechwomanZ},
    {GREATGUARD2, "Cgreatguard2Z", &Cgreatguard2Z},
    {GREATGUARD, "CgreatguardZ", &CgreatguardZ},
    {GREYGUARD, "CgreyguardZ", &CgreyguardZ},
    {GREYMAN, "CgreymanZ", &CgreymanZ},
    {HEADALAN, "CheadalanZ", &CheadalanZ},
    {HEADB, "CheadbZ", &CheadbZ},
    {HEADBALACLAVA, "CheadbalaclavaZ", &CheadbalaclavaZ},
    {HEADBIKE, "CheadbikeZ", &CheadbikeZ},
    {HEADBROSNAN, "CheadbrosnanZ", &CheadbrosnanZ},
    {HEADBROSNANBOILER, "CheadbrosnanboilerZ", &CheadbrosnanboilerZ},
    {HEADBROSNANSNOW, "CheadbrosnansnowZ", &CheadbrosnansnowZ},
    {HEADBROSNANSUIT, "CheadbrosnansuitZ", &CheadbrosnansuitZ},
    {HEADBROSNANTIMBER, "CheadbrosnantimberZ", &CheadbrosnantimberZ},
    {HEADCHRIS, "CheadchrisZ", &CheadchrisZ},
    {HEADDAVE, "CheaddaveZ", &CheaddaveZ},
    {HEADDES, "CheaddesZ", &CheaddesZ},
    {HEADDUNCAN, "CheadduncanZ", &CheadduncanZ},
    {HEADDWAYNE, "CheaddwayneZ", &CheaddwayneZ},
    {HEADGRAHAM, "CheadgrahamZ", &CheadgrahamZ},
    {HEADGRANT, "CheadgrantZ", &CheadgrantZ},
    {HEADJIM, "CheadjimZ", &CheadjimZ},
    {HEADJOE2, "Cheadjoe2Z", &Cheadjoe2Z},
    {HEADJOE, "CheadjoeZ", &CheadjoeZ},
    {HEADJOEL, "CheadjoelZ", &CheadjoelZ},
    {HEADKARL, "CheadkarlZ", &CheadkarlZ},
    {HEADKEN, "CheadkenZ", &CheadkenZ},
    {HEADLEE, "CheadleeZ", &CheadleeZ},
    {HEADMANDY, "CheadmandyZ", &CheadmandyZ},
    {HEADMARION, "CheadmarionZ", &CheadmarionZ},
    {HEADMARK, "CheadmarkZ", &CheadmarkZ},
    {HEADMARTIN, "CheadmartinZ", &CheadmartinZ},
    {HEADMISHKIN, "CheadmishkinZ", &CheadmishkinZ},
    {HEADNEIL, "CheadneilZ", &CheadneilZ},
    {HEADPETE, "CheadpeteZ", &CheadpeteZ},
    {HEADROBIN, "CheadrobinZ", &CheadrobinZ},
    {HEADSALLY, "CheadsallyZ", &CheadsallyZ},
    {HEADSCOTT, "CheadscottZ", &CheadscottZ},
    {HEADSHAUN, "CheadshaunZ", &CheadshaunZ},
    {HEADSTEVEE, "CheadsteveeZ", &CheadsteveeZ},
    {HEADSTEVEH, "CheadstevehZ", &CheadstevehZ},
    {HEADVIVIEN, "CheadvivienZ", &CheadvivienZ},
    {JAWS, "CjawsZ", &CjawsZ},
    {JEANWOMAN, "CjeanwomanZ", &CjeanwomanZ},
    {MAYDAY, "CmaydayZ", &CmaydayZ},
    {MOONFEMALE, "CmoonfemaleZ", &CmoonfemaleZ},
    {MOONGUARD, "CmoonguardZ", &CmoonguardZ},
    {NATALYA, "CnatalyaZ", &CnatalyaZ},
    {NAVYGUARD, "CnavyguardZ", &CnavyguardZ},
    {ODDJOB, "CoddjobZ", &CoddjobZ},
    {OLIVEGUARD, "ColiveguardZ", &ColiveguardZ},
    {ORUMOV, "CorumovZ", &CorumovZ},
    {PILOT, "CpilotZ", &CpilotZ},
    {REDMAN, "CredmanZ", &CredmanZ},
    {RUSGUARD, "CrusguardZ", &CrusguardZ},
    {SNOWBOND, "CsnowbondZ", &CsnowbondZ},
    {SNOWGUARD, "CsnowguardZ", &CsnowguardZ},
    {SPICEBOND, "CspicebondZ", &CspicebondZ},
    {SUIT_LF_HAND, "Csuit_lf_handZ", &Csuit_lf_handZ},
    {SUITBOND, "CsuitbondZ", &CsuitbondZ},
    {TECHMAN, "CtechmanZ", &CtechmanZ},
    {TECHWOMAN, "CtechwomanZ", &CtechwomanZ},
    {TIMBERBOND, "CtimberbondZ", &CtimberbondZ},
    {TREVELYAN, "CtrevelyanZ", &CtrevelyanZ},
    {TREVGUARD, "CtrevguardZ", &CtrevguardZ},
    {VALENTIN, "CvalentinZ", &CvalentinZ},
    {XENIA, "CxeniaZ", &CxeniaZ},

    {AK47, "Gak47Z", &Gak47Z},
    {AUDIOTAPE, "GaudiotapeZ", &GaudiotapeZ},
    {AUTOSHOT, "GautoshotZ", &GautoshotZ},
    {BLACKBOX, "GblackboxZ", &GblackboxZ},
    {BLUEPRINTS, "GblueprintsZ", &GblueprintsZ},
    {BOMBCASE, "GbombcaseZ", &GbombcaseZ},
    {BOMBDEFUSER, "GbombdefuserZ", &GbombdefuserZ},
    {BRIEFCASE, "GbriefcaseZ", &GbriefcaseZ},
    {BUG, "GbugZ", &GbugZ},
    {BUGDETECTOR, "GbugdetectorZ", &GbugdetectorZ},
    {BUNGEE, "GbungeeZ", &GbungeeZ},
    {CAMERA, "GcameraZ", &GcameraZ},
    {CARTBLUE, "GcartblueZ", &GcartblueZ},
    {CARTRIDGE, "GcartridgeZ", &GcartridgeZ},
    {CARTRIFLE, "GcartrifleZ", &GcartrifleZ},
    {CARTSHELL, "GcartshellZ", &GcartshellZ},
    {CIRCUITBOARD, "GcircuitboardZ", &GcircuitboardZ},
    {CLIPBOARD, "GclipboardZ", &GclipboardZ},
    {CREDITCARD, "GcreditcardZ", &GcreditcardZ},
    {DARKGLASSES, "GdarkglassesZ", &GdarkglassesZ},
    {DATATHIEF, "GdatathiefZ", &GdatathiefZ},
    {DATTAPE, "GdattapeZ", &GdattapeZ},
    {DOORDECODER, "GdoordecoderZ", &GdoordecoderZ},
    {DOOREXPLODER, "GdoorexploderZ", &GdoorexploderZ},
    {DOSSIERRED, "GdossierredZ", &GdossierredZ},
    {DYNAMITE, "GdynamiteZ", &GdynamiteZ},
    {EXPLOSIVEFLOPPY, "GexplosivefloppyZ", &GexplosivefloppyZ},
    {EXPLOSIVEPEN, "GexplosivepenZ", &GexplosivepenZ},
    {EXTINGUISHER, "GextinguisherZ", &GextinguisherZ},
    {FINGERGUN, "GfingergunZ", &GfingergunZ},
    {FIST, "GfistZ", &GfistZ},
    {FLAREPISTOL, "GflarepistolZ", &GflarepistolZ},
    {FNP90, "Gfnp90Z", &Gfnp90Z},
    {GASKEYRING, "GgaskeyringZ", &GgaskeyringZ},
    {GOLDBAR, "GgoldbarZ", &GgoldbarZ},
    {GOLDENEYEKEY, "GgoldeneyekeyZ", &GgoldeneyekeyZ},
    {GOLDENGUN, "GgoldengunZ", &GgoldengunZ},
    {GOLDWPPK, "GgoldwppkZ", &GgoldwppkZ},
    {GRENADE, "GgrenadeZ", &GgrenadeZ},
    {GRENADELAUNCH, "GgrenadelaunchZ", &GgrenadelaunchZ},
    {HEROIN, "GheroinZ", &GheroinZ},
    {JOYPAD, "GjoypadZ", &GjoypadZ},
    {KEYANALYSERCASE, "GkeyanalysercaseZ", &GkeyanalysercaseZ},
    {KEYBOLT, "GkeyboltZ", &GkeyboltZ},
    {KEYCARD, "GkeycardZ", &GkeycardZ},
    {KEYYALE, "GkeyyaleZ", &GkeyyaleZ},
    {KNIFE, "GknifeZ", &GknifeZ},
    {LASER, "GlaserZ", &GlaserZ},
    {LECTRE, "GlectreZ", &GlectreZ},
    {LOCKEXPLODER, "GlockexploderZ", &GlockexploderZ},
    {M16, "Gm16Z", &Gm16Z},
    {MAP, "GmapZ", &GmapZ},
    {MICROCAMERA, "GmicrocameraZ", &GmicrocameraZ},
    {MICROCODE, "GmicrocodeZ", &GmicrocodeZ},
    {MICROFILM, "GmicrofilmZ", &GmicrofilmZ},
    {MONEY, "GmoneyZ", &GmoneyZ},
    {MP5K, "Gmp5kZ", &Gmp5kZ},
    {MP5KSIL, "Gmp5ksilZ", &Gmp5ksilZ},
    {PITONGUN, "GpitongunZ", &GpitongunZ},
    {PLANS, "GplansZ", &GplansZ},
    {PLASTIQUE, "GplastiqueZ", &GplastiqueZ},
    {POLARIZEDGLASSES, "GpolarizedglassesZ", &GpolarizedglassesZ},
    {PROXIMITYMINE, "GproximitymineZ", &GproximitymineZ},
    {REMOTEMINE, "GremotemineZ", &GremotemineZ},
    {ROCKETLAUNCH, "GrocketlaunchZ", &GrocketlaunchZ},
    {RUGER, "GrugerZ", &GrugerZ},
    {SAFECRACKERCASE, "GsafecrackercaseZ", &GsafecrackercaseZ},
    {SHOTGUN, "GshotgunZ", &GshotgunZ},
    {SILVERWPPK, "GsilverwppkZ", &GsilverwppkZ},
    {SKORPION, "GskorpionZ", &GskorpionZ},
    {SNIPERRIFLE, "GsniperrifleZ", &GsniperrifleZ},
    {SPECTRE, "GspectreZ", &GspectreZ},
    {SPOOLTAPE, "GspooltapeZ", &GspooltapeZ},
    {SPYFILE, "GspyfileZ", &GspyfileZ},
    {STAFFLIST, "GstafflistZ", &GstafflistZ},
    {TASER, "GtaserZ", &GtaserZ},
    {THROWKNIFE, "GthrowknifeZ", &GthrowknifeZ},
    {TIMEDMINE, "GtimedmineZ", &GtimedmineZ},
    {TRIGGER, "GtriggerZ", &GtriggerZ},
    {TT33, "Gtt33Z", &Gtt33Z},
    {UZI, "GuziZ", &GuziZ},
    {VIDEOTAPE, "GvideotapeZ", &GvideotapeZ},
    {WATCHCOMMUNICATOR, "GwatchcommunicatorZ", &GwatchcommunicatorZ},
    {WATCHGEIGERCOUNTER, "GwatchgeigercounterZ", &GwatchgeigercounterZ},
    {WATCHIDENTIFIER, "GwatchidentifierZ", &GwatchidentifierZ},
    {WATCHLASER, "GwatchlaserZ", &GwatchlaserZ},
    {WATCHMAGNETATTRACT, "GwatchmagnetattractZ", &GwatchmagnetattractZ},
    {WATCHMAGNETREPEL, "GwatchmagnetrepelZ", &GwatchmagnetrepelZ},
    {WEAPONCASE, "GweaponcaseZ", &GweaponcaseZ},
    {WPPK, "GwppkZ", &GwppkZ},
    {WPPKSIL, "GwppksilZ", &GwppksilZ},
    {WRISTDART, "GwristdartZ", &GwristdartZ},

    {ICBM, "PICBMZ", &PICBMZ},
    {ICBM_NOSE, "PICBM_noseZ", &PICBM_noseZ},
    {AK47MAG, "Pak47magZ", &Pak47magZ},
    {ALARM1, "Palarm1Z", &Palarm1Z},
    {ALARM2, "Palarm2Z", &Palarm2Z},
    {AMMO_CRATE1, "Pammo_crate1Z", &Pammo_crate1Z},
    {AMMO_CRATE2, "Pammo_crate2Z", &Pammo_crate2Z},
    {AMMO_CRATE3, "Pammo_crate3Z", &Pammo_crate3Z},
    {AMMO_CRATE4, "Pammo_crate4Z", &Pammo_crate4Z},
    {AMMO_CRATE5, "Pammo_crate5Z", &Pammo_crate5Z},
    {APC, "PapcZ", &PapcZ},
    {ARCHSECDOOR1, "Parchsecdoor1Z", &Parchsecdoor1Z},
    {ARCHSECDOOR2, "Parchsecdoor2Z", &Parchsecdoor2Z},
    {ARTIC, "ParticZ", &ParticZ},
    {ARTICTRAILER, "PartictrailerZ", &PartictrailerZ},
    {BARRICADE, "PbarricadeZ", &PbarricadeZ},
    {BIN1, "Pbin1Z", &Pbin1Z},
    {BLOTTER1, "Pblotter1Z", &Pblotter1Z},
    {BODYARMOUR, "PbodyarmourZ", &PbodyarmourZ},
    {BODYARMOURVEST, "PbodyarmourvestZ", &PbodyarmourvestZ},
    {BOLLARD, "PbollardZ", &PbollardZ},
    {BOMB, "PbombZ", &PbombZ},
    {BOOK1, "Pbook1Z", &Pbook1Z},
    {BOOKSHELF1, "Pbookshelf1Z", &Pbookshelf1Z},
    {BORG_CRATE, "Pborg_crateZ", &Pborg_crateZ},
    {BOXCARTRIDGES, "PboxcartridgesZ", &PboxcartridgesZ},
    {BOXES2X4, "Pboxes2x4Z", &Pboxes2x4Z},
    {BOXES3X4, "Pboxes3x4Z", &Pboxes3x4Z},
    {BOXES4X4, "Pboxes4x4Z", &Pboxes4x4Z},
    {BRAKEUNIT, "PbrakeunitZ", &PbrakeunitZ},
    {BRIDGE_CONSOLE1A, "Pbridge_console1aZ", &Pbridge_console1aZ},
    {BRIDGE_CONSOLE1B, "Pbridge_console1bZ", &Pbridge_console1bZ},
    {BRIDGE_CONSOLE2A, "Pbridge_console2aZ", &Pbridge_console2aZ},
    {BRIDGE_CONSOLE2B, "Pbridge_console2bZ", &Pbridge_console2bZ},
    {BRIDGE_CONSOLE3A, "Pbridge_console3aZ", &Pbridge_console3aZ},
    {BRIDGE_CONSOLE3B, "Pbridge_console3bZ", &Pbridge_console3bZ},
    {CARBMW, "PcarbmwZ", &PcarbmwZ},
    {CARD_BOX1, "Pcard_box1Z", &Pcard_box1Z},
    {CARD_BOX2, "Pcard_box2Z", &Pcard_box2Z},
    {CARD_BOX3, "Pcard_box3Z", &Pcard_box3Z},
    {CARD_BOX4_LG, "Pcard_box4_lgZ", &Pcard_box4Z},
    {CARD_BOX5_LG, "Pcard_box5_lgZ", &Pcard_box5Z},
    {CARD_BOX6_LG, "Pcard_box6_lgZ", &Pcard_box6Z},
    {CARESCORT, "PcarescortZ", &PcarescortZ},
    {CARGOLF, "PcargolfZ", &PcargolfZ},
    {CARWEIRD, "PcarweirdZ", &PcarweirdZ},
    {CARZIL, "PcarzilZ", &PcarzilZ},
    {CCTV, "PcctvZ", &PcctvZ},
    {CHRAUDIOTAPE, "PchraudiotapeZ", &PchraudiotapeZ},
    {CHRAUTOSHOT, "PchrautoshotZ", &PchrautoshotZ},
    {CHRBLACKBOX, "PchrblackboxZ", &PchrblackboxZ},
    {CHRBLUEPRINTS, "PchrblueprintsZ", &PchrblueprintsZ},
    {CHRBOMBCASE, "PchrbombcaseZ", &PchrbombcaseZ},
    {CHRBOMBDEFUSER, "PchrbombdefuserZ", &PchrbombdefuserZ},
    {CHRBRIEFCASE, "PchrbriefcaseZ", &PchrbriefcaseZ},
    {CHRBUG, "PchrbugZ", &PchrbugZ},
    {CHRBUGDETECTOR, "PchrbugdetectorZ", &PchrbugdetectorZ},
    {CHRBUNGEE, "PchrbungeeZ", &PchrbungeeZ},
    {CHRCAMERA, "PchrcameraZ", &PchrcameraZ},
    {CHRCIRCUITBOARD, "PchrcircuitboardZ", &PchrcircuitboardZ},
    {CHRCLIPBOARD, "PchrclipboardZ", &PchrclipboardZ},
    {CHRCREDITCARD, "PchrcreditcardZ", &PchrcreditcardZ},
    {CHRDARKGLASSES, "PchrdarkglassesZ", &PchrdarkglassesZ},
    {CHRDATATHIEF, "PchrdatathiefZ", &PchrdatathiefZ},
    {CHRDATTAPE, "PchrdattapeZ", &PchrdattapeZ},
    {CHRDOORDECODER, "PchrdoordecoderZ", &PchrdoordecoderZ},
    {CHRDOOREXPLODER, "PchrdoorexploderZ", &PchrdoorexploderZ},
    {CHRDOSSIERRED, "PchrdossierredZ", &PchrdossierredZ},
    {CHRDYNAMITE, "PchrdynamiteZ", &PchrdynamiteZ},
    {CHREXPLOSIVEPEN, "PchrexplosivepenZ", &PchrexplosivepenZ},
    {CHREXTINGUISHER, "PchrextinguisherZ", &PchrextinguisherZ},
    {CHRFINGERGUN, "PchrfingergunZ", &PchrfingergunZ},
    {CHRFLAREPISTOL, "PchrflarepistolZ", &PchrflarepistolZ},
    {CHRFNP90, "Pchrfnp90Z", &Pchrfnp90Z},
    {CHRGASKEYRING, "PchrgaskeyringZ", &PchrgaskeyringZ},
    {CHRGOLDBAR, "PchrgoldbarZ", &PchrgoldbarZ},
    {CHRGOLDEN, "PchrgoldenZ", &PchrgoldenZ},
    {CHRGOLDENEYEKEY, "PchrgoldeneyekeyZ", &PchrgoldeneyekeyZ},
    {CHRGOLDWPPK, "PchrgoldwppkZ", &PchrgoldwppkZ},
    {CHRGRENADE, "PchrgrenadeZ", &PchrgrenadeZ},
    {CHRGRENADELAUNCH, "PchrgrenadelaunchZ", &PchrgrenadelaunchZ},
    {CHRGRENADEROUND, "PchrgrenaderoundZ", &PchrgrenaderoundZ},
    {CHRHEROIN, "PchrheroinZ", &PchrheroinZ},
    {CHRKALASH, "PchrkalashZ", &PchrkalashZ},
    {CHRKEYANALYSERCASE, "PchrkeyanalysercaseZ", &PchrkeyanalysercaseZ},
    {CHRKEYBOLT, "PchrkeyboltZ", &PchrkeyboltZ},
    {CHRKEYYALE, "PchrkeyyaleZ", &PchrkeyyaleZ},
    {CHRKNIFE, "PchrknifeZ", &PchrknifeZ},
    {CHRLASER, "PchrlaserZ", &PchrlaserZ},
    {CHRLECTRE, "PchrlectreZ", &PchrlectreZ},
    {CHRLOCKEXPLODER, "PchrlockexploderZ", &PchrlockexploderZ},
    {CHRM16, "Pchrm16Z", &Pchrm16Z},
    {CHRMAP, "PchrmapZ", &PchrmapZ},
    {CHRMICROCAMERA, "PchrmicrocameraZ", &PchrmicrocameraZ},
    {CHRMICROCODE, "PchrmicrocodeZ", &PchrmicrocodeZ},
    {CHRMICROFILM, "PchrmicrofilmZ", &PchrmicrofilmZ},
    {CHRMONEY, "PchrmoneyZ", &PchrmoneyZ},
    {CHRMP5K, "Pchrmp5kZ", &Pchrmp5kZ},
    {CHRMP5KSIL, "Pchrmp5ksilZ", &Pchrmp5ksilZ},
    {CHRPITONGUN, "PchrpitongunZ", &PchrpitongunZ},
    {CHRPLANS, "PchrplansZ", &PchrplansZ},
    {CHRPLASTIQUE, "PchrplastiqueZ", &PchrplastiqueZ},
    {CHRPOLARIZEDGLASSES, "PchrpolarizedglassesZ", &PchrpolarizedglassesZ},
    {CHRPROXIMITYMINE, "PchrproximitymineZ", &PchrproximitymineZ},
    {CHRREMOTEMINE, "PchrremotemineZ", &PchrremotemineZ},
    {CHRROCKET, "PchrrocketZ", &PchrrocketZ},
    {CHRROCKETLAUNCH, "PchrrocketlaunchZ", &PchrrocketlaunchZ},
    {CHRRUGER, "PchrrugerZ", &PchrrugerZ},
    {CHRSAFECRACKERCASE, "PchrsafecrackercaseZ", &PchrsafecrackercaseZ},
    {CHRSHOTGUN, "PchrshotgunZ", &PchrshotgunZ},
    {CHRSILVERWPPK, "PchrsilverwppkZ", &PchrsilverwppkZ},
    {CHRSKORPION, "PchrskorpionZ", &PchrskorpionZ},
    {CHRSNIPERRIFLE, "PchrsniperrifleZ", &PchrsniperrifleZ},
    {CHRSPECTRE, "PchrspectreZ", &PchrspectreZ},
    {CHRSPOOLTAPE, "PchrspooltapeZ", &PchrspooltapeZ},
    {CHRSPYFILE, "PchrspyfileZ", &PchrspyfileZ},
    {CHRSTAFFLIST, "PchrstafflistZ", &PchrstafflistZ},
    {CHRTESTTUBE, "PchrtesttubeZ", &PchrtesttubeZ},
    {CHRTHROWKNIFE, "PchrthrowknifeZ", &PchrthrowknifeZ},
    {CHRTIMEDMINE, "PchrtimedmineZ", &PchrtimedmineZ},
    {CHRTT33, "Pchrtt33Z", &Pchrtt33Z},
    {CHRUZI, "PchruziZ", &PchruziZ},
    {CHRVIDEOTAPE, "PchrvideotapeZ", &PchrvideotapeZ},
    {CHRWEAPONCASE, "PchrweaponcaseZ", &PchrweaponcaseZ},
    {CHRWPPK, "PchrwppkZ", &PchrwppkZ},
    {CHRWPPKSIL, "PchrwppksilZ", &PchrwppksilZ},
    {CHRWRISTDART, "PchrwristdartZ", &PchrwristdartZ},
    {CONSOLE1, "Pconsole1Z", &Pconsole1Z},
    {CONSOLE2, "Pconsole2Z", &Pconsole2Z},
    {CONSOLE3, "Pconsole3Z", &Pconsole3Z},
    {CONSOLE_SEV2A, "Pconsole_sev2aZ", &Pconsole_sev2aZ},
    {CONSOLE_SEV2B, "Pconsole_sev2bZ", &Pconsole_sev2bZ},
    {CONSOLE_SEV2C, "Pconsole_sev2cZ", &Pconsole_sev2cZ},
    {CONSOLE_SEV2D, "Pconsole_sev2dZ", &Pconsole_sev2dZ},
    {CONSOLE_SEV_GEA, "Pconsole_sev_GEaZ", &Pconsole_sev_GEaZ},
    {CONSOLE_SEV_GEB, "Pconsole_sev_GEbZ", &Pconsole_sev_GEbZ},
    {CONSOLE_SEVA, "Pconsole_sevaZ", &Pconsole_sevaZ},
    {CONSOLE_SEVB, "Pconsole_sevbZ", &Pconsole_sevbZ},
    {CONSOLE_SEVC, "Pconsole_sevcZ", &Pconsole_sevcZ},
    {CONSOLE_SEVD, "Pconsole_sevdZ", &Pconsole_sevdZ},
    {CRYPTDOOR1A, "Pcryptdoor1aZ", &Pcryptdoor1aZ},
    {CRYPTDOOR1B, "Pcryptdoor1bZ", &Pcryptdoor1bZ},
    {CRYPTDOOR2A, "Pcryptdoor2aZ", &Pcryptdoor2aZ},
    {CRYPTDOOR2B, "Pcryptdoor2bZ", &Pcryptdoor2bZ},
    {CRYPTDOOR3, "Pcryptdoor3Z", &Pcryptdoor3Z},
    {CRYPTDOOR4, "Pcryptdoor4Z", &Pcryptdoor4Z},
    {DAMCHAINDOOR, "PdamchaindoorZ", &PdamchaindoorZ},
    {DAMGATEDOOR, "PdamgatedoorZ", &PdamgatedoorZ},
    {DAMTUNDOOR, "PdamtundoorZ", &PdamtundoorZ},
    {DEPOT_DOOR_STEEL, "Pdepot_door_steelZ", &Pdepot_door_steelZ},
    {DEPOT_GATE_ENTRY, "Pdepot_gate_entryZ", &Pdepot_gate_entryZ},
    {DESK1, "Pdesk1Z", &Pdesk1Z},
    {DESK2, "Pdesk2Z", &Pdesk2Z},
    {DESK_ARECIBO1, "Pdesk_arecibo1Z", &Pdesk_arecibo1Z},
    {DESK_LAMP2, "Pdesk_lamp2Z", &Pdesk_lamp2Z},
    {DEST_ENGINE, "Pdest_engineZ", &Pdest_engineZ},
    {DEST_EXOCET, "Pdest_exocetZ", &Pdest_exocetZ},
    {DEST_GUN, "Pdest_gunZ", &Pdest_gunZ},
    {DEST_HARPOON, "Pdest_harpoonZ", &Pdest_harpoonZ},
    {DEST_SEAWOLF, "Pdest_seawolfZ", &Pdest_seawolfZ},
    {DISC_READER, "Pdisc_readerZ", &Pdisc_readerZ},
    {DISK_DRIVE1, "Pdisk_drive1Z", &Pdisk_drive1Z},
    {DOOR_AZT_CHAIR, "Pdoor_azt_chairZ", &Pdoor_azt_chairZ},
    {DOOR_AZT_DESK, "Pdoor_azt_deskZ", &Pdoor_azt_deskZ},
    {DOOR_AZT_DESK_TOP, "Pdoor_azt_desk_topZ", &Pdoor_azt_desk_topZ},
    {DOOR_AZTEC, "Pdoor_aztecZ", &Pdoor_aztecZ},
    {DOOR_DEST1, "Pdoor_dest1Z", &Pdoor_dest1Z},
    {DOOR_DEST2, "Pdoor_dest2Z", &Pdoor_dest2Z},
    {DOOR_EYELID, "Pdoor_eyelidZ", &Pdoor_eyelidZ},
    {DOOR_IRIS, "Pdoor_irisZ", &Pdoor_irisZ},
    {DOOR_MF, "Pdoor_mfZ", &Pdoor_mfZ},
    {DOOR_ROLLER1, "Pdoor_roller1Z", &Pdoor_roller1Z},
    {DOOR_ROLLER2, "Pdoor_roller2Z", &Pdoor_roller2Z},
    {DOOR_ROLLER3, "Pdoor_roller3Z", &Pdoor_roller3Z},
    {DOOR_ROLLER4, "Pdoor_roller4Z", &Pdoor_roller4Z},
    {DOOR_ROLLERTRAIN, "Pdoor_rollertrainZ", &Pdoor_rollertrainZ},
    {DOOR_ST_AREC1, "Pdoor_st_arec1Z", &Pdoor_st_arec1Z},
    {DOOR_ST_AREC2, "Pdoor_st_arec2Z", &Pdoor_st_arec2Z},
    {DOOR_WIN, "Pdoor_winZ", &Pdoor_winZ},
    {DOORCONSOLE, "PdoorconsoleZ", &PdoorconsoleZ},
    {DOORPANEL, "PdoorpanelZ", &PdoorpanelZ},
    {DOORPRISON1, "Pdoorprison1Z", &Pdoorprison1Z},
    {DOORSTATGATE, "PdoorstatgateZ", &PdoorstatgateZ},
    {EXPLOSIONBIT, "PexplosionbitZ", &PexplosionbitZ},
    {FILING_CABINET1, "Pfiling_cabinet1Z", &Pfiling_cabinet1Z},
    {FLAG, "PflagZ", &PflagZ},
    {FLOPPY, "PfloppyZ", &PfloppyZ},
    {FNP90MAG, "Pfnp90magZ", &Pfnp90magZ},
    {GAS_PLANT_MET1_DO1, "Pgas_plant_met1_do1Z", &Pgas_plant_met1_do1Z},
    {GAS_PLANT_SW2_DO1, "Pgas_plant_sw2_do1Z", &Pgas_plant_sw2_do1Z},
    {GAS_PLANT_SW3_DO1, "Pgas_plant_sw3_do1Z", &Pgas_plant_sw3_do1Z},
    {GAS_PLANT_SW4_DO1, "Pgas_plant_sw4_do1Z", &Pgas_plant_sw4_do1Z},
    {GAS_PLANT_SW_DO1, "Pgas_plant_sw_do1Z", &Pgas_plant_sw_do1Z},
    {GAS_PLANT_WC_CUB1, "Pgas_plant_wc_cub1Z", &Pgas_plant_wc_cub1Z},
    {GASBARREL, "PgasbarrelZ", &PgasbarrelZ},
    {GASBARRELS, "PgasbarrelsZ", &PgasbarrelsZ},
    {GASPLANT_CLEAR_DOOR, "Pgasplant_clear_doorZ", &Pgasplant_clear_doorZ},
    {GASTANK, "PgastankZ", &PgastankZ},
    {GLASSWARE1, "Pglassware1Z", &Pglassware1Z},
    {GLASSWARE2, "Pglassware2Z", &Pglassware2Z},
    {GLASSWARE3, "Pglassware3Z", &Pglassware3Z},
    {GLASSWARE4, "Pglassware4Z", &Pglassware4Z},
    {GOLDENEYELOGO, "PgoldeneyelogoZ", &PgoldeneyelogoZ},
    {GOLDENSHELLS, "PgoldenshellsZ", &PgoldenshellsZ},
    {GROUNDGUN, "PgroundgunZ", &PgroundgunZ},
    {GUN_RUNWAY1, "Pgun_runway1Z", &Pgun_runway1Z},
    {HATBERET, "PhatberetZ", &PhatberetZ},
    {HATBERETBLUE, "PhatberetblueZ", &PhatberetblueZ},
    {HATBERETRED, "PhatberetredZ", &PhatberetredZ},
    {HATCHBOLT, "PhatchboltZ", &PhatchboltZ},
    {HATCHDOOR, "PhatchdoorZ", &PhatchdoorZ},
    {HATCHSEVX, "PhatchsevxZ", &PhatchsevxZ},
    {HATFURRY, "PhatfurryZ", &PhatfurryZ},
    {HATFURRYBLACK, "PhatfurryblackZ", &PhatfurryblackZ},
    {HATFURRYBROWN, "PhatfurrybrownZ", &PhatfurrybrownZ},
    {HATHELMET, "PhathelmetZ", &PhathelmetZ},
    {HATHELMETGREY, "PhathelmetgreyZ", &PhathelmetgreyZ},
    {HATMOON, "PhatmoonZ", &PhatmoonZ},
    {HATPEAKED, "PhatpeakedZ", &PhatpeakedZ},
    {HATTBIRD, "PhattbirdZ", &PhattbirdZ},
    {HATTBIRDBROWN, "PhattbirdbrownZ", &PhattbirdbrownZ},
    {HELICOPTER, "PhelicopterZ", &PhelicopterZ},
    {HIND, "PhindZ", &PhindZ},
    {JEEP, "PjeepZ", &PjeepZ},
    {JERRY_CAN1, "Pjerry_can1Z", &Pjerry_can1Z},
    {JUNGLE3_TREE, "Pjungle3_treeZ", &Pjungle3_treeZ},
    {JUNGLE5_TREE, "Pjungle5_treeZ", &Pjungle5_treeZ},
    {KEY_HOLDER, "Pkey_holderZ", &Pkey_holderZ},
    {KEYBOARD1, "Pkeyboard1Z", &Pkeyboard1Z},
    {KIT_UNITS1, "Pkit_units1Z", &Pkit_units1Z},
    {LABBENCH, "PlabbenchZ", &PlabbenchZ},
    {LANDMINE, "PlandmineZ", &PlandmineZ},
    {LEGALPAGE, "PlegalpageZ", &PlegalpageZ},
    {LETTER_TRAY1, "Pletter_tray1Z", &Pletter_tray1Z},
    {LOCKER3, "Plocker3Z", &Plocker3Z},
    {LOCKER4, "Plocker4Z", &Plocker4Z},
    {M16MAG, "Pm16magZ", &Pm16magZ},
    {MAGNUMSHELLS, "PmagnumshellsZ", &PmagnumshellsZ},
    {MAINFRAME1, "Pmainframe1Z", &Pmainframe1Z},
    {MAINFRAME2, "Pmainframe2Z", &Pmainframe2Z},
    {METAL_CHAIR1, "Pmetal_chair1Z", &Pmetal_chair1Z},
    {METAL_CRATE1, "Pmetal_crate1Z", &Pmetal_crate1Z},
    {METAL_CRATE2, "Pmetal_crate2Z", &Pmetal_crate2Z},
    {METAL_CRATE3, "Pmetal_crate3Z", &Pmetal_crate3Z},
    {METAL_CRATE4, "Pmetal_crate4Z", &Pmetal_crate4Z},
    {MILCOPTER, "PmilcopterZ", &PmilcopterZ},
    {MILTRUCK, "PmiltruckZ", &PmiltruckZ},
    {MISSILE_RACK2, "Pmissile_rack2Z", &Pmissile_rack2Z},
    {MISSILE_RACK, "Pmissile_rackZ", &Pmissile_rackZ},
    {MODEMBOX, "PmodemboxZ", &PmodemboxZ},
    {MOTORBIKE, "PmotorbikeZ", &PmotorbikeZ},
    {MP5KMAG, "Pmp5kmagZ", &Pmp5kmagZ},
    {NINTENDOLOGO, "PnintendologoZ", &PnintendologoZ},
    {OIL_DRUM1, "Poil_drum1Z", &Poil_drum1Z},
    {OIL_DRUM2, "Poil_drum2Z", &Poil_drum2Z},
    {OIL_DRUM3, "Poil_drum3Z", &Poil_drum3Z},
    {OIL_DRUM5, "Poil_drum5Z", &Poil_drum5Z},
    {OIL_DRUM6, "Poil_drum6Z", &Poil_drum6Z},
    {OIL_DRUM7, "Poil_drum7Z", &Poil_drum7Z},
    {PADLOCK, "PpadlockZ", &PpadlockZ},
    {PALM, "PpalmZ", &PpalmZ},
    {PALMTREE, "PpalmtreeZ", &PpalmtreeZ},
    {PHONE1, "Pphone1Z", &Pphone1Z},
    {PLANE, "PplaneZ", &PplaneZ},
    {PLANT11, "Pplant11Z", &Pplant11Z},
    {PLANT1, "Pplant1Z", &Pplant1Z},
    {PLANT2, "Pplant2Z", &Pplant2Z},
    {PLANT2B, "Pplant2bZ", &Pplant2bZ},
    {PLANT3, "Pplant3Z", &Pplant3Z},
    {RADIO_UNIT1, "Pradio_unit1Z", &Pradio_unit1Z},
    {RADIO_UNIT2, "Pradio_unit2Z", &Pradio_unit2Z},
    {RADIO_UNIT3, "Pradio_unit3Z", &Pradio_unit3Z},
    {RADIO_UNIT4, "Pradio_unit4Z", &Pradio_unit4Z},
    {ROOFGUN, "ProofgunZ", &ProofgunZ},
    {SAFE, "PsafeZ", &PsafeZ},
    {SAFEDOOR, "PsafedoorZ", &PsafedoorZ},
    {SAT1_REFLECT, "Psat1_reflectZ", &Psat1_reflectZ},
    {SATBOX, "PsatboxZ", &PsatboxZ},
    {SATDISH, "PsatdishZ", &PsatdishZ},
    {SEC_PANEL, "Psec_panelZ", &Psec_panelZ},
    {SEV_DOOR3, "Psev_door3Z", &Psev_door3Z},
    {SEV_DOOR3_WIND, "Psev_door3_windZ", &Psev_door3_windZ},
    {SEV_DOOR4_WIND, "Psev_door4_windZ", &Psev_door4_windZ},
    {SEV_DOOR, "Psev_doorZ", &Psev_doorZ},
    {SEV_DOOR_V1, "Psev_door_v1Z", &Psev_door_v1Z},
    {SEV_TRISLIDE, "Psev_trislideZ", &Psev_trislideZ},
    {SEVDISH, "PsevdishZ", &PsevdishZ},
    {SEVDOORMETSLIDE, "PsevdoormetslideZ", &PsevdoormetslideZ},
    {SEVDOORNOWIND, "PsevdoornowindZ", &PsevdoornowindZ},
    {SEVDOORWIND, "PsevdoorwindZ", &PsevdoorwindZ},
    {SEVDOORWOOD, "PsevdoorwoodZ", &PsevdoorwoodZ},
    {SHUTTLE, "PshuttleZ", &PshuttleZ},
    {SHUTTLE_DOOR_L, "Pshuttle_door_lZ", &Pshuttle_door_lZ},
    {SHUTTLE_DOOR_R, "Pshuttle_door_rZ", &Pshuttle_door_rZ},
    {SILENCER, "PsilencerZ", &PsilencerZ},
    {SILO_LIFT_DOOR, "Psilo_lift_doorZ", &Psilo_lift_doorZ},
    {SILOTOPDOOR, "PsilotopdoorZ", &PsilotopdoorZ},
    {SKORPIONMAG, "PskorpionmagZ", &PskorpionmagZ},
    {SPECTREMAG, "PspectremagZ", &PspectremagZ},
    {SPEEDBOAT, "PspeedboatZ", &PspeedboatZ},
    {ST_PETE_ROOM_1I, "Pst_pete_room_1iZ", &Pst_pete_room_1iZ},
    {ST_PETE_ROOM_2I, "Pst_pete_room_2iZ", &Pst_pete_room_2iZ},
    {ST_PETE_ROOM_3T, "Pst_pete_room_3tZ", &Pst_pete_room_3tZ},
    {ST_PETE_ROOM_5C, "Pst_pete_room_5cZ", &Pst_pete_room_5cZ},
    {ST_PETE_ROOM_6C, "Pst_pete_room_6cZ", &Pst_pete_room_6cZ},
    {STEEL_DOOR1, "Psteel_door1Z", &Psteel_door1Z},
    {STEEL_DOOR2, "Psteel_door2Z", &Psteel_door2Z},
    {STEEL_DOOR2B, "Psteel_door2bZ", &Psteel_door2bZ},
    {STEEL_DOOR3, "Psteel_door3Z", &Psteel_door3Z},
    {STOOL1, "Pstool1Z", &Pstool1Z},
    {SWIPE_CARD2, "Pswipe_card2Z", &Pswipe_card2Z},
    {SWIVEL_CHAIR1, "Pswivel_chair1Z", &Pswivel_chair1Z},
    {TANK, "PtankZ", &PtankZ},
    {TIGER, "PtigerZ", &PtigerZ},
    {TORPEDO_RACK, "Ptorpedo_rackZ", &Ptorpedo_rackZ},
    {TRAIN_DOOR2, "Ptrain_door2Z", &Ptrain_door2Z},
    {TRAIN_DOOR3, "Ptrain_door3Z", &Ptrain_door3Z},
    {TRAIN_DOOR, "Ptrain_doorZ", &Ptrain_doorZ},
    {TRAINEXTDOOR, "PtrainextdoorZ", &PtrainextdoorZ},
    {TT33MAG, "Ptt33magZ", &Ptt33magZ},
    {TUNING_CONSOLE1, "Ptuning_console1Z", &Ptuning_console1Z},
    {TV1, "Ptv1Z", &Ptv1Z},
    {TV4SCREEN, "Ptv4screenZ", &Ptv4screenZ},
    {TV_HOLDER, "Ptv_holderZ", &Ptv_holderZ},
    {TVSCREEN, "PtvscreenZ", &PtvscreenZ},
    {UZIMAG, "PuzimagZ", &PuzimagZ},
    {VERTDOOR, "PvertdoorZ", &PvertdoorZ},
    {WALLETBOND, "PwalletbondZ", &PwalletbondZ},
    {WINDOW, "PwindowZ", &PwindowZ},
    {WINDOW_COR11, "Pwindow_cor11Z", &Pwindow_cor11Z},
    {WINDOW_LIB_LG1, "Pwindow_lib_lg1Z", &Pwindow_lib_lg1Z},
    {WINDOW_LIB_SM1, "Pwindow_lib_sm1Z", &Pwindow_lib_sm1Z},
    {WOOD_LG_CRATE1, "Pwood_lg_crate1Z", &Pwood_lg_crate1Z},
    {WOOD_LG_CRATE2, "Pwood_lg_crate2Z", &Pwood_lg_crate2Z},
    {WOOD_MD_CRATE3, "Pwood_md_crate3Z", &Pwood_md_crate3Z},
    {WOOD_SM_CRATE4, "Pwood_sm_crate4Z", &Pwood_sm_crate4Z},
    {WOOD_SM_CRATE5, "Pwood_sm_crate5Z", &Pwood_sm_crate5Z},
    {WOOD_SM_CRATE6, "Pwood_sm_crate6Z", &Pwood_sm_crate6Z},
    {WOODEN_TABLE1, "Pwooden_table1Z", &Pwooden_table1Z},
    {WPPKMAG, "PwppkmagZ", &PwppkmagZ},

    {BG_AME_ALL_P_STAN, "Tbg_ame_all_p_stanZ", &Tbg_ame_all_p_stanZ},
    {BG_ARCH_ALL_P_STAN, "Tbg_arch_all_p_stanZ", &Tbg_arch_all_p_stanZ},
    {BG_AREC_ALL_P_STAN, "Tbg_arec_all_p_stanZ", &Tbg_arec_all_p_stanZ},
    {BG_ARK_ALL_P_STAN, "Tbg_ark_all_p_stanZ", &Tbg_ark_all_p_stanZ},
    {BG_ASH_ALL_P_STAN, "Tbg_ash_all_p_stanZ", &Tbg_ash_all_p_stanZ},
    {BG_AZT_ALL_P_STAN, "Tbg_azt_all_p_stanZ", &Tbg_azt_all_p_stanZ},
    {BG_CAT_ALL_P_STAN, "Tbg_cat_all_p_stanZ", &Tbg_cat_all_p_stanZ},
    {BG_CAVE_ALL_P_STAN, "Tbg_cave_all_p_stanZ", &Tbg_cave_all_p_stanZ},
    {BG_CRAD_ALL_P_STAN, "Tbg_crad_all_p_stanZ", &Tbg_crad_all_p_stanZ},
    {BG_CRYP_ALL_P_STAN, "Tbg_cryp_all_p_stanZ", &Tbg_cryp_all_p_stanZ},
    {BG_DAM_ALL_P_STAN, "Tbg_dam_all_p_stanZ", &Tbg_dam_all_p_stanZ},
    {BG_DEPO_ALL_P_STAN, "Tbg_depo_all_p_stanZ", &Tbg_depo_all_p_stanZ},
    {BG_DEST_ALL_P_STAN, "Tbg_dest_all_p_stanZ", &Tbg_dest_all_p_stanZ},
    {BG_DISH_ALL_P_STAN, "Tbg_dish_all_p_stanZ", &Tbg_dish_all_p_stanZ},
    {BG_EAR_ALL_P_STAN, "Tbg_ear_all_p_stanZ", &Tbg_imp_all_p_stanZ},
    {BG_ELD_ALL_P_STAN, "Tbg_eld_all_p_stanZ", &Tbg_imp_all_p_stanZ},
    {BG_IMP_ALL_P_STAN, "Tbg_imp_all_p_stanZ", &Tbg_imp_all_p_stanZ},
    {BG_JUN_ALL_P_STAN, "Tbg_jun_all_p_stanZ", &Tbg_jun_all_p_stanZ},
    {BG_LEE_ALL_P_STAN, "Tbg_lee_all_p_stanZ", &Tbg_len_all_p_stanZ},
    {BG_LEN_ALL_P_STAN, "Tbg_len_all_p_stanZ", &Tbg_len_all_p_stanZ},
    {BG_LIP_ALL_P_STAN, "Tbg_lip_all_p_stanZ", &Tbg_oat_all_p_stanZ},
    {BG_LUE_ALL_P_STAN, "Tbg_lue_all_p_stanZ", &Tbg_oat_all_p_stanZ},
    {BG_OAT_ALL_P_STAN, "Tbg_oat_all_p_stanZ", &Tbg_oat_all_p_stanZ},
    {BG_PAM_ALL_P_STAN, "Tbg_pam_all_p_stanZ", &Tbg_pete_all_p_stanZ},
    {BG_PETE_ALL_P_STAN, "Tbg_pete_all_p_stanZ", &Tbg_pete_all_p_stanZ},
    {BG_REF_ALL_P_STAN, "Tbg_ref_all_p_stanZ", &Tbg_ref_all_p_stanZ},
    {BG_RIT_ALL_P_STAN, "Tbg_rit_all_p_stanZ", &Tbg_run_all_p_stanZ},
    {BG_RUN_ALL_P_STAN, "Tbg_run_all_p_stanZ", &Tbg_run_all_p_stanZ},
    {BG_SEV_ALL_P_STAN, "Tbg_sev_all_p_stanZ", &Tbg_sev_all_p_stanZ},
    {BG_SEVB_ALL_P_STAN, "Tbg_sevb_all_p_stanZ", &Tbg_sevb_all_p_stanZ},
    {BG_SEVX_ALL_P_STAN, "Tbg_sevx_all_p_stanZ", &Tbg_sevx_all_p_stanZ},
    {BG_SILO_ALL_P_STAN, "Tbg_silo_all_p_stanZ", &Tbg_silo_all_p_stanZ},
    {BG_STAT_ALL_P_STAN, "Tbg_stat_all_p_stanZ", &Tbg_stat_all_p_stanZ},
    {BG_TRA_ALL_P_STAN, "Tbg_tra_all_p_stanZ", &Tbg_tra_all_p_stanZ},
    {BG_WAX_ALL_P_STAN, "Tbg_wax_all_p_stanZ", &UbriefarchZ},

    {BRIEFARCH, "UbriefarchZ", &UbriefarchZ},
    {BRIEFARK, "UbriefarkZ", &UbriefarkZ},
    {BRIEFAZT, "UbriefaztZ", &UbriefaztZ},
    {BRIEFCAVE, "UbriefcaveZ", &UbriefcaveZ},
    {BRIEFCONTROL, "UbriefcontrolZ", &UbriefcontrolZ},
    {BRIEFCRAD, "UbriefcradZ", &UbriefcradZ},
    {BRIEFCRYP, "UbriefcrypZ", &UbriefcrypZ},
    {BRIEFDAM, "UbriefdamZ", &UbriefdamZ},
    {BRIEFDEPO, "UbriefdepoZ", &UbriefdepoZ},
    {BRIEFDEST, "UbriefdestZ", &UbriefdestZ},
    {BRIEFJUN, "UbriefjunZ", &UbriefjunZ},
    {BRIEFPETE, "UbriefpeteZ", &UbriefpeteZ},
    {BRIEFRUN, "UbriefrunZ", &UbriefrunZ},
    {BRIEFSEVB, "UbriefsevbZ", &UbriefsevbZ},
    {BRIEFSEVBUNKER, "UbriefsevbunkerZ", &UbriefsevbunkerZ},
    {BRIEFSEVX, "UbriefsevxZ", &UbriefsevxZ},
    {BRIEFSEVXB, "UbriefsevxbZ", &UbriefsevxbZ},
    {BRIEFSILO, "UbriefsiloZ", &UbriefsiloZ},
    {BRIEFSTATUE, "UbriefstatueZ", &UbriefstatueZ},
    {BRIEFTRA, "UbrieftraZ", &UbrieftraZ},

    {MP_SETUPAME, "Ump_setupameZ", &Ump_setupameZ},
    {MP_SETUPARCH, "Ump_setuparchZ", &Ump_setuparchZ},
    {MP_SETUPARK, "Ump_setuparkZ", &Ump_setuparkZ},
    {MP_SETUPASH, "Ump_setupashZ", &Ump_setupashZ},
    {MP_SETUPCAVE, "Ump_setupcaveZ", &Ump_setupcaveZ},
    {MP_SETUPCRAD, "Ump_setupcradZ", &Ump_setupcradZ},
    {MP_SETUPCRYP, "Ump_setupcrypZ", &Ump_setupcrypZ},
    {MP_SETUPDISH, "Ump_setupdishZ", &Ump_setupdishZ},
    {MP_SETUPIMP, "Ump_setupimpZ", &Ump_setupimpZ},
    {MP_SETUPOAT, "Ump_setupoatZ", &Ump_setupoatZ},
    {MP_SETUPREF, "Ump_setuprefZ", &Ump_setuprefZ},
    {MP_SETUPSEVB, "Ump_setupsevbZ", &Ump_setupsevbZ},
    {MP_SETUPSTATUE, "Ump_setupstatueZ", &Ump_setupstatueZ},

    {SETUPARCH, "UsetuparchZ", &UsetuparchZ},
    {SETUPARK, "UsetuparkZ", &UsetuparkZ},
    {SETUPAZT, "UsetupaztZ", &UsetupaztZ},
    {SETUPCAVE, "UsetupcaveZ", &UsetupcaveZ},
    {SETUPCONTROL, "UsetupcontrolZ", &UsetupcontrolZ},
    {SETUPCRAD, "UsetupcradZ", &UsetupcradZ},
    {SETUPCRYP, "UsetupcrypZ", &UsetupcrypZ},
    {SETUPDAM, "UsetupdamZ", &UsetupdamZ},
    {SETUPDEPO, "UsetupdepoZ", &UsetupdepoZ},
    {SETUPDEST, "UsetupdestZ", &UsetupdestZ},
    {SETUPJUN, "UsetupjunZ", &UsetupjunZ},
    {SETUPLEN, "UsetuplenZ", &UsetuplenZ},
    {SETUPPETE, "UsetuppeteZ", &UsetuppeteZ},
    {SETUPRUN, "UsetuprunZ", &UsetuprunZ},
    {SETUPSEVB, "UsetupsevbZ", &UsetupsevbZ},
    {SETUPSEVBUNKER, "UsetupsevbunkerZ", &UsetupsevbunkerZ},
    {SETUPSEVX, "UsetupsevxZ", &UsetupsevxZ},
    {SETUPSEVXB, "UsetupsevxbZ", &UsetupsevxbZ},
    {SETUPSILO, "UsetupsiloZ", &UsetupsiloZ},
    {SETUPSTATUE, "UsetupstatueZ", &UsetupstatueZ},
    {SETUPTRA, "UsetuptraZ", &UsetuptraZ},

    {AMEE, "LameE", &LameE},
    {AMEJ, "LameJ", &LameJ},
#ifdef VERSION_EU
    {AMEP, "LameP", &LameP},
#endif
    {ARCHE, "LarchE", &LarchE},
    {ARCHJ, "LarchJ", &LarchJ},
#ifdef VERSION_EU
    {ARCHP, "LarchP", &LarchP},
#endif
    {ARECE, "LarecE", &LarecE},
    {ARECJ, "LarecJ", &LarecJ},
#ifdef VERSION_EU
    {ARECP, "LarecP", &LarecP},
#endif
    {ARKE, "LarkE", &LarkE},
    {ARKJ, "LarkJ", &LarkJ},
#ifdef VERSION_EU
    {ARKP, "LarkP", &LarkP},
#endif
    {ASHE, "LashE", &LashE},
    {ASHJ, "LashJ", &LashJ},
#ifdef VERSION_EU
    {ASHP, "LashP", &LashP},
#endif
    {AZTE, "LaztE", &LaztE},
    {AZTJ, "LaztJ", &LaztJ},
#ifdef VERSION_EU
    {AZTP, "LaztP", &LaztP},
#endif
    {CATE, "LcatE", &LcatE},
    {CATJ, "LcatJ", &LcatJ},
#ifdef VERSION_EU
    {CATP, "LcatP", &LcatP},
#endif
    {CAVEE, "LcaveE", &LcaveE},
    {CAVEJ, "LcaveJ", &LcaveJ},
#ifdef VERSION_EU
    {CAVEP, "LcaveP", &LcaveP},
#endif
    {CRADE, "LcradE", &LcradE},
    {CRADJ, "LcradJ", &LcradJ},
#ifdef VERSION_EU
    {CRADP, "LcradP", &LcradP},
#endif
    {CRYPE, "LcrypE", &LcrypE},
    {CRYPJ, "LcrypJ", &LcrypJ},
#ifdef VERSION_EU
    {CRYPP, "LcrypP", &LcrypP},
#endif
    {DAME, "LdamE", &LdamE},
    {DAMJ, "LdamJ", &LdamJ},
#ifdef VERSION_EU
    {DAMP, "LdamP", &LdamP},
#endif
    {DEPOE, "LdepoE", &LdepoE},
    {DEPOJ, "LdepoJ", &LdepoJ},
#ifdef VERSION_EU
    {DEPOP, "LdepoP", &LdepoP},
#endif
    {DESTE, "LdestE", &LdestE},
    {DESTJ, "LdestJ", &LdestJ},
#ifdef VERSION_EU
    {DESTP, "LdestP", &LdestP},
#endif
    {DISHE, "LdishE", &LdishE},
    {DISHJ, "LdishJ", &LdishJ},
#ifdef VERSION_EU
    {DISHP, "LdishP", &LdishP},
#endif
    {EARE, "LearE", &LearE},
    {EARJ, "LearJ", &LearJ},
#ifdef VERSION_EU
    {EARP, "LearP", &LearP},
#endif
    {ELDE, "LeldE", &LeldE},
    {ELDJ, "LeldJ", &LeldJ},
#ifdef VERSION_EU
    {ELDP, "LeldP", &LeldP},
#endif
    {GUNE, "LgunE", &LgunE},
    {GUNJ, "LgunJ", &LgunJ},
#ifdef VERSION_EU
    {GUNP, "LgunP", &LgunP},
#endif
    {IMPE, "LimpE", &LimpE},
    {IMPJ, "LimpJ", &LimpJ},
#ifdef VERSION_EU
    {IMPP, "LimpP", &LimpP},
#endif
    {JUNE, "LjunE", &LjunE},
    {JUNJ, "LjunJ", &LjunJ},
#ifdef VERSION_EU
    {JUNP, "LjunP", &LjunP},
#endif
    {LEEE, "LleeE", &LleeE},
    {LEEJ, "LleeJ", &LleeJ},
#ifdef VERSION_EU
    {LEEP, "LleeP", &LleeP},
#endif
    {LENE, "LlenE", &LlenE},
    {LENJ, "LlenJ", &LlenJ},
#ifdef VERSION_EU
    {LENP, "LlenP", &LlenP},
#endif
    {LIPE, "LlipE", &LlipE},
    {LIPJ, "LlipJ", &LlipJ},
#ifdef VERSION_EU
    {LIPP, "LlipP", &LlipP},
#endif
    {LUEE, "LlueE", &LlueE},
    {LUEJ, "LlueJ", &LlueJ},
#ifdef VERSION_EU
    {LUEP, "LlueP", &LlueP},
#endif
    {MISCE, "LmiscE", &LmiscE},
    {MISCJ, "LmiscJ", &LmiscJ},
#ifdef VERSION_EU
    {MISCP, "LmiscP", &LmiscP},
#endif
    {MPMENUE, "LmpmenuE", &LmpmenuE},
    {MPMENUJ, "LmpmenuJ", &LmpmenuJ},
#ifdef VERSION_EU
    {MPMENUP, "LmpmenuP", &LmpmenuP},
#endif
    {MPWEAPONSE, "LmpweaponsE", &LmpweaponsE},
    {MPWEAPONSJ, "LmpweaponsJ", &LmpweaponsJ},
#ifdef VERSION_EU
    {MPWEAPONSP, "LmpweaponsP", &LmpweaponsP},
#endif
    {OATE, "LoatE", &LoatE},
    {OATJ, "LoatJ", &LoatJ},
#ifdef VERSION_EU
    {OATP, "LoatP", &LoatP},
#endif
    {OPTIONSE, "LoptionsE", &LoptionsE},
    {OPTIONSJ, "LoptionsJ", &LoptionsJ},
#ifdef VERSION_EU
    {OPTIONSP, "LoptionsP", &LoptionsP},
#endif
    {PAME, "LpamE", &LpamE},
    {PAMJ, "LpamJ", &LpamJ},
#ifdef VERSION_EU
    {PAMP, "LpamP", &LpamP},
#endif
    {PETEE, "LpeteE", &LpeteE},
    {PETEJ, "LpeteJ", &LpeteJ},
#ifdef VERSION_EU
    {PETEP, "LpeteP", &LpeteP},
#endif
    {PROPOBJE, "LpropobjE", &LpropobjE},
    {PROPOBJJ, "LpropobjJ", &LpropobjJ},
#ifdef VERSION_EU
    {PROPOBJP, "LpropobjP", &LpropobjP},
#endif
    {REFE, "LrefE", &LrefE},
    {REFJ, "LrefJ", &LrefJ},
#ifdef VERSION_EU
    {REFP, "LrefP", &LrefP},
#endif
    {RITE, "LritE", &LritE},
    {RITJ, "LritJ", &LritJ},
#ifdef VERSION_EU
    {RITP, "LritP", &LritP},
#endif
    {RUNE, "LrunE", &LrunE},
    {RUNJ, "LrunJ", &LrunJ},
#ifdef VERSION_EU
    {RUNP, "LrunP", &LrunP},
#endif
    {SEVE, "LsevE", &LsevE},
    {SEVJ, "LsevJ", &LsevJ},
#ifdef VERSION_EU
    {SEVP, "LsevP", &LsevP},
#endif
    {SEVBE, "LsevbE", &LsevbE},
    {SEVBJ, "LsevbJ", &LsevbJ},
#ifdef VERSION_EU
    {SEVBP, "LsevbP", &LsevbP},
#endif
    {SEVXE, "LsevxE", &LsevxE},
    {SEVXJ, "LsevxJ", &LsevxJ},
#ifdef VERSION_EU
    {SEVXP, "LsevxP", &LsevxP},
#endif
    {SEVXBE, "LsevxbE", &LsevxbE},
    {SEVXBJ, "LsevxbJ", &LsevxbJ},
#ifdef VERSION_EU
    {SEVXBP, "LsevxbP", &LsevxbP},
#endif
    {SHOE, "LshoE", &LshoE},
    {SHOJ, "LshoJ", &LshoJ},
#ifdef VERSION_EU
    {SHOP, "LshoP", &LshoP},
#endif
    {SILOE, "LsiloE", &LsiloE},
    {SILOJ, "LsiloJ", &LsiloJ},
#ifdef VERSION_EU
    {SILOP, "LsiloP", &LsiloP},
#endif
    {STATE, "LstatE", &LstatE},
    {STATJ, "LstatJ", &LstatJ},
#ifdef VERSION_EU
    {STATP, "LstatP", &LstatP},
#endif
    {TITLEE, "LtitleE", &LtitleE},
    {TITLEJ, "LtitleJ", &LtitleJ},
#ifdef VERSION_EU
    {TITLEP, "LtitleP", &LtitleP},
#endif
    {TRAE, "LtraE", &LtraE},
    {TRAJ, "LtraJ", &LtraJ},
#ifdef VERSION_EU
    {TRAP, "LtraP", &LtraP},
#endif
    {WAXE, "LwaxE", &LwaxE},
    {WAXJ, "LwaxJ", &LwaxJ},
#ifdef VERSION_EU
    {WAXP, "LwaxP", &LwaxP},
#endif
    
    {OBENDSEG, "ob/ob_end.seg", &ob__ob_end_seg},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0}
};


