
char *LarchE[] = {
 "Captured by the Russians, Bond must escape their military prison.\n",
 "Again? Captured again? I hope you can defend your performance, 007, because there isn't a lawyer in the land who'd take on the case.\nYour only chance is to speak directly to Defense Minister Mishkin. He's a reasonable man, for a member of the Politburo.\nFailure is not an option, Bond.\n",
 "Up to you to get out of this one, 007. I can't hold your hand all the time. By the way, get that flight recorder for me, would you? Thanks.\n",
 "Banged up again, James? Now you know what it's like to be trapped behind a desk, and I'm off out to the theatre with a gentleman tonight. How times change!\n",
 "Escape from interrogation room\n",
 "Find Natalya\n",
 "Recover helicopter black box\n",
 "Escape with Natalya\n",
 "Natalya: James!\n",
 "Natalya: Be careful with that gun!\n",
 "Natalya: We could escape through the\n           library windows.\n",
 "Natalya: I'm scared, I'm getting out of here.\n",
 "Natalya: Aaaaargh!\n",
 "Guard: So Mr. Bond, what do you know\n         about the theft of the\n         Goldeneye?\n",
 "Guard: Nonsense, Mr. Bond,\n         General Ourumov is a hero\n         of the Soviet Union.\n",
 "Bond: Ourumov stole it - he's a traitor.\n",
 "Guard: Drop that weapon NOW!\n",
 "Bond: Perhaps, he was once, but he has\n        betrayed you now.\n",
 "Guard: All lies, Mr. Bond.\n         You are nothing but a terrorist.\n",
 "Guard: You will be executed along with\n         that foolish girl.\n",
 "Bond: Natalya has done nothing wrong.\n        She knows what happened at\n        Severnaya.\n",
 "Guard: Really? Well, we shall have to\n         ask her about that.\n",
 "Guard: I'm sure she can be persuaded\n         to answer our questions more\n         fully.\n",
 "Guard: HALT!\n         You're going nowhere, Mr.Bond!\n",
 "Soldier: New orders from General\n           Ourumov.\n           Kill the spy at once!\n",
 "Mishkin: It appears you were correct,\n           Mr. Bond\n",
 "Mishkin: General Ourumov is our traitor.\n",
 "Bond: Even trusted friends are capable\n        of betrayal.\n",
 "Mishkin: A costly lesson.\n",
 "Mishkin: Do you need the black box\n           from the stolen helicopter?\n",
 "Bond: Yes, it proves that Janus was\n        involved in the Severnaya incident.\n",
 "Mishkin: It is in the safe.\n",
 "Mishkin: I must inform the Politburo\n           of Ourumov's deceit.\n",
 "Mishkin: Good-bye, Mr. Bond\n",
 "Natalya: We need to talk to Defense\n           Minister Mishkin.\n",
 "Got safe key\n",
 "A R C H I V E S\n",
 "captured by the russians, bond must escape their military prison.\n",
 "again? captured again? i hope you can defend your performance, 007, because there isn't a lawyer in the land who'd take on the case.\nyour only chance is to speak directly to defense minister mishkin. he's a reasonable man, for a member of the politburo.\nfailure is not an option, bond.\n",
 "up to you to get out of this one, 007. i can't hold your hand all the time. by the way, get that flight recorder for me, would you? thanks.\n",
 "banged up again, james? now you know what it's like to be trapped behind a desk, and i'm off out to the theatre with a gentleman tonight. how times change!\n",
 "escape from interrogation room\n",
 "find natalya\n",
 "recover helicopter black box\n",
 "escape with natalya\n",
 "GRU Military Intelligence Archives,\nSt. Petersburg\n",
 "\n",
 "door key\n",
 "interrogation room key\n",
 "interrogation room key\n",
 "Picked up a door key.\n",
 0,
 "This safe is locked.\n",
 "flight\n",
 "recorder\n",
 "flight recorder\n",
 "pirate flight recorder\n",
 "Picked up the flight recorder.\n",
 "\n",
 "safe key\n",
 "safe key\n",
 "Safe Key\n",
 "Picked up a safe key.\n",
 0
};
