
char *LarecE[] = {
 "The Janus Control Center has been located in an underground complex in the Cuban jungle.\n",
 "Into the lion's den, 007. Well, just be careful. Remember that you and Miss Simonova are a team, it's critical that you protect her while she's hacking into the Janus computers. With any luck she'll be able to stop the Goldeneye from firing.\n",
 "While you're there old boy, see if you can't erase their databases. The details of Janus' criminal bankrolls are stored on specially armored mainframe units. That information is worth millions to Janus - I'm sure you'll find some way of deleting it.\n",
 "You know, James, she's not the only woman who can operate a computer.\n",
 "Protect Natalya\n",
 "Disable Goldeneye satellite\n",
 "Destroy armored mainframes\n",
 "Natalya: Be careful, James!\n",
 "Bond: Wait here in the lift, Natalya.\n        I'll secure the area.\n",
 "Natalya: The blast doors have been locked\n           by the security computer.\n",
 "Natalya: Got one open! Head for the\n           control room, James, I'll do\n           what I can from here.\n",
 "Natalya: James, you were wonderful!\n",
 "Natalya: James, you're hurt.\n",
 "Natalya: Oh dear, James, that didn't\n           go so well.\n",
 "Natalya: The Goldeneye is set to fire\n           on London!\n",
 "Natalya: I'll try to override the guidance\n           controls.\n",
 "Natalya: I'm coming, James!.\n",
 "Natalya: Did it! The satellite's orbit is\n           decaying.\n",
 "Bond: Get back to the surface, Natalya.\n        I'm going after Trevelyan.\n",
 "Natalya: Good luck, James, I'll be\n           waiting for you.\n",
 "Natalya: The boundary-layer temperature\n           stays pretty steady till re-entry.\n",
 "Natalya: If I can just get the\n           yaw oscillation above 5 degrees.\n",
 "Natalya: James! I need cover while I'm\n           doing this!\n",
 "Natalya: James, do you think you could\n           be a bit quieter? I can't hear\n           myself think.\n",
 "Natalya: James, I...\n",
 "Boris: Please don't shoot!\n        Trevelyan made me do it.\n",
 "Boris: Aha! I am invincible!\n",
 "Trevelyan: Too slow, James!\n",
 "Boris: Oops!\n",
 "Natalya: Very clever, James. Just how\n           am I going to hack into the\n           security computer now?\n",
 "Natalya: Smart work, James. That was\n           the only console which had\n           access to the guidance systems.\n",
 "Natalya: I'm going to the lift. I might\n           still be there when you're\n           finished clowning around here.\n",
 "Natalya: I saw what you did to Boris\n           on the security monitor.\n           It wasn't very nice.\n",
 "Natalya: He was just a programmer,\n           James. You didn't need to\n           kill him.\n",
 "Boris: Don't mind me, I just\n        look after the computers.\n",
 "Natalya has been killed!\n",
 "J A N U S  C O N T R O L\n",
 "the janus control center has been located in an underground complex in the cuban jungle.\n",
 "into the lion's den, 007. well, just be careful. remember that you and miss simonova are a team, it's critical that you protect her while she's hacking into the janus computers. with any luck she'll be able to stop the goldeneye from firing.\n",
 "while you're there old boy, see if you can't erase their databases. the details of janus' criminal bankrolls are stored on specially armored mainframe units. that information is worth millions to janus - i'm sure you'll find some way of deleting it.\n",
 "you know, james, she's not the only woman who can operate a computer.\n",
 "protect natalya\n",
 "disable goldeneye satellite\n",
 "destroy armored mainframes\n",
 "Janus Control Center, Cuba\n",
 0,
 0,
 0
};
