
char *LarkE[] = {
 "Inside the chemical weapons facility you should quickly and efficiently proceed to the bottling area and place demolition charges on the main gas tanks.\nPolitical considerations demand that collateral damage is minimized on this mission. Non-military personnel should be disregarded.\n",
 "You'll be working with 006 on this assignment, the bottling room is the rendezvous point. \nDon't forget to contact our double agent scientist before you leave, and warn him to get out. He will provide you with a decoder for the final security door. There are no women or casinos for a thousand miles, 007, so even you will be able to concentrate on this mission.\n",
 "Now listen carefully, Bond. Those bombs will be armed as soon as the last one is set. Don't be too close when you set them off or you'll go up in flames as well, and while you're at it, please try and bring back that door-opener undamaged for once. Too much rough handling like the last mission and it might go wrong at a bad time.\nHonestly 007, sometimes I think you damage your equipment on purpose.\n",
 "These chemicals could prove to be a match even for your pheromones, James. Don't take too many risks.\n",
 "Gain entry to laboratory area\n",
 "Contact double agent\n",
 "Rendezvous with 006\n",
 "Destroy all tanks in bottling room\n",
 "Minimize scientist casualties\n",
 "Trevelyan: Glad you could make it, 007.\n",
 "Trevelyan: For England - James.\n",
 "Bond: For England, Alec.\n",
 "Bond: It was too easy, Alec.\n",
 "Trevelyan: Half of everything is luck.\n",
 "Bond: ...and the other half?\n",
 "Trevelyan: Fate.\n",
 "Trevelyan: Why, James?\n",
 "Bond: Time to leave, Dr. Doak.\n",
 "Dr. Doak: You'll need this decoder to\n            open the bottling room door.\n            Good luck, 007.\n",
 "Ourumov: Throw down your weapons...\n              You are surrounded!\n",
 "Trevelyan: Finish the job, James!\n",
 "Trevelyan: So, you decided to come\n              back.\n",
 "Trevelyan: There's a job to do here.\n              Don't neglect your duty,\n              James!\n",
 "Bond: It was a bit tricky, Alec.\n",
 "Bond: I almost killed myself getting\n        here, Alec.\n",
 "Ourumov: Nine\n",
 "Ourumov: Eight\n",
 "Ourumov: Seven\n",
 "Ourumov: Six\n",
 "Ourumov: Five\n",
 "Ourumov: Four\n",
 "Ourumov: Three\n",
 "Ourumov: Two\n",
 "Ourumov: One...\n",
 "Ourumov: 1\n",
 "Ourumov: One... Kill him!\n",
 "Ourumov: You have ten seconds...\n",
 "Trevelyan: So, the golden boy is a traitor!\n              How ironic, James.\n",
 "Trevelyan: Why can't you just be a \n              good boy and die, James?\n",
 "Security door activated.\n",
 "Gas leak detected - isolating area.\n",
 "Security code accepted - access granted.\n",
 "Mission Failure: Unacceptable non-military\ncasualties!\n",
 "A R K A N G E L S K\n",
 "inside the chemical weapons facility you should quickly and efficiently proceed to the bottling area and place demolition charges on the main gas tanks.\npolitical considerations demand that collateral damage is minimized on this mission. non-military personnel should be disregarded.\n",
 "you'll be working with 006 on this assignment, the bottling room is the rendezvous point.\n\ndon't forget to contact our double agent scientist before you leave, and warn him to get out.\nhe will provide you with a decoder for the final security door.\n\nthere are no women or casinos for a thousand miles, 007, so even you will be able to concentrate on this mission.\n",
 "now listen carefully, bond. those bombs will be armed as soon as the last one is set. don't be too close when you set them off or you'll go up in flames as well. and while you're at it, please try and bring back that door-opener undamaged for once. too much rough handling like the last mission and it might go wrong at a bad time.\nhonestly 007, sometimes i think you damage your equipment on purpose.\n",
 "these chemicals could prove to be a match even for your pheromones, james. don't take too many risks.\n",
 "gain entry to laboratory area\n",
 "contact double agent\n",
 "rendezvous with 006\n",
 "destroy all tanks in bottling\n    room\n",
 "minimize scientist casualties\n",
 "\n",
 "decoder\n",
 "door decoder\n",
 "Door Decoder\n",
 "Picked up a door decoder.\n",
 "\n",
 "keycard A\n",
 "keycard A\n",
 "keycard A\n",
 "Picked up a clearance A keycard.\n",
 "\n",
 "keycard B\n",
 "keycard B\n",
 "keycard B\n",
 "Picked up a clearance B keycard.\n",
 0,
 "This is a remotely locked\nsecurity door.\n",
 "Chemical Warfare Facility #2\n",
 "Double agent contact has been killed!\n"
};
