#include "game/lvl_text.h"

struct stringentry LaztE[] = {
 "The Drax Corporation continues to be involved in unlicensed space exploration. Many of their projects are of a military nature and constitute a threat to the new world political order.",
 "The Drax launch facility is located in a South American Aztec ruin. They are scheduled to launch a stolen Nasa shuttle with an unknown military payload. We're sending you in alone, 007. Penetrating the base security will be tricky, but once you're in, we believe you will be able to recover the shuttle right out from under their noses. \n",
 "Simple plan, 007. Reprogram the guidance computer with the information on this floppy - then we can take control as soon as the old girl reaches orbit. Now pay attention, one thing we don't know is the Drax launch protocol - you'll have to find that data and install it to initiate the launch. Can't be too difficult to spot, it'll be lying around in some high security area.\n",
 "Quetzacoatl ring any bells, James? No, I didn't think so...\n",
 "Reprogram shuttle guidance\n",
 "Launch shuttle\n",
 "Exhaust bay opening.\n",
 "Exhaust bay closing.\n",
 "Q's guidance data has been uploaded.\n",
 "This disk drive is connected to the\nguidance computer systems.\n",
 "This mainframe controls the shuttle\nlaunch sequence.\n",
 "The launch protocol data has been\nuploaded.\n",
 "Shuttle launch sequence initiated.\n",
 "Final checks cleared. Shuttle launch is go.\n",
 "Shuttle exhaust bay closed!\nLaunch holding at T minus 10 seconds.\n",
 "The exhaust bay is secured for shuttle\nlaunch!\n",
 "A Z T E C\n",
 "the drax corporation continues to be involved in unlicensed space exploration. many of their projects are of a military nature and constitute a threat to the new world political order.",
 "the drax launch facility is located in a south american aztec ruin. they are scheduled to launch a stolen nasa shuttle with an unknown military payload. we're sending you in alone, 007. penetrating the base security will be tricky, but once you're in, we believe you will be able to recover the shuttle right out from under their noses. \n",
 "simple plan, 007. reprogram the guidance computer with the information on this floppy - then we can take control as soon as the old girl reaches orbit. now pay attention, one thing we don't know is the drax launch protocol - you'll have to find that data and install it to initiate the launch. can't be too difficult to spot, it'll be lying around in some high security area.\n",
 "quetzacoatl ring any bells, james? no, i didn't think so...\n",
 "reprogram shuttle guidance\n",
 "launch shuttle\n",
 "Aztec Complex, Teotihuaca'n\n",
 "\n",
 "DAT\n",
 "launch protocol data\n",
 "launch protocol data\n",
 "picked up a DAT\n",
 "\n",
 "smart card\n",
 "security smart card\n",
 "-\n",
 "Picked up a smart card.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 "This mainframe is inoperative.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 "This door requires\na security smart card.\n"
};
