
char *LcaveE[] = {
 "The Janus Control Center communicates with the Goldeneye weapons system via a large satellite dish which is usually concealed underwater. The pumps which allow Janus to flood the communications dish are housed in a subterranean cave complex defended by crack Janus troops.\n",
 "Don't jeopardize the mission by going for the man, Bond - nobody needs a dead hero. You'll be on your own but CIA combat support will be waiting. Find a radio and inform Jack Wade of the exact location of the dish and he'll send in the cavalry.\n",
 "The satellite communication dish is exposed. If you remove the water pumps, Janus will be unable to hide it again.\nDestroy the servo control consoles close to the pumps and be sure to disable the master console.\n",
 "Doing a spot of spelunking?\nWell, don't mess your trousers up, James.\n",
 "Destroy inlet pump controls\n",
 "Destroy outlet pump controls\n",
 "Destroy master control console\n",
 "Use radio to contact Jack Wade\n",
 "Pursue Trevelyan\n",
 "Minimize scientist casualties\n",
 "Trevelyan: So slow, James.\n              ... yet again.\n",
 "Radio damaged:\n      Cannot contact Jack Wade!\n",
 "Jack Wade: Got your bearings Jimbo!\n                Me and my boys are on\n                our way.\n",
 "Mission Failure: Unacceptable non-military\ncasualties!\n",
 "W A T E R   C A V E R N S\n",
 "the janus control center communicates with the goldeneye weapons system via a large satellite dish which is usually concealed underwater. the pumps which allow janus to flood the communications dish are housed in a subterranean cave complex  defended by crack janus troops.\n",
 "don't jeopardize the mission by going for the man, 007 - nobody needs a dead hero. you'll be on your own but CIA combat support will be waiting. find a radio and inform jack wade of the exact location of the dish and he'll send in the cavalry.\n",
 "the satellite communication dish is exposed. if you shut down the water pumps, janus will be unable to hide it again.\ndestroy the servo control consoles close to the pumps and be sure to disable the master console.\n",
 "doing a spot of spelunking?\nwell, don't come back with your trousers all messed up.\n",
 "destroy inlet pump controls\n",
 "destroy outlet pump controls\n",
 "destroy master control console\n",
 "use radio to contact jack wade\n",
 "pursue trevelyan\n",
 "minimize scientist casualties\n",
 "Subterranean Caverns\n",
 "\n",
 "code card\n",
 "code card a\n",
 "code card (blast door a)\n",
 "Picked up a code card\n",
 "\n",
 "code card\n",
 "code card b\n",
 "code card (blast door b)\n",
 "Picked up a code card\n",
 "\n",
 "code card\n",
 "code card c\n",
 "code card (blast door c)\n",
 "Picked up a code card\n",
 0,
 0,
 0
};
