#include "game/lvl_text.h"

struct stringentry LcradE[] = {
 "Janus control communications have been jammed and the Goldeneye satellite orbit is decaying. Only Trevelyan and his personal bodyguard remain unaccounted for.\n",
 "You know my feelings about personal vendettas interfering with mission success, 007. However, in this case, I think we can turn a blind eye to whatever happens out there. \n\nBe careful, and remember,\n                   - you are licensed to kill.\n",
 "Would you believe it, 007? There's another blasted control thingy actually on the antenna cradle. Trevelyan might be able to realign the antenna and get one last firing message through to the satellite. Get out there and destroy it! We don't want things going pear-shaped at the last minute.\n",
 "The hand that rocks the cradle rules the world, James.\nYou know I won't sleep soundly until you get back to England in one piece.\n",
 "Destroy control console\n",
 "Settle the score with Trevelyan\n",
 "Trevelyan has activated the antenna\ncontrol console!\n",
 "3 minutes until antenna realigns!\n",
 "Control console destroyed!\nAntenna inoperative.\n",
 "Antenna will signal satellite in 15 seconds!\n",
 "Mission failure: Goldeneye satellite has\nbeen reactivated!\n",
 "Trevelyan: Closing time, James. Last call.\n",
 "Trevelyan: You haven't won yet!\n",
 "Trevelyan: From the cradle to the grave\n              - your grave, James.\n",
 "Trevelyan: You could have joined me,\n              James, but you had to side\n              with the pen pushers.\n",
 "Trevelyan: Always loyal to the mission\n              - never to your friends.\n",
 "Trevelyan: James Bond. Her Majesty's\n              loyal terrier - you sicken me.\n",
 "Trevelyan: What's the matter, James?\n              No glib remark?\n              No pithy comeback?\n",
 "Trevelyan: Come on! Is that the best\n              you can do?\n",
 "Trevelyan: You never give up, do you?\n              Pathetic really.\n",
 "Trevelyan: You'll never win, James.\n",
 "Trevelyan: Finish the job, James\n                - if you can.\n",
 "Trevelyan: I was always better, James.\n",
 "Trevelyan: For England, James?\n",
 "Bond: No. For me.\n",
 "Trevelyan: You're not looking so well, \n              James - can't take the pace?\n",
 "A N T E N N A   C R A D L E\n",
 "janus control communications have been jammed and the goldeneye satellite orbit is decaying. only trevelyan and his personal bodyguard remain unaccounted for.\n",
 "you know my feelings about personal vendettas interfering with mission success, 007. however, in this case, i think we can turn a blind eye to whatever happens out there. \n\nbe careful, and remember,\n    -you are licensed to kill.\n",
 "would you believe it, 007? there's another blasted control thingy actually on the antenna cradle. trevelyan might be able to realign the antenna and get one last firing message through to the satellite. get out there and destroy it! we don't want things going pear-shaped at the last minute.\n",
 "the hand that rocks the cradle rules the world, james.\nyou know i won't sleep soundly until you get back to england in one piece.\n",
 "destroy control console\n",
 "settle the score with trevelyan\n",
 "\n",
 "Antenna Cradle, Janus Base, Cuba\n",
 NULL
};
