#include "game/lvl_text.h"

struct stringentry LdamE[] = {
 "MI6 has confirmed the existence of a secret chemical warfare facility at the Byelomorye dam, USSR. Its heavily guarded location and workings are a cause for major concern. Nerve gas produced there has been turning up in the hands of hostile regimes around the world and deals with international terrorists have been rumored. This facility should be destroyed with extreme prejudice.\n",
 "The area around the dam is well defended against full scale military attack but a lone agent stands a much better chance. The easiest way to gain entrance to the weapons factory will be to get down the face of the dam. \nQ had an idea about that.\n",
 "Information concerning shipping and contacts is stored on a computer system in a secret ops room within the dam. With this covert modem connected to their satellite link we can intercept the data when a backup is carried out.\nAs for getting down the dam, use the bungee rope. At the bottom of the jump, use the piton gun. Simple.",
 "Hardly a lover's leap, James. Be careful though, I hate to think of you falling for anyone else.\n",
 "Neutralize all alarms\n",
 "Install covert modem\n",
 "Intercept data backup\n",
 "Bungee jump from platform\n",
 "Covert modem installed.\n",
 "Off-site data backup initiated.\n",
 "Off-site data backup completed.\n",
 "... backup failed.\n",
 "Main computer systems damaged.\nOperational data lost.\n",
 "Covert modem not installed.\nData cannot be intercepted by MI6!\n",
 "Satellite communications link destroyed.\nData cannot be intercepted by MI6!\n",
 "Security gate A closing\n- please wait...\n",
 "Security gate B closing\n- please wait...\n",
 "B Y E L O M O R Y E  D A M\n",
 "mi6 has confirmed the existence of a secret chemical warfare facility at the byelomorye dam, ussr. its heavily guarded location and workings are a cause for major concern. nerve gas produced there has been turning up in the hands of hostile regimes around the world and deals with international terrorists have been rumored. this facility should be destroyed with extreme prejudice.\n",
 "the area around the dam is well defended against a full scale military attack but a lone agent stands a much better chance.the easiest way to gain entrance to the weapons factory will be to get down the face of the dam. \nq had an idea about that.\n",
 "information concerning shipping and contacts is stored on a computer system in a secret ops room within the dam. with this covert modem connected to their satellite link we can intercept the data when a backup is carried out.\nas for getting down the dam, use the bungee rope. at the bottom of the jump, use the piton gun. simple.",
 "hardly a lover's leap, james. be careful though, i hate to think of you falling for anyone else.\n",
 "neutralize all alarms\n",
 "install covert modem\n",
 "intercept data backup\n",
 "bungee jump from platform\n",
 "Byelomorye Dam, Arkangelsk, USSR\n",
 "Nine years ago\n",
 "\n",
 "covert modem\n",
 "covert modem\n",
 "covert modem\n",
 "Picked up a covert modem.\n",
 "Covert modem incorrectly installed.\n",
 NULL,
 NULL
};
