#include "game/lvl_text.h"

struct stringentry LdepoE[] = {
 "The Janus operations base in St. Petersburg is located in a disused military rail depot. From here the crime syndicate coordinates illegal arms deals, international terrorism and extortion.\n",
 "Quite a nest of vipers, 007 - do your best to disrupt the Janus operations. We'd be particularly interested if you could retrieve their blueprints for a modified version of the stealth helicopter, it seems they may be thinking of going into production. We also believe that Ourumov has taken Natalya to Trevelyan's converted missile train in the depot. You need to be on that train when it leaves. \n",
 "They've got a pretty sophisticated computer network hidden away somewhere in that depot, 007. Be a good chap and shut it down for them.\n\nOh, and don't forget to blow up the Janus arms cache - I'm just sorry I can't be there myself to enjoy the fireworks.\n",
 "Don't miss your train, James.\n",
 "Destroy illegal arms cache\n",
 "Destroy computer network\n",
 "Obtain safe key\n",
 "Recover helicopter blueprints\n",
 "Locate Trevelyan's train\n",
 "M I L I T A R Y   D E P O T\n",
 "the janus operations base in st. petersburg is located in a disused military rail depot. from here the crime syndicate coordinates illegal arms deals, international terrorism and extortion.\n",
 "quite a nest of vipers, 007 - do your best to disrupt the janus operations. we'd be particularly interested if you could retrieve their blueprints for a modified version of the stealth helicopter, it seems they may be thinking of going into production.\nwe also believe that ourumov has taken natalya to trevelyan's converted missile train in the depot. you need to be on that train when it leaves. \n",
 "they've got a pretty sophisticated computer network hidden away somewhere in that depot, 007. be a good chap and shut it down for them.\n\noh, and don't forget to blow up the janus arms cache - i'm just sorry i can't be there myself to enjoy the fireworks.\n",
 "don't miss your train, james.\n",
 "Disused Military Depot, St. Petersburg\n",
 "destroy illegal arms cache\n",
 "destroy computer network\n",
 "obtain safe key\n",
 "recover helicopter blueprints\n",
 "locate trevelyan's train\n",
 NULL,
 NULL,
 NULL,
 NULL,
 "This safe is locked.\n",
 "\n",
 "helicopter blueprints\n",
 "blueprints\n",
 NULL,
 "Picked up the blueprints\n",
 "\n",
 "safe key\n",
 "safe key\n",
 "Safe Key\n",
 "Picked up a safe key.\n",
 NULL
};
