
char *LdestE[] = {
 "A demonstration of the Pirate stealth helicopter by the French military has been unexpectedly postponed. Official channels insist that nothing is wrong but unofficially MI6 has been asked to help salvage a very tricky hostage situation on board the frigate La Fayette. It seems that the Janus crime syndicate will stop at nothing in its attempt to hijack the helicopter.\n",
 "This is the best chance we've had in years to get a lead on Janus. The French are prepared to play along with an entrapment scenario. We need you to place a tracker on the Pirate so that we can trace its movements after Janus steals it.\n\nThis must go smoothly, 007. If the press get a sniff of this, we'll all have egg on our faces.\n",
 "The French have kindly given us technical details of the Pirate so I've managed to convert this tracker bug into quite a clever little chap. It's undetectable and it locks out all weapon firing commands.\nJanus is also threatening to blow up the ship. They are most likely to have placed explosives on the bridge and in the engine room. Take care, 007, and be certain to use the bomb defuser correctly.\n",
 "Xenia Onatopp, one of Janus' main operatives, may be on board the La Fayette.\n\nThey say she has thighs of steel, James. Just be sure to stay out of their grasp.\n",
 "Rescue hostages\n",
 "Disarm bridge bomb\n",
 "Disarm engine room bomb\n",
 "Plant tracking bug on helicopter\n",
 "Hostage executed!\n",
 "Hostage released!\n",
 "Hostage escaped!\n",
 "Tracker bug successfully planted on Pirate\n",
 "Oops! Careful with those bugs, James.\n",
 "Bridge bomb successfully defused.\n",
 "Engine room bomb successfully defused.\n",
 "F R I G A T E\n",
 "a demonstration of the pirate stealth helicopter by the french military has been unexpectedly postponed. official channels insist that nothing is wrong but unofficially MI6 has been asked to help salvage a very tricky hostage situation on board the frigate la fayette. it seems that the janus crime syndicate will stop at nothing in its attempt  to hijack the helicopter.\n",
 "this is the best chance we've had in years to get a lead on janus. the french are prepared to play along with an entrapment scenario. we need you to place a tracker on the pirate so that we can trace its movements after janus steals it.\n\nthis must go smoothly, 007. if the press get a sniff of this, we'll all have egg on our faces.\n",
 "the french have kindly given us technical details of the pirate so i've managed to convert this tracker bug into quite a clever little chap. it's undetectable and it locks out all weapon firing commands.\njanus is also threatening to blow up the ship. they are most likely to have placed explosives on the bridge and in the engine room. take care, 007, and be certain to use the bomb defuser correctly.\n",
 "xenia onatopp, one of janus' main operatives, may be on board the la fayette.\n\nthey say she has thighs of steel, james. just be sure to stay out of their grasp.\n",
 "rescue hostages\n",
 "disarm bridge bomb\n",
 "disarm engine room bomb\n",
 "plant tracking bug on helicopter\n",
 "Frigate 'La Fayette', Monte Carlo\n",
 "\n",
 "tracker bug\n",
 "tracker bug\n",
 "tracker bug\n",
 "Picked up a tracker bug.\n",
 "Mission Failure: Unacceptable hostage\ncasualties!\n",
 0
};
