enum LGUNE_STRINGS
{
    GUN_STR_00, // "   D5K\n",
    GUN_STR_01, // "   Issue\n",
    GUN_STR_02, // "   Mine\n",
    GUN_STR_03, // "   PP7\n",
    GUN_STR_04, // "  DD44\n",
    GUN_STR_05, // "  Gun\n",
    GUN_STR_06, // "  Knife\n",
    GUN_STR_07, // "  Mine\n",
    GUN_STR_08, // " KF7\n",
    GUN_STR_09, // " Mine\n",
    GUN_STR_0A, // " Rifle\n",
    GUN_STR_0B, // " Rocket\n",
    GUN_STR_0C, // " Shotgun\n",
    GUN_STR_0D, // "(Proximity)\n",
    GUN_STR_0E, // "(Remote)\n",
    GUN_STR_0F, // "(Timed)\n",
    GUN_STR_10, // "(silenced)\n",
    GUN_STR_11, // "-\n",
    GUN_STR_12, // "Assault\n",
    GUN_STR_13, // "Attract\n",
    GUN_STR_14, // "Audio Tape\n",
    GUN_STR_15, // "Automatic Shotgun\n",
    GUN_STR_16, // "Automatic\n",
    GUN_STR_17, // "Blackbox\n",
    GUN_STR_18, // "Blueprints\n",
    GUN_STR_19, // "Bolt Key\n",
    GUN_STR_1A, // "Bomb Case\n",
    GUN_STR_1B, // "Bomb Defuser\n",
    GUN_STR_1C, // "Briefcase\n",
    GUN_STR_1D, // "Bug Detector\n",
    GUN_STR_1E, // "Bug\n",
    GUN_STR_1F, // "Bungee\n",
    GUN_STR_20, // "Camera\n",
    GUN_STR_21, // "Circuit Board\n",
    GUN_STR_22, // "Clipboard\n",
    GUN_STR_23, // "Communicator\n",
    GUN_STR_24, // "Controller\n",
    GUN_STR_25, // "Cougar Magnum\n",
    GUN_STR_26, // "Cougar\n",
    GUN_STR_27, // "Credit Card\n",
    GUN_STR_28, // "D5K (silenced)\n",
    GUN_STR_29, // "D5K Deutsche\n",
    GUN_STR_2A, // "DD44 Dostovei\n",
    GUN_STR_2B, // "Dark Glasses\n",
    GUN_STR_2C, // "Dat Tape\n",
    GUN_STR_2D, // "Datathief\n",
    GUN_STR_2E, // "Detonator\n",
    GUN_STR_2F, // "Deutsche\n",
    GUN_STR_30, // "Door Decoder\n",
    GUN_STR_31, // "Door Exploder\n",
    GUN_STR_32, // "Dostovei\n",
    GUN_STR_33, // "Guidance Data\n",
    GUN_STR_34, // "Flare Pistol\n",
    GUN_STR_35, // "Gas Keyring\n",
    GUN_STR_36, // "Geiger Counter\n",
    GUN_STR_37, // "Gold Bar\n",
    GUN_STR_38, // "Gold PP7\n",
    GUN_STR_39, // "Golden Gun\n",
    GUN_STR_3A, // "GoldenEye Key\n",
    GUN_STR_3B, // "Golden\n",
    GUN_STR_3C, // "Grenade Launcher\n",
    GUN_STR_3D, // "Grenade\n",
    GUN_STR_3E, // "Hand Grenade\n",
    GUN_STR_3F, // "Heroine\n",
    GUN_STR_40, // "Hunting Knife\n",
    GUN_STR_41, // "Identifier\n",
    GUN_STR_42, // "KF7 Soviet\n",
    GUN_STR_43, // "Key Analyzer Case\n",
    GUN_STR_44, // "Key Analyzer\n",
    GUN_STR_45, // "Keycard\n",
    GUN_STR_46, // "Knife\n",
    GUN_STR_47, // "Laser\n",
    GUN_STR_48, // "Launcher\n",
    GUN_STR_49, // "Lectre\n",
    GUN_STR_4A, // "Lock Exploder\n",
    GUN_STR_4B, // "Magnet Repel\n",
    GUN_STR_4C, // "Magnum\n",
    GUN_STR_4D, // "Map\n",
    GUN_STR_4E, // "Micro Camera\n",
    GUN_STR_4F, // "Microcode\n",
    GUN_STR_50, // "Microfilm\n",
    GUN_STR_51, // "Military Laser\n",
    GUN_STR_52, // "Military\n",
    GUN_STR_53, // "Money\n",
    GUN_STR_54, // "Null\n",
    GUN_STR_55, // "PP7 (silenced)\n",
    GUN_STR_56, // "PP7 Special Issue\n",
    GUN_STR_57, // "PP7 Special\n",
    GUN_STR_58, // "Phantom\n",
    GUN_STR_59, // "Piton Gun\n",
    GUN_STR_5A, // "Plans\n",
    GUN_STR_5B, // "Plastique\n",
    GUN_STR_5C, // "Polarized Glasses\n",
    GUN_STR_5D, // "Proximity Mine\n",
    GUN_STR_5E, // "RC-P90\n",
    GUN_STR_5F, // "Red Dossier\n",
    GUN_STR_60, // "Remote Mine\n",
    GUN_STR_61, // "Rocket Launcher\n",
    GUN_STR_62, // "Safecracker Case\n",
    GUN_STR_63, // "Safecracker\n",
    GUN_STR_64, // "Shotgun\n",
    GUN_STR_65, // "Silver PP7\n",
    GUN_STR_66, // "Sniper Rifle\n",
    GUN_STR_67, // "Sniper\n",
    GUN_STR_68, // "Soviet\n",
    GUN_STR_69, // "Spool Tape\n",
    GUN_STR_6A, // "Spy File\n",
    GUN_STR_6B, // "Klobb\n",
    GUN_STR_6C, // "Staff List\n",
    GUN_STR_6D, // "Suit_lf_hand\n",
    GUN_STR_6E, // "Tank\n",
    GUN_STR_6F, // "Taser\n",
    GUN_STR_70, // "Throwing Knife\n",
    GUN_STR_71, // "Throwing\n",
    GUN_STR_72, // "Timed Mine\n",
    GUN_STR_73, // "Token\n",
    GUN_STR_74, // "US AR33 Assault Rifle\n",
    GUN_STR_75, // "US AR33\n",
    GUN_STR_76, // "Unarmed\n",
    GUN_STR_77, // "Video Tape\n",
    GUN_STR_78, // "Watch Communicator\n",
    GUN_STR_79, // "Watch Geiger Counter\n",
    GUN_STR_7A, // "Watch Identifier\n",
    GUN_STR_7B, // "Watch Laser\n",
    GUN_STR_7C, // "Watch Magnet Attract\n",
    GUN_STR_7D, // "Watch Magnet Repel\n",
    GUN_STR_7E, // "Watch Magnet\n",
    GUN_STR_7F, // "Watch\n",
    GUN_STR_80, // "Weapon Case\n",
    GUN_STR_81, // "Yale Key\n",
    GUN_STR_82, // "ZMG (9mm)\n",
    GUN_STR_83, // "\n",
    GUN_STR_84, // "ar33\n",
    GUN_STR_85, // "audio tape\n",
    GUN_STR_86, // "auto shotgun\n",
    GUN_STR_87, // "blackbox\n",
    GUN_STR_88, // "blueprints\n",
    GUN_STR_89, // "bolt key\n",
    GUN_STR_8A, // "bomb case\n",
    GUN_STR_8B, // "bomb defuser\n",
    GUN_STR_8C, // "briefcase\n",
    GUN_STR_8D, // "bug detector\n",
    GUN_STR_8E, // "bug\n",
    GUN_STR_8F, // "bungee\n",
    GUN_STR_90, // "camera\n",
    GUN_STR_91, // "circuit board\n",
    GUN_STR_92, // "clipboard\n",
    GUN_STR_93, // "cougar magnum\n",
    GUN_STR_94, // "credit card\n",
    GUN_STR_95, // "d5k (silenced)\n",
    GUN_STR_96, // "d5k\n",
    GUN_STR_97, // "dark glasses\n",
    GUN_STR_98, // "dat tape\n",
    GUN_STR_99, // "datathief\n",
    GUN_STR_9A, // "dd44\n",
    GUN_STR_9B, // "detonator\n",
    GUN_STR_9C, // "door decoder\n",
    GUN_STR_9D, // "door exploder\n",
    GUN_STR_9E, // "guidance data\n",
    GUN_STR_9F, // "flare pistol\n",
    GUN_STR_A0, // "gas keyring\n",
    GUN_STR_A1, // "gold bar\n",
    GUN_STR_A2, // "gold pp7\n",
    GUN_STR_A3, // "golden gun\n",
    GUN_STR_A4, // "goldeneye key\n",
    GUN_STR_A5, // "grenade launcher\n",
    GUN_STR_A6, // "grenade\n",
    GUN_STR_A7, // "heroine\n",
    GUN_STR_A8, // "hunting knife\n",
    GUN_STR_A9, // "key analyzer\n",
    GUN_STR_AA, // "keycard\n",
    GUN_STR_AB, // "kf7 soviet\n",
    GUN_STR_AC, // "laser\n",
    GUN_STR_AD, // "lectre\n",
    GUN_STR_AE, // "lock exploder\n",
    GUN_STR_AF, // "map\n",
    GUN_STR_B0, // "micro camera\n",
    GUN_STR_B1, // "microcode\n",
    GUN_STR_B2, // "microfilm\n",
    GUN_STR_B3, // "money\n",
    GUN_STR_B4, // "phantom\n",
    GUN_STR_B5, // "piton gun\n",
    GUN_STR_B6, // "plans\n",
    GUN_STR_B7, // "plastique\n",
    GUN_STR_B8, // "polarized glasses\n",
    GUN_STR_B9, // "pp7 (silenced)\n",
    GUN_STR_BA, // "pp7\n",
    GUN_STR_BB, // "proximity mine\n",
    GUN_STR_BC, // "rc-p90\n",
    GUN_STR_BD, // "red dossier\n",
    GUN_STR_BE, // "remote mine\n",
    GUN_STR_BF, // "rocket launcher\n",
    GUN_STR_C0, // "safecracker\n",
    GUN_STR_C1, // "shotgun\n",
    GUN_STR_C2, // "silver pp7\n",
    GUN_STR_C3, // "sniper rifle\n",
    GUN_STR_C4, // "spool tape\n",
    GUN_STR_C5, // "spy file\n",
    GUN_STR_C6, // "klobb\n",
    GUN_STR_C7, // "staff list\n",
    GUN_STR_C8, // "tank\n",
    GUN_STR_C9, // "taser\n",
    GUN_STR_CA, // "throwing knife\n",
    GUN_STR_CB, // "timed mine\n",
    GUN_STR_CC, // "token\n",
    GUN_STR_CD, // "unarmed\n",
    GUN_STR_CE, // "video tape\n",
    GUN_STR_CF, // "watch communicator\n",
    GUN_STR_D0, // "watch geiger counter\n",
    GUN_STR_D1, // "watch identifier\n",
    GUN_STR_D2, // "watch laser\n",
    GUN_STR_D3, // "watch magnet attract\n",
    GUN_STR_D4, // "watch magnet repel\n",
    GUN_STR_D5, // "weapon case\n",
    GUN_STR_D6, // "yale key\n",
    GUN_STR_D7, // "zmg (9mm)\n",
    GUN_STR_D8, // "Analyzing the GoldenEye key...\n",
    GUN_STR_D9, // "You do not have the GoldenEye\n key.\n",
    GUN_STR_DA, // "kill count",
    GUN_STR_DB, // "died once\n",
    GUN_STR_DC, // "died",
    GUN_STR_DD, // "times",
    GUN_STR_DE, // "suicide count",
    GUN_STR_DF // 0
};
