
char *LgunE[] = {
 "   D5K\n",
 "   Issue\n",
 "   Mine\n",
 "   PP7\n",
 "  DD44\n",
 "  Gun\n",
 "  Knife\n",
 "  Mine\n",
 " KF7\n",
 " Mine\n",
 " Rifle\n",
 " Rocket\n",
 " Shotgun\n",
 "(Proximity)\n",
 "(Remote)\n",
 "(Timed)\n",
 "(silenced)\n",
 "-\n",
 "Assault\n",
 "Attract\n",
 "Audio Tape\n",
 "Automatic Shotgun\n",
 "Automatic\n",
 "Blackbox\n",
 "Blueprints\n",
 "Bolt Key\n",
 "Bomb Case\n",
 "Bomb Defuser\n",
 "Briefcase\n",
 "Bug Detector\n",
 "Bug\n",
 "Bungee\n",
 "Camera\n",
 "Circuit Board\n",
 "Clipboard\n",
 "Communicator\n",
 "Controller\n",
 "Cougar Magnum\n",
 "Cougar\n",
 "Credit Card\n",
 "D5K (silenced)\n",
 "D5K Deutsche\n",
 "DD44 Dostovei\n",
 "Dark Glasses\n",
 "Dat Tape\n",
 "Datathief\n",
 "Detonator\n",
 "Deutsche\n",
 "Door Decoder\n",
 "Door Exploder\n",
 "Dostovei\n",
 "Guidance Data\n",
 "Flare Pistol\n",
 "Gas Keyring\n",
 "Geiger Counter\n",
 "Gold Bar\n",
 "Gold PP7\n",
 "Golden Gun\n",
 "GoldenEye Key\n",
 "Golden\n",
 "Grenade Launcher\n",
 "Grenade\n",
 "Hand Grenade\n",
 "Heroine\n",
 "Hunting Knife\n",
 "Identifier\n",
 "KF7 Soviet\n",
 "Key Analyzer Case\n",
 "Key Analyzer\n",
 "Keycard\n",
 "Knife\n",
 "Laser\n",
 "Launcher\n",
 "Lectre\n",
 "Lock Exploder\n",
 "Magnet Repel\n",
 "Magnum\n",
 "Map\n",
 "Micro Camera\n",
 "Microcode\n",
 "Microfilm\n",
 "Military Laser\n",
 "Military\n",
 "Money\n",
 "Null\n",
 "PP7 (silenced)\n",
 "PP7 Special Issue\n",
 "PP7 Special\n",
 "Phantom\n",
 "Piton Gun\n",
 "Plans\n",
 "Plastique\n",
 "Polarized Glasses\n",
 "Proximity Mine\n",
 "RC-P90\n",
 "Red Dossier\n",
 "Remote Mine\n",
 "Rocket Launcher\n",
 "Safecracker Case\n",
 "Safecracker\n",
 "Shotgun\n",
 "Silver PP7\n",
 "Sniper Rifle\n",
 "Sniper\n",
 "Soviet\n",
 "Spool Tape\n",
 "Spy File\n",
 "Klobb\n",
 "Staff List\n",
 "Suit_lf_hand\n",
 "Tank\n",
 "Taser\n",
 "Throwing Knife\n",
 "Throwing\n",
 "Timed Mine\n",
 "Token\n",
 "US AR33 Assault Rifle\n",
 "US AR33\n",
 "Unarmed\n",
 "Video Tape\n",
 "Watch Communicator\n",
 "Watch Geiger Counter\n",
 "Watch Identifier\n",
 "Watch Laser\n",
 "Watch Magnet Attract\n",
 "Watch Magnet Repel\n",
 "Watch Magnet\n",
 "Watch\n",
 "Weapon Case\n",
 "Yale Key\n",
 "ZMG (9mm)\n",
 "\n",
 "ar33\n",
 "audio tape\n",
 "auto shotgun\n",
 "blackbox\n",
 "blueprints\n",
 "bolt key\n",
 "bomb case\n",
 "bomb defuser\n",
 "briefcase\n",
 "bug detector\n",
 "bug\n",
 "bungee\n",
 "camera\n",
 "circuit board\n",
 "clipboard\n",
 "cougar magnum\n",
 "credit card\n",
 "d5k (silenced)\n",
 "d5k\n",
 "dark glasses\n",
 "dat tape\n",
 "datathief\n",
 "dd44\n",
 "detonator\n",
 "door decoder\n",
 "door exploder\n",
 "guidance data\n",
 "flare pistol\n",
 "gas keyring\n",
 "gold bar\n",
 "gold pp7\n",
 "golden gun\n",
 "goldeneye key\n",
 "grenade launcher\n",
 "grenade\n",
 "heroine\n",
 "hunting knife\n",
 "key analyzer\n",
 "keycard\n",
 "kf7 soviet\n",
 "laser\n",
 "lectre\n",
 "lock exploder\n",
 "map\n",
 "micro camera\n",
 "microcode\n",
 "microfilm\n",
 "money\n",
 "phantom\n",
 "piton gun\n",
 "plans\n",
 "plastique\n",
 "polarized glasses\n",
 "pp7 (silenced)\n",
 "pp7\n",
 "proximity mine\n",
 "rc-p90\n",
 "red dossier\n",
 "remote mine\n",
 "rocket launcher\n",
 "safecracker\n",
 "shotgun\n",
 "silver pp7\n",
 "sniper rifle\n",
 "spool tape\n",
 "spy file\n",
 "klobb\n",
 "staff list\n",
 "tank\n",
 "taser\n",
 "throwing knife\n",
 "timed mine\n",
 "token\n",
 "unarmed\n",
 "video tape\n",
 "watch communicator\n",
 "watch geiger counter\n",
 "watch identifier\n",
 "watch laser\n",
 "watch magnet attract\n",
 "watch magnet repel\n",
 "weapon case\n",
 "yale key\n",
 "zmg (9mm)\n",
 "Analyzing the GoldenEye key...\n",
 "You do not have the GoldenEye\n key.\n",
 "kill count",
 "died once\n",
 "died",
 "times",
 "suicide count",
 0
};
