enum LGUNE_STRINGS
{
    GUN_STR_00___MP5_LF,                       // "   D5K\n",
    GUN_STR_01___ISSUE_LF,                     // "   Issue\n",
    GUN_STR_02___MINE_LF,                      // "   Mine\n",
    GUN_STR_03__PPK_LF,                        // "   PP7\n",
    GUN_STR_04__TT33_LF,                       // "  DD44\n",
    GUN_STR_05__GUN_LF,                        // "  Gun\n",
    GUN_STR_06__KNIFE_LF,                      // "  Knife\n",
    GUN_STR_07__MINE_LF,                       // "  Mine\n",
    GUN_STR_08_AK47_LF,                        // " KF7\n",
    GUN_STR_09_MINE_LF,                        // " Mine\n",
    GUN_STR_0A_RIFLE_LF,                       // " Rifle\n",
    GUN_STR_0B_ROCKET_LF,                      // " Rocket\n",
    GUN_STR_0C_SHOTGUN_LF,                     // " Shotgun\n",
    GUN_STR_0D_PROXIMITY_LF,                   // "(Proximity)\n",
    GUN_STR_0E_REMOTE_LF,                      // "(Remote)\n",
    GUN_STR_0F_TIMED_LF,                       // "(Timed)\n",
    GUN_STR_10_SILENCED_LF,                    // "(silenced)\n",
    GUN_STR_11_DASH_LF,                        // "-\n",
    GUN_STR_12_ASSAULT_LF,                     // "Assault\n",
    GUN_STR_13_ATTRACT_LF,                     // "Attract\n",
    GUN_STR_14_AUDIOTAPE_LF,                   // "Audio Tape\n",
    GUN_STR_15_AUTOMATICSHOTGUN_LF,            // "Automatic Shotgun\n",
    GUN_STR_16_AUTOMATIC_LF,                   // "Automatic\n",
    GUN_STR_17_BLACKBOX_LF,                    // "Blackbox\n",
    GUN_STR_18_BLUEPRINTS_LF,                  // "Blueprints\n",
    GUN_STR_19_BOLTKEY_LF,                     // "Bolt Key\n",
    GUN_STR_1A_BOMBCASE_LF,                    // "Bomb Case\n",
    GUN_STR_1B_BOMBDEFUSER_LF,                 // "Bomb Defuser\n",
    GUN_STR_1C_BRIEFCASE_LF,                   // "Briefcase\n",
    GUN_STR_1D_BUGDETECTOR_LF,                 // "Bug Detector\n",
    GUN_STR_1E_BUG_LF,                         // "Bug\n",
    GUN_STR_1F_BUNGEE_LF,                      // "Bungee\n",
    GUN_STR_20_CAMERA_LF,                      // "Camera\n",
    GUN_STR_21_CIRCUITBOARD_LF,                // "Circuit Board\n",
    GUN_STR_22_CLIPBOARD_LF,                   // "Clipboard\n",
    GUN_STR_23_COMMINICATOR_LF,                // "Communicator\n",
    GUN_STR_24_CONTROLLER_LF,                  // "Controller\n",
    GUN_STR_25_ROUGERMAGNUM_LF,                // "Cougar Magnum\n",
    GUN_STR_26_ROUGER_LF,                      // "Cougar\n",
    GUN_STR_27_CREDITCARD_LF,                  // "Credit Card\n",
    GUN_STR_28_MP5KSILENCED_LF,                // "D5K (silenced)\n",
    GUN_STR_29_MP5K_LF,                        // "D5K Deutsche\n",
    GUN_STR_2A_TT33TOKAREV_LF,                 // "DD44 Dostovei\n",
    GUN_STR_2B_DARKGLASSES_LF,                 // "Dark Glasses\n",
    GUN_STR_2C_DATTAPE_LF,                     // "Dat Tape\n",
    GUN_STR_2D_DATATHIEF_LF,                   // "Datathief\n",
    GUN_STR_2E_DETONATOR_LF,                   // "Detonator\n",
    GUN_STR_2F,                                // "Deutsche\n",
    GUN_STR_30_DOORDECODER_LF,                 // "Door Decoder\n",
    GUN_STR_31_DOOREXPLODER_LF,                // "Door Exploder\n",
    GUN_STR_32_TOKAREV_LF,                     // "Dostovei\n",
    GUN_STR_33_GUIDANCEDATA_LF,                // "Guidance Data\n",
    GUN_STR_34_FLAREPISTOL_LF,                 // "Flare Pistol\n",
    GUN_STR_35_GASKEYRING_LF,                  // "Gas Keyring\n",
    GUN_STR_36_GEIGERCOUNTER_LF,               // "Geiger Counter\n",
    GUN_STR_37_GOLDBAR_LF,                     // "Gold Bar\n",
    GUN_STR_38_GOLDPPK_LF,                     // "Gold PP7\n",
    GUN_STR_39_GOLDENGUN_LF,                   // "Golden Gun\n",
    GUN_STR_3A_GOLDENEYEKEY_LF,                // "GoldenEye Key\n",
    GUN_STR_3B_GOLDEN_LF,                      // "Golden\n",
    GUN_STR_3C_GRENADELAUNCHER_LF,             // "Grenade Launcher\n",
    GUN_STR_3D_GRENADE_LF,                     // "Grenade\n",
    GUN_STR_3E_HANDGRENADE_LF,                 // "Hand Grenade\n",
    GUN_STR_3F_HEROINE_LF,                     // "Heroine\n",
    GUN_STR_40_HUNTINGKNIFE_LF,                // "Hunting Knife\n",
    GUN_STR_41_IDENTIFIER_LF,                  // "Identifier\n",
    GUN_STR_42_AK47_LF,                        // "KF7 Soviet\n",
    GUN_STR_43_KEYANALYZERCASE_LF,             // "Key Analyzer Case\n",
    GUN_STR_44_KEYANALYZER_LF,                 // "Key Analyzer\n",
    GUN_STR_45_KEYCARD_LF,                     // "Keycard\n",
    GUN_STR_46_KNIFE_LF,                       // "Knife\n",
    GUN_STR_47_LASER_LF,                       // "Laser\n",
    GUN_STR_48_LAUNCHER_LF,                    // "Launcher\n",
    GUN_STR_49_LECTRE_LF,                      // "Lectre\n",
    GUN_STR_4A_LOCKEXPLODER_LF,                // "Lock Exploder\n",
    GUN_STR_4B_MAGNETREPEL_LF,                 // "Magnet Repel\n",
    GUN_STR_4C_MAGNUM_LF,                      // "Magnum\n",
    GUN_STR_4D_MAP_LF,                         // "Map\n",
    GUN_STR_4E_MICROCAMERA_LF,                 // "Micro Camera\n",
    GUN_STR_4F_MICROCODE_LF,                   // "Microcode\n",
    GUN_STR_50_MICROFILM_LF,                   // "Microfilm\n",
    GUN_STR_51_MILITARYLASER_LF,               // "Military Laser\n",
    GUN_STR_52_MILITARY_LF,                    // "Military\n",
    GUN_STR_53_MONEY_LF,                       // "Money\n",
    GUN_STR_54_NULL_LF,                        // "Null\n",
    GUN_STR_55_PPKSILENSED_LF,                 // "PP7 (silenced)\n",
    GUN_STR_56_WALTHERPPK_LF,                  // "PP7 Special Issue\n",
    GUN_STR_57_WALTHERPPK2_LF,                 // "PP7 Special\n",
    GUN_STR_58_SPECTRE_LF,                     // "Phantom\n",
    GUN_STR_59_PITONGUN_LF,                    // "Piton Gun\n",
    GUN_STR_5A_PLANS_LF,                       // "Plans\n",
    GUN_STR_5B_PLASTIQUE_LF,                   // "Plastique\n",
    GUN_STR_5C_POLARISEDGLASSES_LF,            // "Polarized Glasses\n",
    GUN_STR_5D_PROXIMITYMINE_LF,               // "Proximity Mine\n",
    GUN_STR_5E_FNP90_LF,                       // "RC-P90\n",
    GUN_STR_5F_REDDOSSIER_LF,                  // "Red Dossier\n",
    GUN_STR_60_REMOTEMINE_LF,                  // "Remote Mine\n",
    GUN_STR_61_ROCKETLAUNCHER_LF,              // "Rocket Launcher\n",
    GUN_STR_62_SAFECRACKERCASE_LF,             // "Safecracker Case\n",
    GUN_STR_63_SAFECRACKER_LF,                 // "Safecracker\n",
    GUN_STR_64_SHOTGUN_LF,                     // "Shotgun\n",
    GUN_STR_65_SILVERPPK_LF,                   // "Silver PP7\n",
    GUN_STR_66_SNIPERRIFLE_LF,                 // "Sniper Rifle\n",
    GUN_STR_67_SNIPER_LF,                      // "Sniper\n",
    GUN_STR_68_SOVIET_LF,                      // "Soviet\n",
    GUN_STR_69_SPOOLTAPE_LF,                   // "Spool Tape\n",
    GUN_STR_6A_SPYFILE_LF,                     // "Spy File\n",
    GUN_STR_6B_SKORPION_LF,                    // "Klobb\n",
    GUN_STR_6C_STAFFLIST_LF,                   // "Staff List\n",
    GUN_STR_6D_SUIT_LF_HAND_LF,                // "Suit_lf_hand\n",
    GUN_STR_6E_TANK_LF,                        // "Tank\n",
    GUN_STR_6F_TASER_LF,                       // "Taser\n",
    GUN_STR_70_THROWINGKNIFE_LF,               // "Throwing Knife\n",
    GUN_STR_71_THROWING_LF,                    // "Throwing\n",
    GUN_STR_72_TIMEDMINE_LF,                   // "Timed Mine\n",
    GUN_STR_73_TOKEN_LF,                       // "Token\n",
    GUN_STR_74_M16ASSAULTRIFLE_LF,             // "US AR33 Assault Rifle\n",
    GUN_STR_75_M16_LF,                         // "US AR33\n",
    GUN_STR_76_UNARMED_LF,                     // "Unarmed\n",
    GUN_STR_77_VIDEOTAPE_LF,                   // "Video Tape\n",
    GUN_STR_78_WATCHCOMMINUCATOR_LF,           // "Watch Communicator\n",
    GUN_STR_79_WATCHGEIGERCOUNTER_LF,          // "Watch Geiger Counter\n",
    GUN_STR_7A_WATCHIDENTIFIER_LF,             // "Watch Identifier\n",
    GUN_STR_7B_WATCHLASER_LF,                  // "Watch Laser\n",
    GUN_STR_7C_WATCHMAGNETATTRACT_LF,          // "Watch Magnet Attract\n",
    GUN_STR_7D_WATCHMAGNETREPEL_LF,            // "Watch Magnet Repel\n",
    GUN_STR_7E_WATCHMAGNET_LF,                 // "Watch Magnet\n",
    GUN_STR_7F_WATCH_LF,                       // "Watch\n",
    GUN_STR_80_WEAPONCASE_LF,                  // "Weapon Case\n",
    GUN_STR_81_YALEKEY_LF,                     // "Yale Key\n",
    GUN_STR_82_UZI_LF,                         // "ZMG (9mm)\n",
    GUN_STR_83_LF,                             // "\n",
    GUN_STR_84_M16_LF,                         // "ar33\n",
    GUN_STR_85_AUDIOTAPE_LF,                   // "audio tape\n",
    GUN_STR_86_AUTOSHOTGUN_LF,                 // "auto shotgun\n",
    GUN_STR_87_BLACKBOX_LF,                    // "blackbox\n",
    GUN_STR_88_BLUEPRINTS_LF,                  // "blueprints\n",
    GUN_STR_89_BOLTKEY_LF,                     // "bolt key\n",
    GUN_STR_8A_BOMBCASE_LF,                    // "bomb case\n",
    GUN_STR_8B_BOMBDEFUSER_LF,                 // "bomb defuser\n",
    GUN_STR_8C_BRIEFCASE_LF,                   // "briefcase\n",
    GUN_STR_8D_BUGDETECTOR_LF,                 // "bug detector\n",
    GUN_STR_8E_BUG_LF,                         // "bug\n",
    GUN_STR_8F_BUNGEE_LF,                      // "bungee\n",
    GUN_STR_90_CAMERA_LF,                      // "camera\n",
    GUN_STR_91_CIRCUITBOARD_LF,                // "circuit board\n",
    GUN_STR_92_CLIPBOARD_LF,                   // "clipboard\n",
    GUN_STR_93_ROUGERMAGNUM_LF,                // "cougar magnum\n",
    GUN_STR_94_CREDITCARD_LF,                  // "credit card\n",
    GUN_STR_95_MP5SILENSED_LF,                 // "d5k (silenced)\n",
    GUN_STR_96_MP5_LF,                         // "d5k\n",
    GUN_STR_97_DARKGLASSES_LF,                 // "dark glasses\n",
    GUN_STR_98_DATTAPE_LF,                     // "dat tape\n",
    GUN_STR_99_DATATHIEF_LF,                   // "datathief\n",
    GUN_STR_9A_TT33_LF,                        // "dd44\n",
    GUN_STR_9B_DETONATOR_LF,                   // "detonator\n",
    GUN_STR_9C_DOORDECODER_LF,                 // "door decoder\n",
    GUN_STR_9D_DOOREXPLODER_LF,                // "door exploder\n",
    GUN_STR_9E_GUIDANCEDATA_LF,                // "guidance data\n",
    GUN_STR_9F_FLAREPISTOL_LF,                 // "flare pistol\n",
    GUN_STR_A0_GASKEYRING_LF,                  // "gas keyring\n",
    GUN_STR_A1_GOLDBAR_LF,                     // "gold bar\n",
    GUN_STR_A2_GOLDPPK_LF,                     // "gold pp7\n",
    GUN_STR_A3_GOLDENGUN_LF,                   // "golden gun\n",
    GUN_STR_A4_GOLDENEYEKEY_LF,                // "goldeneye key\n",
    GUN_STR_A5_GRENADELAUNCHER_LF,             // "grenade launcher\n",
    GUN_STR_A6_GRENADE_LF,                     // "grenade\n",
    GUN_STR_A7_HEROINE_LF,                     // "heroine\n",
    GUN_STR_A8_HUNTINGKNIFE_LF,                // "hunting knife\n",
    GUN_STR_A9_KEYANALYZER_LF,                 // "key analyzer\n",
    GUN_STR_AA_KEYCARD_LF,                     // "keycard\n",
    GUN_STR_AB_AK47_LF,                        // "kf7 soviet\n",
    GUN_STR_AC_LASER_LF,                       // "laser\n",
    GUN_STR_AD_LECTRE_LF,                      // "lectre\n",
    GUN_STR_AE_LOCKEXPLODER_LF,                // "lock exploder\n",
    GUN_STR_AF_MAP_LF,                         // "map\n",
    GUN_STR_B0_MICROCAMERA_LF,                 // "micro camera\n",
    GUN_STR_B1_MICROCODE_LF,                   // "microcode\n",
    GUN_STR_B2_MICROFILM_LF,                   // "microfilm\n",
    GUN_STR_B3_MONEY_LF,                       // "money\n",
    GUN_STR_B4_SPECTRE_LF,                     // "phantom\n",
    GUN_STR_B5_PITONGUN_LF,                    // "piton gun\n",
    GUN_STR_B6_PLANS_LF,                       // "plans\n",
    GUN_STR_B7_PLASTIQUE_LF,                   // "plastique\n",
    GUN_STR_B8_POLARIZEDGLASSES_LF,            // "polarized glasses\n",
    GUN_STR_B9_SILENCEDPPK_LF,                 // "pp7 (silenced)\n",
    GUN_STR_BA_PPK_LF,                         // "pp7\n",
    GUN_STR_BB_PROXIMIYTYMINE_LF,              // "proximity mine\n",
    GUN_STR_BC_FNP90_LF,                       // "rc-p90\n",
    GUN_STR_BD_REDDOSSIER_LF,                  // "red dossier\n",
    GUN_STR_BE_REMOTEMINE_LF,                  // "remote mine\n",
    GUN_STR_BF_ROCKETLAUNCHER_LF,              // "rocket launcher\n",
    GUN_STR_C0_SAFECRACKER_LF,                 // "safecracker\n",
    GUN_STR_C1_SHOTGUN_LF,                     // "shotgun\n",
    GUN_STR_C2_SILVERPPK_LF,                   // "silver pp7\n",
    GUN_STR_C3_SNIPERRIFLE_LF,                 // "sniper rifle\n",
    GUN_STR_C4_SPOOLTAPE_LF,                   // "spool tape\n",
    GUN_STR_C5_SPYFILE_LF,                     // "spy file\n",
    GUN_STR_C6_SKORPION_LF,                    // "klobb\n",
    GUN_STR_C7_STAFFLIST_LF,                   // "staff list\n",
    GUN_STR_C8_TANK_LF,                        // "tank\n",
    GUN_STR_C9_TASER_LF,                       // "taser\n",
    GUN_STR_CA_THROWINGKNIFE_LF,               // "throwing knife\n",
    GUN_STR_CB_TIMEDMINE_LF,                   // "timed mine\n",
    GUN_STR_CC_TOKEN_LF,                       // "token\n",
    GUN_STR_CD_UNARMED_LF,                     // "unarmed\n",
    GUN_STR_CE_VIDEOTAPE_LF,                   // "video tape\n",
    GUN_STR_CF_WATCHCOMMUNICATOR_LF,           // "watch communicator\n",
    GUN_STR_D0_WATCHGEIGERCOUNTER_LF,          // "watch geiger counter\n",
    GUN_STR_D1_WATCHIDENTIFIER_LF,             // "watch identifier\n",
    GUN_STR_D2_WATCHLASER_LF,                  // "watch laser\n",
    GUN_STR_D3_WATCHMAGNETICATTRACT_LF,        // "watch magnet attract\n",
    GUN_STR_D4_WATCHMAGNETICREPEL_LF,          // "watch magnet repel\n",
    GUN_STR_D5_WEAPONCASE_LF,                  // "weapon case\n",
    GUN_STR_D6_YALEKEY_LF,                     // "yale key\n",
    GUN_STR_D7_UZI_LF,                         // "zmg (9mm)\n",
    GUN_STR_D8_ANALYZINGTHEGOLDENEYEKEY_LF,    // "Analyzing the GoldenEye key...\n",
    GUN_STR_D9_YOUDONOTHAVETHEGOLDENEYEKEY_LF, // "You do not have the GoldenEye\n key.\n",
    GUN_STR_DA_KILLCOUNT,                      // "kill count",
    GUN_STR_DB_DIEDONCE_LF,                    // "died once\n",
    GUN_STR_DC_DIED,                           // "died",
    GUN_STR_DD_TIMES,                          // "times",
    GUN_STR_DE_SUICIDECOUNT,                   // "suicide count",
    GUN_STR_DF                                 // 0
};
