
char *LjunE[] = {
 "Satellite reconnaissance has been unable to locate any installation near the coordinates recovered from the Janus computers in St. Petersburg. It seems likely that a ground search will be necessary. The CIA has provided you with a light aircraft. Underfly Janus radar and parachute in to the drop, proceed through the jungle eliminating any opposition and attempt to locate the Janus base.\n",
 "Miss Simonova will be with you on this mission. If Janus is operating a Goldeneye satellite, her computing skills will be essential when you try to disable their systems.\nJack Wade has given her some basic firearms training and he thinks she'll be able to carry her weight in a combat situation. Be careful though, 007, remember she isn't an experienced operative like yourself.\n",
 "You'll know you're on the right trail if you encounter Janus troops or automated defenses. Be especially wary of their robotic drone guns. I'm giving you some triggered mines for their ammo dump, try not to waste them on silly things. Oh, and look out for that Xenia woman, 007, I think she's after you. You lucky devil.\n",
 "A hot date in the rainforest? With two women!\nShame on you James.\n",
 "Destroy drone guns\n",
 "Eliminate Xenia\n",
 "Blow up ammo dump\n",
 "Escort Natalya to Janus base\n",
 "Natalya: Got one!\n",
 "Natalya: That looked painful.\n",
 "Natalya: Too slow.\n",
 "Natalya: Gotcha!\n",
 "Natalya: Did you see that?\n",
 "Natalya: This is fun.\n",
 "Natalya: Close, but no cigar.\n",
 "Natalya: Oh, that's a nice plant.\n",
 "Natalya: This gun's quite powerful.\n",
 "Natalya: Who was that guy?\n",
 "Natalya: I like this game.\n",
 "Natalya: Cover me.\n",
 "Natalya: Naughty boy.\n",
 "Natalya: Unlucky.\n",
 "Natalya: Oh, messy.\n",
 "Natalya: Advantage, Natalya Simonova.\n",
 "Natalya: That's one more for me.\n",
 "Natalya: Loser.\n",
 "Natalya: Just like the movies.\n",
 "Natalya: \n",
 "Natalya: Let's go to work.\n",
 "Natalya: Be careful, James!\n",
 "Xenia: This time, Mr. Bond, the pleasure\n          will be all mine.\n",
 "Mission failure. Natalya has been killed.\n",
 "C U B A N   J U N G L E\n",
 "satellite reconnaissance has been unable to locate any installation near the coordinates recovered from the janus computers in st. petersburg. it seems likely that a ground search will be necessary. the cia has provided you with a light aircraft. underfly janus radar and parachute in to the drop, proceed through the jungle eliminating any opposition and attempt to locate the janus base.\n",
 "miss simonova will be with you on this mission. if janus is operating a goldeneye satellite, her computing skills will be essential when you try to disable their systems.\njack wade has given her some basic firearms training and he thinks she'll be able to carry her weight in a combat situation. be careful though, 007, \nremember she isn't an experienced operative like yourself.\n",
 "you'll know you're on the right trail if you encounter janus troops or automated defenses. be especially wary of their robotic drone guns. i'm giving you some triggered mines for their ammo dump, try not to waste them on silly things. oh, and look out for that xenia woman, 007, i think she's after you. you lucky devil.\n",
 "a hot date in the rainforest? \nwith two women!\nshame on you james.\n",
 "destroy drone guns\n",
 "eliminate xenia\n",
 "blow up ammo dump\n",
 "escort natalya to janus base\n",
 "Cuban Jungle\n",
 0,
 0
};
