#include "game/lvl_text.h"

struct stringentry LlenE[] = {
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 "Natalya: James, are you alright?\n",
 "Bond: Yes, I'm fine thank you.\n",
 "Natalya: Ohhh, James...\n",
 "C U B A N   J U N G L E\n",
 "\n",
 "\n",
 "\n",
 "\n",
 "The Cast\n",
 "\n",
 "James Bond\n",
 "007\n",
 "Natalya Simonova\n",
 "Satellite Programmer\n",
 "Alec Trevelyan\n",
 "006 / Janus\n",
 "Xenia Onatopp\n",
 "Janus Operative\n",
 "Arkady Ourumov\n",
 "Russian General\n",
 "Boris Grishenko\n",
 "Valentin Zukovsky\n",
 "Arms Dealer\n",
 "Dimitri Mishkin\n",
 "Defense Minister\n",
 "Produced and Directed by\n",
 "Martin Hollis\n",
 "Director of Photography\n",
 "Mark Edmonds M.A.\n",
 "Original Screenplay\n",
 "Dr. David Doak\n",
 "Scenic Art Director\n",
 "Karl Hilton\n",
 "Production Designer\n",
 "Duncan Botwood\n",
 "Costume Designer\n",
 "B Jones\n",
 "2nd-Unit Director\n",
 "Stephen Ellis\n",
 "Original Music\n",
 "Grant Kirkhope\n",
 "Graeme Norgate\n",
 "Sound Effects\n",
 "1st Scenic Artist\n",
 "2nd Scenic Artist\n",
 "3rd Scenic Artist\n",
 "Scene Choreographer\n",
 "Lighting\n",
 "Casting\n",
 "Electrical Best Boy\n",
 "Special Effects Supervisor\n",
 "Stunt Capture\n",
 "Make-up Supervisor\n",
 "Sound Recordist\n",
 "Elevator Music by\n",
 "Robin Beanland\n",
 "Set Decorator\n",
 "Animation\n",
 "Weapons Consultant\n",
 "Dialogue Coach\n",
 "Multiplay Director\n",
 "Property Master\n",
 "Hairdressing\n",
 "Dolly Grip\n",
 "Production Manager\n",
 "Simon Farmer\n",
 "System Support\n",
 "Paul Mikell\n",
 "Additional Graphics\n",
 "Adrian Smith\n",
 "Sound System and Tools\n",
 "Graham Smith\n",
 "Rare Testers\n",
 "Huw Ward\n",
 "Gary Richards\n",
 "Gavin Hood\n",
 "Jamie Williams\n",
 "Gareth Jones\n",
 "Martin Penny\n",
 "David Wong\n",
 "Stephen Stamper\n",
 "NOA\n",
 "Treehouse Staff\n",
 "Ken Lobb\n",
 "Rich Richardson\n",
 "Henry Sterchi\n",
 "Erich Waas\n",
 "Armond Williams Jr.\n",
 "NOA Testing\n",
 "Michael Kelbaugh\n",
 "Tim Bechtel\n",
 "David Bridgham\n",
 "Kirk Buchanan\n",
 "Kyle Carlson\n",
 "Chris Dolan\n",
 "Melvin Forrest\n",
 "Tom Hertzog\n",
 "Sam Hosier III\n",
 "Robert Johnson\n",
 "Arnold Myers II\n",
 "Chris Needham\n",
 "Sara Osborne\n",
 "Christian Phillips\n",
 "Edward A. Ridgeway\n",
 "Ben Smith\n",
 "Sharon Evans\n",
 "Bill Giese\n",
 "Sam Kujath\n",
 "Jim Holdeman\n",
 "David Hunziker\n",
 "The Q Branch XVI\n",
 "Translation\n",
 "Kenji Okubo\n",
 "Keisuke Terasaki\n",
 "Special Thanks\n",
 "Mr. Arakawa\n",
 "Howard Lincoln\n",
 "Mr. Fukuda\n",
 "Joel Hochberg\n",
 "Tim Stamper\n",
 "Chris Stamper\n",
 "Rare US Staff\n",
 "Eileen Hochberg\n",
 "Scott Hochberg\n",
 "Jerry Rogowski\n",
 "Filmed at Twycross Studios, England\n",
 "IN NINTENDOVISION\n",
 "Produced by Rare\n",
 "Presented by Nintendo\n",
 #ifdef VERSION_US
 "JAMES BOND WILL RETURN\n",
  NULL,
  NULL
 #endif
 #ifdef VERSION_JP
  "Executive Producer\n",
  "Hiroshi Yamauchi\n",
  "Nintendo Producer\n",
  "Kenji Miki\n",
  "NCL Staff\n",
  "Eiji Onozuka\n",
  "Masashi Goto\n",
  "NCL Super Mario Club\n",
  "Special Thanks to\n",
  "NCL\n",
  "JAMES BOND WILL RETURN\n",
 #endif

};
