#include "game/lvl_text.h"

struct stringentry LmiscE[] = {
 "Invincible",
 "All Guns",
 "Super x2 Health",
 "Super x2 Armor",
 "Bond Invisible",
 "Bond Phase",
 "Infinite Ammo",
 "DK Mode",
 "Tiny Bond",
 "Super x10 Health",
 "Magnum",
 "Laser",
 "Golden Gun",
 "Silver PP7",
 "Gold PP7",
 "invincibility on\n",
 "all guns on\n",
 "maximum ammo\n",
 "super x2 health\n",
 "super x2 armor\n",
 "invisibility on\n",
 "bond phase on\n",
 "infinite ammo on\n",
 "dk mode on\n",
 "extra weapons\n",
 "tiny bond on\n",
 "paintball mode on\n",
 "super x10 health\n",
 "happy now karl?\n",
 "fast mode on\n",
 "invincibility off\n",
 "all guns off\n",
 "invisibility off\n",
 "bond phase off\n",
 "infinite ammo off\n",
 "dk mode off\n",
 "tiny bond off\n",
 "paintball mode off\n",
 "radar on\n",
 "fast mode off\n",
 "NO NAME",
 "E R R O R\n",
 "no briefing for this mission\n",
 "\n",
 "objective",
 "completed\n",
 "incomplete\n",
 "failed\n",
 "slowest motion\n",
 "very slow motion\n",
 "slow motion\n",
 "normal motion\n",
 "fast motion\n",
 "very fast motion\n",
 "fastest motion\n",
 "Line Mode",
 "Paintball Mode",
 "Enemy Rockets",
 "2x Rocket L.",
 "2x Grenade L.",
 "2x RC-P90",
 "2x Throwing Knife",
 "2x Hunting Knife",
 "2x Laser",
 "Turbo Mode",
 "Fast Animation",
 "Slow Animation",
 "No Radar [Multi]"
 #ifdef VERSION_JP
 ,"One minute left"
 #endif
};
