enum LMISCE_STRINGS
{
    MISC_STR_00_INVINCIBLE,          // "Invincible",
    MISC_STR_01_ALLGUNS,             // "All Guns",
    MISC_STR_02_SUPER2XHEALTH,       // "Super x2 Health",
    MISC_STR_03_SUPER2XARMOUR,       // "Super x2 Armor",
    MISC_STR_04_BONDINVISIBLE,       // "Bond Invisible",
    MISC_STR_05_BONDPHASE,           // "Bond Phase",
    MISC_STR_06_INFINITAMMO,         // "Infinite Ammo",
    MISC_STR_07_DKMODE,              // "DK Mode",
    MISC_STR_08_TINYBOND,            // "Tiny Bond",
    MISC_STR_09_SUPER10XHEALTH,      // "Super x10 Health",
    MISC_STR_0A_MAGNUM,              // "Magnum",
    MISC_STR_0B_LASER,               // "Laser",
    MISC_STR_0C_GOLDENGUN,           // "Golden Gun",
    MISC_STR_0D_SILVERPPK,           // "Silver PP7",
    MISC_STR_0E_GOLDPPK,             // "Gold PP7",
    MISC_STR_0F_INVINCIBILITYON_LF,  // "invincibility on\n",
    MISC_STR_10_ALLGUNSON_LF,        // "all guns on\n",
    MISC_STR_11_MAXIMUMAMMO_LF,      // "maximum ammo\n",
    MISC_STR_12_SUPER2XHEALTH_LF,    // "super x2 health\n",
    MISC_STR_13_SUPER2XARMOUR_LF,    // "super x2 armor\n",
    MISC_STR_14_INVISIBILITYON_LF,   // "invisibility on\n",
    MISC_STR_15_BONDPHASEON_LF,      // "bond phase on\n",
    MISC_STR_16_INFINITEAMMOON_LF,   // "infinite ammo on\n",
    MISC_STR_17_DKMODEON_LF,         // "dk mode on\n",
    MISC_STR_18_EXTRAWEAPONS_LF,     // "extra weapons\n",
    MISC_STR_19_TINYBONDON_LF,       // "tiny bond on\n",
    MISC_STR_1A_PAINTBALMODEON_LF,   // "paintball mode on\n",
    MISC_STR_1B_SUPER10XHEALTH_LF,   // "super x10 health\n",
    MISC_STR_1C_HAPPYNOWKARL_LF,     // "happy now karl?\n",
    MISC_STR_1D_FASTMODEON_LF,       // "fast mode on\n",
    MISC_STR_1E_INVINCIBILITYOFF_LF, // "invincibility off\n",
    MISC_STR_1F_ALLGUNSOFF_LF,       // "all guns off\n",
    MISC_STR_20_INVISIBILITYOFF_LF,  // "invisibility off\n",
    MISC_STR_21_BONDPHASEOFF_LF,     // "bond phase off\n",
    MISC_STR_22_INFINITEAMMOOFF_LF,  // "infinite ammo off\n",
    MISC_STR_23_DKMODEOFF_LF,        // "dk mode off\n",
    MISC_STR_24_TINYBONDOFF_LF,      // "tiny bond off\n",
    MISC_STR_25_PAINTBALLMODEOFF_LF, // "paintball mode off\n",
    MISC_STR_26_RADARON_LF,          // "radar on\n",
    MISC_STR_27_FASTMODEOFF_LF,      // "fast mode off\n",
    MISC_STR_28_NONAME,              // "NO NAME",
    MISC_STR_29_ERROR_LF,            // "E R R O R\n",
    MISC_STR_2A_NOBRIEFING_LF,       // "no briefing for this mission\n",
    MISC_STR_2B_LF,                  // "\n",
    MISC_STR_2C_OBJECTIVE,           // "objective",
    MISC_STR_2D_COMPLETED_LF,        // "completed\n",
    MISC_STR_2E_INCOMPLETE_LF,       // "incomplete\n",
    MISC_STR_2F_FAILED_LF,           // "failed\n",
    MISC_STR_30_SLOWESTMOTION_LF,    // "slowest motion\n",
    MISC_STR_31_VERYSLOWMOTION_LF,   // "very slow motion\n",
    MISC_STR_32_SLOWMOTION_LF,       // "slow motion\n",
    MISC_STR_33_NORMALMOTION_LF,     // "normal motion\n",
    MISC_STR_34_FASTMOTION_LF,       // "fast motion\n",
    MISC_STR_35_VERYFASTMOTION_LF,   // "very fast motion\n",
    MISC_STR_36_FASTESTMOTION_LF,    // "fastest motion\n",
    MISC_STR_37_LINEMODE,            // "Line Mode",
    MISC_STR_38_PAINTBALLMODE,       // "Paintball Mode",
    MISC_STR_39_ENEMYROCKETS,        // "Enemy Rockets",
    MISC_STR_3A_2XROCKETLAUNCHER,    // "2x Rocket L.",
    MISC_STR_3B_2XGRENADELAUNCHER,   // "2x Grenade L.",
    MISC_STR_3C_2XFNP90,             // "2x RC-P90",
    MISC_STR_3D_2XTHROWINGKNIFE,     // "2x Throwing Knife",
    MISC_STR_3E_2XHUNTINGKNIFE,      // "2x Hunting Knife",
    MISC_STR_3F_2XLASER,             // "2x Laser",
    MISC_STR_40_TURBOMODE,           // "Turbo Mode",
    MISC_STR_41_FASTANIMATION,       // "Fast Animation",
    MISC_STR_42_SLOWANIMATION,       // "Slow Animation",
    MISC_STR_43_NORADAR              // "No Radar [Multi]"

#ifdef VERSION_JP
        ,
    MISC_STR_44 //,"One minute left"
#endif
};
