enum LMISCE_STRINGS
{
    MISC_STR_00, // "Invincible",
    MISC_STR_01, // "All Guns",
    MISC_STR_02, // "Super x2 Health",
    MISC_STR_03, // "Super x2 Armor",
    MISC_STR_04, // "Bond Invisible",
    MISC_STR_05, // "Bond Phase",
    MISC_STR_06, // "Infinite Ammo",
    MISC_STR_07, // "DK Mode",
    MISC_STR_08, // "Tiny Bond",
    MISC_STR_09, // "Super x10 Health",
    MISC_STR_0A, // "Magnum",
    MISC_STR_0B, // "Laser",
    MISC_STR_0C, // "Golden Gun",
    MISC_STR_0D, // "Silver PP7",
    MISC_STR_0E, // "Gold PP7",
    MISC_STR_0F, // "invincibility on\n",
    MISC_STR_10, // "all guns on\n",
    MISC_STR_11, // "maximum ammo\n",
    MISC_STR_12, // "super x2 health\n",
    MISC_STR_13, // "super x2 armor\n",
    MISC_STR_14, // "invisibility on\n",
    MISC_STR_15, // "bond phase on\n",
    MISC_STR_16, // "infinite ammo on\n",
    MISC_STR_17, // "dk mode on\n",
    MISC_STR_18, // "extra weapons\n",
    MISC_STR_19, // "tiny bond on\n",
    MISC_STR_1A, // "paintball mode on\n",
    MISC_STR_1B, // "super x10 health\n",
    MISC_STR_1C, // "happy now karl?\n",
    MISC_STR_1D, // "fast mode on\n",
    MISC_STR_1E, // "invincibility off\n",
    MISC_STR_1F, // "all guns off\n",
    MISC_STR_20, // "invisibility off\n",
    MISC_STR_21, // "bond phase off\n",
    MISC_STR_22, // "infinite ammo off\n",
    MISC_STR_23, // "dk mode off\n",
    MISC_STR_24, // "tiny bond off\n",
    MISC_STR_25, // "paintball mode off\n",
    MISC_STR_26, // "radar on\n",
    MISC_STR_27, // "fast mode off\n",
    MISC_STR_28, // "NO NAME",
    MISC_STR_29, // "E R R O R\n",
    MISC_STR_2A, // "no briefing for this mission\n",
    MISC_STR_2B, // "\n",
    MISC_STR_2C, // "objective",
    MISC_STR_2D, // "completed\n",
    MISC_STR_2E, // "incomplete\n",
    MISC_STR_2F, // "failed\n",
    MISC_STR_30, // "slowest motion\n",
    MISC_STR_31, // "very slow motion\n",
    MISC_STR_32, // "slow motion\n",
    MISC_STR_33, // "normal motion\n",
    MISC_STR_34, // "fast motion\n",
    MISC_STR_35, // "very fast motion\n",
    MISC_STR_36, // "fastest motion\n",
    MISC_STR_37, // "Line Mode",
    MISC_STR_38, // "Paintball Mode",
    MISC_STR_39, // "Enemy Rockets",
    MISC_STR_3A, // "2x Rocket L.",
    MISC_STR_3B, // "2x Grenade L.",
    MISC_STR_3C, // "2x RC-P90",
    MISC_STR_3D, // "2x Throwing Knife",
    MISC_STR_3E, // "2x Hunting Knife",
    MISC_STR_3F, // "2x Laser",
    MISC_STR_40, // "Turbo Mode",
    MISC_STR_41, // "Fast Animation",
    MISC_STR_42, // "Slow Animation",
    MISC_STR_43 // "No Radar [Multi]"
    
#ifdef VERSION_JP
    ,MISC_STR_44//,"One minute left"
#endif
};
