enum LMPMENUE_STRINGS
{
    MPMENU_STR_00, // "Lemming Award",
    MPMENU_STR_01, // "Where's the Ammo?",
    MPMENU_STR_02, // "Where's the Armor?",
    MPMENU_STR_03, // "AC -10 Award",
    MPMENU_STR_04, // "Marksmanship Award",
    MPMENU_STR_05, // "Most Professional",
    MPMENU_STR_06, // "Most Deadly",
    MPMENU_STR_07, // "Mostly Harmless",
    MPMENU_STR_08, // "Most Cowardly",
    MPMENU_STR_09, // "Most Frantic",
    MPMENU_STR_0A, // "Most Honorable",
    MPMENU_STR_0B, // "Most Dishonorable",
    MPMENU_STR_0C, // "Shortest Innings",
    MPMENU_STR_0D, // "Longest Innings",
    MPMENU_STR_0E, // "Double Kill",
    MPMENU_STR_0F, // "Triple Kill",
    MPMENU_STR_10, // "Quad Kill (Doh!)",
    MPMENU_STR_11, // "Rank: 1st",
    MPMENU_STR_12, // "Rank: 2nd",
    MPMENU_STR_13, // "Rank: 3rd",
    MPMENU_STR_14, // "Rank: 4th",
    MPMENU_STR_15, // "PLAY",
    MPMENU_STR_16, // "GAME OVER",
    MPMENU_STR_17, // "START TO EXIT",
    MPMENU_STR_18, // "PAUSED",
    MPMENU_STR_19, // "PAUSE",
    MPMENU_STR_1A, // "EXIT",
    MPMENU_STR_1B, // "SCORES",
    MPMENU_STR_1C, // "P",
    MPMENU_STR_1D, // "KILLS",
    MPMENU_STR_1E, // "LOSSES",
    MPMENU_STR_1F, // "Weapon of choice:",
    MPMENU_STR_20, // "cancel",
    MPMENU_STR_21, // "confirm",
    MPMENU_STR_22, // "press start\n",
    MPMENU_STR_23, // "to continue\n"
};
