enum LMPMENUE_STRINGS
{
    MPMENU_STR_00_LEMMINGAWARD,      // "Lemming Award",
    MPMENU_STR_01_WHERESTHEAMMO,     // "Where's the Ammo?",
    MPMENU_STR_02_WHERESTHEARMOR,    // "Where's the Armor?",
    MPMENU_STR_03_AC10AWARD,         // "AC -10 Award",
    MPMENU_STR_04_MARKSMANSHIPAWARD, // "Marksmanship Award",
    MPMENU_STR_05_MOSTPROFESSIONAL,  // "Most Professional",
    MPMENU_STR_06_MOSTDEADLY,        // "Most Deadly",
    MPMENU_STR_07_MOSTLYHARMLESS,    // "Mostly Harmless",
    MPMENU_STR_08_MOSTCOWARD,        // "Most Cowardly",
    MPMENU_STR_09_MOSTFRANTIC,       // "Most Frantic",
    MPMENU_STR_0A_MOSTHONORABLE,     // "Most Honorable",
    MPMENU_STR_0B_MOSTDISHONORABLE,  // "Most Dishonorable",
    MPMENU_STR_0C_SHORTESTINNINGS,   // "Shortest Innings",
    MPMENU_STR_0D_LONGESTINNINGS,    // "Longest Innings",
    MPMENU_STR_0E_DOUBLEKILL,        // "Double Kill",
    MPMENU_STR_0F_TRIPLEKILL,        // "Triple Kill",
    MPMENU_STR_10_QUADKILL,          // "Quad Kill (Doh!)",
    MPMENU_STR_11_RANK1ST,           // "Rank: 1st",
    MPMENU_STR_12_RANK2ND,           // "Rank: 2nd",
    MPMENU_STR_13_RANK3RD,           // "Rank: 3rd",
    MPMENU_STR_14_RANK4TH,           // "Rank: 4th",
    MPMENU_STR_15_PLAY,              // "PLAY",
    MPMENU_STR_16_GAMEOVER,          // "GAME OVER",
    MPMENU_STR_17_STARTTTOEXIT,      // "START TO EXIT",
    MPMENU_STR_18_PAUSED,            // "PAUSED",
    MPMENU_STR_19_PAUSE,             // "PAUSE",
    MPMENU_STR_1A_EXIT,              // "EXIT",
    MPMENU_STR_1B_SCORES,            // "SCORES",
    MPMENU_STR_1C_P,                 // "P",
    MPMENU_STR_1D_KILLS,             // "KILLS",
    MPMENU_STR_1E_LOSSES,            // "LOSSES",
    MPMENU_STR_1F_WEAPONOFCHOICE,    // "Weapon of choice:",
    MPMENU_STR_20_CANCEL,            // "cancel",
    MPMENU_STR_21_CONFIRM,           // "confirm",
    MPMENU_STR_22_PRESSSTART_LF,     // "press start\n",
    MPMENU_STR_23_TOCONTINUE_LF      // "to continue\n"
};
