
char *LmpmenuE[] = {
 "Lemming Award",
 "Where's the Ammo?",
 "Where's the Armor?",
 "AC -10 Award",
 "Marksmanship Award",
 "Most Professional",
 "Most Deadly",
 "Mostly Harmless",
 "Most Cowardly",
 "Most Frantic",
 "Most Honorable",
 "Most Dishonorable",
 "Shortest Innings",
 "Longest Innings",
 "Double Kill",
 "Triple Kill",
 "Quad Kill (Doh!)",
 "Rank: 1st",
 "Rank: 2nd",
 "Rank: 3rd",
 "Rank: 4th",
 "PLAY",
 "GAME OVER",
 "START TO EXIT",
 "PAUSED",
 "PAUSE",
 "EXIT",
 "SCORES",
 "P",
 "KILLS",
 "LOSSES",
 "Weapon of choice:",
 "cancel",
 "confirm",
 "press start\n",
 "to continue\n"
};
