enum LOPTIONE_STRINGS
{
    OPTION_STR_00_FIRE_LF,               //"fire\n",
    OPTION_STR_01_AIM_LF,                //"aim\n",
    OPTION_STR_02_ACTION_LF,             //"action\n",
    OPTION_STR_03_WEAPON_LF,             //"weapon\n",
    OPTION_STR_04_PAUSE_LF,              //"pause\n",
    OPTION_STR_05_MOVE_LF,               //"move\n",
    OPTION_STR_06_LOOK_LF,               //"look\n",
    OPTION_STR_07_QUESTION_LF,           //"?\n",
    OPTION_STR_08_MOVESIGHT_LF,          //"move sight\n",
    OPTION_STR_09_11HONEY_LF,            //"1.1 honey\n",
    OPTION_STR_0A_12SOLITAIRE_LF,        //"1.2 solitaire\n",
    OPTION_STR_0B_13KISSY_LF,            //"1.3 kissy\n",
    OPTION_STR_0C_14GOODNIGHT_LF,        //"1.4 goodnight\n",
    OPTION_STR_0D_21PLENTY_LF,           //"2.1 plenty\n",
    OPTION_STR_0E_22GALORE_LF,           //"2.2 galore\n",
    OPTION_STR_0F_23DOMINO_LF,           //"2.3 domino\n",
    OPTION_STR_10_24GOODHEAD_LF,         //"2.4 goodhead\n",
    OPTION_STR_11_LOOKUPDOWN_LF,         //"look up/down\n",
    OPTION_STR_12_AUTOAIM_LF,            //"auto-aim\n",
    OPTION_STR_13_LOOKAHEAD_LF,          //"look ahead\n",
    OPTION_STR_14_AIMCONTROL_LF,         //"aim control\n",
    OPTION_STR_15_SIGHTONSCREEN_LF,      //"sight on-screen\n",
    OPTION_STR_16_AMMOONSCREEN_LF,       //"ammo on-screen\n",
    OPTION_STR_17_SCREEN_LF,             //"screen\n",
    OPTION_STR_18_RATIO_LF,              //"ratio\n",
    OPTION_STR_19_ON_LF,                 //"on\n",
    OPTION_STR_1A_OFF_LF,                //"off\n",
    OPTION_STR_1B_UPRIGHT_LF,            //"upright\n",
    OPTION_STR_1C_REVERSE_LF,            //"reverse\n",
    OPTION_STR_1D_TOGGLE_LF,             //"toggle\n",
    OPTION_STR_1E_HOLD_LF,               //"hold\n",
    OPTION_STR_1F_FULL_LF,               //"full\n",
    OPTION_STR_20_WIDE_LF,               //"wide\n",
    OPTION_STR_21_CINEMA_LF,             //"cinema\n",
    OPTION_STR_22_NORMAL_LF,             //"normal\n",
    OPTION_STR_23_169_LF,                //"16:9\n",
    OPTION_STR_24_ABORT_LF,              //"abort:\n",
    OPTION_STR_25_CONFIRM_LF,            //"confirm\n",
    OPTION_STR_26_CANCEL_LF,             //"cancel\n",
    OPTION_STR_27_MISSIONSTATUS_LF,      //"mission status:\n",
    OPTION_STR_28_COMPLETE_LF,           //"complete\n",
    OPTION_STR_29_INCOMPLETE_LF,         //"incomplete\n",
    OPTION_STR_2A_LEFTHAND_LF,           //"Left Hand\n",
    OPTION_STR_2B_QWATCHVERSION_LF,      //"q watch v2.01 beta\n",
    OPTION_STR_2C_DOWN_LF,               //"down\n",
    OPTION_STR_2D_UP_LF,                 //"up\n",
    OPTION_STR_2E_SIDESTEP_LF,           //"sidestep\n",
    OPTION_STR_2F_SIDESTEP_LF,           //"sidestep\n",
    OPTION_STR_30_FORWARD_LF,            //"forward\n",
    OPTION_STR_31_BACK_LF,               //"back\n",
    OPTION_STR_32_CONTROLSTYLE_LF,       //"control style\n",
    OPTION_STR_33_CONTROLLER_LF,         //"controller\n",
    OPTION_STR_34_CONTROLLERS_LF,        //"controllers\n",
    OPTION_STR_35_MUSIC_LF,              //"music\n",
    OPTION_STR_36_FX_LF,                 //"fx\n",
    OPTION_STR_37_FAILED_LF,             //"failed\n",
    OPTION_STR_38_2BACKGROUND_LF,        //"2. background\n",
    OPTION_STR_39_3MBRIEFING_LF,         //"3. M briefing\n",
    OPTION_STR_3A_4QBRANCH_LF,           //"4. Q branch\n",
    OPTION_STR_3B_5MONEYPENNY_LF,        //"5. moneypenny\n",
    OPTION_STR_3C_1MISSIONOBJECTIVES_LF, //"1. mission objectives\n",
    OPTION_STR_3D,                       // 0,
    OPTION_STR_3E,                       // 0,
    OPTION_STR_3F                        // 0
};
