
char *LoptionsE[] = {
 "fire\n",
 "aim\n",
 "action\n",
 "weapon\n",
 "pause\n",
 "move\n",
 "look\n",
 "?\n",
 "move sight\n",
 "1.1 honey\n",
 "1.2 solitaire\n",
 "1.3 kissy\n",
 "1.4 goodnight\n",
 "2.1 plenty\n",
 "2.2 galore\n",
 "2.3 domino\n",
 "2.4 goodhead\n",
 "look up/down\n",
 "auto-aim\n",
 "look ahead\n",
 "aim control\n",
 "sight on-screen\n",
 "ammo on-screen\n",
 "screen\n",
 "ratio\n",
 "on\n",
 "off\n",
 "upright\n",
 "reverse\n",
 "toggle\n",
 "hold\n",
 "full\n",
 "wide\n",
 "cinema\n",
 "normal\n",
 "16:9\n",
 "abort:\n",
 "confirm\n",
 "cancel\n",
 "mission status:\n",
 "complete\n",
 "incomplete\n",
 "Left Hand\n",
 "q watch v2.01 beta\n",
 "down\n",
 "up\n",
 "sidestep\n",
 "sidestep\n",
 "forward\n",
 "back\n",
 "control style\n",
 "controller\n",
 "controllers\n",
 "music\n",
 "fx\n",
 "failed\n",
 "2. background\n",
 "3. M briefing\n",
 "4. Q branch\n",
 "5. moneypenny\n",
 "1. mission objectives\n",
 0,
 0,
 0
};
