enum LOPTIONE_STRINGS
{
    OPTION_STR_00, //"fire\n",
    OPTION_STR_01, //"aim\n",
    OPTION_STR_02, //"action\n",
    OPTION_STR_03, //"weapon\n",
    OPTION_STR_04, //"pause\n",
    OPTION_STR_05, //"move\n",
    OPTION_STR_06, //"look\n",
    OPTION_STR_07, //"?\n",
    OPTION_STR_08, //"move sight\n",
    OPTION_STR_09, //"1.1 honey\n",
    OPTION_STR_0A, //"1.2 solitaire\n",
    OPTION_STR_0B, //"1.3 kissy\n",
    OPTION_STR_0C, //"1.4 goodnight\n",
    OPTION_STR_0D, //"2.1 plenty\n",
    OPTION_STR_0E, //"2.2 galore\n",
    OPTION_STR_0F, //"2.3 domino\n",
    OPTION_STR_10, //"2.4 goodhead\n",
    OPTION_STR_11, //"look up/down\n",
    OPTION_STR_12, //"auto-aim\n",
    OPTION_STR_13, //"look ahead\n",
    OPTION_STR_14, //"aim control\n",
    OPTION_STR_15, //"sight on-screen\n",
    OPTION_STR_16, //"ammo on-screen\n",
    OPTION_STR_17, //"screen\n",
    OPTION_STR_18, //"ratio\n",
    OPTION_STR_19, //"on\n",
    OPTION_STR_1A, //"off\n",
    OPTION_STR_1B, //"upright\n",
    OPTION_STR_1C, //"reverse\n",
    OPTION_STR_1D, //"toggle\n",
    OPTION_STR_1E, //"hold\n",
    OPTION_STR_1F, //"full\n",
    OPTION_STR_20, //"wide\n",
    OPTION_STR_21, //"cinema\n",
    OPTION_STR_22, //"normal\n",
    OPTION_STR_23, //"16:9\n",
    OPTION_STR_24, //"abort:\n",
    OPTION_STR_25, //"confirm\n",
    OPTION_STR_26, //"cancel\n",
    OPTION_STR_27, //"mission status:\n",
    OPTION_STR_28, //"complete\n",
    OPTION_STR_29, //"incomplete\n",
    OPTION_STR_2A, //"Left Hand\n",
    OPTION_STR_2B, //"q watch v2.01 beta\n",
    OPTION_STR_2C, //"down\n",
    OPTION_STR_2D, //"up\n",
    OPTION_STR_2E, //"sidestep\n",
    OPTION_STR_2F, //"sidestep\n",
    OPTION_STR_30, //"forward\n",
    OPTION_STR_31, //"back\n",
    OPTION_STR_32, //"control style\n",
    OPTION_STR_33, //"controller\n",
    OPTION_STR_34, //"controllers\n",
    OPTION_STR_35, //"music\n",
    OPTION_STR_36, //"fx\n",
    OPTION_STR_37, //"failed\n",
    OPTION_STR_38, //"2. background\n",
    OPTION_STR_39, //"3. M briefing\n",
    OPTION_STR_3A, //"4. Q branch\n",
    OPTION_STR_3B, //"5. moneypenny\n",
    OPTION_STR_3C, //"1. mission objectives\n",
    OPTION_STR_3D, //0,
    OPTION_STR_3E, //0,
    OPTION_STR_3F //0
};
