#include "game/lvl_text.h"

struct stringentry LpeteE[] = {
 "After escaping KGB interrogation at the military archives, Natalya has been recaptured by General Ourumov. She is being taken by car to the Janus operations base in St. Petersburg.\n",
 "Get after them, 007! We can't afford to let the trail go cold and the chances are they'll lead you straight to Trevelyan. Keep a clear head though, any civilian casualties on the streets of St. Petersburg could create an unfortunate international incident.\nWe believe that Valentin Zukovsky is still in the area - he may be able to help you.\n",
 "No gadgets this time, 007. Though you should be on the lookout for hardware the Russians may have left lying around. Keys in the ignition and all that, old chap.\n",
 "I don't think she's worth the trouble, James.\n\nPerhaps you should be looking closer to home for a more reliable woman?\n",
 "Pursue Ourumov and Natalya\n",
 "Minimize civilian casualties\n",
 "Contact Valentin\n",
 "Warning: Civilian casualties high.\n",
 "Warning: Civilian casualties critical!\n",
 "Mission Failure: Too many civilian\n                     casualties.\n",
 "Mission Failure: Ourumov has escaped\n                     with Natalya.\n",
 "Valentin: Ah, Mr. Bond, I see you have\n           eluded the clutches of Military\n           Intelligence.\n",
 "Bond: Yes, but General Ourumov has\n        taken Natalya!\n",
 "Valentin: I saw the car, he's taking the\n           girl to a disused military depot\n           not far from here.\n",
 "Valentin: The Janus base is there.\n           A simple phone call and my\n           men will delay them.\n",
 "Bond: What's in it for you, Valentin?\n",
 "Valentin: Business is business, Mr. Bond.\n           I'd like to see my competitors\n           out of action.\n",
 "Valentin: I'm trying to help you, Mr. Bond.\n           You could at least\n           be civil enough to listen to me.\n",
 "Valentin has left.\n",
 "Valentin has contacted his 'associates'.\n",
 "S T .  P E T E R S B U R G\n",
 "after escaping kgb interrogation at the military archives, natalya has been recaptured by general ourumov. she is being taken by car to the janus operations base in st. petersburg.\n",
 "get after them, 007! we can't afford to let the trail go cold and the chances are they'll lead you straight to trevelyan. keep a clear head though, any civilian casualties on the streets of st. petersburg could create an unfortunate international incident.\nwe believe that valentin zukovsky is still in the area - he may be able to help you.\n",
 "no gadgets this time, 007. though you should be on the lookout for hardware the russians may have left lying around. keys in the ignition and all that, old chap.\n",
 "i don't think she's worth the trouble, james.\n\nperhaps you should be looking closer to home for a more reliable woman?\n",
 "pursue ourumov and natalya\n",
 "minimize civilian casualties\n",
 "contact valentin\n",
 "St. Petersburg\n",
 NULL,
 NULL,
 NULL
};
