#include "game/lvl_text.h"

struct stringentry LpropobjE[] = {
 "Picked up ",
 "some ",
 "a ",
 "an ",
 "the ",
 "ammo",
 "shotgun cartridge",
 "magnum bullet",
 "golden bullet",
 "hand grenade",
 "grenade round",
 "rocket",
 "remote mine",
 "proximity mine",
 "timed mine",
 "throwing ",
 "knife",
 "knives",
 "s",
 "dart",
 "explosive pen",
 "explosive case",
 "flare",
 "piton",
 "of dynamite",
 "stick ",
 "sticks ",
 "bug",
 "micro camera",
 "GoldenEye key",
 "token",
 "plastique",
 "a hunting knife.\n",
 "a PP7.\n",
 "a silenced PP7.\n",
 "a DD44 Dostovei.\n",
 "a Klobb.\n",
 "a KF7 Soviet.\n",
 "a ZMG (9mm).\n",
 "a D5K Deutsche.\n",
 "a silenced D5K.\n",
 "a Phantom.\n",
 "an AR33 assault rifle.\n",
 "an RC-P90.\n",
 "a shotgun.\n",
 "an automatic shotgun.\n",
 "a sniper rifle.\n",
 "a grenade launcher.\n",
 "a rocket launcher.\n",
 "a Cougar Magnum.\n",
 "the Golden Gun.\n",
 "a Moonraker laser.\n",
 "a flare pistol.\n",
 "a piton gun.\n",
 "a silver PP7.\n",
 "a gold PP7.\n",
 "a keycard.\n",
 "a yale key.\n",
 "a bolt key.\n",
 "a new weapon.\n",
 "Picked up a key.\n",
 "Picked up some body armor.\n",
 "body armor.\n",
 "Picked up something.\n",
 "This door is locked.\n",
 NULL,
 NULL,
 NULL
};
