enum LPROPOBJE_STRINGS
{
    PROPOBJ_STR_00_PICKEDUP, // "Picked up ",
    PROPOBJ_STR_01_SOME, // "some ",
    PROPOBJ_STR_02_A, // "a ",
    PROPOBJ_STR_03_AN, // "an ",
    PROPOBJ_STR_04_THE, // "the ",
    PROPOBJ_STR_05_AMMO, // "ammo",
    PROPOBJ_STR_06_SHOTGUNCARTRIDGE, // "shotgun cartridge",
    PROPOBJ_STR_07_MAGNUMBULLET, // "magnum bullet",
    PROPOBJ_STR_08_GOLDENBULLET, // "golden bullet",
    PROPOBJ_STR_09_HANDGRENADE, // "hand grenade",
    PROPOBJ_STR_0A_GRENADEROUND, // "grenade round",
    PROPOBJ_STR_0B_ROCKET, // "rocket",
    PROPOBJ_STR_0C_REMOTEMINE, // "remote mine",
    PROPOBJ_STR_0D_PROXIMITYMINE, // "proximity mine",
    PROPOBJ_STR_0E_TIMEDMINE, // "timed mine",
    PROPOBJ_STR_0F_THROWING, // "throwing ",
    PROPOBJ_STR_10_KNIFE, // "knife",
    PROPOBJ_STR_11_KNIVES, // "knives",
    PROPOBJ_STR_12_S, // "s",
    PROPOBJ_STR_13_DART, // "dart",
    PROPOBJ_STR_14_EXPLOSIVEPEN, // "explosive pen",
    PROPOBJ_STR_15_EXPLOSIVECASE, // "explosive case",
    PROPOBJ_STR_16_FLARE, // "flare",
    PROPOBJ_STR_17_PITON, // "piton",
    PROPOBJ_STR_18_OFDYNAMITE, // "of dynamite",
    PROPOBJ_STR_19_STICK, // "stick ",
    PROPOBJ_STR_1A_STICKS, // "sticks ",
    PROPOBJ_STR_1B_BUG, // "bug",
    PROPOBJ_STR_1C_MICROCAMERA, // "micro camera",
    PROPOBJ_STR_1D_GOLDENEYEKEY, // "GoldenEye key",
    PROPOBJ_STR_1E_TOKEN, // "token",
    PROPOBJ_STR_1F_PLASTIQUE, // "plastique",
    PROPOBJ_STR_20_AHUNTINGKNIFE, // "a hunting knife.\n",
    PROPOBJ_STR_21_APPK, // "a PP7.\n", Using filename since renaming was probably done after localisation
    PROPOBJ_STR_22_ASILENCEDPPK, // "a silenced PP7.\n",
    PROPOBJ_STR_23_ATT33, // "a DD44 Dostovei.\n",
    PROPOBJ_STR_24_ASPKORPION, // "a Klobb.\n",
    PROPOBJ_STR_25_ANAK47, // "a KF7 Soviet.\n",
    PROPOBJ_STR_26_ANUZI, // "a ZMG (9mm).\n",
    PROPOBJ_STR_27_ANMP5K, // "a D5K Deutsche.\n",
    PROPOBJ_STR_28_ASILENCEDMP5, // "a silenced D5K.\n",
    PROPOBJ_STR_29_ASPECTRE, // "a Phantom.\n",
    PROPOBJ_STR_2A_ANM16, // "an AR33 assault rifle.\n",
    PROPOBJ_STR_2B_ANFNP90, // "an RC-P90.\n",
    PROPOBJ_STR_2C_ASHOTGUN, // "a shotgun.\n",
    PROPOBJ_STR_2D_ANAUTOSHOTGUN, // "an automatic shotgun.\n",
    PROPOBJ_STR_2E_ASNIPERRIFLE, // "a sniper rifle.\n",
    PROPOBJ_STR_2F_AGRENADELAUNCHER, // "a grenade launcher.\n",
    PROPOBJ_STR_30_AROCKETLAUNCHER, // "a rocket launcher.\n",
    PROPOBJ_STR_31_ARUGERMAGNUM, // "a Cougar Magnum.\n",
    PROPOBJ_STR_32_THEGOLDENGUN, // "the Golden Gun.\n",
    PROPOBJ_STR_33_AMOOKRAKERLASER, // "a Moonraker laser.\n",
    PROPOBJ_STR_34_AFLAREPISTOL, // "a flare pistol.\n",
    PROPOBJ_STR_35_APITONGUN, // "a piton gun.\n",
    PROPOBJ_STR_36_ASILVERPPK, // "a silver PP7.\n",
    PROPOBJ_STR_37_AGOLDPPK, // "a gold PP7.\n",
    PROPOBJ_STR_38_AKEYCARD, // "a keycard.\n",
    PROPOBJ_STR_39_AYALEKEY, // "a yale key.\n",
    PROPOBJ_STR_3A_ABOLTKEY, // "a bolt key.\n",
    PROPOBJ_STR_3B_ANEWWEAPON, // "a new weapon.\n",
    PROPOBJ_STR_3C_PICKEDUPAKEY, // "Picked up a key.\n",
    PROPOBJ_STR_3D_PICKEDUPSOMEBODEYARMOUR, // "Picked up some body armor.\n",
    PROPOBJ_STR_3E_BODYARMOUR, // "body armor.\n",
    PROPOBJ_STR_3F_PICKEDUPSOMETHING, // "Picked up something.\n",
    PROPOBJ_STR_40_THISDOORISLOCKED, // "This door is locked.\n",
    PROPOBJ_STR_41, // 0,
    PROPOBJ_STR_42, // 0,
    PROPOBJ_STR_43 // 0
};

