enum LPROPOBJE_STRINGS
{
    PROPOBJ_STR_00, // "Picked up ",
    PROPOBJ_STR_01, // "some ",
    PROPOBJ_STR_02, // "a ",
    PROPOBJ_STR_03, // "an ",
    PROPOBJ_STR_04, // "the ",
    PROPOBJ_STR_05, // "ammo",
    PROPOBJ_STR_06, // "shotgun cartridge",
    PROPOBJ_STR_07, // "magnum bullet",
    PROPOBJ_STR_08, // "golden bullet",
    PROPOBJ_STR_09, // "hand grenade",
    PROPOBJ_STR_0A, // "grenade round",
    PROPOBJ_STR_0B, // "rocket",
    PROPOBJ_STR_0C, // "remote mine",
    PROPOBJ_STR_0D, // "proximity mine",
    PROPOBJ_STR_0E, // "timed mine",
    PROPOBJ_STR_0F, // "throwing ",
    PROPOBJ_STR_10, // "knife",
    PROPOBJ_STR_11, // "knives",
    PROPOBJ_STR_12, // "s",
    PROPOBJ_STR_13, // "dart",
    PROPOBJ_STR_14, // "explosive pen",
    PROPOBJ_STR_15, // "explosive case",
    PROPOBJ_STR_16, // "flare",
    PROPOBJ_STR_17, // "piton",
    PROPOBJ_STR_18, // "of dynamite",
    PROPOBJ_STR_19, // "stick ",
    PROPOBJ_STR_1A, // "sticks ",
    PROPOBJ_STR_1B, // "bug",
    PROPOBJ_STR_1C, // "micro camera",
    PROPOBJ_STR_1D, // "GoldenEye key",
    PROPOBJ_STR_1E, // "token",
    PROPOBJ_STR_1F, // "plastique",
    PROPOBJ_STR_20, // "a hunting knife.\n",
    PROPOBJ_STR_21, // "a PP7.\n",
    PROPOBJ_STR_22, // "a silenced PP7.\n",
    PROPOBJ_STR_23, // "a DD44 Dostovei.\n",
    PROPOBJ_STR_24, // "a Klobb.\n",
    PROPOBJ_STR_25, // "a KF7 Soviet.\n",
    PROPOBJ_STR_26, // "a ZMG (9mm).\n",
    PROPOBJ_STR_27, // "a D5K Deutsche.\n",
    PROPOBJ_STR_28, // "a silenced D5K.\n",
    PROPOBJ_STR_29, // "a Phantom.\n",
    PROPOBJ_STR_2A, // "an AR33 assault rifle.\n",
    PROPOBJ_STR_2B, // "an RC-P90.\n",
    PROPOBJ_STR_2C, // "a shotgun.\n",
    PROPOBJ_STR_2D, // "an automatic shotgun.\n",
    PROPOBJ_STR_2E, // "a sniper rifle.\n",
    PROPOBJ_STR_2F, // "a grenade launcher.\n",
    PROPOBJ_STR_30, // "a rocket launcher.\n",
    PROPOBJ_STR_31, // "a Cougar Magnum.\n",
    PROPOBJ_STR_32, // "the Golden Gun.\n",
    PROPOBJ_STR_33, // "a Moonraker laser.\n",
    PROPOBJ_STR_34, // "a flare pistol.\n",
    PROPOBJ_STR_35, // "a piton gun.\n",
    PROPOBJ_STR_36, // "a silver PP7.\n",
    PROPOBJ_STR_37, // "a gold PP7.\n",
    PROPOBJ_STR_38, // "a keycard.\n",
    PROPOBJ_STR_39, // "a yale key.\n",
    PROPOBJ_STR_3A, // "a bolt key.\n",
    PROPOBJ_STR_3B, // "a new weapon.\n",
    PROPOBJ_STR_3C, // "Picked up a key.\n",
    PROPOBJ_STR_3D, // "Picked up some body armor.\n",
    PROPOBJ_STR_3E, // "body armor.\n",
    PROPOBJ_STR_3F, // "Picked up something.\n",
    PROPOBJ_STR_40, // "This door is locked.\n",
    PROPOBJ_STR_41, // 0,
    PROPOBJ_STR_42, // 0,
    PROPOBJ_STR_43 // 0
};

