#include "game/lvl_text.h"

struct stringentry LrunE[] = {
 "The service runway is the obvious escape route from the Arkangelsk chemical weapons facility.\n",
 "006 knew this was going to be a risky mission. His sacrifice should give you enough time to find an aircraft.\n\nKeep a cool head and you'll get out alive. Just be certain to knock out the heavy gun emplacements and missile battery or they'll swat you out of the air like a silly fly.\n",
 "No time for gadgets here, 007. Just improvise with what you can find close to hand.\n",
 "Grace under pressure, as always, James. \n",
 "Find plane ignition key\n",
 "Destroy heavy gun emplacements\n",
 "Destroy missile battery\n",
 "Escape in plane\n",
 "You do not have the aircraft ignition key.\n",
 "Plane destroyed!\n",
 "R U N W A Y\n",
 "the service runway is the obvious escape route from the arkangelsk chemical weapons facility.\n",
 "006 knew this was going to be a risky mission. his sacrifice should give you enough time to find an aircraft.\n\nkeep a cool head and you'll get out alive. just be certain to knock out the heavy gun emplacements and missile battery or they'll swat you out of the air like a silly fly.\n",
 "no time for gadgets here, 007. just improvise with what you can find close to hand.\n",
 "grace under pressure, as always, james. \n",
 "find plane ignition key\n",
 "destroy heavy gun emplacements\n",
 "destroy missile battery\n",
 "escape in plane\n",
 "Runway, Chemical Weapons Facility#2\n",
 "\n",
 "ignition key\n",
 "ignition key\n",
 "ignition key\n",
 "Picked up an ignition key.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 "This door leads back\ninto the gasplant!\n",
 NULL,
 NULL
};
