#include "game/lvl_text.h"

struct stringentry LsevxbE[] = {
 "The Pirate helicopter was tracked to Severnaya, where a Keyhole-1 ELINT satellite recorded a brief firefight.\nAfter the Pirate left, the same satellite observed a troop helicopter being made ready at a Spetznaz camp, 200 miles due south.\nThe only way that we can get you there quickly is to drop you from  a spy plane, and the Soviet Special Forces will be there before you. \n",
 "You should remember this place, 007. We need any evidence of Janus' presence there, and fast. Disable the troop helicopter so that nothing can be removed from the scene, and destroy their surveillance cameras.\nThis had to be an inside job, Bond. Find out who their contact was - the macabre way to do it would be to use their casualty list. Of course, you'd have to know who was there first.\n",
 "Right, I've altered a standard mine to take a ten-second fuse. There's only one, so don't play around with it. That should take care of their helicopter. This is a covert op, so I've fitted a silencer to your pistol. Satisfied? No? Well, tough; that's all you're getting. \n",
 "Remember the saying, James? 'Never go back'? \n",
 "Disrupt all surveillance equipment\n",
 "Break communications link to bunker\n",
 "Disable Spetznaz support aircraft\n",
 "Gain entry to bunker\n",
 "Communications link damaged.\n",
 "<<Da? What is wrong, comrade?>>\n",
 "Surveillance camera disabled.\n",
 "Bomb placed on Hound MI-4.\n",
 "Bomb incorrectly placed - inactive!\n",
 "Hound MI-4 destroyed.\n",
 "Welcome to Severnaya, comrade.\n",
 "S E V E R N A Y A\n",
 "the pirate helicopter was tracked to severnaya, where a keyhole-1 ELINT satellite recorded a brief firefight.\nafter the pirate left, the same satellite observed a troop helicopter being made ready at a spetznaz camp, 200 miles due south.\nthe only way we can get you there quickly is to drop you from a spy plane, and the soviet special forces will be there before you. \n",
 "you should remember this place, 007. we need any evidence of janus' presence there, and fast. disable the troop helicopter so that nothing can be removed from the scene, and destroy their surveillance cameras.\nthis had to be an inside job, bond. find out who their contact was - the macabre way to do it would be to use their casualty list. of course, you'd have to know who was there first.\n",
 "right, i've altered a standard mine to take a ten-second fuse. there's only one, so don't play around with it. that should take care of their helicopter. this is a covert operation, so i've fitted a silencer to your pistol. satisfied? no? well, tough; that's all you're getting. \n",
 "remember the saying, james? 'never go back'? \n",
 "disrupt all surveillance\n   equipment\n",
 "break communications link\n   to bunker\n",
 "disable spetznaz support\n   aircraft\n",
 "gain entry to bunker\n",
 "Severnaya Installation, Siberian Plateau\n",
 "\n",
 "comms room key\n",
 "comms room key \n",
 "comms room key \n",
 "Picked up comms room key.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 "this access hatch has\nbeen welded shut.\n",
 NULL
};
