#include "game/lvl_text.h"

struct stringentry LsevbE[] = {
 "Escape is the first priority. Find the staff and casualty lists, and the CCTV tape of your capture. If there are any witnesses, try and bring them out as well. \n",
 "Unbelievable, 007. If this gets out we'll be the laughing stock of the international community. As soon as you get back - IF you get back - you're getting a performance review. Only completing the objectives will give you a hope of keeping your rather checkered career intact. \n",
 "You've got your wits and that's about it, 007. Not much I can do to help you here. You might try to find your equipment again when you escape from the cell, though. It took me a lot of time to get all of that stuff together.\n",
 "Grabbed by the Spetznaz, James? Sounds painful!\n",
 "Compare staff / casualty lists\n",
 "Recover CCTV tape\n",
 "Disable all security cameras\n",
 "Recover Goldeneye operations manual\n",
 "Escape with Natalya\n",
 "Bond: It appears that we are cellmates\n",
 "Woman: Who are you, anyway?\n",
 "Bond: The name's Bond, James Bond.\n",
 "Woman: Natalya Fyodorovna Simonova.\n",
 "Bond: Charmed to meet you, Natalya.\n        Why have you been locked up?\n",
 "Natalya: They think that I am a traitor,\n           - that I betrayed my countrymen.\n",
 "Bond: ...and did you?\n",
 "Natalya: Of course not.\n           Ourumov stole the Goldeneye.\n",
 "Bond: Colonel Arkady Grigorovich\n        Ourumov? I've met him before.\n",
 "Natalya: Ourumov is a general now.\n           In charge of the Space Weapon\n           program.\n",
 "Natalya: What brings you to Siberia,\n           James Bond?\n",
 "Bond: I work for the British Government.\n        I'm looking for a stolen helicopter.\n",
 "Natalya: That doesn't matter anymore.\n",
 "Bond: Why not?\n",
 "Natalya: You are a spy and I am a\n           traitor. We will be shot.\n",
 "Bond: I don't think so.\n        I have a cunning plan.\n",
 "",
 "Bond: Guard! My stomach hurts.\n        I'm going to be sick.\n",
 "Jailer: <sigh> You must think\n         I was born yesterday.\n",
 "Natalya: That worked well.\n",
 "Bond: I'm really ill.\n        Open the cell door!\n",
 "Jailer: Shut up!\n         Don't bother me again.\n",
 "Natalya: Nice work.\n",
 "Natalya: You seem to know your way\n           around, James. Have you been\n           here before?\n",
 "Natalya: We should go to the main\n           control room.\n",
 "Natalya has died.\n",
 "natalya has died.\n",
 "Jailer: Stop or I'll shoot!\n",
 "",
 "Natalya: I'm going to check the control\n           console.\n",
 "Natalya: Ourumov has activated the\n           Goldeneye satellite!\n",
 "Natalya: It's going to fire on Severnaya!\n",
 "Natalya: We've got to escape!\n",
 "S E V E R N A Y A \n",
 "escape is the first priority. find the staff and casualty lists, and the CCTV tape of your capture. if there are any witnesses, try and bring them out as well. \n",
 "unbelievable, 007. if this gets out we'll be the laughing stock of the international community. as soon as you get back - IF you get back - you're getting a performance review. only completing the objectives will give you a hope of keeping your rather checkered career intact. \n",
 "you've got your wits and that's about it, 007. not much I can do to help you here. you might try to find your equipment again when you escape from the cell, though. it took me a lot of time to get all of that stuff together.\n",
 "grabbed by the spetznaz, james? sounds painful!\n",
 "compare staff / casualty lists\n",
 "recover cctv tape\n",
 "disable all security cameras\n",
 "recover goldeneye ops manual\n",
 "escape with natalya\n",
 "\n",
 "cell key\n",
 "cell key 2\n",
 "cell key 2\n",
 "Picked up a cell key.\n",
 "\n",
 "cell key\n",
 "cell key 1\n",
 "cell key 1\n",
 "Picked up a cell key.\n",
 "\n",
 "keycard\n",
 "keycard A\n",
 "Keycard (Clearance A)\n",
 "Picked up a keycard.\n",
 "\n",
 "keycard\n",
 "keycard B\n",
 "Keycard (Clearance B)\n",
 "Picked up a keycard.\n",
 "\n",
 "safe key\n",
 "safe key 1\n",
 "Twinned Safe Key 1\n",
 "Picked up a safe key.\n",
 "\n",
 "safe key\n",
 "safe key 2\n",
 "Twinned Safe Key 2\n",
 "Picked up a safe key.\n",
 "severnaya\n",
 "stafflist\n",
 "severnaya stafflist\n",
 "Severnaya Stafflist\n",
 "Picked up a document.\n",
 "severnaya\n",
 "casualty list\n",
 "casualty list\n",
 "Severnaya Casualty List\n",
 "Picked up a clipboard.\n",
 "\n",
 "video tape\n",
 "cctv video tape\n",
 "Goldeneye CCTV video tape\n",
 "Picked up a video tape.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 "This safe is locked.\n",
 "Severnaya Bunker Complex\n",
 "\n",
 "Goldeneye manual\n",
 "Goldeneye operations manual\n",
 "Goldeneye operations manual\n",
 "Picked up a red dossier.\n"
};
