
char *LsevxE[] = {
 "A spy satellite has detected increased levels of activity at an old observatory complex near Severnaya (62.08n, 102.58e) in Russia.\n\nOther sources have confirmed the shipment of a large amount of computer hardware to that location, and an influx of skilled personnel.\n",
 "It might be coincidence that there is a new head of the Soviet Space Weapons Division, your old friend General Ourumov, or it might not. Penetrate the base and find out what is going on. Building plans for the underground section would be ideal. They're unlikely to be just lying around so look for a safe - there's bound to be someone you can borrow a key from. \n",
 "I've looked over the recon photographs and I advise you to stay clear of the main bunker entrance by the helipad. However, there seems to be a ventilation tower nearby which would make an excellent spot for a covert entry.\nYou ought to power down the comms dish too, no point in letting them tell the whole of Russia you've dropped in.\n",
 "It's cold in Siberia, James.\n\nMake sure you wrap up warm and take care to protect your extremities.\n",
 "Power down communications dish\n",
 "Obtain safe key\n",
 "Steal building plans\n",
 "Enter base via ventilation tower\n",
 "Communications dish powered down.\n",
 "Dish controls destroyed!\nEmergency power systems engaged\n",
 "Access Denied!\n",
 "S E V E R N A Y A\n",
 "a spy satellite has detected increased levels of activity at an old observatory complex near severnaya (62.08n, 102.58e) in russia.\n\nother sources have confirmed the shipment of a large amount of computer hardware to that location, and an influx of skilled personnel.\n",
 "it might be coincidence that there is a new head of the soviet space weapons division, your old friend general ourumov, or it might not. penetrate the base and find out what is going on. building plans for the underground section would be ideal. they're unlikely to be just lying around so look for a safe - there's bound to be someone you can borrow a key from. \n",
 "i've looked over the recon photographs and i advise you to stay clear of the main bunker entrance by the helipad. however, there seems to be a ventilation tower nearby which would make an excellent spot for a covert entry.\nyou ought to power down the comms dish too, no point in letting them tell the whole of russia you've dropped in.\n",
 "it's cold in siberia, james.\n\nmake sure you wrap up warm and take care to protect your extremities.\n",
 "power down communications dish\n",
 "obtain safe key\n",
 "steal building plans\n",
 "enter base via ventilation tower\n",
 "Severnaya Installation, Siberian Plateau\n",
 "Four years ago\n",
 0,
 0,
 0,
 0,
 "This safe is locked.\n",
 "severnaya\n",
 "bunker plans\n",
 "bunker plans\n",
 "Bunker Plans\n",
 "Picked up Bunker plans.\n",
 "\n",
 "safe key\n",
 "safe key\n",
 "Safe Key\n",
 "Picked up a safe key.\n",
 "\n",
 "hut door key\n",
 "hut door key\n",
 "Hut Door Key\n",
 "Picked up a large key.\n"
};
