#include "game/lvl_text.h"

struct stringentry LsevE[] = {
 "A spy satellite has detected increased levels of activity at an old observatory complex near Severnaya (62.08n, 102.58e) in Russia.\n\nOther sources have confirmed the shipment of a large amount of computer hardware to that location, and an influx of skilled personnel.\n",
 "007, I want you to infiltrate this base and find out what the devil's going on there. The satellite photographs reveal that there has been recent underground excavation. We'd like to know the exact nature and planned extent of the workings.\n\nBy the way, this is a covert operation. You may have to neutralize the security, but try not to be too obvious about it.\n",
 "You'll be doing some computer hacking on this mission, 007. I know you'd rather be cracking open a bottle of bubbly than cracking passwords, so I've taken the liberty of putting together a little gadget which will do the hard work for you. If you attach the data thief to their mainframe it should override any computer security measures and download the information we require.\n",
 "Underground in Siberia, James? Some of us don't get further than the Northern Line.\n",
 "Disrupt all surveillance equipment\n",
 "Copy Goldeneye key and leave original\n",
 "Get personnel to activate computer\n",
 "Download data from computer\n",
 "Photograph main video screen\n",
 "hello\n",
 "Bond: Take me to the mainframe terminal!\n",
 "Programmer: Don't shoot! It's this way.\n",
 "Programmer: Just through here.\n",
 "Programmer: Let me see.\n",
 "Programmer: Shouldn't take long.\n",
 "Programmer: Hmmh, the root password\n                  has been changed.\n",
 "Programmer: 'K' 'N' 'O' 'C' 'K' 'E' 'R' 'S'\n                  <return>\n",
 "Programmer: Oops!\n",
 "Bond: Disable the security!\n",
 "The programmer has escaped without\nactivating the computer!\n",
 "The computer has not been\n activated.\n",
 "Downloading data...\n",
 "Finished download.\n",
 "Programmer: There's no way I can fix\n                  this!\n",
 "S E V E R N A Y A\n",
 "a spy satellite has detected increased levels of activity at an old observatory complex near severnaya (62.08n, 102.58e) in russia.\n\nother sources have confirmed the shipment of a large amount of computer hardware to that location, and an influx of skilled personnel.\n",
 "007, i want you to infiltrate this base and find out what the devil's going on there. the satellite photographs reveal that there has been recent underground excavation we'd like to know the exact nature and planned extent of the workings.\n\nby the way, this is a covert operation. you may have to neutralize the security, but try not to be too obvious about it.\n",
 "you'll be doing some computer hacking on this mission, 007. i know you'd rather be cracking open a bottle of bubbly than cracking passwords, so i've taken the liberty of putting together a little gadget which will do the hard work for you.\nif you attach the data thief to their mainframe it should override any computer security measures and download the information we require.\n",
 "underground in siberia, james? some of us don't get further than the northern line.\n",
 "disrupt all surveillance\n    equipment\n",
 "copy goldeneye key and leave\n    original\n",
 "get personnel to activate\n    computer\n",
 "download data from computer\n",
 "photograph main video screen\n",
 "\n",
 "keycard\n",
 "computer room keycard\n",
 "Computer Room Keycard\n",
 "Picked up a computer room\n keycard.\n",
 "\n",
 "keycard\n",
 "security keycard\n",
 "Security Keycard\n",
 "Picked up a security keycard.\n",
 "Satellite Control Bunker\n",
 "Present day\n",
 "Mainframe destroyed!\nData cannot be downloaded.\n",
 NULL
};
