#include "game/lvl_text.h"

struct stringentry LsiloE[] = {
 "MI6 has become concerned that unscheduled test firings from a missile silo in Kirghizstan are being used to cover the launch of Goldeneye weapons satellites.\n\nDeep intelligence reports suggest that this operation may well be outside the control of the former Soviet powers in the region.",
 "Infiltrate the silo and ascertain what is being placed into orbit; if it is the satellites, recover their control circuitry and sabotage the launches. You are authorized to destroy the base if necessary.\n\nThis is a matter of international security, 007. Consider the military personnel expendable.\n",
 "The layout of the missile silo means that a few carefully placed explosive charges will destroy the entire complex - concentrate on the fuel rooms (H4, C3, K2 and A1). 007, remember to treat the timed explosives with respect - you know what happened to 004 in Beirut.\n\nOh, and get me a picture of the satellite, there's a good chap.\n",
 "You leave at 1800 hours for Bishkek.\n\nJames, just imagine those romantic nights in the steppes. Lying beneath the stars, the campfires twinkling on the hills - sounds like heaven. When you're in the arms of some dusky maiden, spare a thought for poor old me cooped up behind a desk in rainy London.",
 "Plant bombs in fuel rooms\n",
 "Photograph satellite\n",
 "Obtain telemetric data\n",
 "Retrieve satellite circuitry\n",
 "Minimize scientist casualties\n",
 "Explosive charge placed -\n              6 minutes to detonation!\n",
 "Ourumov: Kill him!\n",
 "Caution: Detonation imminent!\n",
 "Mission Failure: Unacceptable non-military\ncasualties!\n",
 "K I R G H I Z S T A N\n",
 "MI6 has become concerned that unscheduled test firings from a missile silo in kirghizstan are being used to cover the launch of goldeneye weapons satellites.\n\ndeep intelligence reports suggest that this operation may well be outside the control of the former soviet powers in the region.",
 "infiltrate the silo and ascertain what is being placed into orbit;\nif it is the satellites, recover their control circuitry and sabotage the launches. you are authorized to destroy the base if necessary.\n\nthis is a matter of international security, 007. consider the military personnel expendable.\n",
 "the layout of the missile silo means that a few carefully placed explosive charges will destroy the entire complex -\nconcentrate on the fuel rooms\n      (H4, C3, K2 and A1).\n\n007, remember to treat the timed explosives with respect - you know what happened to 004 in beirut.\n\noh, and get me a picture of the satellite, there's a good chap.\n",
 "you leave at 1800 hours for bishkek.\n\njames, just imagine those romantic nights in the steppes. lying beneath the stars, the campfires twinkling on the hills - sounds like heaven. when you're in the arms of some dusky maiden, spare a thought for poor old me cooped up behind a desk in rainy london.",
 "plant bombs in fuel rooms\n",
 "photograph satellite\n",
 "obtain telemetric data\n",
 "retrieve satellite circuitry\n",
 "minimize scientist casualties\n",
 "\n",
 "cpu circuitry\n",
 "cpu circuit board\n",
 "CPU Circuit Board\n",
 "Picked up a circuit board\n",
 "\n",
 "i/o circuitry\n",
 "i/o circuit board\n",
 "I/O Circuit Board\n",
 "Picked up a circuit board\n",
 "\n",
 "rsp circuitry\n",
 "rsp circuit board\n",
 "RSP Circuit Board\n",
 "Picked up a circuit board\n",
 "\n",
 "rdp circuitry\n",
 "rdp circuit board\n",
 "RDP Circuit Board\n",
 "Picked up a circuit board\n",
 "\n",
 "DAT\n",
 "telemetry data DAT\n",
 "DAT - Telemetry Data\n",
 "Picked up a DAT\n",
 "\n",
 "keycard\n",
 "keycard 4-H4\n",
 "Keycard (Level 4-H4)\n",
 "Picked up a keycard.\n",
 "\n",
 "keycard\n",
 "keycard 4-C3\n",
 "Keycard (Level 4-C3)\n",
 "Picked up a keycard.\n",
 "\n",
 "keycard\n",
 "keycard 4-K2\n",
 "Keycard (Level 4-K2)\n",
 "Picked up a keycard.\n",
 "Ourumov's\n",
 "briefcase\n",
 "ourumov's briefcase\n",
 "Ourumov's Briefcase\n",
 "Picked up Ourumov's briefcase.\n",
 "Soviet Missile Silo, Kirghizstan\n",
 "Two years ago\n",
 "Silo infiltrated -\nexplosive charges automatically primed!\n",
 NULL
};
