#include "game/lvl_text.h"

struct stringentry LstatE[] = {
 "Following the Severnaya incident, MI6 has lost track of the Pirate helicopter. Presumably the bugging device has been located and destroyed. Natalya Simonova, who returned to St. Petersburg against our advice, has gone missing. We can only assume that she has been abducted by the Janus syndicate in a belated attempt to cover their tracks.\n",
 "The situation is critical, 007. Janus know we're on to them and they're taking control. We're going to circumvent the usual channels on this one. I've arranged contact with an ex-KGB agent, Valentin Zukovsky, in Statue Park, St. Petersburg. He claims he can set up a meeting with Janus. Apparently, the head of Janus wants to see you in person. Frankly, I'm uneasy about this but it's all we've got to go on.\n",
 "No gizmos this time, old boy.\n",
 "Hmm, a damsel in distress.\n\nJust be careful with that chopper, James.\n",
 "Contact Valentin\n",
 "Confront and unmask Janus\n",
 "Locate helicopter\n",
 "Rescue Natalya\n",
 "Find flight recorder\n",
 "Valentin: Good evening, Mr. Bond.\n           These are strange times...\n",
 "Bond: With an ex-KGB agent meeting\n        an MI6 operative in the middle\n        of St. Petersburg?\n",
 "Valentin: Ha! I never thought I'd find\n           myself helping you, but things\n           have changed in Russia.\n",
 "Valentin: Janus will meet you by Lenin's\n           statue. Beware him, he's a Lienz\n           Cossack traitor.\n",
 "Valentin: Now I must leave - the guards\n           are out in force and I fear they\n           may mistake me for a spy!\n",
 "Valentin: I'm risking my life being here,\n           Mr Bond! You could at least\n           be civil enough to listen to me.\n",
 "Valentin has left. Contact failed!\n",
 "null\n",
 "null\n",
 "Janus: Good evening, 007.\n",
 "Janus: Put the gun away.\n         It's insulting to think I haven't\n         anticipated your every move.\n",
 "Janus: There's a good fellow.\n",
 "Trevelyan: So stubborn, James.\n              You always did think you\n              knew best.\n",
 "Bond: Alec? You're Janus?\n",
 "Trevelyan: Yes, the MI6 'hero',\n              back from the dead.\n",
 "Bond: But why, Alec? I trusted you.\n",
 "Trevelyan: Trust can be misplaced,\n              James. My parents trusted\n              the British government.\n",
 "Trevelyan: They were betrayed with all\n              the other Lienz Cossacks.\n              I will have my revenge.\n",
 "Bond: What have you done with Natalya?\n",
 "Trevelyan: The girl? I've left her with\n              the Pirate helicopter at the\n              park gates.\n",
 "Trevelyan: We've finished with them.\n              I have the Goldeneye\n              firing key now.\n",
 "Trevelyan: By the way, the helicopter's\n              rigged to blow in 3 minutes.\n              I doubt she'll survive.\n",
 "3 Minutes until helicopter bomb explodes.\n",
 "Helicopter destroyed.\n",
 "Janus: If he won't drop the gun kill him!\n",
 "Janus: You're an impatient fool, 007, \n         and now you'll die for it.\n",
 "Natalya: James!\n",
 "Bond: Quickly, this way!\n        The helicopter's about to explode.\n",
 "Bond: I have to find the helicopter flight\n        recorder. Wait for me at the gates.\n",
 "Bond: Natalya!\n",
 "The flight recorder could not have been\nthrown this far from the helicopter\nexplosion!\n",
 "Mishkin: Ah, Mr Bond. I see you've taken\n           it upon yourself to liven up the\n           nightlife in St. Petersburg.\n",
 "Mishkin: Blowing up helicopters,\n           shooting guards\n           - quite a jolly little soiree.\n",
 "Mishkin: Well, it's time to stop now,\n           before any more people get\n           hurt.\n",
 "Mishkin: I'd like to ask you and Miss\n           Simonova some questions\n           about the Severnaya incident.\n",
 "Mishkin: Perhaps you'd care to lead the\n           way to Military Intelligence HQ.\n",
 "Mishkin: There's a truck waiting outside.\n",
 "Mishkin: Come back Mr. Bond,\n           there's no other way out!\n",
 "Mishkin: Come along Mr. Bond, just step\n           through the gates and we can\n           clear up this misunderstanding.\n",
 "Valentin is dead - mission failure!\n",
 "Trevelyan: Closing time, James\n              - last call.\n",
 "Proximity fuse triggered.\n15 seconds to helicopter detonation!\n",
 "Janus: No gun, 007? \n         MI6 must be cutting their budget\n         these days.\n",
 "S T A T U E   P A R K\n",
 "following the severnaya incident, MI6 has lost track of the pirate helicopter. presumably the bugging device has been located and destroyed. natalya simonova, who returned to st. petersburg against our advice, has gone missing. we can only assume that she has been abducted by the janus syndicate in a belated attempt to cover their tracks.\n",
 "the situation is critical, 007. janus know we're on to them and they're taking control. we're going to circumvent the usual channels on this one. i've arranged contact with an ex-kgb agent, valentin zukovsky, in statue park, st. petersburg. he claims he can set up a meeting with janus. apparently, the head of janus wants to see you in person. frankly, i'm uneasy about this but it's all we've got to go on.\n",
 "no gizmos this time, old boy.\n",
 "hmm, a damsel in distress, james.\njust be careful with that chopper.\n",
 "contact valentin\n",
 "confront and unmask janus\n",
 "locate helicopter\n",
 "rescue natalya\n",
 "find flight recorder\n",
 "Statue Park, St. Petersburg\n",
 "flight\n",
 "recorder\n",
 "flight recorder\n",
 "pirate flight recorder\n",
 "Recovered the flight recorder.\n"
};
