#include "game/lvl_text.h"

struct stringentry LtitleE[] = {
 "hour",
 "minute",
 "second",
 "s",
 "START\n",
 "NEXT\n",
 "PREVIOUS\n",
 "TWYCROSS BOARD OF GAME CLASSIFICATION\n",
 "This is to certify\n",
 "(c) 1997 Nintendo/Rare\n",
 "(c) 1962, 1995 Danjaq, LLC. &\n",
 "U.A.C. All Rights Reserved\n",
 "(c) 1997 Eon Productions\n",
 "Ltd. & Mac B. Inc.\n",
 "Suitable only for 1-4 persons\n",
 "PRESIDENT\n",
 "VICE\n",
 "James Bond theme by Monty Norman.\n",
 "Used by permission of EMI Unart Catalog Inc.\n",
 "Agent",
 "Secret Agent",
 "00 Agent",
 "007",
 "Erase file?\n",
 "cancel\n",
 "confirm\n",
 "Mission ",
 "Copy\n",
 "Erase\n",
 "SELECT MISSION\n",
 "MULTIPLAYER\n",
 "CHEAT OPTIONS\n",
 ": James Bond\n",
 "Mission ",
 "Part ",
 "DIFFICULTY:\n",
 "Agent\n",
 "Secret Agent\n",
 "00 Agent\n",
 "007\n",
 "SPECIAL OPTIONS:\n",
 "Enemy reaction speed\n",
 "Enemy health\n",
 "Enemy damage\n",
 "Enemy accuracy\n",
 "Unlimited",
 "5 Minutes",
 "10 Minutes",
 "20 Minutes",
 "First to 5 points",
 "First to 10 points",
 "First to 20 points",
 "Last person alive wins",
 "Normal",
 "You Only Live Twice",
 "The Living Daylights [Flag Tag]",
 "The Man With the Golden Gun",
 "License to Kill",
 "Team: 2 vs 2",
 "Team: 3 vs 1",
 "Team: 2 vs 1",
 "Health -10\n(Hero)",
 "Health -4\n(Veteran)",
 "Health -3\n(Veteran)",
 "Health -2\n(Veteran)",
 "Health -1\n(Veteran)",
 "Health +0\n(Normal)",
 "Health +1\n(Novice)",
 "Health +2\n(Novice)",
 "Health +3\n(Novice)",
 "Health +4\n(Novice)",
 "Health +10\n(Rookie)",
 "Sight OFF, Auto Aim OFF",
 "Sight ON, Auto Aim OFF",
 "Sight OFF, Auto Aim ON",
 "Sight ON, Auto Aim ON",
 "MULTIPLAYER OPTIONS:\n",
 "Players:\n",
 "Scenario:\n",
 "Level:\n",
 "Game Length:\n",
 "Weapons:\n",
 "Characters\n",
 "Health\n",
 "Aim:\n",
 "Select Character",
 "Select Handicap:",
 "SCENARIO:\n",
 "Select Teams",
 "Red Team",
 "Blue Team",
 "Completed\n",
 "FAILED\n",
 "PRIMARY OBJECTIVES:\n",
 "BACKGROUND:\n",
 "M BRIEFING:\n",
 "Q BRANCH:\n",
 "MONEYPENNY:\n",
 "REPORT:\n",
 "Mission status:\n",
 " KILLED IN ACTION\n",
 " ABORTED\n",
 " Completed\n",
 " FAILED\n",
 "STATISTICS:\n",
 "Time:\n",
 "Accuracy:\n",
 "Weapon of choice:\n",
 "Shot total:\n",
 "Head hits:\n",
 "Body hits:\n",
 "Limb hits:\n",
 "Others:\n",
 "Kill total:\n",
 "CHEAT OPTIONS:\n",
 "ON\n",
 "OFF\n",
 "CHEAT SELECT MISSION",
 "NO CONTROLLER IN CONTROLLER SOCKET 1",
 "PLEASE POWER OFF AND ATTACH A CONTROLLER",
 "Arkangelsk",
 "Dam",
 "Facility",
 "Runway",
 "Severnaya",
 "Surface",
 "Bunker",
 "Kirghizstan",
 "Launch Silo #4",
 "Silo",
 "Monte Carlo",
 "Frigate",
 "St. Petersburg",
 "Statue Park",
 "Statue",
 "Military Archives",
 "Archives",
 "Streets",
 "Depot",
 "Train",
 "Cuba",
 "Jungle",
 "Control Center",
 "Control",
 "Water Caverns",
 "Caverns",
 "Antenna Cradle",
 "Cradle",
 "Teotihuaca'n",
 "Aztec Complex",
 "Aztec",
 "el-Saghira",
 "Egyptian Temple",
 "Egyptian",
 "Random",
 "RANDOM",
 "Temple",
 "TEMPLE",
 "Complex",
 "COMPLEX",
 "Library",
 "LIBRARY",
 "Caves",
 "CAVES",
 "Facility",
 "FACILITY",
 "Severnaya Bunker",
 "BUNKER",
 "Military Archives",
 "ARCHIVES",
 "Water Caverns",
 "CAVERNS",
 "Egyptian Temple",
 "EGYPTIAN",
 "Citadel",
 "CITADEL",
 "dest",
 "dest",
 "stat",
 "stat",
 "crad",
 "cradle",
 "azt",
 "azt",
 "Bond",
 "Mishkin",
 "Boris",
 "Ourumov",
 "Trevelyan",
 "Valentin",
 "Xenia",
 "Natalya",
 "Baron Samedi",
 "Jaws",
 "Mayday",
 "Oddjob",
 "Rosika",
 "Karl",
 "Martin",
 "Mark",
 "Dave",
 "Duncan",
 "B",
 "Steve E",
 "Grant",
 "Graeme",
 "Ken",
 "Alan",
 "Pete",
 "Shaun",
 "Dwayne",
 "Des",
 "Chris",
 "Lee",
 "Neil",
 "Jim",
 "Robin",
 "Steve H",
 "Terrorist",
 "Biker",
 "Joel",
 "Scott",
 "Joe",
 "Sally",
 "Marion",
 "Mandy",
 "Vivien",
 "\n",
 "The Actors\n",
 "Starring\n",
 "Also Featuring\n",
 "Guest Star\n",
 "007\n",
 "James Bond",
 "Natalya Simonova\n",
 "006\n",
 "Alec Trevelyan\n",
 "Janus Operative\n",
 "Xenia Onatopp\n",
 "General\n",
 "Arkady Ourumov\n",
 "Boris Grishenko\n",
 "Ex KGB Agent\n",
 "Valentin Zukovsky\n",
 "Defense Minister\n",
 "Dimitri Mishkin\n",
 "Mayday\n",
 "Jaws\n",
 "Oddjob\n",
 "Baron Samedi\n",
 "Jungle Commando\n",
 "St. Petersburg Guard\n",
 "Russian Infantry\n",
 "Russian Soldier\n",
 "Janus Marine\n",
 "Janus Special Forces\n",
 "Russian Commandant\n",
 "Naval Officer\n",
 "Siberian Guard\n",
 "Arctic Commando\n",
 "Siberian Special Forces\n",
 "Moonraker Elite\n",
 "Helicopter Pilot\n",
 "Scientist\n",
 "Civilian\n",
 "1.\n",
 "2.\n",
 "3.\n",
 "4.\n",
 "Basement",
 "BASEMENT",
 "Stack",
 "STACK",
 "Best Time:",
 "Target:",
 "New Cheat Available",
 "CHEAT MULTIPLAYER\n",
 "1.1 Honey\n",
 "1.2 Solitaire\n",
 "1.3 Kissy\n",
 "1.4 Goodnight\n",
 "2.1 Plenty\n",
 "2.2 Galore\n",
 "2.3 Domino\n",
 "2.4 Goodhead\n",
 "Select Control Style\n",
 "Control Style\n",
 #ifdef VERSION_US
 NULL
 #endif
 #ifdef VERSION_JP
 "Russian Soldier\n",
 "Russian Infantry\n",
 "Scientist\n",
 "Russian Commandant\n",
 "Janus Marine\n",
 "Naval Officer\n",
 "Helicopter Pilot\n",
 "St. Petersburg Guard\n",
 "Civilian\n",
 "Siberian Guard\n",
 "Arctic Commando\n",
 "Siberian Special Forces\n",
 "Jungle Commando\n",
 "Janus Special Forces\n",
 "Moonraker Elite\n"
 #endif
};
