#include "game/lvl_text.h"

struct stringentry LtraE[] = {
 "The leader of Janus, Alec Trevelyan, is holding Natalya hostage on his armored train.\n",
 "We've lost experienced agents before in hostage situations. Keep a clear head, 007, and don't get sidetracked settling old scores.\n",
 "A train, 007, pretty simple. Destroy the braking units in each carriage and the emergency \nsystems should bring it to a halt.\n",
 "That girl again, James? \n",
 "Destroy brake units\n",
 "Rescue Natalya\n",
 "Locate Janus secret base\n",
 "Crack Boris' password\n",
 "Escape to safety\n",
 "Trevelyan: That's close enough!\n",
 "Trevelyan: Come on James, don't try\n              to be clever. Make your move.\n",
 "Bond: You first.\n",
 "Trevelyan: Two targets. Time for one shot.\n              The girl or the mission?\n",
 "Trevelyan: You'll never win, James.\n",
 "Xenia: Wait for me Alec, I'm hit!\n",
 "Trevelyan: Kill them!\n",
 "Trevelyan: James, what an unpleasant\n              surprise. Do come in.\n",
 "Trevelyan: Leaving already, James?\n              I don't think so.\n",
 "Trevelyan: Good luck with the floor, \n              James.\n",
 "Trevelyan: It shouldn't take more than\n              a minute.\n",
 "Natalya: Boris is still backing up his files.\n           I can find out where they're\n           going.\n",
 "Natalya: He's in Cuba!\n",
 "Natalya: Now, if I just had time to crack \n           his password...\n",
 "Natalya: Got it!\n           You're a slug-head, Boris!\n",
 "Natalya: I'm coming, James!\n",
 "Trevelyan: Too slow, 007.\n",
 "Natalya: Well done, James, that's the\n           computer out of action.\n",
 "Natalya: Just how am I supposed to\n           locate the Janus base?\n",
 "Mission failure. Natalya has been killed.\n",
 "T R A I N\n",
 "the leader of janus, alec trevelyan, is holding natalya hostage on his armored train.\n",
 "we've lost experienced agents before in hostage situations. Keep a clear head, 007, and don't get sidetracked settling old scores.\n",
 "a train, 007, pretty simple. destroy the braking units in each carriage and the emergency \nsystems should bring it to a halt.\n",
 "that girl again, james? \n",
 "destroy brake units\n",
 "rescue natalya\n",
 "locate janus secret base\n",
 "crack boris' password\n",
 "escape to safety\n",
 "\n",
 "door key\n",
 "train door key\n",
 "train door key\n",
 "Picked up a door key.\n",
 "Converted Missile Train, heading east\n",
 NULL,
 NULL,
 NULL
};
