# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# c file -- needs decomp

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel _ldexpf
/* 01B500 7001A900 10C00007 */  beqz  $a2, .L7001A920
/* 01B504 7001A904 240E0001 */   li    $t6, 1
/* 01B508 7001A908 00CE7804 */  sllv  $t7, $t6, $a2
/* 01B50C 7001A90C 448F2000 */  mtc1  $t7, $f4
/* 01B510 7001A910 00000000 */  nop   
/* 01B514 7001A914 468021A1 */  cvt.d.w $f6, $f4
/* 01B518 7001A918 46266302 */  mul.d $f12, $f12, $f6
/* 01B51C 7001A91C 00000000 */  nop   
.L7001A920:
/* 01B520 7001A920 03E00008 */  jr    $ra
/* 01B524 7001A924 46206006 */   mov.d $f0, $f12
.size _ldexpf, . - _ldexpf

glabel _frexpf
/* 01B528 7001A928 44801800 */  mtc1  $zero, $f3
/* 01B52C 7001A92C 44801000 */  mtc1  $zero, $f2
/* 01B530 7001A930 ACC00000 */  sw    $zero, ($a2)
/* 01B534 7001A934 3C013FF0 */  lui   $at, 0x3ff0
/* 01B538 7001A938 46226032 */  c.eq.d $f12, $f2
/* 01B53C 7001A93C 00000000 */  nop   
/* 01B540 7001A940 45020004 */  bc1fl .L7001A954
/* 01B544 7001A944 462C103C */   c.lt.d $f2, $f12
/* 01B548 7001A948 03E00008 */  jr    $ra
/* 01B54C 7001A94C 46206006 */   mov.d $f0, $f12
/* 01B550 7001A950 462C103C */  c.lt.d $f2, $f12
.L7001A954:
/* 01B554 7001A954 44817800 */  mtc1  $at, $f15
/* 01B558 7001A958 44807000 */  mtc1  $zero, $f14
/* 01B55C 7001A95C 3C013FE0 */  lui   $at, 0x3fe0
/* 01B560 7001A960 45020004 */  bc1fl .L7001A974
/* 01B564 7001A964 46206007 */   neg.d $f0, $f12
/* 01B568 7001A968 10000002 */  b     .L7001A974
/* 01B56C 7001A96C 46206006 */   mov.d $f0, $f12
/* 01B570 7001A970 46206007 */  neg.d $f0, $f12
.L7001A974:
/* 01B574 7001A974 4620703E */  c.le.d $f14, $f0
/* 01B578 7001A978 00000000 */  nop   
/* 01B57C 7001A97C 4502000D */  bc1fl .L7001A9B4
/* 01B580 7001A980 3C013FE0 */   li    $at, 0x3FE00000 # 1.750000
/* 01B584 7001A984 44818800 */  mtc1  $at, $f17
/* 01B588 7001A988 44808000 */  mtc1  $zero, $f16
/* 01B58C 7001A98C 00000000 */  nop   
.L7001A990:
/* 01B590 7001A990 46300002 */  mul.d $f0, $f0, $f16
/* 01B594 7001A994 8CCE0000 */  lw    $t6, ($a2)
/* 01B598 7001A998 25CF0001 */  addiu $t7, $t6, 1
/* 01B59C 7001A99C ACCF0000 */  sw    $t7, ($a2)
/* 01B5A0 7001A9A0 4620703E */  c.le.d $f14, $f0
/* 01B5A4 7001A9A4 00000000 */  nop   
/* 01B5A8 7001A9A8 4501FFF9 */  bc1t  .L7001A990
/* 01B5AC 7001A9AC 00000000 */   nop   
/* 01B5B0 7001A9B0 3C013FE0 */  li    $at, 0x3FE00000 # 1.750000
.L7001A9B4:
/* 01B5B4 7001A9B4 44818800 */  mtc1  $at, $f17
/* 01B5B8 7001A9B8 44808000 */  mtc1  $zero, $f16
/* 01B5BC 7001A9BC 00000000 */  nop   
/* 01B5C0 7001A9C0 4630003C */  c.lt.d $f0, $f16
/* 01B5C4 7001A9C4 00000000 */  nop   
/* 01B5C8 7001A9C8 45020009 */  bc1fl .L7001A9F0
/* 01B5CC 7001A9CC 462C103C */   c.lt.d $f2, $f12
/* 01B5D0 7001A9D0 46200000 */  add.d $f0, $f0, $f0
.L7001A9D4:
/* 01B5D4 7001A9D4 8CD80000 */  lw    $t8, ($a2)
/* 01B5D8 7001A9D8 4630003C */  c.lt.d $f0, $f16
/* 01B5DC 7001A9DC 2719FFFF */  addiu $t9, $t8, -1
/* 01B5E0 7001A9E0 ACD90000 */  sw    $t9, ($a2)
/* 01B5E4 7001A9E4 4503FFFB */  bc1tl .L7001A9D4
/* 01B5E8 7001A9E8 46200000 */   add.d $f0, $f0, $f0
/* 01B5EC 7001A9EC 462C103C */  c.lt.d $f2, $f12
.L7001A9F0:
/* 01B5F0 7001A9F0 00000000 */  nop   
/* 01B5F4 7001A9F4 45020004 */  bc1fl .L7001AA08
/* 01B5F8 7001A9F8 46200087 */   neg.d $f2, $f0
/* 01B5FC 7001A9FC 10000002 */  b     .L7001AA08
/* 01B600 7001AA00 46200086 */   mov.d $f2, $f0
/* 01B604 7001AA04 46200087 */  neg.d $f2, $f0
.L7001AA08:
/* 01B608 7001AA08 46201006 */  mov.d $f0, $f2
/* 01B60C 7001AA0C 03E00008 */  jr    $ra
/* 01B610 7001AA10 00000000 */   nop   
.size _frexpf, . - _frexpf

glabel alEnvmixerParam
/* 01B614 7001AA14 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01B618 7001AA18 24020001 */  li    $v0, 1
/* 01B61C 7001AA1C AFBF0014 */  sw    $ra, 0x14($sp)
/* 01B620 7001AA20 10A20027 */  beq   $a1, $v0, .L7001AAC0
/* 01B624 7001AA24 00803825 */   move  $a3, $a0
/* 01B628 7001AA28 24010003 */  li    $at, 3
/* 01B62C 7001AA2C 10A10007 */  beq   $a1, $at, .L7001AA4C
/* 01B630 7001AA30 24010004 */   li    $at, 4
/* 01B634 7001AA34 10A1000D */  beq   $a1, $at, .L7001AA6C
/* 01B638 7001AA38 24010009 */   li    $at, 9
/* 01B63C 7001AA3C 50A10017 */  beql  $a1, $at, .L7001AA9C
/* 01B640 7001AA40 8CE40000 */   lw    $a0, ($a3)
/* 01B644 7001AA44 10000021 */  b     .L7001AACC
/* 01B648 7001AA48 8CE40000 */   lw    $a0, ($a3)
.L7001AA4C:
/* 01B64C 7001AA4C 8CE20040 */  lw    $v0, 0x40($a3)
/* 01B650 7001AA50 50400004 */  beql  $v0, $zero, .L7001AA64
/* 01B654 7001AA54 ACE6003C */   sw    $a2, 0x3c($a3)
/* 01B658 7001AA58 10000002 */  b     .L7001AA64
/* 01B65C 7001AA5C AC460000 */   sw    $a2, ($v0)
/* 01B660 7001AA60 ACE6003C */  sw    $a2, 0x3c($a3)
.L7001AA64:
/* 01B664 7001AA64 1000001E */  b     .L7001AAE0
/* 01B668 7001AA68 ACE60040 */   sw    $a2, 0x40($a3)
.L7001AA6C:
/* 01B66C 7001AA6C 8CE40000 */  lw    $a0, ($a3)
/* 01B670 7001AA70 ACE20038 */  sw    $v0, 0x38($a3)
/* 01B674 7001AA74 ACE00048 */  sw    $zero, 0x48($a3)
/* 01B678 7001AA78 10800019 */  beqz  $a0, .L7001AAE0
/* 01B67C 7001AA7C A4E2001A */   sh    $v0, 0x1a($a3)
/* 01B680 7001AA80 8C990008 */  lw    $t9, 8($a0)
/* 01B684 7001AA84 24050004 */  li    $a1, 4
/* 01B688 7001AA88 0320F809 */  jalr  $t9
/* 01B68C 7001AA8C 00000000 */  nop   
/* 01B690 7001AA90 10000014 */  b     .L7001AAE4
/* 01B694 7001AA94 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01B698 7001AA98 8CE40000 */  lw    $a0, ($a3)
.L7001AA9C:
/* 01B69C 7001AA9C ACE20048 */  sw    $v0, 0x48($a3)
/* 01B6A0 7001AAA0 50800010 */  beql  $a0, $zero, .L7001AAE4
/* 01B6A4 7001AAA4 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01B6A8 7001AAA8 8C990008 */  lw    $t9, 8($a0)
/* 01B6AC 7001AAAC 24050009 */  li    $a1, 9
/* 01B6B0 7001AAB0 0320F809 */  jalr  $t9
/* 01B6B4 7001AAB4 00000000 */  nop   
/* 01B6B8 7001AAB8 1000000A */  b     .L7001AAE4
/* 01B6BC 7001AABC 8FBF0014 */   lw    $ra, 0x14($sp)
.L7001AAC0:
/* 01B6C0 7001AAC0 10000007 */  b     .L7001AAE0
/* 01B6C4 7001AAC4 ACE60000 */   sw    $a2, ($a3)
/* 01B6C8 7001AAC8 8CE40000 */  lw    $a0, ($a3)
.L7001AACC:
/* 01B6CC 7001AACC 50800005 */  beql  $a0, $zero, .L7001AAE4
/* 01B6D0 7001AAD0 8FBF0014 */   lw    $ra, 0x14($sp)
/* 01B6D4 7001AAD4 8C990008 */  lw    $t9, 8($a0)
/* 01B6D8 7001AAD8 0320F809 */  jalr  $t9
/* 01B6DC 7001AADC 00000000 */  nop   
.L7001AAE0:
/* 01B6E0 7001AAE0 8FBF0014 */  lw    $ra, 0x14($sp)
.L7001AAE4:
/* 01B6E4 7001AAE4 27BD0018 */  addiu $sp, $sp, 0x18
/* 01B6E8 7001AAE8 00001025 */  move  $v0, $zero
/* 01B6EC 7001AAEC 03E00008 */  jr    $ra
/* 01B6F0 7001AAF0 00000000 */   nop   
.size alEnvmixerParam, . - alEnvmixerParam

glabel ultra_7001AAF4
/* 01B6F4 7001AAF4 5480000C */  bnezl $a0, .L7001AB28
/* 01B6F8 7001AAF8 44843000 */   mtc1  $a0, $f6
/* 01B6FC 7001AAFC 460C703E */  c.le.s $f14, $f12
/* 01B700 7001AB00 340EFFFF */  li    $t6, 65535
/* 01B704 7001AB04 24028000 */  li    $v0, -32768
/* 01B708 7001AB08 45000004 */  bc1f  .L7001AB1C
/* 01B70C 7001AB0C 00000000 */   nop   
/* 01B710 7001AB10 A4AE0000 */  sh    $t6, ($a1)
/* 01B714 7001AB14 03E00008 */  jr    $ra
/* 01B718 7001AB18 24027FFF */   li    $v0, 32767
.L7001AB1C:
/* 01B71C 7001AB1C 03E00008 */  jr    $ra
/* 01B720 7001AB20 A4A00000 */   sh    $zero, ($a1)
/* 01B724 7001AB24 44843000 */  mtc1  $a0, $f6
.L7001AB28:
/* 01B728 7001AB28 460E6101 */  sub.s $f4, $f12, $f14
/* 01B72C 7001AB2C 3C014020 */  li    $at, 0x40200000 # 2.500000
/* 01B730 7001AB30 44812800 */  mtc1  $at, $f5
/* 01B734 7001AB34 46803220 */  cvt.s.w $f8, $f6
/* 01B738 7001AB38 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 01B73C 7001AB3C 46082283 */  div.s $f10, $f4, $f8
/* 01B740 7001AB40 44802000 */  mtc1  $zero, $f4
/* 01B744 7001AB44 460051A1 */  cvt.d.s $f6, $f10
/* 01B748 7001AB48 44805000 */  mtc1  $zero, $f10
/* 01B74C 7001AB4C 46243202 */  mul.d $f8, $f6, $f4
/* 01B750 7001AB50 462040A0 */  cvt.s.d $f2, $f8
/* 01B754 7001AB54 460A103C */  c.lt.s $f2, $f10
/* 01B758 7001AB58 46001006 */  mov.s $f0, $f2
/* 01B75C 7001AB5C 45020005 */  bc1fl .L7001AB74
/* 01B760 7001AB60 4600010D */   trunc.w.s $f4, $f0
/* 01B764 7001AB64 44813000 */  mtc1  $at, $f6
/* 01B768 7001AB68 00000000 */  nop   
/* 01B76C 7001AB6C 46061001 */  sub.s $f0, $f2, $f6
/* 01B770 7001AB70 4600010D */  trunc.w.s $f4, $f0
.L7001AB74:
/* 01B774 7001AB74 3C018003 */  lui   $at, %hi(F32_80029964)
/* 01B778 7001AB78 44032000 */  mfc1  $v1, $f4
/* 01B77C 7001AB7C C4249964 */  lwc1  $f4, %lo(F32_80029964)($at)
/* 01B780 7001AB80 0003C400 */  sll   $t8, $v1, 0x10
/* 01B784 7001AB84 00181403 */  sra   $v0, $t8, 0x10
/* 01B788 7001AB88 44824000 */  mtc1  $v0, $f8
/* 01B78C 7001AB8C 00000000 */  nop   
/* 01B790 7001AB90 468042A0 */  cvt.s.w $f10, $f8
/* 01B794 7001AB94 460A0181 */  sub.s $f6, $f0, $f10
/* 01B798 7001AB98 46043202 */  mul.s $f8, $f6, $f4
/* 01B79C 7001AB9C 4600428D */  trunc.w.s $f10, $f8
/* 01B7A0 7001ABA0 440F5000 */  mfc1  $t7, $f10
/* 01B7A4 7001ABA4 00000000 */  nop   
/* 01B7A8 7001ABA8 A4AF0000 */  sh    $t7, ($a1)
/* 01B7AC 7001ABAC 03E00008 */  jr    $ra
/* 01B7B0 7001ABB0 00000000 */   nop  
.size ultra_7001AAF4, . - ultra_7001AAF4 

glabel ultra_7001ABB4
/* 01B7B4 7001ABB4 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 01B7B8 7001ABB8 AFBF001C */  sw    $ra, 0x1c($sp)
/* 01B7BC 7001ABBC 16400003 */  bnez  $s2, .L7001ABCC
/* 01B7C0 7001ABC0 8E110000 */   lw    $s1, ($s0)
/* 01B7C4 7001ABC4 1000009F */  b     .L7001AE44
/* 01B7C8 7001ABC8 02801025 */   move  $v0, $s4
.L7001ABCC:
/* 01B7CC 7001ABCC 16200008 */  bnez  $s1, .L7001ABF0
/* 01B7D0 7001ABD0 3C048003 */   lui   $a0, %hi(aAssertionFaultSSLineD_1)
/* 01B7D4 7001ABD4 3C058003 */  lui   $a1, %hi(aSource)
/* 01B7D8 7001ABD8 3C068003 */  lui   $a2, %hi(aEnv_c_1)
/* 01B7DC 7001ABDC 24C6995C */  addiu $a2, %lo(aEnv_c_1) # addiu $a2, $a2, -0x66a4
/* 01B7E0 7001ABE0 24A59954 */  addiu $a1, %lo(aSource) # addiu $a1, $a1, -0x66ac
/* 01B7E4 7001ABE4 24849928 */  addiu $a0, %lo(aAssertionFaultSSLineD_1) # addiu $a0, $a0, -0x66d8
/* 01B7E8 7001ABE8 0C0033D1 */  jal   osSyncPrintf
/* 01B7EC 7001ABEC 24070175 */   li    $a3, 373
.L7001ABF0:
/* 01B7F0 7001ABF0 AFB40010 */  sw    $s4, 0x10($sp)
/* 01B7F4 7001ABF4 8E390004 */  lw    $t9, 4($s1)
/* 01B7F8 7001ABF8 02202025 */  move  $a0, $s1
/* 01B7FC 7001ABFC 02A02825 */  move  $a1, $s5
/* 01B800 7001AC00 02403025 */  move  $a2, $s2
/* 01B804 7001AC04 0320F809 */  jalr  $t9
/* 01B808 7001AC08 02C03825 */  move  $a3, $s6
/* 01B80C 7001AC0C 86AE0000 */  lh    $t6, ($s5)
/* 01B810 7001AC10 3C010800 */  lui   $at, 0x800
/* 01B814 7001AC14 0012A040 */  sll   $s4, $s2, 1
/* 01B818 7001AC18 31CFFFFF */  andi  $t7, $t6, 0xffff
/* 01B81C 7001AC1C 01E1C025 */  or    $t8, $t7, $at
/* 01B820 7001AC20 AC580000 */  sw    $t8, ($v0)
/* 01B824 7001AC24 86790000 */  lh    $t9, ($s3)
/* 01B828 7001AC28 3C010808 */  lui   $at, 0x808
/* 01B82C 7001AC2C 24510010 */  addiu $s1, $v0, 0x10
/* 01B830 7001AC30 272F0440 */  addiu $t7, $t9, 0x440
/* 01B834 7001AC34 000FC400 */  sll   $t8, $t7, 0x10
/* 01B838 7001AC38 3299FFFF */  andi  $t9, $s4, 0xffff
/* 01B83C 7001AC3C 03197025 */  or    $t6, $t8, $t9
/* 01B840 7001AC40 AC4E0004 */  sw    $t6, 4($v0)
/* 01B844 7001AC44 866F0000 */  lh    $t7, ($s3)
/* 01B848 7001AC48 02209025 */  move  $s2, $s1
/* 01B84C 7001AC4C 25F80580 */  addiu $t8, $t7, 0x580
/* 01B850 7001AC50 3319FFFF */  andi  $t9, $t8, 0xffff
/* 01B854 7001AC54 03217025 */  or    $t6, $t9, $at
/* 01B858 7001AC58 AC4E0008 */  sw    $t6, 8($v0)
/* 01B85C 7001AC5C 86630000 */  lh    $v1, ($s3)
/* 01B860 7001AC60 246F0800 */  addiu $t7, $v1, 0x800
/* 01B864 7001AC64 31F8FFFF */  andi  $t8, $t7, 0xffff
/* 01B868 7001AC68 246E06C0 */  addiu $t6, $v1, 0x6c0
/* 01B86C 7001AC6C 000E7C00 */  sll   $t7, $t6, 0x10
/* 01B870 7001AC70 030FC825 */  or    $t9, $t8, $t7
/* 01B874 7001AC74 AC59000C */  sw    $t9, 0xc($v0)
/* 01B878 7001AC78 8E0E0038 */  lw    $t6, 0x38($s0)
/* 01B87C 7001AC7C 3C198003 */  lui   $t9, %hi(eqpower)
/* 01B880 7001AC80 51C00067 */  beql  $t6, $zero, .L7001AE20
/* 01B884 7001AC84 3C0E0308 */   lui   $t6, 0x308
/* 01B888 7001AC88 86180018 */  lh    $t8, 0x18($s0)
/* 01B88C 7001AC8C AE000038 */  sw    $zero, 0x38($s0)
/* 01B890 7001AC90 860E001A */  lh    $t6, 0x1a($s0)
/* 01B894 7001AC94 00187840 */  sll   $t7, $t8, 1
/* 01B898 7001AC98 032FC821 */  addu  $t9, $t9, $t7
/* 01B89C 7001AC9C 873981E0 */  lh    $t9, %lo(eqpower)($t9)
/* 01B8A0 7001ACA0 8E040034 */  lw    $a0, 0x34($s0)
/* 01B8A4 7001ACA4 26050024 */  addiu $a1, $s0, 0x24
/* 01B8A8 7001ACA8 032E0019 */  multu $t9, $t6
/* 01B8AC 7001ACAC 8619001C */  lh    $t9, 0x1c($s0)
/* 01B8B0 7001ACB0 44992000 */  mtc1  $t9, $f4
/* 01B8B4 7001ACB4 00000000 */  nop   
/* 01B8B8 7001ACB8 468023A0 */  cvt.s.w $f14, $f4
/* 01B8BC 7001ACBC 0000C012 */  mflo  $t8
/* 01B8C0 7001ACC0 00187BC3 */  sra   $t7, $t8, 0xf
/* 01B8C4 7001ACC4 A60F0028 */  sh    $t7, 0x28($s0)
/* 01B8C8 7001ACC8 860E0028 */  lh    $t6, 0x28($s0)
/* 01B8CC 7001ACCC 448E3000 */  mtc1  $t6, $f6
/* 01B8D0 7001ACD0 0C006ABD */  jal   ultra_7001AAF4
/* 01B8D4 7001ACD4 46803320 */   cvt.s.w $f12, $f6
/* 01B8D8 7001ACD8 86180018 */  lh    $t8, 0x18($s0)
/* 01B8DC 7001ACDC 3C0E8003 */  lui   $t6, %hi(eqpower+0xFE)
/* 01B8E0 7001ACE0 A6020026 */  sh    $v0, 0x26($s0)
/* 01B8E4 7001ACE4 00187840 */  sll   $t7, $t8, 1
/* 01B8E8 7001ACE8 000FC823 */  negu  $t9, $t7
/* 01B8EC 7001ACEC 01D97021 */  addu  $t6, $t6, $t9
/* 01B8F0 7001ACF0 85CE82DE */  lh    $t6, %lo(eqpower+0xFE)($t6)
/* 01B8F4 7001ACF4 8618001A */  lh    $t8, 0x1a($s0)
/* 01B8F8 7001ACF8 8E040034 */  lw    $a0, 0x34($s0)
/* 01B8FC 7001ACFC 2605002A */  addiu $a1, $s0, 0x2a
/* 01B900 7001AD00 01D80019 */  multu $t6, $t8
/* 01B904 7001AD04 860E001E */  lh    $t6, 0x1e($s0)
/* 01B908 7001AD08 448E4000 */  mtc1  $t6, $f8
/* 01B90C 7001AD0C 00000000 */  nop   
/* 01B910 7001AD10 468043A0 */  cvt.s.w $f14, $f8
/* 01B914 7001AD14 00007812 */  mflo  $t7
/* 01B918 7001AD18 000FCBC3 */  sra   $t9, $t7, 0xf
/* 01B91C 7001AD1C A619002E */  sh    $t9, 0x2e($s0)
/* 01B920 7001AD20 8618002E */  lh    $t8, 0x2e($s0)
/* 01B924 7001AD24 44985000 */  mtc1  $t8, $f10
/* 01B928 7001AD28 0C006ABD */  jal   ultra_7001AAF4
/* 01B92C 7001AD2C 46805320 */   cvt.s.w $f12, $f10
/* 01B930 7001AD30 860F001C */  lh    $t7, 0x1c($s0)
/* 01B934 7001AD34 A602002C */  sh    $v0, 0x2c($s0)
/* 01B938 7001AD38 02201825 */  move  $v1, $s1
/* 01B93C 7001AD3C 3C010906 */  lui   $at, 0x906
/* 01B940 7001AD40 31F9FFFF */  andi  $t9, $t7, 0xffff
/* 01B944 7001AD44 03217025 */  or    $t6, $t9, $at
/* 01B948 7001AD48 AC6E0000 */  sw    $t6, ($v1)
/* 01B94C 7001AD4C AC600004 */  sw    $zero, 4($v1)
/* 01B950 7001AD50 8618001E */  lh    $t8, 0x1e($s0)
/* 01B954 7001AD54 26310008 */  addiu $s1, $s1, 8
/* 01B958 7001AD58 02202025 */  move  $a0, $s1
/* 01B95C 7001AD5C 3C010904 */  lui   $at, 0x904
/* 01B960 7001AD60 330FFFFF */  andi  $t7, $t8, 0xffff
/* 01B964 7001AD64 01E1C825 */  or    $t9, $t7, $at
/* 01B968 7001AD68 AC990000 */  sw    $t9, ($a0)
/* 01B96C 7001AD6C AC800004 */  sw    $zero, 4($a0)
/* 01B970 7001AD70 860E0028 */  lh    $t6, 0x28($s0)
/* 01B974 7001AD74 26310008 */  addiu $s1, $s1, 8
/* 01B978 7001AD78 3C010902 */  lui   $at, 0x902
/* 01B97C 7001AD7C 31D8FFFF */  andi  $t8, $t6, 0xffff
/* 01B980 7001AD80 03017825 */  or    $t7, $t8, $at
/* 01B984 7001AD84 02202825 */  move  $a1, $s1
/* 01B988 7001AD88 ACAF0000 */  sw    $t7, ($a1)
/* 01B98C 7001AD8C 860E0026 */  lh    $t6, 0x26($s0)
/* 01B990 7001AD90 96190024 */  lhu   $t9, 0x24($s0)
/* 01B994 7001AD94 26310008 */  addiu $s1, $s1, 8
/* 01B998 7001AD98 000EC400 */  sll   $t8, $t6, 0x10
/* 01B99C 7001AD9C 03197025 */  or    $t6, $t8, $t9
/* 01B9A0 7001ADA0 ACAE0004 */  sw    $t6, 4($a1)
/* 01B9A4 7001ADA4 860F002E */  lh    $t7, 0x2e($s0)
/* 01B9A8 7001ADA8 3C010900 */  lui   $at, 0x900
/* 01B9AC 7001ADAC 02203025 */  move  $a2, $s1
/* 01B9B0 7001ADB0 31F8FFFF */  andi  $t8, $t7, 0xffff
/* 01B9B4 7001ADB4 0301C825 */  or    $t9, $t8, $at
/* 01B9B8 7001ADB8 ACD90000 */  sw    $t9, ($a2)
/* 01B9BC 7001ADBC 860F002C */  lh    $t7, 0x2c($s0)
/* 01B9C0 7001ADC0 960E002A */  lhu   $t6, 0x2a($s0)
/* 01B9C4 7001ADC4 26310008 */  addiu $s1, $s1, 8
/* 01B9C8 7001ADC8 000FC400 */  sll   $t8, $t7, 0x10
/* 01B9CC 7001ADCC 030E7825 */  or    $t7, $t8, $t6
/* 01B9D0 7001ADD0 ACCF0004 */  sw    $t7, 4($a2)
/* 01B9D4 7001ADD4 86190020 */  lh    $t9, 0x20($s0)
/* 01B9D8 7001ADD8 3C010908 */  lui   $at, 0x908
/* 01B9DC 7001ADDC 02201025 */  move  $v0, $s1
/* 01B9E0 7001ADE0 3338FFFF */  andi  $t8, $t9, 0xffff
/* 01B9E4 7001ADE4 03017025 */  or    $t6, $t8, $at
/* 01B9E8 7001ADE8 AC4E0000 */  sw    $t6, ($v0)
/* 01B9EC 7001ADEC 860F0022 */  lh    $t7, 0x22($s0)
/* 01B9F0 7001ADF0 26310008 */  addiu $s1, $s1, 8
/* 01B9F4 7001ADF4 02209025 */  move  $s2, $s1
/* 01B9F8 7001ADF8 31F9FFFF */  andi  $t9, $t7, 0xffff
/* 01B9FC 7001ADFC AC590004 */  sw    $t9, 4($v0)
/* 01BA00 7001AE00 3C180309 */  lui   $t8, 0x309
/* 01BA04 7001AE04 AE580000 */  sw    $t8, ($s2)
/* 01BA08 7001AE08 8E040014 */  lw    $a0, 0x14($s0)
/* 01BA0C 7001AE0C 0C003A2C */  jal   osVirtualToPhysical
/* 01BA10 7001AE10 26310008 */   addiu $s1, $s1, 8
/* 01BA14 7001AE14 10000007 */  b     .L7001AE34
/* 01BA18 7001AE18 AE420004 */   sw    $v0, 4($s2)
/* 01BA1C 7001AE1C 3C0E0308 */  lui   $t6, 0x308
.L7001AE20:
/* 01BA20 7001AE20 AE4E0000 */  sw    $t6, ($s2)
/* 01BA24 7001AE24 8E040014 */  lw    $a0, 0x14($s0)
/* 01BA28 7001AE28 0C003A2C */  jal   osVirtualToPhysical
/* 01BA2C 7001AE2C 26310008 */   addiu $s1, $s1, 8
/* 01BA30 7001AE30 AE420004 */  sw    $v0, 4($s2)
.L7001AE34:
/* 01BA34 7001AE34 86AF0000 */  lh    $t7, ($s5)
/* 01BA38 7001AE38 02201025 */  move  $v0, $s1
/* 01BA3C 7001AE3C 01F4C821 */  addu  $t9, $t7, $s4
/* 01BA40 7001AE40 A6B90000 */  sh    $t9, ($s5)
.L7001AE44:
/* 01BA44 7001AE44 8FBF001C */  lw    $ra, 0x1c($sp)
/* 01BA48 7001AE48 27BD0020 */  addiu $sp, $sp, 0x20
/* 01BA4C 7001AE4C 03E00008 */  jr    $ra
/* 01BA50 7001AE50 00000000 */   nop   
.size ultra_7001ABB4, . - ultra_7001ABB4

/* 01BA54 7001AE54 03E00008 */  jr    $ra
/* 01BA58 7001AE58 00000000 */   nop   

glabel alEnvmixerPull
/* 01BA5C 7001AE5C 27BDFF28 */  addiu $sp, $sp, -0xd8
/* 01BA60 7001AE60 8FAE00E8 */  lw    $t6, 0xe8($sp)
/* 01BA64 7001AE64 AFBF0054 */  sw    $ra, 0x54($sp)
/* 01BA68 7001AE68 AFBE0050 */  sw    $fp, 0x50($sp)
/* 01BA6C 7001AE6C AFB7004C */  sw    $s7, 0x4c($sp)
/* 01BA70 7001AE70 AFB60048 */  sw    $s6, 0x48($sp)
/* 01BA74 7001AE74 AFB50044 */  sw    $s5, 0x44($sp)
/* 01BA78 7001AE78 AFB40040 */  sw    $s4, 0x40($sp)
/* 01BA7C 7001AE7C AFB3003C */  sw    $s3, 0x3c($sp)
/* 01BA80 7001AE80 AFB20038 */  sw    $s2, 0x38($sp)
/* 01BA84 7001AE84 AFB10034 */  sw    $s1, 0x34($sp)
/* 01BA88 7001AE88 AFB00030 */  sw    $s0, 0x30($sp)
/* 01BA8C 7001AE8C F7B60028 */  sdc1  $f22, 0x28($sp)
/* 01BA90 7001AE90 F7B40020 */  sdc1  $f20, 0x20($sp)
/* 01BA94 7001AE94 AFA500DC */  sw    $a1, 0xdc($sp)
/* 01BA98 7001AE98 AFA600E0 */  sw    $a2, 0xe0($sp)
/* 01BA9C 7001AE9C AFA700E4 */  sw    $a3, 0xe4($sp)
/* 01BAA0 7001AEA0 AFA400D0 */  sw    $a0, 0xd0($sp)
/* 01BAA4 7001AEA4 AFA700C4 */  sw    $a3, 0xc4($sp)
/* 01BAA8 7001AEA8 A7A000BE */  sh    $zero, 0xbe($sp)
/* 01BAAC 7001AEAC A7A000CE */  sh    $zero, 0xce($sp)
/* 01BAB0 7001AEB0 AFAE00D4 */  sw    $t6, 0xd4($sp)
/* 01BAB4 7001AEB4 8C98003C */  lw    $t8, 0x3c($a0)
/* 01BAB8 7001AEB8 0080B825 */  move  $s7, $a0
/* 01BABC 7001AEBC 3C013FC0 */  li    $at, 0x3FC00000 # 1.500000
/* 01BAC0 7001AEC0 53000162 */  beql  $t8, $zero, .L7001B44C
/* 01BAC4 7001AEC4 8EEE0048 */   lw    $t6, 0x48($s7)
/* 01BAC8 7001AEC8 4481B800 */  mtc1  $at, $f23
/* 01BACC 7001AECC 3C0140F0 */  li    $at, 0x40F00000 # 7.500000
/* 01BAD0 7001AED0 4481A800 */  mtc1  $at, $f21
/* 01BAD4 7001AED4 4480B000 */  mtc1  $zero, $f22
/* 01BAD8 7001AED8 4480A000 */  mtc1  $zero, $f20
/* 01BADC 7001AEDC 24110001 */  li    $s1, 1
/* 01BAE0 7001AEE0 8EF9003C */  lw    $t9, 0x3c($s7)
.L7001AEE4:
/* 01BAE4 7001AEE4 8FA200C4 */  lw    $v0, 0xc4($sp)
/* 01BAE8 7001AEE8 8FB800E0 */  lw    $t8, 0xe0($sp)
/* 01BAEC 7001AEEC 8F2E0004 */  lw    $t6, 4($t9)
/* 01BAF0 7001AEF0 3C048003 */  lui   $a0, %hi(aAssertionFaultSSLineD)
/* 01BAF4 7001AEF4 24849890 */  addiu $a0, %lo(aAssertionFaultSSLineD) # addiu $a0, $a0, -0x6770
/* 01BAF8 7001AEF8 01C2F023 */  subu  $fp, $t6, $v0
/* 01BAFC 7001AEFC 031E082A */  slt   $at, $t8, $fp
/* 01BB00 7001AF00 14200151 */  bnez  $at, .L7001B448
/* 01BB04 7001AF04 AFAE00C4 */   sw    $t6, 0xc4($sp)
/* 01BB08 7001AF08 07C10006 */  bgez  $fp, .L7001AF24
/* 01BB0C 7001AF0C 3C058003 */   lui   $a1, %hi(aSamples0)
/* 01BB10 7001AF10 3C068003 */  lui   $a2, %hi(aEnv_c)
/* 01BB14 7001AF14 24C698CC */  addiu $a2, %lo(aEnv_c) # addiu $a2, $a2, -0x6734
/* 01BB18 7001AF18 24A598BC */  addiu $a1, %lo(aSamples0) # addiu $a1, $a1, -0x6744
/* 01BB1C 7001AF1C 0C0033D1 */  jal   osSyncPrintf
/* 01BB20 7001AF20 24070068 */   li    $a3, 104
.L7001AF24:
/* 01BB24 7001AF24 2BC100A1 */  slti  $at, $fp, 0xa1
/* 01BB28 7001AF28 14200008 */  bnez  $at, .L7001AF4C
/* 01BB2C 7001AF2C 3C048003 */   lui   $a0, %hi(aAssertionFaultSSLineD_0)
/* 01BB30 7001AF30 3C058003 */  lui   $a1, %hi(aSamplesAl_max_rsp_samples)
/* 01BB34 7001AF34 3C068003 */  lui   $a2, %hi(aEnv_c_0)
/* 01BB38 7001AF38 24C69920 */  addiu $a2, %lo(aEnv_c_0) # addiu $a2, $a2, -0x66e0
/* 01BB3C 7001AF3C 24A59900 */  addiu $a1, %lo(aSamplesAl_max_rsp_samples) # addiu $a1, $a1, -0x6700
/* 01BB40 7001AF40 248498D4 */  addiu $a0, %lo(aAssertionFaultSSLineD_0) # addiu $a0, $a0, -0x672c
/* 01BB44 7001AF44 0C0033D1 */  jal   osSyncPrintf
/* 01BB48 7001AF48 24070069 */   li    $a3, 105
.L7001AF4C:
/* 01BB4C 7001AF4C 8EE3003C */  lw    $v1, 0x3c($s7)
/* 01BB50 7001AF50 94790008 */  lhu   $t9, 8($v1)
/* 01BB54 7001AF54 2F210011 */  sltiu $at, $t9, 0x11
/* 01BB58 7001AF58 10200117 */  beqz  $at, .L7001B3B8
/* 01BB5C 7001AF5C 0019C880 */   sll   $t9, $t9, 2
/* 01BB60 7001AF60 3C018003 */  lui   $at, %hi(jpt_80029968)
/* 01BB64 7001AF64 00390821 */  addu  $at, $at, $t9
/* 01BB68 7001AF68 8C399968 */  lw    $t9, %lo(jpt_80029968)($at)
/* 01BB6C 7001AF6C 03200008 */  jr    $t9
/* 01BB70 7001AF70 00000000 */   nop   
.L7001AF74:
/* 01BB74 7001AF74 846E000A */  lh    $t6, 0xa($v1)
/* 01BB78 7001AF78 00608025 */  move  $s0, $v1
/* 01BB7C 7001AF7C 51C00007 */  beql  $t6, $zero, .L7001AF9C
/* 01BB80 7001AF80 8EF90008 */   lw    $t9, 8($s7)
/* 01BB84 7001AF84 8EF90008 */  lw    $t9, 8($s7)
/* 01BB88 7001AF88 02E02025 */  move  $a0, $s7
/* 01BB8C 7001AF8C 24050008 */  li    $a1, 8
/* 01BB90 7001AF90 0320F809 */  jalr  $t9
/* 01BB94 7001AF94 00003025 */  move  $a2, $zero
/* 01BB98 7001AF98 8EF90008 */  lw    $t9, 8($s7)
.L7001AF9C:
/* 01BB9C 7001AF9C 02E02025 */  move  $a0, $s7
/* 01BBA0 7001AFA0 24050005 */  li    $a1, 5
/* 01BBA4 7001AFA4 0320F809 */  jalr  $t9
/* 01BBA8 7001AFA8 8E060018 */  lw    $a2, 0x18($s0)
/* 01BBAC 7001AFAC 8EF90008 */  lw    $t9, 8($s7)
/* 01BBB0 7001AFB0 02E02025 */  move  $a0, $s7
/* 01BBB4 7001AFB4 24050009 */  li    $a1, 9
/* 01BBB8 7001AFB8 0320F809 */  jalr  $t9
/* 01BBBC 7001AFBC 00003025 */  move  $a2, $zero
/* 01BBC0 7001AFC0 AEF10038 */  sw    $s1, 0x38($s7)
/* 01BBC4 7001AFC4 AEE00030 */  sw    $zero, 0x30($s7)
/* 01BBC8 7001AFC8 8E0F0014 */  lw    $t7, 0x14($s0)
/* 01BBCC 7001AFCC AEEF0034 */  sw    $t7, 0x34($s7)
/* 01BBD0 7001AFD0 86030010 */  lh    $v1, 0x10($s0)
/* 01BBD4 7001AFD4 00630019 */  multu $v1, $v1
/* 01BBD8 7001AFD8 00002012 */  mflo  $a0
/* 01BBDC 7001AFDC 0004C3C3 */  sra   $t8, $a0, 0xf
/* 01BBE0 7001AFE0 A6F8001A */  sh    $t8, 0x1a($s7)
/* 01BBE4 7001AFE4 920E0012 */  lbu   $t6, 0x12($s0)
/* 01BBE8 7001AFE8 3C188003 */  lui   $t8, %hi(eqpower)
/* 01BBEC 7001AFEC A6EE0018 */  sh    $t6, 0x18($s7)
/* 01BBF0 7001AFF0 92190013 */  lbu   $t9, 0x13($s0)
/* 01BBF4 7001AFF4 00197840 */  sll   $t7, $t9, 1
/* 01BBF8 7001AFF8 030FC021 */  addu  $t8, $t8, $t7
/* 01BBFC 7001AFFC 871881E0 */  lh    $t8, %lo(eqpower)($t8)
/* 01BC00 7001B000 A6F80020 */  sh    $t8, 0x20($s7)
/* 01BC04 7001B004 920E0013 */  lbu   $t6, 0x13($s0)
/* 01BC08 7001B008 3C188003 */  lui   $t8, %hi(eqpower+0xFE)
/* 01BC0C 7001B00C 000EC840 */  sll   $t9, $t6, 1
/* 01BC10 7001B010 00197823 */  negu  $t7, $t9
/* 01BC14 7001B014 030FC021 */  addu  $t8, $t8, $t7
/* 01BC18 7001B018 871882DE */  lh    $t8, %lo(eqpower+0xFE)($t8)
/* 01BC1C 7001B01C A6F80022 */  sh    $t8, 0x22($s7)
/* 01BC20 7001B020 8E0E0014 */  lw    $t6, 0x14($s0)
/* 01BC24 7001B024 51C00005 */  beql  $t6, $zero, .L7001B03C
/* 01BC28 7001B028 86E20018 */   lh    $v0, 0x18($s7)
/* 01BC2C 7001B02C A6F1001C */  sh    $s1, 0x1c($s7)
/* 01BC30 7001B030 10000013 */  b     .L7001B080
/* 01BC34 7001B034 A6F1001E */   sh    $s1, 0x1e($s7)
/* 01BC38 7001B038 86E20018 */  lh    $v0, 0x18($s7)
.L7001B03C:
/* 01BC3C 7001B03C 3C0F8003 */  lui   $t7, %hi(eqpower)
/* 01BC40 7001B040 86E3001A */  lh    $v1, 0x1a($s7)
/* 01BC44 7001B044 0002C840 */  sll   $t9, $v0, 1
/* 01BC48 7001B048 01F97821 */  addu  $t7, $t7, $t9
/* 01BC4C 7001B04C 85EF81E0 */  lh    $t7, %lo(eqpower)($t7)
/* 01BC50 7001B050 0019C823 */  negu  $t9, $t9
/* 01BC54 7001B054 01E30019 */  multu $t7, $v1
/* 01BC58 7001B058 3C0F8003 */  lui   $t7, %hi(eqpower+0xFE)
/* 01BC5C 7001B05C 01F97821 */  addu  $t7, $t7, $t9
/* 01BC60 7001B060 0000C012 */  mflo  $t8
/* 01BC64 7001B064 001873C3 */  sra   $t6, $t8, 0xf
/* 01BC68 7001B068 A6EE001C */  sh    $t6, 0x1c($s7)
/* 01BC6C 7001B06C 85EF82DE */  lh    $t7, %lo(eqpower+0xFE)($t7)
/* 01BC70 7001B070 01E30019 */  multu $t7, $v1
/* 01BC74 7001B074 0000C012 */  mflo  $t8
/* 01BC78 7001B078 001873C3 */  sra   $t6, $t8, 0xf
/* 01BC7C 7001B07C A6EE001E */  sh    $t6, 0x1e($s7)
.L7001B080:
/* 01BC80 7001B080 8EF90000 */  lw    $t9, ($s7)
/* 01BC84 7001B084 532000DF */  beql  $t9, $zero, .L7001B404
/* 01BC88 7001B088 87B800BE */   lh    $t8, 0xbe($sp)
/* 01BC8C 7001B08C C604000C */  lwc1  $f4, 0xc($s0)
/* 01BC90 7001B090 24050007 */  li    $a1, 7
/* 01BC94 7001B094 E7A400A4 */  swc1  $f4, 0xa4($sp)
/* 01BC98 7001B098 8EE40000 */  lw    $a0, ($s7)
/* 01BC9C 7001B09C 8FA600A4 */  lw    $a2, 0xa4($sp)
/* 01BCA0 7001B0A0 8C990008 */  lw    $t9, 8($a0)
/* 01BCA4 7001B0A4 0320F809 */  jalr  $t9
/* 01BCA8 7001B0A8 00000000 */  nop   
/* 01BCAC 7001B0AC 100000D5 */  b     .L7001B404
/* 01BCB0 7001B0B0 87B800BE */   lh    $t8, 0xbe($sp)
.L7001B0B4:
/* 01BCB4 7001B0B4 02E08025 */  move  $s0, $s7
/* 01BCB8 7001B0B8 27B500CE */  addiu $s5, $sp, 0xce
/* 01BCBC 7001B0BC 27B300BE */  addiu $s3, $sp, 0xbe
/* 01BCC0 7001B0C0 03C09025 */  move  $s2, $fp
/* 01BCC4 7001B0C4 8FB600E4 */  lw    $s6, 0xe4($sp)
/* 01BCC8 7001B0C8 0C006AED */  jal   ultra_7001ABB4
/* 01BCCC 7001B0CC 8FB400D4 */   lw    $s4, 0xd4($sp)
/* 01BCD0 7001B0D0 AFA200D4 */  sw    $v0, 0xd4($sp)
/* 01BCD4 7001B0D4 8EEF0030 */  lw    $t7, 0x30($s7)
/* 01BCD8 7001B0D8 8EE40034 */  lw    $a0, 0x34($s7)
/* 01BCDC 7001B0DC 24110001 */  li    $s1, 1
/* 01BCE0 7001B0E0 01FE2821 */  addu  $a1, $t7, $fp
/* 01BCE4 7001B0E4 00A4082A */  slt   $at, $a1, $a0
/* 01BCE8 7001B0E8 14200019 */  bnez  $at, .L7001B150
/* 01BCEC 7001B0EC AEE50030 */   sw    $a1, 0x30($s7)
/* 01BCF0 7001B0F0 86E20018 */  lh    $v0, 0x18($s7)
/* 01BCF4 7001B0F4 3C198003 */  lui   $t9, %hi(eqpower)
/* 01BCF8 7001B0F8 86E3001A */  lh    $v1, 0x1a($s7)
/* 01BCFC 7001B0FC 00027040 */  sll   $t6, $v0, 1
/* 01BD00 7001B100 032EC821 */  addu  $t9, $t9, $t6
/* 01BD04 7001B104 873981E0 */  lh    $t9, %lo(eqpower)($t9)
/* 01BD08 7001B108 000E7023 */  negu  $t6, $t6
/* 01BD0C 7001B10C 03230019 */  multu $t9, $v1
/* 01BD10 7001B110 3C198003 */  lui   $t9, %hi(eqpower+0xFE)
/* 01BD14 7001B114 032EC821 */  addu  $t9, $t9, $t6
/* 01BD18 7001B118 00007812 */  mflo  $t7
/* 01BD1C 7001B11C 000FC3C3 */  sra   $t8, $t7, 0xf
/* 01BD20 7001B120 A6F80028 */  sh    $t8, 0x28($s7)
/* 01BD24 7001B124 873982DE */  lh    $t9, %lo(eqpower+0xFE)($t9)
/* 01BD28 7001B128 86EE0028 */  lh    $t6, 0x28($s7)
/* 01BD2C 7001B12C AEE40030 */  sw    $a0, 0x30($s7)
/* 01BD30 7001B130 03230019 */  multu $t9, $v1
/* 01BD34 7001B134 A6EE001C */  sh    $t6, 0x1c($s7)
/* 01BD38 7001B138 00007812 */  mflo  $t7
/* 01BD3C 7001B13C 000FC3C3 */  sra   $t8, $t7, 0xf
/* 01BD40 7001B140 A6F8002E */  sh    $t8, 0x2e($s7)
/* 01BD44 7001B144 86F9002E */  lh    $t9, 0x2e($s7)
/* 01BD48 7001B148 10000040 */  b     .L7001B24C
/* 01BD4C 7001B14C A6F9001E */   sh    $t9, 0x1e($s7)
.L7001B150:
/* 01BD50 7001B150 86EF001C */  lh    $t7, 0x1c($s7)
/* 01BD54 7001B154 86E30026 */  lh    $v1, 0x26($s7)
/* 01BD58 7001B158 96E40024 */  lhu   $a0, 0x24($s7)
/* 01BD5C 7001B15C 448F3000 */  mtc1  $t7, $f6
/* 01BD60 7001B160 0003C400 */  sll   $t8, $v1, 0x10
/* 01BD64 7001B164 44984000 */  mtc1  $t8, $f8
/* 01BD68 7001B168 44842000 */  mtc1  $a0, $f4
/* 01BD6C 7001B16C 46803320 */  cvt.s.w $f12, $f6
/* 01BD70 7001B170 00A01025 */  move  $v0, $a1
/* 01BD74 7001B174 3C014F80 */  li    $at, 0x4F800000 # 4294967296.000000
/* 01BD78 7001B178 468042A0 */  cvt.s.w $f10, $f8
/* 01BD7C 7001B17C 04810004 */  bgez  $a0, .L7001B190
/* 01BD80 7001B180 468021A0 */   cvt.s.w $f6, $f4
/* 01BD84 7001B184 44814000 */  mtc1  $at, $f8
/* 01BD88 7001B188 00000000 */  nop   
/* 01BD8C 7001B18C 46083180 */  add.s $f6, $f6, $f8
.L7001B190:
/* 01BD90 7001B190 46065100 */  add.s $f4, $f10, $f6
/* 01BD94 7001B194 86EF001E */  lh    $t7, 0x1e($s7)
/* 01BD98 7001B198 86E3002C */  lh    $v1, 0x2c($s7)
/* 01BD9C 7001B19C 96E4002A */  lhu   $a0, 0x2a($s7)
/* 01BDA0 7001B1A0 46002221 */  cvt.d.s $f8, $f4
/* 01BDA4 7001B1A4 44822000 */  mtc1  $v0, $f4
/* 01BDA8 7001B1A8 46344283 */  div.d $f10, $f8, $f20
/* 01BDAC 7001B1AC 0003C400 */  sll   $t8, $v1, 0x10
/* 01BDB0 7001B1B0 00A01025 */  move  $v0, $a1
/* 01BDB4 7001B1B4 3C014F80 */  li    $at, 0x4F800000 # 4294967296.000000
/* 01BDB8 7001B1B8 46802220 */  cvt.s.w $f8, $f4
/* 01BDBC 7001B1BC 462051A0 */  cvt.s.d $f6, $f10
/* 01BDC0 7001B1C0 46083282 */  mul.s $f10, $f6, $f8
/* 01BDC4 7001B1C4 46006221 */  cvt.d.s $f8, $f12
/* 01BDC8 7001B1C8 46005121 */  cvt.d.s $f4, $f10
/* 01BDCC 7001B1CC 46362182 */  mul.d $f6, $f4, $f22
/* 01BDD0 7001B1D0 46264280 */  add.d $f10, $f8, $f6
/* 01BDD4 7001B1D4 448F4000 */  mtc1  $t7, $f8
/* 01BDD8 7001B1D8 44983000 */  mtc1  $t8, $f6
/* 01BDDC 7001B1DC 46205320 */  cvt.s.d $f12, $f10
/* 01BDE0 7001B1E0 468040A0 */  cvt.s.w $f2, $f8
/* 01BDE4 7001B1E4 4600610D */  trunc.w.s $f4, $f12
/* 01BDE8 7001B1E8 468032A0 */  cvt.s.w $f10, $f6
/* 01BDEC 7001B1EC 44192000 */  mfc1  $t9, $f4
/* 01BDF0 7001B1F0 44842000 */  mtc1  $a0, $f4
/* 01BDF4 7001B1F4 A6F9001C */  sh    $t9, 0x1c($s7)
/* 01BDF8 7001B1F8 04810004 */  bgez  $a0, .L7001B20C
/* 01BDFC 7001B1FC 46802220 */   cvt.s.w $f8, $f4
/* 01BE00 7001B200 44813000 */  mtc1  $at, $f6
/* 01BE04 7001B204 00000000 */  nop   
/* 01BE08 7001B208 46064200 */  add.s $f8, $f8, $f6
.L7001B20C:
/* 01BE0C 7001B20C 46085100 */  add.s $f4, $f10, $f8
/* 01BE10 7001B210 460021A1 */  cvt.d.s $f6, $f4
/* 01BE14 7001B214 44822000 */  mtc1  $v0, $f4
/* 01BE18 7001B218 46343283 */  div.d $f10, $f6, $f20
/* 01BE1C 7001B21C 468021A0 */  cvt.s.w $f6, $f4
/* 01BE20 7001B220 46205220 */  cvt.s.d $f8, $f10
/* 01BE24 7001B224 46064282 */  mul.s $f10, $f8, $f6
/* 01BE28 7001B228 460011A1 */  cvt.d.s $f6, $f2
/* 01BE2C 7001B22C 46005121 */  cvt.d.s $f4, $f10
/* 01BE30 7001B230 46362202 */  mul.d $f8, $f4, $f22
/* 01BE34 7001B234 46283280 */  add.d $f10, $f6, $f8
/* 01BE38 7001B238 462050A0 */  cvt.s.d $f2, $f10
/* 01BE3C 7001B23C 4600110D */  trunc.w.s $f4, $f2
/* 01BE40 7001B240 44192000 */  mfc1  $t9, $f4
/* 01BE44 7001B244 00000000 */  nop   
/* 01BE48 7001B248 A6F9001E */  sh    $t9, 0x1e($s7)
.L7001B24C:
/* 01BE4C 7001B24C 86EF001C */  lh    $t7, 0x1c($s7)
/* 01BE50 7001B250 55E00003 */  bnezl $t7, .L7001B260
/* 01BE54 7001B254 86F8001E */   lh    $t8, 0x1e($s7)
/* 01BE58 7001B258 A6F1001C */  sh    $s1, 0x1c($s7)
/* 01BE5C 7001B25C 86F8001E */  lh    $t8, 0x1e($s7)
.L7001B260:
/* 01BE60 7001B260 57000003 */  bnezl $t8, .L7001B270
/* 01BE64 7001B264 8EE3003C */   lw    $v1, 0x3c($s7)
/* 01BE68 7001B268 A6F1001E */  sh    $s1, 0x1e($s7)
/* 01BE6C 7001B26C 8EE3003C */  lw    $v1, 0x3c($s7)
.L7001B270:
/* 01BE70 7001B270 2401000C */  li    $at, 12
/* 01BE74 7001B274 84640008 */  lh    $a0, 8($v1)
/* 01BE78 7001B278 54810005 */  bnel  $a0, $at, .L7001B290
/* 01BE7C 7001B27C 2401000B */   li    $at, 11
/* 01BE80 7001B280 8C6E000C */  lw    $t6, 0xc($v1)
/* 01BE84 7001B284 A6EE0018 */  sh    $t6, 0x18($s7)
/* 01BE88 7001B288 84640008 */  lh    $a0, 8($v1)
/* 01BE8C 7001B28C 2401000B */  li    $at, 11
.L7001B290:
/* 01BE90 7001B290 5481000B */  bnel  $a0, $at, .L7001B2C0
/* 01BE94 7001B294 24010010 */   li    $at, 16
/* 01BE98 7001B298 AEE00030 */  sw    $zero, 0x30($s7)
/* 01BE9C 7001B29C 8C62000C */  lw    $v0, 0xc($v1)
/* 01BEA0 7001B2A0 00420019 */  multu $v0, $v0
/* 01BEA4 7001B2A4 00001012 */  mflo  $v0
/* 01BEA8 7001B2A8 0002CBC3 */  sra   $t9, $v0, 0xf
/* 01BEAC 7001B2AC A6F9001A */  sh    $t9, 0x1a($s7)
/* 01BEB0 7001B2B0 8C6F0010 */  lw    $t7, 0x10($v1)
/* 01BEB4 7001B2B4 AEEF0034 */  sw    $t7, 0x34($s7)
/* 01BEB8 7001B2B8 84640008 */  lh    $a0, 8($v1)
/* 01BEBC 7001B2BC 24010010 */  li    $at, 16
.L7001B2C0:
/* 01BEC0 7001B2C0 1481000E */  bne   $a0, $at, .L7001B2FC
/* 01BEC4 7001B2C4 00000000 */   nop   
/* 01BEC8 7001B2C8 8C78000C */  lw    $t8, 0xc($v1)
/* 01BECC 7001B2CC 3C198003 */  lui   $t9, %hi(eqpower)
/* 01BED0 7001B2D0 00187040 */  sll   $t6, $t8, 1
/* 01BED4 7001B2D4 032EC821 */  addu  $t9, $t9, $t6
/* 01BED8 7001B2D8 873981E0 */  lh    $t9, %lo(eqpower)($t9)
/* 01BEDC 7001B2DC A6F90020 */  sh    $t9, 0x20($s7)
/* 01BEE0 7001B2E0 8C6F000C */  lw    $t7, 0xc($v1)
/* 01BEE4 7001B2E4 3C198003 */  lui   $t9, %hi(eqpower+0xFE)
/* 01BEE8 7001B2E8 000FC040 */  sll   $t8, $t7, 1
/* 01BEEC 7001B2EC 00187023 */  negu  $t6, $t8
/* 01BEF0 7001B2F0 032EC821 */  addu  $t9, $t9, $t6
/* 01BEF4 7001B2F4 873982DE */  lh    $t9, %lo(eqpower+0xFE)($t9)
/* 01BEF8 7001B2F8 A6F90022 */  sh    $t9, 0x22($s7)
.L7001B2FC:
/* 01BEFC 7001B2FC 10000040 */  b     .L7001B400
/* 01BF00 7001B300 AEF10038 */   sw    $s1, 0x38($s7)
.L7001B304:
/* 01BF04 7001B304 846F000A */  lh    $t7, 0xa($v1)
/* 01BF08 7001B308 00608025 */  move  $s0, $v1
/* 01BF0C 7001B30C 51E00007 */  beql  $t7, $zero, .L7001B32C
/* 01BF10 7001B310 8EF90008 */   lw    $t9, 8($s7)
/* 01BF14 7001B314 8EF90008 */  lw    $t9, 8($s7)
/* 01BF18 7001B318 02E02025 */  move  $a0, $s7
/* 01BF1C 7001B31C 24050008 */  li    $a1, 8
/* 01BF20 7001B320 0320F809 */  jalr  $t9
/* 01BF24 7001B324 00003025 */  move  $a2, $zero
/* 01BF28 7001B328 8EF90008 */  lw    $t9, 8($s7)
.L7001B32C:
/* 01BF2C 7001B32C 02E02025 */  move  $a0, $s7
/* 01BF30 7001B330 24050005 */  li    $a1, 5
/* 01BF34 7001B334 0320F809 */  jalr  $t9
/* 01BF38 7001B338 8E06000C */  lw    $a2, 0xc($s0)
/* 01BF3C 7001B33C 8EF90008 */  lw    $t9, 8($s7)
/* 01BF40 7001B340 02E02025 */  move  $a0, $s7
/* 01BF44 7001B344 24050009 */  li    $a1, 9
/* 01BF48 7001B348 0320F809 */  jalr  $t9
/* 01BF4C 7001B34C 00003025 */  move  $a2, $zero
/* 01BF50 7001B350 1000002C */  b     .L7001B404
/* 01BF54 7001B354 87B800BE */   lh    $t8, 0xbe($sp)
.L7001B358:
/* 01BF58 7001B358 02E08025 */  move  $s0, $s7
/* 01BF5C 7001B35C 27B500CE */  addiu $s5, $sp, 0xce
/* 01BF60 7001B360 27B300BE */  addiu $s3, $sp, 0xbe
/* 01BF64 7001B364 03C09025 */  move  $s2, $fp
/* 01BF68 7001B368 8FB600E4 */  lw    $s6, 0xe4($sp)
/* 01BF6C 7001B36C 0C006AED */  jal   ultra_7001ABB4
/* 01BF70 7001B370 8FB400D4 */   lw    $s4, 0xd4($sp)
/* 01BF74 7001B374 AFA200D4 */  sw    $v0, 0xd4($sp)
/* 01BF78 7001B378 8EF90008 */  lw    $t9, 8($s7)
/* 01BF7C 7001B37C 24110001 */  li    $s1, 1
/* 01BF80 7001B380 02E02025 */  move  $a0, $s7
/* 01BF84 7001B384 24050004 */  li    $a1, 4
/* 01BF88 7001B388 0320F809 */  jalr  $t9
/* 01BF8C 7001B38C 00003025 */  move  $a2, $zero
/* 01BF90 7001B390 1000001C */  b     .L7001B404
/* 01BF94 7001B394 87B800BE */   lh    $t8, 0xbe($sp)
.L7001B398:
/* 01BF98 7001B398 8C78000C */  lw    $t8, 0xc($v1)
/* 01BF9C 7001B39C 3C048002 */  lui   $a0, %hi(alGlobals)
/* 01BFA0 7001B3A0 8C8476E0 */  lw    $a0, %lo(alGlobals)($a0)
/* 01BFA4 7001B3A4 AF0000D8 */  sw    $zero, 0xd8($t8)
/* 01BFA8 7001B3A8 0C003C08 */  jal   _freePVoice
/* 01BFAC 7001B3AC 8C65000C */   lw    $a1, 0xc($v1)
/* 01BFB0 7001B3B0 10000014 */  b     .L7001B404
/* 01BFB4 7001B3B4 87B800BE */   lh    $t8, 0xbe($sp)
.L7001B3B8:
/* 01BFB8 7001B3B8 02E08025 */  move  $s0, $s7
/* 01BFBC 7001B3BC 27B500CE */  addiu $s5, $sp, 0xce
/* 01BFC0 7001B3C0 27B300BE */  addiu $s3, $sp, 0xbe
/* 01BFC4 7001B3C4 03C09025 */  move  $s2, $fp
/* 01BFC8 7001B3C8 8FB600E4 */  lw    $s6, 0xe4($sp)
/* 01BFCC 7001B3CC 0C006AED */  jal   ultra_7001ABB4
/* 01BFD0 7001B3D0 8FB400D4 */   lw    $s4, 0xd4($sp)
/* 01BFD4 7001B3D4 AFA200D4 */  sw    $v0, 0xd4($sp)
/* 01BFD8 7001B3D8 8EEE0030 */  lw    $t6, 0x30($s7)
/* 01BFDC 7001B3DC 8EF90008 */  lw    $t9, 8($s7)
/* 01BFE0 7001B3E0 8EE3003C */  lw    $v1, 0x3c($s7)
/* 01BFE4 7001B3E4 01DE7821 */  addu  $t7, $t6, $fp
/* 01BFE8 7001B3E8 AEEF0030 */  sw    $t7, 0x30($s7)
/* 01BFEC 7001B3EC 24110001 */  li    $s1, 1
/* 01BFF0 7001B3F0 02E02025 */  move  $a0, $s7
/* 01BFF4 7001B3F4 8C66000C */  lw    $a2, 0xc($v1)
/* 01BFF8 7001B3F8 0320F809 */  jalr  $t9
/* 01BFFC 7001B3FC 84650008 */  lh    $a1, 8($v1)
.L7001B400:
/* 01C000 7001B400 87B800BE */  lh    $t8, 0xbe($sp)
.L7001B404:
/* 01C004 7001B404 8FB900E0 */  lw    $t9, 0xe0($sp)
/* 01C008 7001B408 001E7040 */  sll   $t6, $fp, 1
/* 01C00C 7001B40C 030E7821 */  addu  $t7, $t8, $t6
/* 01C010 7001B410 033EC023 */  subu  $t8, $t9, $fp
/* 01C014 7001B414 A7AF00BE */  sh    $t7, 0xbe($sp)
/* 01C018 7001B418 AFB800E0 */  sw    $t8, 0xe0($sp)
/* 01C01C 7001B41C 8EE4003C */  lw    $a0, 0x3c($s7)
/* 01C020 7001B420 8C8E0000 */  lw    $t6, ($a0)
/* 01C024 7001B424 15C00002 */  bnez  $t6, .L7001B430
/* 01C028 7001B428 AEEE003C */   sw    $t6, 0x3c($s7)
/* 01C02C 7001B42C AEE00040 */  sw    $zero, 0x40($s7)
.L7001B430:
/* 01C030 7001B430 0C003C2E */  jal   __freeParam
/* 01C034 7001B434 00000000 */   nop   
/* 01C038 7001B438 8FB900D0 */  lw    $t9, 0xd0($sp)
/* 01C03C 7001B43C 8F38003C */  lw    $t8, 0x3c($t9)
/* 01C040 7001B440 5700FEA8 */  bnezl $t8, .L7001AEE4
/* 01C044 7001B444 8EF9003C */   lw    $t9, 0x3c($s7)
.L7001B448:
/* 01C048 7001B448 8EEE0048 */  lw    $t6, 0x48($s7)
.L7001B44C:
/* 01C04C 7001B44C 24110001 */  li    $s1, 1
/* 01C050 7001B450 02E08025 */  move  $s0, $s7
/* 01C054 7001B454 162E000B */  bne   $s1, $t6, .L7001B484
/* 01C058 7001B458 27B500CE */   addiu $s5, $sp, 0xce
/* 01C05C 7001B45C 27B300BE */  addiu $s3, $sp, 0xbe
/* 01C060 7001B460 8FB200E0 */  lw    $s2, 0xe0($sp)
/* 01C064 7001B464 8FB600E4 */  lw    $s6, 0xe4($sp)
/* 01C068 7001B468 0C006AED */  jal   ultra_7001ABB4
/* 01C06C 7001B46C 8FB400D4 */   lw    $s4, 0xd4($sp)
/* 01C070 7001B470 AFA200D4 */  sw    $v0, 0xd4($sp)
/* 01C074 7001B474 8EEF0030 */  lw    $t7, 0x30($s7)
/* 01C078 7001B478 8FB900E0 */  lw    $t9, 0xe0($sp)
/* 01C07C 7001B47C 01F9C021 */  addu  $t8, $t7, $t9
/* 01C080 7001B480 AEF80030 */  sw    $t8, 0x30($s7)
.L7001B484:
/* 01C084 7001B484 8EE40034 */  lw    $a0, 0x34($s7)
/* 01C088 7001B488 8EEE0030 */  lw    $t6, 0x30($s7)
/* 01C08C 7001B48C 008E082A */  slt   $at, $a0, $t6
/* 01C090 7001B490 50200003 */  beql  $at, $zero, .L7001B4A0
/* 01C094 7001B494 8FBF0054 */   lw    $ra, 0x54($sp)
/* 01C098 7001B498 AEE40030 */  sw    $a0, 0x30($s7)
/* 01C09C 7001B49C 8FBF0054 */  lw    $ra, 0x54($sp)
.L7001B4A0:
/* 01C0A0 7001B4A0 8FA200D4 */  lw    $v0, 0xd4($sp)
/* 01C0A4 7001B4A4 D7B40020 */  ldc1  $f20, 0x20($sp)
/* 01C0A8 7001B4A8 D7B60028 */  ldc1  $f22, 0x28($sp)
/* 01C0AC 7001B4AC 8FB00030 */  lw    $s0, 0x30($sp)
/* 01C0B0 7001B4B0 8FB10034 */  lw    $s1, 0x34($sp)
/* 01C0B4 7001B4B4 8FB20038 */  lw    $s2, 0x38($sp)
/* 01C0B8 7001B4B8 8FB3003C */  lw    $s3, 0x3c($sp)
/* 01C0BC 7001B4BC 8FB40040 */  lw    $s4, 0x40($sp)
/* 01C0C0 7001B4C0 8FB50044 */  lw    $s5, 0x44($sp)
/* 01C0C4 7001B4C4 8FB60048 */  lw    $s6, 0x48($sp)
/* 01C0C8 7001B4C8 8FB7004C */  lw    $s7, 0x4c($sp)
/* 01C0CC 7001B4CC 8FBE0050 */  lw    $fp, 0x50($sp)
/* 01C0D0 7001B4D0 03E00008 */  jr    $ra
/* 01C0D4 7001B4D4 27BD00D8 */   addiu $sp, $sp, 0xd8
.size alEnvmixerPull, . - alEnvmixerPull
/* 01C0D8 7001B4D8 00000000 */  nop   
/* 01C0DC 7001B4DC 00000000 */  nop

.section .data
glabel eqpower
.half 32767,32764,32757,32744,32727,32704,32677,32644
.half 32607,32564,32517,32464,32407,32344,32277,32205
.half 32127,32045,31958,31866,31770,31668,31561,31450
.half 31334,31213,31087,30957,30822,30682,30537,30388
.half 30234,30075,29912,29744,29572,29395,29214,29028
.half 28838,28643,28444,28241,28033,27821,27605,27385
.half 27160,26931,26698,26461,26220,25975,25726,25473
.half 25216,24956,24691,24423,24151,23875,23596,23313
.half 23026,22736,22442,22145,21845,21541,21234,20924
.half 20610,20294,19974,19651,19325,18997,18665,18331
.half 17993,17653,17310,16965,16617,16266,15913,15558
.half 15200,14840,14477,14113,13746,13377,13006,12633
.half 12258,11881,11503,11122,10740,10357, 9971, 9584
.half  9196, 8806, 8415, 8023, 7630, 7235, 6839, 6442
.half  6044, 5646, 5246, 4845, 4444, 4042, 3640, 3237
.half  2833, 2429, 2025, 1620, 1216,  810,  405,    0
.size eqpower, . - eqpower

.section .rodata
glabel aAssertionFaultSSLineD
.asciiz "\n--- ASSERTION FAULT - %s - %s, line %d\n\n"
.align 2
glabel aSamples0
.asciiz "samples >= 0"
.align 2
glabel aEnv_c
.asciiz "env.c"
.align 2
glabel aAssertionFaultSSLineD_0
.asciiz "\n--- ASSERTION FAULT - %s - %s, line %d\n\n"
.align 4
glabel aSamplesAl_max_rsp_samples
.asciiz "samples <= AL_MAX_RSP_SAMPLES"
.align 4
glabel aEnv_c_0
.asciiz "env.c"
.align 2
glabel aAssertionFaultSSLineD_1
.asciiz "\n--- ASSERTION FAULT - %s - %s, line %d\n\n"
.align 2
glabel aSource
.asciiz "source"
.align 2
glabel aEnv_c_1
.asciiz "env.c"
.align 2
glabel F32_80029964
.float 65535.0
glabel jpt_80029968
.word .L7001B398
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B3B8
.word .L7001B0B4
.word .L7001B0B4
.word .L7001AF74
.word .L7001B304
.word .L7001B358
.word .L7001B0B4
.align 4
