
 #include "ultra64.h"

extern u32 point_table_binary_1[];
extern u32 point_table_binary_2[];
extern u32 point_table_binary_3[];
extern u32 point_table_binary_4[];
extern u32 point_table_binary_5[];
extern u32 point_table_binary_6[];
extern u32 point_table_binary_7[];
extern u32 point_table_binary_8[];
extern u32 point_table_binary_9[];
extern u32 point_table_binary_10[];
extern u32 point_table_binary_11[];
extern u32 point_table_binary_12[];
extern u32 point_table_binary_13[];
extern u32 point_table_binary_14[];
extern u32 point_table_binary_15[];
extern u32 point_table_binary_16[];
extern u32 point_table_binary_17[];
extern u32 point_table_binary_18[];
extern u32 point_table_binary_19[];
extern u32 point_table_binary_20[];
extern u32 point_table_binary_21[];
extern u32 point_table_binary_22[];
extern u32 point_table_binary_23[];
extern u32 point_table_binary_24[];
extern u32 point_table_binary_25[];
extern u32 point_table_binary_26[];
extern u32 point_table_binary_27[];
extern u32 point_table_binary_28[];
extern u32 point_table_binary_29[];
extern u32 point_table_binary_30[];
extern u32 point_table_binary_31[];
extern u32 point_table_binary_32[];
extern u32 point_table_binary_33[];
extern u32 point_table_binary_34[];
extern u32 point_table_binary_35[];
extern u32 point_table_binary_36[];
extern u32 point_table_binary_37[];
extern u32 point_table_binary_38[];
extern u32 point_table_binary_39[];
extern u32 point_table_binary_40[];
extern u32 point_table_binary_41[];
extern u32 point_table_binary_42[];
extern u32 point_table_binary_43[];
extern u32 point_table_binary_44[];
extern u32 point_table_binary_45[];
extern u32 point_table_binary_46[];
extern u32 point_table_binary_47[];
extern u32 point_table_binary_48[];
extern u32 point_table_binary_49[];
extern u32 point_table_binary_50[];
extern u32 point_table_binary_51[];
extern u32 point_table_binary_52[];
extern u32 point_table_binary_53[];
extern u32 point_table_binary_54[];
extern u32 point_table_binary_55[];
extern u32 point_table_binary_56[];
extern u32 point_table_binary_57[];
extern u32 point_table_binary_58[];
extern u32 point_table_binary_59[];
extern u32 point_table_binary_60[];
extern u32 point_table_binary_61[];
extern u32 point_table_binary_62[];
extern u32 point_table_binary_63[];
extern u32 point_table_binary_64[];
extern u32 point_table_binary_65[];
extern u32 point_table_binary_66[];
extern u32 point_table_binary_67[];
extern u32 point_table_binary_68[];
extern u32 point_table_binary_69[];
extern u32 point_table_binary_70[];
extern u32 point_table_binary_71[];
extern u32 point_table_binary_72[];
extern u32 point_table_binary_73[];
extern u32 point_table_binary_74[];
extern u32 point_table_binary_75[];
extern u32 point_table_binary_76[];
extern u32 point_table_binary_77[];
extern u32 point_table_binary_78[];
extern u32 point_table_binary_79[];
extern u32 point_table_binary_80[];
extern u32 point_table_binary_81[];
extern u32 point_table_binary_82[];
extern u32 point_table_binary_83[];
extern u32 point_table_binary_84[];
extern u32 point_table_binary_85[];
extern u32 point_table_binary_86[];
extern u32 point_table_binary_87[];
extern u32 point_table_binary_88[];
extern u32 point_table_binary_89[];
extern u32 point_table_binary_90[];
extern u32 point_table_binary_91[];
extern u32 point_table_binary_92[];

extern u32 pri_mapping_binary_1[];
extern u32 sec_mapping_binary_1[];
extern u32 pri_mapping_binary_2[];
extern u32 sec_mapping_binary_2[];
extern u32 pri_mapping_binary_3[];
extern u32 sec_mapping_binary_3[];
extern u32 pri_mapping_binary_4[];
extern u32 sec_mapping_binary_4[];
extern u32 pri_mapping_binary_5[];
extern u32 sec_mapping_binary_5[];
extern u32 pri_mapping_binary_6[];
extern u32 sec_mapping_binary_6[];
extern u32 pri_mapping_binary_7[];
extern u32 sec_mapping_binary_7[];
extern u32 pri_mapping_binary_8[];
extern u32 sec_mapping_binary_8[];
extern u32 pri_mapping_binary_9[];
extern u32 sec_mapping_binary_9[];
extern u32 pri_mapping_binary_10[];
extern u32 sec_mapping_binary_10[];
extern u32 pri_mapping_binary_11[];
extern u32 sec_mapping_binary_11[];
extern u32 pri_mapping_binary_12[];
extern u32 sec_mapping_binary_12[];
extern u32 pri_mapping_binary_13[];
extern u32 sec_mapping_binary_13[];
extern u32 pri_mapping_binary_14[];
extern u32 sec_mapping_binary_14[];
extern u32 pri_mapping_binary_15[];
extern u32 sec_mapping_binary_15[];
extern u32 pri_mapping_binary_16[];
extern u32 sec_mapping_binary_16[];
extern u32 pri_mapping_binary_17[];
extern u32 sec_mapping_binary_17[];
extern u32 pri_mapping_binary_18[];
extern u32 sec_mapping_binary_18[];
extern u32 pri_mapping_binary_19[];
extern u32 sec_mapping_binary_19[];
extern u32 pri_mapping_binary_20[];
extern u32 pri_mapping_binary_21[];
extern u32 sec_mapping_binary_21[];
extern u32 pri_mapping_binary_22[];
extern u32 pri_mapping_binary_23[];
extern u32 sec_mapping_binary_23[];
extern u32 pri_mapping_binary_24[];
extern u32 sec_mapping_binary_24[];
extern u32 pri_mapping_binary_25[];
extern u32 sec_mapping_binary_25[];
extern u32 pri_mapping_binary_26[];
extern u32 sec_mapping_binary_26[];
extern u32 pri_mapping_binary_27[];
extern u32 sec_mapping_binary_27[];
extern u32 pri_mapping_binary_28[];
extern u32 sec_mapping_binary_28[];
extern u32 pri_mapping_binary_29[];
extern u32 sec_mapping_binary_29[];
extern u32 pri_mapping_binary_30[];
extern u32 sec_mapping_binary_30[];
extern u32 pri_mapping_binary_31[];
extern u32 sec_mapping_binary_31[];
extern u32 pri_mapping_binary_32[];
extern u32 sec_mapping_binary_32[];
extern u32 pri_mapping_binary_33[];
extern u32 pri_mapping_binary_34[];
extern u32 pri_mapping_binary_35[];
extern u32 sec_mapping_binary_35[];
extern u32 pri_mapping_binary_36[];
extern u32 pri_mapping_binary_37[];
extern u32 pri_mapping_binary_38[];
extern u32 pri_mapping_binary_39[];
extern u32 pri_mapping_binary_40[];
extern u32 pri_mapping_binary_41[];
extern u32 sec_mapping_binary_41[];
extern u32 pri_mapping_binary_42[];
extern u32 pri_mapping_binary_43[];
extern u32 sec_mapping_binary_43[];
extern u32 pri_mapping_binary_44[];
extern u32 pri_mapping_binary_45[];
extern u32 pri_mapping_binary_46[];
extern u32 pri_mapping_binary_47[];
extern u32 pri_mapping_binary_48[];
extern u32 pri_mapping_binary_49[];
extern u32 pri_mapping_binary_50[];
extern u32 pri_mapping_binary_51[];
extern u32 pri_mapping_binary_52[];
extern u32 pri_mapping_binary_53[];
extern u32 pri_mapping_binary_54[];
extern u32 pri_mapping_binary_55[];
extern u32 pri_mapping_binary_56[];
extern u32 pri_mapping_binary_57[];
extern u32 pri_mapping_binary_58[];
extern u32 pri_mapping_binary_59[];
extern u32 pri_mapping_binary_60[];
extern u32 pri_mapping_binary_61[];
extern u32 pri_mapping_binary_62[];
extern u32 pri_mapping_binary_63[];
extern u32 pri_mapping_binary_64[];
extern u32 pri_mapping_binary_65[];
extern u32 sec_mapping_binary_65[];
extern u32 pri_mapping_binary_66[];
extern u32 pri_mapping_binary_67[];
extern u32 pri_mapping_binary_68[];
extern u32 pri_mapping_binary_69[];
extern u32 sec_mapping_binary_69[];
extern u32 pri_mapping_binary_70[];
extern u32 sec_mapping_binary_70[];
extern u32 pri_mapping_binary_71[];
extern u32 pri_mapping_binary_72[];
extern u32 pri_mapping_binary_73[];
extern u32 pri_mapping_binary_74[];
extern u32 pri_mapping_binary_75[];
extern u32 pri_mapping_binary_76[];
extern u32 pri_mapping_binary_77[];
extern u32 pri_mapping_binary_78[];
extern u32 pri_mapping_binary_79[];
extern u32 pri_mapping_binary_80[];
extern u32 pri_mapping_binary_81[];
extern u32 pri_mapping_binary_82[];
extern u32 pri_mapping_binary_83[];
extern u32 pri_mapping_binary_84[];
extern u32 pri_mapping_binary_85[];
extern u32 pri_mapping_binary_86[];
extern u32 pri_mapping_binary_87[];
extern u32 pri_mapping_binary_88[];
extern u32 pri_mapping_binary_89[];
extern u32 pri_mapping_binary_90[];
extern u32 pri_mapping_binary_91[];
extern u32 sec_mapping_binary_91[];
extern u32 pri_mapping_binary_92[];

extern struct portal_4_point portal_0;
extern struct portal_4_point portal_1;
extern struct portal_4_point portal_2;
extern struct portal_4_point portal_3;
extern struct portal_4_point portal_4;
extern struct portal_4_point portal_5;
extern struct portal_4_point portal_6;
extern struct portal_4_point portal_7;
extern struct portal_4_point portal_8;
extern struct portal_4_point portal_9;
extern struct portal_4_point portal_10;
extern struct portal_4_point portal_11;
extern struct portal_4_point portal_12;
extern struct portal_4_point portal_13;
extern struct portal_4_point portal_14;
extern struct portal_4_point portal_15;
extern struct portal_4_point portal_16;
extern struct portal_4_point portal_17;
extern struct portal_4_point portal_18;
extern struct portal_4_point portal_19;
extern struct portal_4_point portal_20;
extern struct portal_4_point portal_21;
extern struct portal_4_point portal_22;
extern struct portal_4_point portal_23;
extern struct portal_4_point portal_24;
extern struct portal_4_point portal_25;
extern struct portal_4_point portal_26;
extern struct portal_4_point portal_27;
extern struct portal_4_point portal_28;
extern struct portal_4_point portal_29;
extern struct portal_4_point portal_30;
extern struct portal_4_point portal_31;
extern struct portal_4_point portal_32;
extern struct portal_4_point portal_33;
extern struct portal_4_point portal_34;
extern struct portal_4_point portal_35;
extern struct portal_4_point portal_36;
extern struct portal_4_point portal_37;
extern struct portal_4_point portal_38;
extern struct portal_4_point portal_39;
extern struct portal_4_point portal_40;
extern struct portal_4_point portal_41;
extern struct portal_4_point portal_42;
extern struct portal_4_point portal_43;
extern struct portal_4_point portal_44;
extern struct portal_4_point portal_45;
extern struct portal_4_point portal_46;
extern struct portal_4_point portal_47;
extern struct portal_4_point portal_48;
extern struct portal_4_point portal_49;
extern struct portal_4_point portal_50;
extern struct portal_4_point portal_51;
extern struct portal_4_point portal_52;
extern struct portal_4_point portal_53;
extern struct portal_4_point portal_54;
extern struct portal_4_point portal_55;
extern struct portal_4_point portal_56;
extern struct portal_4_point portal_57;
extern struct portal_4_point portal_58;
extern struct portal_4_point portal_59;
extern struct portal_4_point portal_60;
extern struct portal_4_point portal_61;
extern struct portal_4_point portal_62;
extern struct portal_4_point portal_63;
extern struct portal_4_point portal_64;
extern struct portal_4_point portal_65;
extern struct portal_4_point portal_66;
extern struct portal_4_point portal_67;
extern struct portal_4_point portal_68;
extern struct portal_4_point portal_69;
extern struct portal_4_point portal_70;
extern struct portal_4_point portal_71;
extern struct portal_4_point portal_72;
extern struct portal_4_point portal_73;
extern struct portal_4_point portal_74;
extern struct portal_4_point portal_75;
extern struct portal_4_point portal_76;
extern struct portal_4_point portal_77;
extern struct portal_4_point portal_78;
extern struct portal_4_point portal_79;
extern struct portal_4_point portal_80;
extern struct portal_4_point portal_81;
extern struct portal_4_point portal_82;
extern struct portal_4_point portal_83;
extern struct portal_4_point portal_84;
extern struct portal_4_point portal_85;
extern struct portal_4_point portal_86;
extern struct portal_4_point portal_87;
extern struct portal_4_point portal_88;
extern struct portal_4_point portal_89;
extern struct portal_3_point portal_90;
extern struct portal_4_point portal_91;
extern struct portal_3_point portal_92;
extern struct portal_4_point portal_93;
extern struct portal_4_point portal_94;
extern struct portal_4_point portal_95;
extern struct portal_4_point portal_96;
extern struct portal_4_point portal_97;
extern struct portal_4_point portal_98;
extern struct portal_4_point portal_99;
extern struct portal_4_point portal_100;
extern struct portal_4_point portal_101;
extern struct portal_4_point portal_102;
extern struct portal_4_point portal_103;
extern struct portal_4_point portal_104;
extern struct portal_4_point portal_105;
extern struct portal_4_point portal_106;
extern struct portal_4_point portal_107;
extern struct portal_4_point portal_108;
extern struct portal_4_point portal_109;
extern struct portal_4_point portal_110;
extern struct portal_4_point portal_111;
extern struct portal_4_point portal_112;
extern struct portal_4_point portal_113;
extern struct portal_4_point portal_114;
extern struct portal_4_point portal_115;
extern struct portal_4_point portal_116;
extern struct portal_6_point portal_117;
extern struct portal_6_point portal_118;
extern struct portal_4_point portal_119;
extern struct portal_4_point portal_120;
extern struct portal_4_point portal_121;
extern struct portal_4_point portal_122;
extern struct portal_4_point portal_123;
extern struct portal_4_point portal_124;
extern struct portal_4_point portal_125;
extern struct portal_4_point portal_126;
extern struct portal_4_point portal_127;
extern struct portal_4_point portal_128;
extern struct portal_4_point portal_129;
extern struct portal_4_point portal_130;
extern struct portal_4_point portal_131;
extern struct portal_4_point portal_132;
extern struct portal_4_point portal_133;
extern struct portal_4_point portal_134;
extern struct portal_4_point portal_135;
extern struct portal_4_point portal_136;
extern struct portal_4_point portal_137;
extern struct portal_4_point portal_138;
extern struct portal_4_point portal_139;
extern struct portal_4_point portal_140;
