
 #include <ultra64.h>

extern u32 point_table_binary_1[];
extern u32 point_table_binary_2[];
extern u32 point_table_binary_3[];
extern u32 point_table_binary_4[];
extern u32 point_table_binary_5[];
extern u32 point_table_binary_6[];
extern u32 point_table_binary_7[];
extern u32 point_table_binary_8[];
extern u32 point_table_binary_9[];
extern u32 point_table_binary_10[];
extern u32 point_table_binary_11[];
extern u32 point_table_binary_12[];
extern u32 point_table_binary_13[];
extern u32 point_table_binary_14[];
extern u32 point_table_binary_15[];
extern u32 point_table_binary_16[];
extern u32 point_table_binary_17[];
extern u32 point_table_binary_18[];
extern u32 point_table_binary_19[];
extern u32 point_table_binary_20[];
extern u32 point_table_binary_21[];
extern u32 point_table_binary_22[];
extern u32 point_table_binary_23[];
extern u32 point_table_binary_24[];
extern u32 point_table_binary_25[];
extern u32 point_table_binary_26[];
extern u32 point_table_binary_27[];
extern u32 point_table_binary_28[];
extern u32 point_table_binary_29[];
extern u32 point_table_binary_30[];
extern u32 point_table_binary_31[];
extern u32 point_table_binary_32[];
extern u32 point_table_binary_33[];
extern u32 point_table_binary_34[];
extern u32 point_table_binary_35[];
extern u32 point_table_binary_36[];
extern u32 point_table_binary_37[];
extern u32 point_table_binary_38[];
extern u32 point_table_binary_39[];
extern u32 point_table_binary_40[];
extern u32 point_table_binary_41[];
extern u32 point_table_binary_42[];
extern u32 point_table_binary_43[];
extern u32 point_table_binary_44[];
extern u32 point_table_binary_45[];

extern u32 pri_mapping_binary_1[];
extern u32 sec_mapping_binary_1[];
extern u32 pri_mapping_binary_2[];
extern u32 sec_mapping_binary_2[];
extern u32 pri_mapping_binary_3[];
extern u32 pri_mapping_binary_4[];
extern u32 pri_mapping_binary_5[];
extern u32 pri_mapping_binary_6[];
extern u32 pri_mapping_binary_7[];
extern u32 sec_mapping_binary_7[];
extern u32 pri_mapping_binary_8[];
extern u32 pri_mapping_binary_9[];
extern u32 pri_mapping_binary_10[];
extern u32 pri_mapping_binary_11[];
extern u32 pri_mapping_binary_12[];
extern u32 pri_mapping_binary_13[];
extern u32 pri_mapping_binary_14[];
extern u32 pri_mapping_binary_15[];
extern u32 sec_mapping_binary_15[];
extern u32 pri_mapping_binary_16[];
extern u32 pri_mapping_binary_17[];
extern u32 pri_mapping_binary_18[];
extern u32 pri_mapping_binary_19[];
extern u32 pri_mapping_binary_20[];
extern u32 sec_mapping_binary_20[];
extern u32 pri_mapping_binary_21[];
extern u32 sec_mapping_binary_21[];
extern u32 pri_mapping_binary_22[];
extern u32 sec_mapping_binary_22[];
extern u32 pri_mapping_binary_23[];
extern u32 pri_mapping_binary_24[];
extern u32 sec_mapping_binary_24[];
extern u32 pri_mapping_binary_25[];
extern u32 pri_mapping_binary_26[];
extern u32 pri_mapping_binary_27[];
extern u32 pri_mapping_binary_28[];
extern u32 pri_mapping_binary_29[];
extern u32 sec_mapping_binary_29[];
extern u32 pri_mapping_binary_30[];
extern u32 pri_mapping_binary_31[];
extern u32 pri_mapping_binary_32[];
extern u32 sec_mapping_binary_32[];
extern u32 pri_mapping_binary_33[];
extern u32 pri_mapping_binary_34[];
extern u32 sec_mapping_binary_34[];
extern u32 pri_mapping_binary_35[];
extern u32 sec_mapping_binary_35[];
extern u32 pri_mapping_binary_36[];
extern u32 sec_mapping_binary_36[];
extern u32 pri_mapping_binary_37[];
extern u32 pri_mapping_binary_38[];
extern u32 pri_mapping_binary_39[];
extern u32 pri_mapping_binary_40[];
extern u32 pri_mapping_binary_41[];
extern u32 pri_mapping_binary_42[];
extern u32 sec_mapping_binary_42[];
extern u32 pri_mapping_binary_43[];
extern u32 pri_mapping_binary_44[];
extern u32 sec_mapping_binary_44[];
extern u32 pri_mapping_binary_45[];

extern struct portal_4_point portal_0;
extern struct portal_4_point portal_1;
extern struct portal_4_point portal_2;
extern struct portal_4_point portal_3;
extern struct portal_4_point portal_4;
extern struct portal_4_point portal_5;
extern struct portal_4_point portal_6;
extern struct portal_4_point portal_7;
extern struct portal_4_point portal_8;
extern struct portal_4_point portal_9;
extern struct portal_4_point portal_10;
extern struct portal_4_point portal_11;
extern struct portal_4_point portal_12;
extern struct portal_4_point portal_13;
extern struct portal_4_point portal_14;
extern struct portal_4_point portal_15;
extern struct portal_4_point portal_16;
extern struct portal_4_point portal_17;
extern struct portal_4_point portal_18;
extern struct portal_4_point portal_19;
extern struct portal_4_point portal_20;
extern struct portal_4_point portal_21;
extern struct portal_4_point portal_22;
extern struct portal_4_point portal_23;
extern struct portal_4_point portal_24;
extern struct portal_4_point portal_25;
extern struct portal_4_point portal_26;
extern struct portal_4_point portal_27;
extern struct portal_4_point portal_28;
extern struct portal_4_point portal_29;
extern struct portal_4_point portal_30;
extern struct portal_4_point portal_31;
extern struct portal_4_point portal_32;
extern struct portal_4_point portal_33;
extern struct portal_4_point portal_34;
extern struct portal_4_point portal_35;
extern struct portal_4_point portal_36;
extern struct portal_4_point portal_37;
extern struct portal_4_point portal_38;
extern struct portal_4_point portal_39;
extern struct portal_4_point portal_40;
extern struct portal_4_point portal_41;
extern struct portal_4_point portal_42;
extern struct portal_4_point portal_43;
extern struct portal_4_point portal_44;
extern struct portal_4_point portal_45;
extern struct portal_4_point portal_46;
extern struct portal_4_point portal_47;
extern struct portal_4_point portal_48;
extern struct portal_4_point portal_49;
extern struct portal_4_point portal_50;
extern struct portal_4_point portal_51;
extern struct portal_4_point portal_52;
extern struct portal_4_point portal_53;
extern struct portal_4_point portal_54;
extern struct portal_4_point portal_55;
extern struct portal_4_point portal_56;
extern struct portal_4_point portal_57;
extern struct portal_4_point portal_58;
extern struct portal_4_point portal_59;
