
 #include "ultra64.h"

extern u32 point_table_binary_1[];
extern u32 point_table_binary_2[];
extern u32 point_table_binary_3[];
extern u32 point_table_binary_4[];
extern u32 point_table_binary_5[];
extern u32 point_table_binary_6[];
extern u32 point_table_binary_7[];
extern u32 point_table_binary_8[];
extern u32 point_table_binary_9[];
extern u32 point_table_binary_10[];
extern u32 point_table_binary_11[];
extern u32 point_table_binary_12[];
extern u32 point_table_binary_13[];
extern u32 point_table_binary_14[];
extern u32 point_table_binary_15[];
extern u32 point_table_binary_16[];
extern u32 point_table_binary_17[];
extern u32 point_table_binary_18[];
extern u32 point_table_binary_19[];
extern u32 point_table_binary_20[];
extern u32 point_table_binary_21[];
extern u32 point_table_binary_22[];
extern u32 point_table_binary_23[];
extern u32 point_table_binary_24[];
extern u32 point_table_binary_25[];
extern u32 point_table_binary_26[];
extern u32 point_table_binary_27[];
extern u32 point_table_binary_28[];
extern u32 point_table_binary_29[];
extern u32 point_table_binary_30[];
extern u32 point_table_binary_31[];

extern u32 pri_mapping_binary_1[];
extern u32 sec_mapping_binary_1[];
extern u32 pri_mapping_binary_2[];
extern u32 sec_mapping_binary_2[];
extern u32 pri_mapping_binary_3[];
extern u32 sec_mapping_binary_3[];
extern u32 pri_mapping_binary_4[];
extern u32 pri_mapping_binary_5[];
extern u32 sec_mapping_binary_5[];
extern u32 pri_mapping_binary_6[];
extern u32 sec_mapping_binary_6[];
extern u32 pri_mapping_binary_7[];
extern u32 pri_mapping_binary_8[];
extern u32 pri_mapping_binary_9[];
extern u32 sec_mapping_binary_9[];
extern u32 pri_mapping_binary_10[];
extern u32 sec_mapping_binary_10[];
extern u32 pri_mapping_binary_11[];
extern u32 sec_mapping_binary_11[];
extern u32 pri_mapping_binary_12[];
extern u32 sec_mapping_binary_12[];
extern u32 pri_mapping_binary_13[];
extern u32 sec_mapping_binary_13[];
extern u32 pri_mapping_binary_14[];
extern u32 pri_mapping_binary_15[];
extern u32 sec_mapping_binary_15[];
extern u32 pri_mapping_binary_16[];
extern u32 sec_mapping_binary_16[];
extern u32 pri_mapping_binary_17[];
extern u32 sec_mapping_binary_17[];
extern u32 pri_mapping_binary_18[];
extern u32 sec_mapping_binary_18[];
extern u32 pri_mapping_binary_19[];
extern u32 sec_mapping_binary_19[];
extern u32 pri_mapping_binary_20[];
extern u32 sec_mapping_binary_20[];
extern u32 pri_mapping_binary_21[];
extern u32 sec_mapping_binary_21[];
extern u32 pri_mapping_binary_22[];
extern u32 sec_mapping_binary_22[];
extern u32 pri_mapping_binary_23[];
extern u32 sec_mapping_binary_23[];
extern u32 pri_mapping_binary_24[];
extern u32 pri_mapping_binary_25[];
extern u32 sec_mapping_binary_25[];
extern u32 pri_mapping_binary_26[];
extern u32 sec_mapping_binary_26[];
extern u32 pri_mapping_binary_27[];
extern u32 sec_mapping_binary_27[];
extern u32 pri_mapping_binary_28[];
extern u32 sec_mapping_binary_28[];
extern u32 pri_mapping_binary_29[];
extern u32 sec_mapping_binary_29[];
extern u32 pri_mapping_binary_30[];
extern u32 sec_mapping_binary_30[];
extern u32 pri_mapping_binary_31[];

extern struct portal_4_point portal_0;
extern struct portal_4_point portal_1;
extern struct portal_4_point portal_2;
extern struct portal_4_point portal_3;
extern struct portal_4_point portal_4;
extern struct portal_4_point portal_5;
extern struct portal_4_point portal_6;
extern struct portal_4_point portal_7;
extern struct portal_4_point portal_8;
extern struct portal_4_point portal_9;
extern struct portal_4_point portal_10;
extern struct portal_4_point portal_11;
extern struct portal_4_point portal_12;
extern struct portal_4_point portal_13;
extern struct portal_4_point portal_14;
extern struct portal_4_point portal_15;
extern struct portal_4_point portal_16;
extern struct portal_4_point portal_17;
extern struct portal_4_point portal_18;
extern struct portal_4_point portal_19;
extern struct portal_4_point portal_20;
extern struct portal_4_point portal_21;
extern struct portal_4_point portal_22;
extern struct portal_4_point portal_23;
extern struct portal_4_point portal_24;
extern struct portal_4_point portal_25;
extern struct portal_4_point portal_26;
extern struct portal_4_point portal_27;
extern struct portal_4_point portal_28;
extern struct portal_4_point portal_29;
