# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"

.section .text, "ax"
glabel aspMainTextStart
.incbin "/bin/aspboot.text.bin"
/*D:80023044*/
glabel unknown_init_val
.word 2

glabel cart_hw_address
.word 0x10000000

glabel debug_handler_table 
.word sp_boot, aBoot
.word sp_rmon, aRmon
.word sp_idle, aIdle
.word sp_shed, aShed
.word sp_main, aMain
.word sp_audi, aAudi
.word 0, 0
.word 0, 0

.section .rodata
glabel aBoot
.word 0x626F6F74, 0x00000000

glabel aRmon
.word 0x726D6F6E, 0x00000000

glabel aIdle
.word 0x69646C65, 0x00000000

glabel aShed
.word 0x73686564, 0x00000000

glabel aMain
.word 0x6D61696E, 0x00000000

glabel aAudi
.word 0x61756469, 0x00000000


.section .data
glabel aspMainDataStart
.incbin "/bin/aspboot.data.bin"
.section .rodata
.section .bss
