# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"

.section .text, "ax"
glabel gsp3DTextStart
.incbin "bin/gspboot.text.bin"
glabel gsp3DTextEnd

.section .data
glabel gsp3DDataStart
.incbin "bin/gspboot.data.bin"
glabel gsp3DDataEnd
.section .rodata
.section .bss
