# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"

.section .text, "ax"
glabel rspbootTextStart
.ifdef VERSION_US
.incbin "build/u/rsp/rspboot.bin"
.endif
.ifdef VERSION_JP
.incbin "build/j/rsp/rspboot.bin"
.endif
.ifdef VERSION_EU
.incbin "build/e/rsp/rspboot.bin"
.endif
glabel rspbootTextEnd
.section .data
.section .rodata
.section .bss
