#include "game/lvl_text.h"

struct stringentry LlenJ[] = {
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "€ä€ß€»€÷€Ğ:€‡‚€È€»€ğƒ ‚¼‚ğ´ÉÒÑ ! €ˆ\n",
    "€ÏŠ:€‡ºº €ä€ß€»€÷€Ğ ! €ˆ\n",
    "€ä€ß€»€÷€Ğ:€‡‚¼‚óß¿´É...€ˆ\n",
    "€Ö€Ì€»‹ ‚€Ë€Ï€ş€ø\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "€Ö€Ë€Ü€ã\n",
    "\n",
    "‚€È€»€ğƒ€…€ÏŠ\n",
    "007\n",
    "€ä€ß€»€÷€Ğ€…€Û€ï€Í€è‹\n",
    "€Ú€â€ö€Ñ€ã€…’€ú€ş€ö€î€»\n",
    "€Ğ€ù€Ê€×€…€ã€ùÿ€È€ø€ó€Ï\n",
    "006/€ó€æ€Ü\n",
    "„€å€Ğ€…€Ô€ä€ã€Ê’\n",
    "€ó€æ€Ü………Û\n",
    "€Ğ€»€Õ€»‰€Æ€…€Ò€ø€ò€ë\n",
    "„€‚²\n",
    "€÷€Ü€…€ş€÷€Û€È€Ï€Ù\n",
    "ÿ€Å€ù€Ï€â€Æ€Ï€…ƒ€Ù€ë€Ü€Ö€»\n",
    "…ÙKGB„¥‚Çƒù\n",
    "‰€ï€ã€÷€…€ï€Û€Ì€Ö€Ï\n",
    "…¨‚Îƒö…ø\n",
    "The Bond Team\n",
    "Martin Hollis\n",
    "Karl Hilton\n",
    "Mark Edmonds\n",
    "B Jones\n",
    "Duncan Botwood\n",
    "Dave Doak\n",
    "Steve Ellis\n",
    "Graeme Norgate\n",
    "Grant Kirkhope\n",
    "Robin Beanland\n",
    "Des Hinkson\n",
    "Martin Wakeley\n",
    "The Testers\n",
    "Huw Ward\n",
    "Gary Richards\n",
    "Martin Penny\n",
    "Jamie Williams\n",
    "David Wong\n",
    "Gareth Jones\n",
    "Gavin Hood\n",
    "\"JAMES BOND WILL RETURN\"\n",
    NULL
};
