
char * LpropobjJ[] = {
    "¸‚¡Ï‚ºãÉ",
    "",
    "",
    "",
    "",
    "<„Ž>",
    "€Û€Í€Ê€ã€ü€ÏÒ„Ž",
    "€î€þ€ä€ð‚×Ò„Ž",
    "†Â„“Ò„Ž",
    "‚¡á¶¼„Ž",
    "€þ€ù€ç€»Š€ö€Ï€à€Ë€»Ò„Ž",
    "€ú€Ø€Ê€ã„Ž",
    "€÷€ò€Ù€Ï†òƒ“„Ž",
    "€ò€»€Û€Í€Ï€Ý€Ï€Ú€»ƒ“„Ž",
    "‚Ó†–ƒ“„Ž",
    "‚¡†âé",
    "€ä€Ñ€ë",
    "€ä€Ñ€ë",
    "",
    "dart",
    "explosive pen",
    "explosive case",
    "flare",
    "‘€»€ã€Ï",
    "of dynamite",
    "stick",
    "sticks",
    "„ö„÷‚Þ‚ß",
    "micro camera",
    "€€»€ø‰€Ï€Ð€Ñ€…€Ö€»",
    "€ë€ö€Ê€þ",
    "’€ö€Ü€à€Ê€×ƒ“„Ž",
    "€é€Ï€â€Æ€Ï€þ€…€ä€Ñ€ë\n",
    "PP7\n",
    "€Ú€Ñ€ù€Ï€Ú€»PP7\n",
    "DD44 Dostovei\n",
    "Klobb\n",
    "KF7 Soviet\n",
    "ZMG (9mm)\n",
    "D5K Deutsche\n",
    "€Ú€Ñ€ù€Ï€Ú€»D5K\n",
    "Phantom\n",
    "AR33„‹„Œ€ö€Ñ€ë€ø\n",
    "RC-P90\n",
    "€Û€Í€Ê€ã€ü€Ï\n",
    "…æ‚õ€Û€Í€Ê€ã€ü€Ï\n",
    "€Ü€ä€Ñ€»€ö€Ñ€ë€ø\n",
    "€þ€ù€ç€»Š€ö€Ï€à€Ë€»\n",
    "€ú€Ø€Ê€ã€ö€Ï€à€Ë€»\n",
    "Cougar Magnum\n",
    "†Â„“‚×\n",
    "€ð€»€Ï€ù€Ñ€Õ€»€…€ù€»€»‚×\n",
    "",
    "‘€»€ã€Ï‚×\n",
    "€Û€ø‹€»PP7\n",
    "€€»€øŠPP7\n",
    "€Ö€»€Õ€»Š\n",
    "€Ö€»\n",
    "ƒþ†ò€Ö€»\n",
    "†óÅ»†Ž‚‡\n",
    "€Ö€»¸‚¡Ï‚ºãÉ\n",
    "…¨„Ž€à€Í€Ê€Ö¸‚¡Ï‚ºãÉ\n",
    "…¨„Ž€à€Í€Ê€Ö\n",
    "„†¿¸‚¡Ï‚ºãÉ\n",
    "€ú€Ê€×ÄãÌ»ØÆ\n",
    0,
    0,
    0
};
