# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# asm file.

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text
glabel __osGetSR
/* 018730 70017B30 40026000 */  mfc0  $v0, $12
/* 018734 70017B34 03E00008 */  jr    $ra
/* 018738 70017B38 00000000 */   nop   

/* 01873C 70017B3C 00000000 */  nop   
