# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# asm file.

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"


.section .text, "ax" 
.section .text  
glabel __osSetSR
/* 018720 70017B20 40846000 */  mtc0  $a0, $12
/* 018724 70017B24 00000000 */  nop   
/* 018728 70017B28 03E00008 */  jr    $ra
/* 01872C 70017B2C 00000000 */   nop  
